'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const C=require('../food-catalogue'),O=require('../off-catalogue'),R=require('../retailer-catalogue'),A=require('../retailer-source'),B=require('../scripts/build_aldi_catalogue'),G=require('../guided-product-resolution');
require('../woolworths-au-catalogue');require('../coles-au-catalogue');const {index}=require('../aldi-au-catalogue');
const {rows,policy}=B.derive(),approved=rows.filter(r=>r.food.browseEligible),bread=approved.find(r=>r.item.categoryId==='bread').food;
test.afterEach(()=>A.register(index));
test('frozen pool is pinned and the reviewed projection rebuilds byte-identically',()=>{B.build({check:true});assert.equal(rows.length,28);assert.equal(approved.length,20);assert.equal(rows.filter(r=>!r.food.browseEligible).length,8);});
test('retailers register once in the established deterministic order',()=>{A.register(index);assert.deepEqual(R.commercialOptions('bread').map(r=>r.id),['woolworths','coles','aldi']);assert.equal(R.recognise('Aldi').id,'aldi');assert.equal(C.queryIntent('Aldi').kind,'retailer');});
test('directory counts and All Items are deterministic and lazy',async()=>{const reads=[];A.register(index,{loadJSON:async f=>{reads.push(f);return require('../data/aldi-au/'+f);}});const d=R.directory('aldi');assert.equal(reads.length,0);assert.equal(d.total,87);assert.equal(d.categories.length,13);const page=await R.page('aldi');assert.equal(page.foods.length,20);assert.equal(page.total,87);assert.equal(page.hasMore,true);assert.deepEqual(page.foods.map(f=>f.id),index.entries.slice(0,20).map(e=>e.id));assert.equal(new Set(page.foods.map(f=>f.id)).size,20);});
test('every visible item has approved explicit Australia-only store evidence, source brand and attribution',async()=>{for(const f of (await R.page('aldi')).foods){const r=approved.find(r=>r.food.id===f.id);assert(r);assert.equal(f.brand,r.record.brand);assert.equal(C.sourceDeclaredRetailerMembership(f,'aldi').length,1);assert.equal(C.retailerMembership(f,'aldi').length,0);assert.equal(C.commercialIdentityMembership(R.entity('aldi'),f).matches,false);assert.deepEqual(f.sourceProvenance.countriesTags,['en:australia']);assert.equal(f.sourceAttribution.attribution,'Open Food Facts contributors');assert.equal(f.currentState,'unknown');assert.equal(C.productEligibility(f).addability.normalLoggingAllowed,true);assert.equal(C.productEligibility(f).verified,false);assert.deepEqual(f.nutrients,O.toFood(r.record).nutrients);assert.deepEqual(f.rawSourceNutrients,r.record.nutrients);}});
test('all 705 retained exclusions and lexical rejects remain outside the production index',()=>{const m=require('../data/aldi-au/retained-state-manifest.json');assert.equal(m.total,725);assert.equal(m.nonBrowsable,705);assert.equal(m.lexicalRejected.count,647);assert.deepEqual(m.states,{'needs-nutrition-completion':621,'wider-potentially-loggable':38,'conservative-multi-country':32,'first-wave-approved':20,'details-only':6,'first-wave-review-excluded':8});for(const r of m.records)if(r.ordinaryAldiBrowse)assert(index.entries.some(e=>e.barcode===r.code));for(const r of rows.filter(r=>!r.food.browseEligible))assert(!index.entries.some(e=>e.barcode===r.record.barcode));});
test('community provenance cannot be fabricated from names, brand, partial store text, foreign country or missing pins',()=>{const edits=[f=>f.retailerMemberships=[],f=>f.retailerMemberships[0].verified=true,f=>f.retailerMemberships[0].evidence.stores='Aldington',f=>f.retailerMemberships[0].evidence.stores='Aldi Supermarket',f=>f.retailerMemberships[0].evidence.countriesTags=['en:united-kingdom'],f=>f.retailerMemberships[0].evidence.sha256='',f=>f.retailerMemberships[0].evidence.url='https://evilopenfoodfacts.org/product/'+f.barcode,f=>f.retailerMemberships[0].evidence.recordId='off:12345678'];for(const edit of edits){const f=structuredClone(bread);edit(f);assert.equal(C.sourceDeclaredRetailerMembership(f,'aldi').length,0);assert.equal(C.retailerMembership(f,'aldi').length,0);}});
test('tampered hydrated community evidence fails closed',async()=>{A.register(index,{loadJSON:async file=>{const page=structuredClone(require('../data/aldi-au/'+file));page.records.forEach(f=>f.retailerMemberships=[]);return page;}});await assert.rejects(R.page('aldi'),/community store evidence differs/);});
for(const [concept,count] of [['bread',1],['yoghurt',5],['cheese',1],['cereal',2]])test('guided '+concept+' is limited to its approved Aldi concept',async()=>{const result=await R.page('aldi',{scope:'commercial-identity',conceptId:concept});assert(result.total>=count);assert.equal(result.foods.length,Math.min(20,result.total));assert(result.foods.every(f=>f.conceptIds.includes(concept)));});
test('retailer-aware Aldi bread uses the food concept even without bread in the source title',async()=>{const result=await R.search('Aldi bread');assert(result.total>=1);assert(result.foods.some(f=>f.barcode===bread.barcode&&f.brand==='Bakers Life'));assert((await R.search('Aldi muesli')).total>=2);});
test('cancellation clears Aldi ownership and preserves generic Bread intent',async()=>{const s=R.createSession('aldi',{ownerQuery:'Aldi',ownerRevision:1});await R.load(s);R.cancel(s);assert.equal(s.result,null);assert.equal(s.active,false);assert.equal(R.recognise('Bread'),null);assert.equal(C.queryIntent('Bread').kind,'product');});
test('all 20 existing protected OFF GTIN records merge compatibly without changing brand or nutrition',()=>{for(const {food} of approved){const ref=require('../data/open-food-facts-au/barcodes/'+food.barcode.slice(0,2)+'.json').barcodes[food.barcode];assert(ref);const [shard,row]=ref.split(':'),raw=require('../data/open-food-facts-au/products/'+shard+'.json').products[Number(row)];for(const pair of [[food,O.toFood(raw)],[O.toFood(raw),food]]){const merged=C.canonicaliseRecords(pair);assert.equal(merged.length,1);assert.equal(merged[0].brand,food.brand);assert([food.nutrients,O.toFood(raw).nutrients].some(n=>JSON.stringify(n)===JSON.stringify(merged[0].nutrients)),'Canonical nutrition must equal one complete source, never an average');assert.equal(C.sourceDeclaredRetailerMembership(merged[0],'aldi').length,1);assert.equal(C.productEligibility(merged[0]).addability.normalLoggingAllowed,true);assert.deepEqual(C.sourceConflicts(merged[0]),[]);}}});
test('incompatible same-GTIN identity remains blocked through repeated canonicalisation',()=>{for(const change of [{brand:'Synthetic different brand'},{packageSize:'99 kg',pack:{amount:99000,unit:'g'}},{physicalForm:'liquid'}]){const other={...structuredClone(bread),id:'synthetic:conflict',...change},f=C.canonicaliseRecords([bread,other])[0];assert.equal(C.productEligibility(f).addability.normalLoggingAllowed,false);assert.equal(C.productEligibility(C.canonicaliseRecords([f,bread])[0]).addability.normalLoggingAllowed,false);}});
const samples=[['bread slices','4061462249464','slice',2,75],['liquid Pepsi','9313820016108','mL',250,250],['gram cheese','4088700157008','g',40,40],['muesli serve','4088700219737','serve',1,45],['gram yoghurt','26283517','g',150,150]];
for(const [label,code,unit,amount,base] of samples)test(label+' preserves identity, amount conversion and one final Review',()=>{const f=approved.find(r=>r.record.barcode===code).food,s=G.createSession([f],f.name,{intent:{kind:'exact-product'}});G.selectMeasure(s,unit);G.selectAmount(s,amount);assert.equal(s.stage,G.stages.CONFIRMATION);assert.equal(s.exactProduct.barcode,code);assert.equal(s.exactProduct.brand,f.brand);assert(Math.abs(f.units[unit]*amount-base/100)<1e-8);assert(Math.abs(s.nutrition.calories-f.nutrients.calories*base/100)<1e-8);if(code==='26283517')assert.equal(s.nutrition.fibre,null);});
test('unknown values stay unknown; explicit water zeroes remain zero; packs never create count measures',()=>{const f=approved.find(r=>r.record.barcode==='26283517').food;assert.equal(f.packIdentity.text,null);assert.equal(f.sourceServing.text,null);assert.equal(f.nutrients.fibre,undefined);assert.deepEqual(f.units,{g:.01});for(const code of ['4088700091173','4088700160466','4088700194393'])assert.deepEqual(approved.find(r=>r.record.barcode===code).food.units,{g:.01});const water=approved.find(r=>r.record.barcode==='4088700038505').food;assert.equal(water.nutrients.calories,0);assert(!('serve' in water.units));for(const {food} of approved)if(food.physicalForm!=='liquid')assert(!['mL','L','cup'].some(k=>k in food.units));});
test('bounded Woolworths and Coles regressions retain their roots and accepted catalogues',async()=>{assert(R.directory('woolworths').categories.length>0);assert(R.directory('woolworths').total>0);assert.equal(R.directory('coles').total,860);assert.equal(R.directory('coles').categories.length,19);assert((await R.page('coles',{categoryId:'bread'})).total>3);assert((await R.page('woolworths',{categoryId:'bread'})).total>3);});

test('submitted retailer product filter keeps approved concept evidence across either merge order',()=>{const r=approved.find(r=>r.food.id===bread.id),raw=O.toFood(r.record);for(const pair of [[bread,raw],[raw,bread]]){const f=C.canonicaliseRecords(pair)[0];assert(C.explicitIdentityMatch(f,'Aldi bread'));assert(!C.explicitIdentityMatch(f,'Aldi bread caramel'));assert.equal(C.submittedResultModel([f],'Aldi bread').total,1);}assert(!C.explicitIdentityMatch({...raw,brand:'Aldi',name:'Bread'},'Aldi bread'));});

test('shared concept source choices expose covered retailers without altering generic-only concepts',()=>{for(const conceptId of ['yoghurt','cheese','cereal']){const s={conceptId,known:{}};assert.equal(R.conceptSourceQuestion(s).key,'catalogueOrigin');s.known.catalogueOrigin='commercial';assert.equal(R.conceptSourceQuestion(s).key,'catalogueSource');s.known.catalogueSource='supermarket';assert(R.conceptSourceQuestion(s).options.some(o=>o.value==='aldi'));}assert.equal(R.conceptSourceQuestion({conceptId:'bread',known:{}}),null);assert.equal(R.conceptSourceQuestion({conceptId:'apple',known:{}}),null);});
test('retailer search uses registered food-concept aliases before title matching',async()=>{for(const [query,total]of [['Aldi toast',1],['Aldi yogurt',5],['Aldi breakfast cereal',2]])assert((await R.search(query)).total>=total);});
