'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),C=require('../food-catalogue'),S=require('../serving-foundation'),R=require('../retailer-catalogue'),B=require('../brand-catalogue'),X=require('../scripts/catalogue-round-two'),A=require('../scripts/audit_house_brands');
for(const id of ['woolworths','coles','aldi'])require('../'+id+'-au-catalogue');
const additions=require('../data/catalogue-round-three/approved-products.json').records,before=A.read('baseline.json'),audit=A.read('family-audit-after.json');const old=new Map(require('../data/catalogue-round-three/baseline-selected-products.json').records.map(f=>[C.canonicalKey(f),f]));
test('all house-brand admissions reuse accepted canonical identity, brand, nutrition and measures',()=>{assert.equal(additions.length,291);assert.equal(new Set(additions.map(C.canonicalKey)).size,291);for(const f of additions){const p=old.get(C.canonicalKey(f));assert(p,f.id);for(const key of ['id','barcode','brand','name','units','nutrients','nutritionPer100','packageSize','sourceServing','sourceProvenance'])assert.deepEqual(f[key],p[key],f.id+' '+key);assert(C.productEligibility(f).addability.normalLoggingAllowed,f.id);assert(f.privateTestingApproved&&f.publicReleaseReviewRequired);assert.equal(C.canonicaliseRecords([p,f]).length,1);assert(C.productEligibility(C.canonicaliseRecords([p,f])[0]).addability.normalLoggingAllowed);}});
test('official house-brand relationship is bound to both identities and AU product evidence',()=>{const f=additions.find(f=>f.brand==='Seasons Pride'),id='aldi';assert.equal(C.privateLabelCollectionMembership(f,id).length,1);assert.equal(C.retailerMembership(f,id).length,0,'not asserted as a verified current listing');for(const edit of [x=>x.brand='Unrelated',x=>x.barcode='99999999',x=>x.privateLabelCollections[0].evidence.houseBrandRelationship.retailerId='coles',x=>x.privateLabelCollections[0].evidence.houseBrandRelationship.brandKey='aldi',x=>x.privateLabelCollections[0].evidence.sha256='',x=>x.privateLabelCollections[0].evidence.productEvidence.countriesTags=['en:australia','en:germany'],x=>x.privateLabelCollections[0].verified=false,x=>x.privateLabelCollections[0].evidence.houseBrandRelationship.relationshipVerified=false]){const changed=structuredClone(f);edit(changed);assert.equal(C.privateLabelCollectionMembership(changed,id).length,0);}assert.equal(C.privateLabelCollectionMembership(f,'coles').length,0);});
test('every retailer root exposes only audited eligible house families once',async()=>{for(const [id,total,ordinary]of [['woolworths',362,347],['coles',417,417],['aldi',222,222]]){assert.equal(R.recognise(id).id,id);assert.equal(R.directory(id).total,total);const keys=new Set(),loggable=[];for(let offset=0;;offset+=20){const page=await R.page(id,{offset});for(const f of page.foods){assert(!keys.has(C.canonicalKey(f)));keys.add(C.canonicalKey(f));assert(X.membership(f,id).length);if(C.productEligibility(f).addability.normalLoggingAllowed)loggable.push(f);}if(!page.hasMore)break;}assert.equal(keys.size,total);assert.equal(loggable.length,ordinary);for(const f of additions.filter(f=>X.membership(f,id).length))assert(keys.has(C.canonicalKey(f)),f.id);}});
test('direct house-brand search reaches the same canonical records without retailer brand replacement',async()=>{for(const key of ['seasonspride','elmsbury','westacre','westacredairy','hillcrest','macro','macrowholefoodsmarket','colesfinest','coleskitchen','natureskitchen']){const expected=B.index.entries.filter(e=>e.brandKeys.includes(key));const found=await B.search(B.index.brands.find(b=>b.key===key).name,{limit:1000});assert.deepEqual(new Set(found.foods.map(C.canonicalKey)),new Set(expected.map(C.canonicalKey)),key);for(const f of found.foods)assert(B.isBrandMember(f,key));}assert.equal(B.index.entries.length,7489);assert.equal(B.index.brands.length,2736);assert.deepEqual(B.index.entries.map(C.canonicalKey),before.brandKeys);});
test('source spelling keys, legacy Select and unresolved candidate holds remain explicit',()=>{for(const key of ['seasonspride','elmsbury','westacre','hillcrest'])assert.equal(audit.rows.find(f=>f.retailer==='aldi'&&f.key===key).status,'current');assert.equal(audit.rows.find(f=>f.key==='woolworthsselect').status,'legacy');assert(audit.rows.find(f=>f.key==='westacredairy'));assert(audit.rows.find(f=>f.key==='hillcrestaldi'));for(const row of audit.rows){assert.equal(row.endingAcceptedCount,row.startingAcceptedCount);assert.equal(row.endingRetailerCount,row.startingRetailerCount+row.admittedAdditionalCount);for(const d of row.decisions.filter(d=>!d.eligible)){assert(d.reasons.length);assert(!additions.some(f=>C.canonicalKey(f)===d.canonicalKey&&C.brandKey(f.brand)===row.key&&C.privateLabelCollectionMembership(f,row.retailer).some(m=>m.basis==='official-house-brand-relationship')));}}});
test('unknown nutrition stays unknown and natural measures do not change',()=>{let unknown=0;for(const f of additions){const p=old.get(C.canonicalKey(f));for(const key of ['fibre','sugar','sodium','protein','carbs','fat'])if(p.nutrients[key]==null){unknown++;assert(f.nutrients[key]==null);}const form=S.physicalForm(f).form,measures=S.servingMeasureProfile(f).measures;if(!['liquid','spread','unknown'].includes(form))assert(!measures.some(m=>['mL','L','cup'].includes(m.key)),f.id);if(form==='liquid')assert(!measures.some(m=>['piece','slice','bar','biscuit'].includes(m.key)),f.id);}assert(unknown>0);});
test('incomplete nutrition and same-GTIN conflicts never gain ordinary admission',()=>{const rows=require('../data/catalogue-round-two/audit.json').off;for(const f of additions){const d=rows.find(r=>r.id===f.id);assert(d&&!d.reasons.length);for(const key of ['protein','carbs','fat','calories'])assert(Number.isFinite(f.nutrients[key]),f.id+' '+key);assert(!rows.some(r=>r.id===f.id&&r.reasons.includes('missing-required-macros')));}const f=additions[0],other={...structuredClone(f),id:'conflicting-new-evidence',brand:'Incompatible brand',name:'Unrelated identity'};assert(!C.productEligibility(C.canonicaliseRecords([f,other])[0]).addability.normalLoggingAllowed);});
test('protected McCain canonical alias and 75 g Review energy are unchanged',async()=>{const page=await R.search('McCain Hash Browns',{limit:20});const f=page.foods.find(f=>f.barcode==='9310174025084');assert(f);assert.equal(f.id,'woolworths-au:98299');assert.equal(Math.round(f.nutrients.calories*f.units.g*75),130);assert.equal(Math.round(f.nutrients.energyKj*f.units.g*75),543);assert(!additions.some(f=>f.barcode==='9310174025084'));});
test('family audit and admissions are hash-pinned with private-testing policy intact',()=>{const policy=A.read('policy.json');assert.equal(policy.publicReleaseLicensingAdmissionGate,false);for(const [file,key]of [['approved-products.json','approvedSha256'],['family-audit-before.json','beforeAuditSha256'],['reviewed-evidence.json','evidenceSha256']])assert.equal(A.hash(fs.readFileSync(require('path').join(A.BASE,file))),policy[key]);});

test('all accepted brand identity, panel and measure bytes match starting SOURCE',()=>{const baseline=A.read('baseline-brand-core.json');const records=new Map(B.index.files.flatMap(s=>require('../data/brand-au/'+s.path).records).map(f=>[C.canonicalKey(f),f]));for(const row of baseline.records){const f=records.get(row.key);assert(f,row.key);assert.deepEqual(Object.fromEntries(baseline.fields.filter(k=>f[k]!==undefined).map(k=>[k,f[k]])),row.facts,row.key);}});
test('house-brand ingredient and use mentions cannot pollute concept narrowing',()=>{for(const [id,banned]of [['off:4061461202163','milk'],['off:4061462678165','bread'],['off:4088700194638','cheese'],['off:9310645476063','bread']]){const entry=B.index.entries.find(f=>f.id===id);assert(!entry.conceptIds.includes(banned),id);}});

test('explicit retailer and house-brand product requests preserve evidenced identity',async()=>{for(const query of ['Coles Finest Garlic & Parsley Sausages','Aldi Seasons Pride Potato Jewels']){const result=await R.search(query);assert.equal(result.foods.length,1);const f=result.foods[0];assert(C.explicitIdentityMatch(f,query),query);assert.equal(C.submittedResultModel(result.foods,query).total,1);const unrelated={...structuredClone(f),brand:'Unrelated brand',privateLabelCollections:[]};assert(!C.explicitIdentityMatch(unrelated,query));}assert(!C.explicitIdentityMatch(additions.find(f=>f.brand==='Seasons Pride'),'Coles Potato Jewels',{kind:'product',entity:{id:'coles',type:'retailer',name:'Coles',aliases:['Coles']},productQuery:'Potato Jewels'}));});
