'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),C=require('../food-catalogue'),D=require('../catalogue-discovery'),S=require('../serving-foundation'),G=require('../guided-product-resolution'),F=require('../food-sources');
require('../australian-catalogue-data');require('../mcdonalds-au-catalogue');require('../kfc-au-catalogue');
const probes=require('../scripts/catalogue-wave-5a-restaurant-probes');
for(const [source,brand,name,loggable,form]of probes)test(source+' '+name+' retains evidenced portion and eligibility',()=>{const f=F.foodRecords({sourceId:source}).find(f=>f.name===name);assert(f);assert.equal(C.canLog(f),loggable);const p=S.servingMeasureProfile(f);if(form)assert.equal(p.physicalForm,form);else if(loggable)assert(!p.measures.some(m=>['mL','L','cup'].includes(m.key)));const model=C.submittedResultModel(F.foodRecords(),brand+' '+name),items=D.submittedGroups(model,{restaurant:true}).flatMap(g=>g.items);assert(items.some(i=>i.recordId===f.id),name+' unreachable');const session=G.createSession([f],brand+' '+name,{intent:{kind:'exact-product'}});if(loggable){if(session.stage===G.stages.CUSTOMISATION)G.chooseCustomisation(session,'standard');G.selectMeasure(session,p.preferredMeasure);G.selectAmount(session,2);assert.equal(session.stage,G.stages.CONFIRMATION);assert.equal(session.exactProduct.id,f.id);assert.equal(session.nutrition.energyKj,f.nutrients.energyKj*f.units[p.preferredMeasure]*2);}else assert.notEqual(session.stage,G.stages.CONFIRMATION);});
test('official fixed restaurant portion requires explicit matching evidence and grants no conversion',()=>{const original=F.foodRecords({sourceId:'hungry-jacks-au'}).find(f=>f.name==='Biscoff Shake Small'),other={...structuredClone(original),name:'Example Chilled Beverage',brand:'Unrelated Restaurant',id:'food-source:example:drink',canonicalId:'food-source:example:drink',foodSourceId:'example',sourceAliases:['Example']};assert.deepEqual(S.servingMeasureProfile(other).measures.map(m=>m.key),['drink']);for(const mutate of [f=>delete f.sourceNutritionEvidence.perServing,f=>f.sourceNutritionEvidence.perServing.energyKj=null,f=>f.sourceNutritionEvidence.perServing.energyKj='1733',f=>f.sourceProvenance.trustClass='open-food-facts-au',f=>f.sourceProvenance.sha256='']){const bad=structuredClone(other);mutate(bad);assert.equal(S.servingMeasureProfile(bad).measures.length,0);}const injected=structuredClone(other);injected.units.mL=.01;injected.units.g=.01;assert.deepEqual(S.servingMeasureProfile(injected).measures,[],'Contradictory injected base units fail closed rather than grant a conversion');});
test('restaurant semantic families retain every meaningful sibling and configurable detail',()=>{const foods=F.foodRecords();for(const [query,names]of [['KFC Wicked Wings',['3 Wicked Wings','6 Wicked Wings','10 Wicked Wings']],['KFC Popcorn Chicken',['Snack Popcorn Chicken','Regular Popcorn Chicken','Maxi Popcorn Chicken']]]){const m=C.submittedResultModel(foods,query),groups=D.submittedGroups(m,{restaurant:true});assert.equal(groups[0].key,'restaurant-family');assert.deepEqual(groups[0].items.map(i=>i.name),names);assert(groups.find(g=>g.key==='details').items.some(i=>/Combo/.test(i.name)&&!i.addability.normalLoggingAllowed));}for(const count of [3,6,10]){const m=C.submittedResultModel(foods,'KFC '+count+' Wicked Wings');assert.equal(m.groups[0].key,'best');assert.equal(m.groups[0].items[0].name,count+' Wicked Wings');}});
test('shortlist bounds are context specific; family decisions are never blindly cut at 24',()=>{const items=Array.from({length:40},(_,i)=>({name:'Variant '+i,addability:{normalLoggingAllowed:true}})),details={key:'details',items:[{name:'Configure order',addability:{normalLoggingAllowed:false}}]};assert.equal(D.submittedGroups({groups:[{key:'restaurant-family',items},details]}).flatMap(g=>g.items).length,41);assert.equal(D.submittedGroups({groups:[{key:'best',items},details]}).flatMap(g=>g.items).length,24);const restaurant=D.submittedGroups({groups:[{key:'best',items},details]},{restaurant:true});assert.equal(restaurant[0].items.length,24);assert.equal(restaurant[1].items.length,1);});
test('compound food guards preserve buns, soup, pickles and ambiguous chicken chips',()=>{for(const name of ['Chocolate Chips Hot Cross Buns','Pea & Ham Soup','Ham & Mustard Pickles','Chicken Chips Small'])assert.equal(D.category({name}),null,name);assert.equal(D.category({name:'Thinly Sliced Honey Leg Ham'}).id,'protein');});

test('blank official energy is unknown, not an evidenced zero',()=>{const tea=structuredClone(F.foodRecords({sourceId:'hungry-jacks-au'}).find(f=>f.name==='Tea Black Small'));assert.deepEqual(S.servingMeasureProfile(tea).measures.map(m=>m.key),['drink']);tea.sourceNutritionEvidence.perServing.energyKj='';assert.equal(S.servingMeasureProfile(tea).measures.length,0);});

test('returning from a transient Review consumes its history entry and preserves the real origin',()=>{
 const vm=require('node:vm'),text=require('node:fs').readFileSync(require('node:path').join(__dirname,'../alpha064.js'),'utf8'),code=text.slice(text.indexOf('// Navigation: every working room'),text.indexOf('// Energy calculation details'));
 for(const origin of ['home','food-diary']){let active='food-entry-editor',observe;const callbacks=[],timers=[],scope={window:{openAlpha05Feature:id=>{active=id;observe();},show:id=>{active=id;observe();},scrollTo(){}},activeScreen:()=>active,qa:()=>[],document:{addEventListener:(type,cb)=>callbacks.push(cb)},MutationObserver:class{constructor(cb){observe=cb;}observe(){}},track(){},setTimeout:cb=>timers.push(cb)};vm.createContext(scope);vm.runInContext(code,scope);vm.runInContext('navStack='+JSON.stringify([{id:origin},{id:'food-library'}])+';',scope);assert.equal(scope.window.HECNavigation.returnTo('food-library'),true);assert.equal(active,'food-library');timers.splice(0).forEach(fn=>fn());callbacks[0]({target:{closest:selector=>selector==='[data-hec-back]'?{}:null},preventDefault(){},stopImmediatePropagation(){}});assert.equal(active,origin);assert.notEqual(active,'food-entry-editor');timers.splice(0).forEach(fn=>fn());active='food-entry-editor';observe();active='food-library';observe();assert.equal(vm.runInContext('navStack.some(entry=>entry.id==="food-entry-editor")',scope),false,'Non-guided Review exit also cannot retain an abandoned item');}
});
