'use strict';

const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const catalogue=require('../food-catalogue.js');
const guided=require('../guided-product-resolution.js');
const serving=require('../serving-foundation.js');
const audit=require('../scripts/audit_open_food_facts_au.js');

const ROOT=path.resolve(__dirname,'..');
const runtime=fs.readFileSync(path.join(ROOT,'alpha06.js'),'utf8');
const manifest=audit.read('manifest.json');
audit.allProducts(manifest);
const localTrim=[
  {id:'norco-trim',canonicalId:'norco-trim',recordType:'external-catalogue',market:'AU',name:'Trim Milk',brand:'Norco',barcode:'9300000000001',nutrients:{calories:40}},
  {id:'pauls-trim',canonicalId:'pauls-trim',recordType:'external-catalogue',market:'AU',name:'Trim Low Fat Milk',brand:'Pauls',barcode:'9300000000002',nutrients:{calories:42}}
];
const onlineTrim=[{id:'online-value',recordType:'online-candidate',market:'international',name:'Value',brand:'Online Candidate',nutrients:{calories:39}}];
const wait=milliseconds=>new Promise(resolve=>setTimeout(resolve,milliseconds));
const names=rows=>rows.map(row=>row.name);
const packaged=values=>({recordType:'external-catalogue',market:'AU',defaultAmount:100,defaultUnit:'g',units:{g:.01},unitLabels:{g:'g'},nutritionPer100:{calories:100},nutrients:{calories:100},...values});

async function timingPermutation({localDelay,onlineDelay}){
  const state=catalogue.newFederatedSearchState(),revision=catalogue.beginQueryRevision(state,'Trim Milk');
  await Promise.all([
    wait(localDelay).then(()=>catalogue.commitLocalSnapshot(state,revision,'Trim Milk',localTrim,{exactProductId:'norco-trim'})),
    wait(onlineDelay).then(()=>catalogue.appendOnlineSnapshot(state,revision,'Trim Milk',onlineTrim))
  ]);
  return {local:names(state.local),online:names(state.online),exactProductId:state.localMeta.exactProductId,localFrozen:Object.isFrozen(state.local)};
}

test('1. delayed online arrivals never reorder or replace the local Trim Milk snapshot',async()=>{const states=await Promise.all([{localDelay:1,onlineDelay:15},{localDelay:15,onlineDelay:1},{localDelay:2,onlineDelay:3},{localDelay:3,onlineDelay:2}].map(timingPermutation));for(const state of states)assert.deepEqual(state,{local:['Trim Milk','Trim Low Fat Milk'],online:['Value'],exactProductId:'norco-trim',localFrozen:true});});
test('2. a stale Trim mil response is rejected after Trim milk becomes active',async()=>{const state=catalogue.newFederatedSearchState(),oldRevision=catalogue.beginQueryRevision(state,'Trim mil'),oldArrival=wait(8).then(()=>catalogue.appendOnlineSnapshot(state,oldRevision,'Trim mil',onlineTrim));const currentRevision=catalogue.beginQueryRevision(state,'Trim milk');catalogue.commitLocalSnapshot(state,currentRevision,'Trim milk',localTrim,{exactProductId:'norco-trim'});assert.equal(await oldArrival,false);assert.deepEqual(names(state.local),['Trim Milk','Trim Low Fat Milk']);assert.deepEqual(state.online,[]);});
test('3. repeating one normalized query preserves its revision and immutable local result',()=>{const state=catalogue.newFederatedSearchState(),first=catalogue.beginQueryRevision(state,' Trim   Milk ');catalogue.commitLocalSnapshot(state,first,'trim milk',localTrim,{exactProductId:'norco-trim'});const second=catalogue.beginQueryRevision(state,'trim milk');catalogue.appendOnlineSnapshot(state,second,'TRIM MILK',onlineTrim);assert.equal(second,first);assert.deepEqual(names(state.local),['Trim Milk','Trim Low Fat Milk']);assert.equal(state.localMeta.exactProductId,'norco-trim');assert.throws(()=>state.local.push(onlineTrim[0]),TypeError);});
test('4. every changed normalized query receives a monotonic revision',()=>{const state=catalogue.newFederatedSearchState(),revisions=['Trim','Trim m','Trim mi','Trim mil','Trim milk'].map(query=>catalogue.beginQueryRevision(state,query));assert.deepEqual(revisions,[1,2,3,4,5]);});

test('5. weak names cannot become exact while meaningful peer identities exist',()=>{const strong=packaged({id:'strong',canonicalId:'strong',name:'Flora Original Spread',brand:'Flora'}),weak=[packaged({id:'proactiv',canonicalId:'proactiv',name:'Proactiv',brand:'Flora'}),packaged({id:'butter',canonicalId:'butter',name:'Butter',brand:'Flora'}),packaged({id:'beurre-a',canonicalId:'beurre-a',name:'Beurre',brand:'Meadow Lea'}),packaged({id:'beurre-b',canonicalId:'beurre-b',name:'Beurre',brand:'Meadow Lea'})];for(const food of weak)assert.equal(catalogue.exactProductQuality(food,{candidates:[strong,...weak]}).exactEligible,false,food.name);});
test('6. barcode-known identity remains incomplete rather than exact',()=>{const barcode=packaged({id:'barcode',canonicalId:'barcode',name:'Barcode 9354237000328',brand:'',barcode:'9354237000328'}),session=guided.createSession([barcode],'9354237000328',{intent:{kind:'barcode'}});assert.equal(catalogue.exactProductQuality(barcode,{candidates:[barcode]}).reason,'barcode-known-name-incomplete');assert.equal(session.resolutionState,guided.states.INCOMPLETE);assert.equal(session.exactProduct,null);});
test('7. brand references remain navigation-only',()=>{const reference=packaged({id:'flora-reference',canonicalId:'flora-reference',name:'Flora',brand:'Flora'});assert.equal(catalogue.exactProductQuality(reference,{candidates:[reference]}).exactEligible,false);});

test('8. small and medium sets use direct concrete products',()=>{for(const count of [6,30,50]){const rows=Array.from({length:count},(_,index)=>packaged({id:`p-${count}-${index}`,canonicalId:`p-${count}-${index}`,name:`Example Product ${index+1}`,brand:'Example'})),session=guided.createSession(rows,'Example',{intent:{kind:'consumer-brand'}});assert.equal(session.nextQuestion.key,'product');assert.equal(guided.presentationForSession(session),'direct-products');assert.equal(session.nextQuestion.options.length,count);}});
test('9. a balanced shopper-facing facet is accepted only for a genuinely large set',()=>{const labels=['Full Cream','Light','Skim','Lactose Free'],rows=Array.from({length:80},(_,index)=>packaged({id:`milk-${index}`,canonicalId:`milk-${index}`,name:`Example ${labels[index%4]} Milk ${index+1}`,brand:'Example Dairy',fatLevel:labels[index%4]})),quality=guided.facetQuality('fatLevel',rows),session=guided.createSession(rows,'Example Dairy',{intent:{kind:'consumer-brand'}});assert.equal(quality.accepted,true);assert.ok(quality.score>=70);assert.equal(session.nextQuestion.key,'fatLevel');assert.equal(guided.presentationForSession(session),'useful-facet');guided.answerDistinction(session,'fatLevel','Skim');assert.equal(session.nextQuestion.key,'product');assert.equal(session.nextQuestion.options.length,20);});
test('10. broad taxonomy noise is rejected and large results paginate real products',()=>{const labels=['Other products','Fats','Dairies'],rows=Array.from({length:80},(_,index)=>packaged({id:`spread-${index}`,canonicalId:`spread-${index}`,name:`Example Spread ${index+1}`,brand:'Example',categoryFacet:labels[index%3]})),quality=guided.facetQuality('category',rows),session=guided.createSession(rows,'Example',{intent:{kind:'consumer-brand'}});assert.equal(quality.accepted,false);assert.ok(quality.reasons.includes('weak-taxonomy-label'));assert.equal(guided.presentationForSession(session),'paginated-products');assert.equal(session.nextQuestion.options.length,guided.directProductLimit);});

test('11. spread keeps grams and the trusted 5 g teaspoon without invented measures',()=>{const food=packaged({id:'spread',canonicalId:'spread',name:'Original Plant Spread',brand:'Example',physicalForm:'spread',categories:['Spreads']}),profile=guided.servingProfile(food),grams=profile.measures.find(item=>item.key==='g'),teaspoon=profile.measures.find(item=>item.key==='tsp');assert.equal(teaspoon.multiplier/grams.multiplier,5);for(const key of ['tbsp','thinSpread','regularSpread','thickSpread'])assert.equal(profile.measures.some(item=>item.key===key),false);const session=guided.createSession([food],food.name,{intent:{kind:'exact-product'}});guided.selectMeasure(session,'g');guided.selectAmount(session,2.5);assert.equal(session.amount,2.5);});
test('12. liquid milk keeps arbitrary mL and the Australian 250 mL cup',()=>{const food=audit.api.toFood({id:'milk',sourceId:'milk',barcode:'9300000000001',name:'Example Fresh Milk',brand:'Example',brandKey:'example',genericName:'Milk',quantity:'2 L',countries:['en:australia'],categories:['Dairies','Milks'],servingSize:'250 mL',nutrients:{calories:50,energyKj:209,protein:3.5,carbs:5,fat:2},nutritionCompleteness:'complete'}),profile=guided.servingProfile(food),cup=profile.measures.find(item=>item.key==='cup'),millilitres=profile.measures.find(item=>item.key==='mL');assert.equal(cup.multiplier/millilitres.multiplier,250);const session=guided.createSession([food],food.name,{intent:{kind:'exact-product'}});guided.selectMeasure(session,'mL');guided.selectAmount(session,375);assert.equal(session.amount,375);});

test('13. production online append updates only the broader surface',()=>{const start=runtime.indexOf('function alpha0631RenderOnlineProgress'),end=runtime.indexOf('\nfunction ',start+10),block=runtime.slice(start,end);assert.ok(start>0&&end>start);assert.doesNotMatch(block,/renderLibrary\(/);assert.match(block,/renderAllResourcesOnlineAppendOnly/);assert.match(block,/psSearchRevisionCurrent/);});
test('14. production large-search awaits are guarded by token, revision and current input',()=>{const start=runtime.indexOf('async function psLargeSearch'),end=runtime.indexOf('\nfunction ',start+10),block=runtime.slice(start,end);assert.ok(start>0&&end>start);assert.ok((block.match(/psSearchRevisionCurrent/g)||[]).length>=2);assert.ok((block.match(/by\('food-search'\)/g)||[]).length>=2);assert.ok((block.match(/token!==psLargeSearchToken/g)||[]).length>=2);});
test('15. weak online shells are excluded from exact-product selection',()=>{const start=runtime.indexOf('function rc5ExactDecision'),end=runtime.indexOf('\n}',start)+2,block=runtime.slice(start,end);assert.match(block,/recordType\?\.\(exact\)!=='online-candidate'/);assert.match(block,/exactProductQuality/);assert.match(runtime,/const ps33ExactProductBase=rc4ExactProduct;rc4ExactProduct=function\(raw\).*online-candidate.*exactProductQuality/);});
test('16. recovery production modules contain no named-brand resolver branches',()=>{for(const file of ['food-catalogue.js','guided-product-resolution.js','serving-foundation.js']){const source=fs.readFileSync(path.join(ROOT,file),'utf8');for(const brand of ['Flora','Meadow Lea','Trim Milk','Pauls'])assert.doesNotMatch(source,new RegExp(`(?:query|brand|name)\\s*={2,3}\\s*['\"]${brand}['\"]`,'i'),`${file}: ${brand}`);}});
test('17. mobile safeguards retain bounded choices, stable caret and unresolved-action suppression',()=>{const styles=fs.readFileSync(path.join(ROOT,'styles.css'),'utf8');assert.match(styles,/guided-resolution-card\{[^}]*max-width:100%/);assert.match(styles,/guided-resolution-choice\{[^}]*min-height:48px/);assert.match(runtime,/setSelectionRange\(caret,caret\)/);assert.match(styles,/body\.guided-product-unresolved #resource-add-button[^}]*display:none!important/);});
test('18. catalogue manifest remains the approved production-scale snapshot',()=>{assert.equal(manifest.importedProducts,73300);assert.equal(manifest.searchableProducts,70832);assert.equal(manifest.uniqueBrands,12239);assert.equal(manifest.validGtins,72671);assert.equal(manifest.sourceSnapshotDate,'2026-08-30');assert.equal(manifest.sourceSha256,'F72687EE8BC6522054FE69DBFDA6B91902C16AF1EC2E043CDE27BC6C29AD8176');});
