'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const registry=require('../entity-registry'),C=require('../food-catalogue'),qa=require('../scripts/audit_physical_form_measures_edge');
const source=fs.readFileSync(path.join(__dirname,'../off-catalogue.js'),'utf8');
function fixture({missing=false,corrupt=false,productsPerBrand=1}={}){
  const names=['Acorn','Ácorn','Cote','Côte','Eclair','Éclair','Burgen','Bürgen','Häagen-Dazs','Haagen-Dazs'],files={},requests=[];
  // Independent reproduction of the protected import's ASCII token addresses.
  names.forEach((name,i)=>{const key=(name.toLowerCase().match(/[a-z0-9]+/g)||[]).join(''),file=`intelligence/${(key+'__').slice(0,2)}.json`;files[file] ||= {brands:{}};files[file].brands[key]={name,refs:Array.from({length:productsPerBrand},(_,j)=>`fixture:${i*productsPerBrand+j}`),names:{},facets:[]};});
  files['manifest.json']={intelligenceShards:Object.keys(files).map(path=>({path}))};
  const context={HECAustralianEntityRegistry:registry,HECAustralianCatalogueData:{brands:names.map(name=>({name,count:productsPerBrand}))},fetch:async url=>{const file=String(url).replace('./data/open-food-facts-au/','');requests.push(file);return {ok:!!files[file]&&!(missing&&file==='intelligence/ac.json'),status:missing?404:files[file]?200:404,json:async()=>{if(corrupt&&file==='intelligence/ac.json')throw Error('Invalid shard JSON');return files[file];}};}};
  vm.runInNewContext(source,context);return {api:context.HECOpenFoodFactsAU,requests,files,names};
}
for(const [input,key,prefix]of [['Acorn','acorn','ac'],['Ácorn','corn','co'],['Eclair','eclair','ec'],['Éclair','clair','cl'],['Cote','cote','co'],['Côte','cte','ct']])test(`historical storage address for ${input} is ASCII and identity remains exact`,async()=>{
  const f=fixture();assert.equal(f.api.historicalBrandIndexKey(input),key);assert.equal(f.api.intelligencePath(key),`intelligence/${prefix}.json`);const entry=await f.api.exactBrandRefs(input);assert.equal(entry.name,input);assert.equal(entry.refs[0],`fixture:${f.names.indexOf(input)}`);assert(f.requests.includes(`intelligence/${prefix}.json`));assert(f.requests.every(file=>!/[^\x00-\x7f]/.test(file)));
});
test('NFC/NFD input shares only the explicitly identified source entry',async()=>{const f=fixture();for(const input of ['Éclair','E\u0301clair']){const entry=await f.api.exactBrandRefs(input);assert.equal(entry.name,'Éclair');}assert.notEqual(C.brandKey('Éclair'),C.brandKey('Eclair'));assert.equal(f.api.intelligencePath('éclair'),null);});
for(const [a,b,count]of [['Burgen','Bürgen',2],['Häagen-Dazs','Haagen-Dazs',2]])test(`${a} approved storage addresses preserve family retrieval and fresh query ownership`,async()=>{
  const f=fixture(),first=await f.api.exactBrandRefs(a),before=f.requests.length,second=await f.api.exactBrandRefs(b);assert.equal(first.refs.length,count);assert.deepEqual(Array.from(first.refs),Array.from(second.refs));assert.equal(f.requests.length,before);const state=C.newFederatedSearchState(),old=C.beginQueryRevision(state,a);assert(C.beginQueryRevision(state,b)>old);assert(!C.revisionMatches(state,old,a));
});
test('shorter accented prefixes use historical ASCII addresses without authorizing an alias',async()=>{const f=fixture({productsPerBrand:2});const entry=await f.api.recogniseBrand('Éclair Market');assert.equal(entry.name,'Éclair');assert.equal(entry.residual,'market');const first=f.names.indexOf('Éclair')*2;assert.deepEqual(Array.from(entry.refs),[`fixture:${first}`,`fixture:${first+1}`]);assert(f.requests.includes('intelligence/cl.json'));assert.equal(await f.api.exactBrandRefs('Éclair Market'),null);assert.equal(await f.api.exactBrandRefs('Clair'),null);assert(f.requests.every(file=>!/[^\x00-\x7f]/.test(file)));});
test('a minimal single-product brand supports exact lookup without inventing a broader prefix match',async()=>{const f=fixture(),exact=await f.api.recogniseBrand('Éclair');assert.equal(exact.name,'Éclair');assert.deepEqual(Array.from(exact.refs),[`fixture:${f.names.indexOf('Éclair')}`]);assert.equal(await f.api.recogniseBrand('Éclair Market'),null);});
test('unlisted intelligence prefix is an empty lookup without an asset request',async()=>{const f=fixture();assert.equal(await f.api.exactBrandRefs('Zzunknown'),null);assert.deepEqual(f.requests,['manifest.json']);assert.equal(await f.api.exactBrandRefs('Zzunknown'),null);assert.deepEqual(f.requests,['manifest.json']);});
test('listed required intelligence shard failure propagates instead of becoming no matches',async()=>{await assert.rejects(fixture({missing:true}).api.exactBrandRefs('Acorn'),/OFF catalogue 404/);await assert.rejects(fixture({corrupt:true}).api.exactBrandRefs('Acorn'),/Invalid shard JSON/);});
test('routing classification keeps required assets strict and optional misses narrowly bounded',()=>{
  const manifest={intelligenceShards:[{path:'intelligence/ac.json'}],searchShards:[],barcodeShards:[]};
  assert.equal(qa.localAssetDisposition('alpha06.js',true,manifest),'local-asset');
  for(const file of ['alpha06.js','data/open-food-facts-au/intelligence/ac.json','data/open-food-facts-au/intelligence/hä.json','data/open-food-facts-au/products/zz.json','data/open-food-facts-au/intelligence/../../../alpha06.js'])assert.equal(qa.localAssetDisposition(file,false,manifest),'required-local-missing',file);
  assert.equal(qa.localAssetDisposition('data/open-food-facts-au/intelligence/zz.json',false,manifest),'optional-local-miss');
  assert.equal(qa.localAssetDisposition('data/open-food-facts-au/intelligence/zz.json',false,{}),'required-local-missing');
});
async function routerHarness(){const events={},report=qa.evidence();let handler;const context={on:(name,fn)=>events[name]=fn,route:async(pattern,fn)=>{handler=fn;}};await qa.contextFor({newContext:async options=>{assert.equal(options.serviceWorkers,'block');return context;}},{width:320,height:568},report);return {report,async request(relative){const url=qa.ORIGIN+'/'+relative,request={url:()=>url};events.request(request);await handler({request:()=>request,fulfill:async response=>events.response({url:()=>url,request:()=>request,status:()=>response.status,fromServiceWorker:()=>false}),abort:async()=>{}});return request;}};}
test('a locally generated required-asset 502 is fatal but is not live fallthrough',async()=>{const h=await routerHarness();await h.request('missing-required-acceptance-asset.js');assert.equal(h.report.localResponses,1);assert.equal(h.report.localFulfilled,0);assert.equal(h.report.requiredAssetMisses.length,1);assert.equal(h.report.liveFallthrough,0);assert.throws(()=>qa.requireEvidence(h.report));});
test('successful local responses satisfy strict accounting',async()=>{const h=await routerHarness();await h.request('index.html');assert.equal(h.report.localFulfilled,1);assert.equal(h.report.optionalLocalMisses.length,0);qa.requireEvidence(h.report);});
test('optional local 404 is counted separately and handled by production as an empty posting lookup',async()=>{
  const root=path.join(__dirname,'../data/open-food-facts-au'),manifest=JSON.parse(fs.readFileSync(path.join(root,'manifest.json'),'utf8')),listed=new Set(manifest.searchShards.map(item=>item.path));let relative;
  for(const a of 'abcdefghijklmnopqrstuvwxyz')for(const b of 'abcdefghijklmnopqrstuvwxyz'){const candidate=`search/${a+b}.json`;if(!relative&&!listed.has(candidate)&&!fs.existsSync(path.join(root,candidate)))relative=candidate;}
  assert(relative);const h=await routerHarness();await h.request('data/open-food-facts-au/'+relative);assert.equal(h.report.optionalLocalMisses.length,1);assert.equal(h.report.requiredAssetMisses.length,0);assert.equal(h.report.liveFallthrough,0);qa.requireEvidence(h.report);
  const f=fixture(),query=path.basename(relative,'.json')+'unknown';assert.equal((await f.api.postingRefs(query)).refs.length,0);assert(f.requests.includes(relative));
});
test('an unhandled response or service-worker response remains fatal live fallthrough',()=>{for(const fromServiceWorker of [false,true]){const report=qa.evidence(),request={},routed=fromServiceWorker?new Set([request]):new Set();qa.recordResponse(report,request,routed,{url:qa.ORIGIN+'/',status:200,fromServiceWorker});assert.equal(report.liveFallthrough,1);assert.throws(()=>qa.requireEvidence(report));}});
