'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),S=require('../search-foundation'),REG=require('../entity-registry');
const runtime=fs.readFileSync(require.resolve('../alpha06.js'),'utf8'),section=runtime.slice(runtime.indexOf('function alpha0627GenericHeadSuggestions('),runtime.indexOf('function alpha0627SourceModeFromQuery('));
function harness(foods,registry={predict:()=>[]}){const ctx={Intl,S23:S,REG29:registry,s23Singular:S.singular,s23Norm:S.norm,s23Title:S.title,s23Parsed:S.parseQuery,s23ProductLike:f=>!!f.product,s23Head:f=>S.singular(f.name.split(',')[0]),allFoods:()=>foods};vm.createContext(ctx);vm.runInContext(section+'\nglobalThis.get=(q,n,live)=>alpha0627ConceptSuggestions(q,n,{liveAlphabetical:live});',ctx);return (q,n=7,live=true)=>JSON.parse(JSON.stringify(ctx.get(q,n,live)));}
const names=['Bar','Bacon','Banana','Bagel','Basil','Barley','Baked Bean','Banana Chip','Baby Food','Bácon'];
test('live ordinary candidates are alphabetic after dedupe and before either candidate/display truncation',()=>{const rows=names.map(name=>({name})),get=harness(rows),result=get('Ba',4);assert.deepEqual(result.map(x=>x.label),['Baby Food','Bacon','Bagel','Baked Bean']);assert.equal(get('Ba',30).filter(x=>S.norm(x.label)==='bacon').length,1);assert(!result.some(x=>x.kind==='entity'));});
test('ordinary ordering ignores source insertion, length scores, usage and popularity',()=>{const foods=names.map((name,i)=>({name,usage:1000-i,score:9999-i,popularity:i})),before=JSON.stringify(foods);assert.deepEqual(harness(foods)('Ba'),harness([...foods].reverse())('Ba'));assert.equal(JSON.stringify(foods),before);const full=harness(foods)('Ba',30).map(x=>x.label);assert(full.indexOf('Bacon')<full.indexOf('Banana'));assert(full.indexOf('Banana')<full.indexOf('Bar'));});
test('Ban and Bac narrow the existing legitimate prefix candidates',()=>{const get=harness(names.map(name=>({name})));assert.deepEqual(get('Ban').map(x=>x.label),['Banana','Banana Chip']);assert.deepEqual(get('Bac').map(x=>x.label),['Bacon']);for(const q of ['Ba','Ban','Bac'])for(const row of get(q,30))assert(S.norm(row.label).startsWith(S.norm(q)));});
test('general rule preserves alias matching and normalized visible duplicates',()=>{const get=harness(['Pear Tart','Peanut','Pear','Péanut','Peach','Pea','Pepper'].map(name=>({name})));assert.deepEqual(get('Pe',30).map(x=>x.label),['Capsicum','Pasta','Pea','Peach','Peanut','Pear','Pear Tart','Pepper']);assert.equal(get('Pe',30).filter(x=>S.norm(x.label)==='peanut').length,1);});
test('entity treatment and default non-live ranking remain independent',()=>{const get=harness(names.map(name=>({name})));assert.equal(get('Ba',7,false)[0].label,'Banana');assert.equal(get('Ba')[0].label,'Baby Food');const entity=harness(names.map(name=>({name})),{predict:()=>[{entity:{id:'z-brand',name:'Z Brand',type:'brand'}}]});assert.equal(entity('Ba')[0].kind,'entity');assert.equal(entity('Ba')[1].label,'Baby Food');assert.equal((runtime.match(/liveAlphabetical:true/g)||[]).length,1);assert(runtime.includes('alpha0627ConceptSuggestions(raw,6)'));});
test('approved brand spellings and distinct unapproved identities are preserved',()=>{assert.equal(REG.brandSearchKey('Nescafé'),REG.brandSearchKey('Nescafe'));assert.equal(REG.brandSearchKey('Bürgen'),REG.brandSearchKey('Burgen'));assert.notEqual(REG.brandSearchKey('Côte'),REG.brandSearchKey('Cote'));assert.equal(REG.brandSearchKey('Häagen-Dazs'),REG.brandSearchKey('Haagen-Dazs'));assert(REG.primary('Weet-Bix',['brand']));});
test('alphabetical live phone flow, query ownership and accepted product guards',{timeout:240000},async()=>{await require('../scripts/audit_live_prefix_alphabetical_edge').run({outputDirectory:process.env.HEC_PREFIX_EDGE_OUTPUT});});
