'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const qa=require('../scripts/audit_physical_form_measures_edge'),{returningProfile}=require('../scripts/audit_navigation_startup_edge');
const P=require('../packaged-foods');require('../product-serving-semantics');require('../serving-foundation');const X=require('../capture-foundation');
const stored=page=>page.evaluate(()=>JSON.parse(localStorage.getItem(HEC_APP.functionalStorageKey)));
const entries=state=>Object.values(state.diary||{}).flat();
const action=(page,kind)=>page.locator('[data-capture-source="ocr"][data-capture-action="'+kind+'"]');
async function fill(page,values){for(const [id,value] of Object.entries(values)){const field=page.locator('#'+id);if(await field.evaluate(n=>n.tagName==='SELECT'))await field.selectOption(String(value));else await field.fill(String(value));}}
async function values(page,expected){for(const [id,value] of Object.entries(expected))assert.equal(await page.locator('#'+id).inputValue(),String(value),id);}
async function start(page){await page.evaluate(()=>openAlpha05Feature('scan-centre'));await page.locator('[data-scan-mode="label"]').click();await page.locator('#capture-new-active').click();await page.locator('#capture-manual').click();}
async function frames(page){await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));}
async function reachable(page,selector){const field=page.locator(selector);await field.scrollIntoViewIfNeeded();const box=await field.evaluate(n=>{const r=n.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return {left:r.left,right:r.right,top:r.top,bottom:r.bottom,width:innerWidth,height:innerHeight,tap:r.height,hit:hit===n||n.contains(hit),overflow:document.documentElement.scrollWidth>innerWidth+1,label:n.labels?.length||n.getAttribute('aria-label')||n.textContent};});assert(box.left>=0&&box.right<=box.width+1&&box.top>=0&&box.bottom<=box.height&&box.hit,JSON.stringify({selector,...box}));assert.equal(box.overflow,false);assert(box.tap>=44,selector+' target height '+box.tap);assert(box.label,selector+' needs a label');}
async function photo(page,text){await page.evaluate(text=>{window.Tesseract={createWorker:async()=>({setParameters:async()=>{},recognize:async()=>({data:{text,confidence:95}}),terminate:async()=>{}})};},text);await page.locator('#scan-image').setInputFiles({name:'manual-fixture.svg',mimeType:'image/svg+xml',buffer:Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="300" height="300"><rect width="300" height="300" fill="white"/></svg>')});await page.waitForFunction(()=>document.activeElement.id==='run-label-ocr');await page.locator('#run-label-ocr').click();await page.waitForFunction(()=>!document.querySelector('#run-label-ocr').disabled);}
async function reviewSaved(page,id){await page.evaluate(()=>openAlpha05Feature('food-library'));await page.locator('[data-library-tab="saved"]').click();await page.locator('#food-results [data-food-details="'+id+'"]').click();await page.locator('[data-review-product-nutrition="'+id+'"]:visible').click();}

for(const viewport of [{width:390,height:844},{width:320,height:568}])test('manual-only and partial prefill workflows at '+viewport.width+'x'+viewport.height,{timeout:180000},async()=>{
 const report=qa.evidence(),{chromium,edge}=qa.browserTools(),browser=await chromium.launch({headless:true,executablePath:edge}),output=fs.mkdtempSync(path.join(os.tmpdir(),'hec-manual-'+viewport.width+'-'));let page;
 try{
  const context=await qa.contextFor(browser,viewport,report);await context.addInitScript(returningProfile);page=await context.newPage();await page.goto(qa.ORIGIN+'/');await page.waitForFunction(()=>HECRelease.snapshot().state==='ready');
  await start(page);await frames(page);assert.equal(await page.evaluate(()=>document.activeElement.id),'ocr-food-name');
  assert(await page.locator('#ocr-serving-details').evaluate(n=>n.open));assert(await page.locator('#ocr-advanced').evaluate(n=>n.open));assert.match(await page.locator('#capture-manual-guidance').innerText(),/Type.*packet/i);
  for(const id of ['capture-manual','ocr-food-name','ocr-food-brand','ocr-serving-amount','ocr-serving-unit','ocr-servings-per-pack','ocr-pack-size','ocr-serving-count','ocr-serving-count-unit','ocr-selected-basis'])await reachable(page,'#'+id);
  await fill(page,{'ocr-food-name':'Example Crackers','ocr-food-brand':'Synthetic Fixture','ocr-serving-amount':25,'ocr-serving-unit':'g','ocr-servings-per-pack':8,'ocr-pack-size':'200 g','ocr-serving-count':4,'ocr-serving-count-unit':'cracker','ocr-selected-basis':'perServing'});
  await page.locator('#ocr-serving-count-unit').selectOption('');assert.equal(await page.locator('#ocr-serving-count').evaluate(n=>n.classList.contains('capture-required')),false);assert.equal(await page.locator('#ocr-serving-count-unit').evaluate(n=>n.classList.contains('capture-required')),true);await page.locator('#ocr-serving-count-unit').selectOption('cracker');assert.match(await page.locator('#ocr-review-status').innerText(),/Enter energy for one serve.*packet/i);assert(await action(page,'save').isDisabled());
  await page.locator('#ocr-serving-details').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(output,'manual-serving.png')});
  await page.setViewportSize({width:viewport.width,height:330});await fill(page,{'ocr-energy-kj':420,'ocr-calories':100,'ocr-protein':2,'ocr-fat':3,'ocr-sat-fat':.5,'ocr-carbs':15,'ocr-sugar':1,'ocr-fibre':1.5,'ocr-sodium':120});
  await reachable(page,'#ocr-sodium');await page.setViewportSize(viewport);
  await fill(page,{'ocr100-energy-kj':1680,'ocr100-calories':400,'ocr100-protein':8,'ocr100-fat':12,'ocr100-sat-fat':2,'ocr100-carbs':60,'ocr100-sugar':4,'ocr100-fibre':6,'ocr100-sodium':480});
  await page.locator('#ocr-optional-nutrients').evaluate(n=>n.open=true);await fill(page,{'ocr-calcium':'  ','ocr-iron':'0','ocr100-iron':'0'});
  for(const id of ['ocr-energy-kj','ocr100-energy-kj','ocr-calories','ocr100-calories','ocr-calcium','ocr100-calcium'])await reachable(page,'#'+id);
  assert.equal(await page.locator('.ocr-raw-details').evaluate(n=>n.open),false);assert.equal(await page.locator('#ocr-text').inputValue(),'');
  await page.locator('#ocr-package-confirmed').check();assert(await action(page,'both').isEnabled());await page.setViewportSize({width:viewport.width,height:330});await reachable(page,'[data-capture-source="ocr"][data-capture-action="both"]');await action(page,'both').click();await page.setViewportSize(viewport);
  await fill(page,{'capture-amount':4,'capture-amount-unit':'cracker'});await page.locator('#capture-amount-review').click();assert.equal(await page.locator('#entry-unit').inputValue(),'cracker');await page.locator('#entry-meal').selectOption('Lunch');await page.locator('#save-food-entry').click();
  let state=await stored(page),entry=entries(state).at(-1),food=state.customFoods.find(f=>f.id===entry.foodId);assert.equal(entry.nutrients.calories,100);assert.equal(entry.nutrients.sodium,120);assert.equal(entry.foodSnapshot.nutrients.calcium,null);assert.equal(entry.foodSnapshot.nutrients.iron,0);assert.equal(food.nutritionBasis.servingCount,4);assert.equal(food.nutritionBasis.per100.calories,400);assert.equal(food.nutrients.calcium,null);assert.equal(food.nutrients.iron,0);assert.equal(food.nutritionBasis.per100.calcium,null);assert.equal(food.nutritionBasis.per100.iron,0);
  await reviewSaved(page,food.id);await values(page,{'ocr-serving-count':4,'ocr-serving-count-unit':'cracker','ocr-calcium':'','ocr-iron':0,'ocr100-calcium':'','ocr100-iron':0,'ocr-calories':100,'ocr100-calories':400});
  const before=JSON.stringify((await stored(page)).customFoods);await page.locator('#capture-manual').click();await fill(page,{'ocr-food-name':'Unfinished edit','ocr-calories':101});await page.locator('#capture-cancel').click();assert(await page.locator('#food-library.active').isVisible());assert.equal(JSON.stringify((await stored(page)).customFoods),before);
  await start(page);await fill(page,{'ocr-food-name':'Synthetic Partial Bread'});await photo(page,'Serving size: 67 g (2 slices)');await values(page,{'ocr-serving-amount':67,'ocr-serving-count':2,'ocr-serving-count-unit':'slice','ocr-energy-kj':'','ocr-calories':''});
  await page.locator('#capture-manual').click();await frames(page);assert.equal(await page.evaluate(()=>document.activeElement.id),'ocr-selected-basis');await page.locator('#ocr-selected-basis').selectOption('perServing');await page.locator('#capture-manual').click();assert.equal(await page.evaluate(()=>document.activeElement.id),'ocr-energy-kj');await values(page,{'ocr-serving-amount':67,'ocr-serving-count':2,'ocr-serving-count-unit':'slice'});
  await fill(page,{'ocr-servings-per-pack':10.5,'ocr-energy-kj':697,'ocr-calories':166,'ocr100-energy-kj':1040,'ocr100-calories':243,'ocr-sodium':255,'ocr100-sodium':380});await page.locator('#capture-manual').click();assert.equal(await page.evaluate(()=>document.activeElement.id),'ocr-protein');
  await page.locator('#ocr-package-confirmed').check();assert(await action(page,'save').isEnabled());await page.waitForFunction(()=>getComputedStyle(document.querySelector('#a05-action-toast')).opacity==='0');await page.locator('#ocr-energy-kj').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(output,'partial-nutrition.png')});await action(page,'save').click();
  state=await stored(page);food=state.customFoods.find(f=>f.name==='Synthetic Partial Bread');assert(food);assert.equal(food.nutritionBasis.perServing.energyKj,697);assert.equal(food.nutritionBasis.per100.calories,243);assert.equal(food.nutritionBasis.per100.sodium,380);assert.equal(food.nutritionBasis.servingCount,2);assert.equal(food.captureEvidence.extracted.perServing.calories,null);
  for(const key of ['protein','fat','satFat','carbs','sugar','fibre','calcium','iron','potassium']){assert.equal(food.nutrients[key],null,key);assert.equal(food.nutritionBasis.per100[key],null,key);}
  await reviewSaved(page,food.id);await values(page,{'ocr-serving-amount':67,'ocr-serving-count':2,'ocr-servings-per-pack':10.5,'ocr-calories':166,'ocr100-calories':243,'ocr-sodium':255,'ocr100-sodium':380,'ocr-protein':''});
  const snapshot=JSON.stringify((await stored(page)).customFoods);await fill(page,{'ocr-sodium':999});await page.locator('#scan-centre [data-hec-back]').click();assert.equal(JSON.stringify((await stored(page)).customFoods),snapshot);assert(await page.locator('#food-library.active').isVisible());await page.evaluate(()=>openAlpha05Feature('scan-centre'));await page.locator('#capture-resume-draft').click();assert.equal(await page.locator('#ocr-sodium').inputValue(),'999');await page.locator('#capture-cancel').click();assert.equal(JSON.stringify((await stored(page)).customFoods),snapshot);
  qa.requireEvidence(report);console.log('Manual capture evidence: '+output);
 }catch(error){if(page)await page.screenshot({path:path.join(output,'failure.png'),fullPage:true});console.error('Manual capture evidence: '+output);throw error;}finally{await browser.close();}
});

test('private/barcode manual entry preserves trusted sachet, water and provenance; prepared reference stays separate',{timeout:120000},async()=>{
 const report=qa.evidence(),{chromium,edge}=qa.browserTools(),browser=await chromium.launch({headless:true,executablePath:edge});
 try{
  const context=await qa.contextFor(browser,{width:320,height:568},report);await context.addInitScript(returningProfile);
  const saved=X.buildPanelFood({id:'synthetic-private-manual',name:'Synthetic Sachet Drink',brand:'Fixture Brand',barcode:'9900000000791',confirmed:true,model:P.basisModel({servingAmount:12.5,servingUnit:'g',manufacturerServing:true,servingCount:1,servingCountUnit:'sachet',perServing:{calories:47,fat:0},selectedBasis:'perServing',waterPreparation:true})}).food;assert(saved);
  await context.addInitScript(saved=>{if(location.origin==='https://mlwes-hec-test.github.io')localStorage.setItem('healthyEatingCompanionTestAlpha06Functional',JSON.stringify({customFoods:[saved],savedFoodIds:[saved.id],onlineFoods:[],ui:{}}));},saved);
  await context.route('**/api/v2/product/**',route=>route.fulfill({json:{status:1,product:{code:saved.barcode,product_name:saved.name,brands:saved.brand,serving_size:'12.5 g',serving_quantity:12.5,serving_quantity_unit:'g',nutriments:{'energy-kcal_serving':47,proteins_serving:'  ',fat_serving:0,sugars_serving:'unreadable'}}}}));
  const page=await context.newPage();await page.goto(qa.ORIGIN+'/');await page.waitForFunction(()=>HECRelease.snapshot().state==='ready');await page.evaluate(()=>openAlpha05Feature('scan-centre'));await page.locator('[data-scan-mode="barcode"]').click();await page.locator('#manual-barcode-details').evaluate(n=>n.open=true);await fill(page,{'scan-barcode-input':saved.barcode});await page.evaluate(()=>{const overlay=HECCaptureFoundation.privateServingOverlay;HECCaptureFoundation.privateServingOverlay=(food,saved)=>{window.syntheticBarcodeBaseline=food;return overlay(food,saved);};});await page.locator('#lookup-barcode').click();await page.locator('[data-compare-barcode-panel]').waitFor();
  const catalogue=await page.evaluate(()=>window.syntheticBarcodeBaseline);assert.equal(catalogue.nutrients.protein,null);assert.equal(catalogue.nutrients.sugar,null);assert.equal(catalogue.nutrients.fat,0);
  await page.locator('[data-compare-barcode-panel]').click();await page.locator('#capture-manual').click();await frames(page);
  await values(page,{'ocr-food-name':saved.name,'ocr-food-brand':saved.brand,'scan-barcode-input':saved.barcode,'ocr-serving-amount':12.5,'ocr-serving-unit':'g','ocr-serving-count':1,'ocr-serving-count-unit':'sachet','ocr-calories':47,'ocr-energy-kj':'','ocr-protein':'','ocr-fat':0,'ocr-sodium':'','ocr-preparation-liquid':'water'});
  assert(await page.locator('#ocr-water-preparation').isChecked());assert.equal(await page.locator('#ocr-calories').getAttribute('aria-invalid'),'false');
  const baseline=JSON.stringify((await stored(page)).customFoods);await fill(page,{'ocr-sodium':51,'ocr-serving-count':2});assert.equal(JSON.stringify((await stored(page)).customFoods),baseline);await fill(page,{'ocr-serving-count':1,'ocr-per100-context':'as-prepared','ocr-per100-unit':'mL','ocr100-calories':32});
  assert.match(await page.locator('#ocr-100-column').innerText(),/Per 100 mL As Prepared/);assert.equal(await page.locator('#ocr-optional-100-column').textContent(),'Per 100 mL As Prepared');assert.equal(await page.locator('#ocr100-calories').getAttribute('aria-label'),'Energy (Cal) per 100 ml as prepared');
  await page.locator('#ocr-package-confirmed').check();await action(page,'save').click();const food=(await stored(page)).customFoods.find(f=>f.id===saved.id);assert.equal(food.nutritionBasis.servingAmount,12.5);assert.equal(food.nutritionBasis.servingCount,1);assert.equal(food.nutrients.calories,47);assert.equal(food.nutrients.fat,0);assert.equal(food.nutrients.protein,null);assert.equal(food.nutritionBasis.per100.calories,32);assert.equal(food.nutritionBasis.per100Context,'as-prepared');assert.equal(food.nutritionBasis.per100Unit,'mL');assert.equal(food.preparation.type,'water');assert.equal(food.captureEvidence.extracted,null);assert(food.captureEvidence.previous);assert.equal(food.captureEvidence.catalogue.nutrients.protein,null);
  assert.deepEqual(await page.evaluate(()=>window.syntheticBarcodeBaseline),catalogue);
  await reviewSaved(page,food.id);await values(page,{'ocr-calories':47,'ocr100-calories':32,'ocr-per100-context':'as-prepared','ocr-per100-unit':'mL','ocr-serving-count':1,'ocr-serving-count-unit':'sachet','ocr-sodium':51,'ocr-protein':''});
  qa.requireEvidence(report);
 }finally{await browser.close();}
});

test('unread panel, blank energy, printed zero and per-100 mL manual-only gate',{timeout:120000},async()=>{
 const report=qa.evidence(),{chromium,edge}=qa.browserTools(),browser=await chromium.launch({headless:true,executablePath:edge});
 try{
  const context=await qa.contextFor(browser,{width:390,height:844},report);await context.addInitScript(returningProfile);const page=await context.newPage();await page.goto(qa.ORIGIN+'/');await page.waitForFunction(()=>HECRelease.snapshot().state==='ready');await start(page);await fill(page,{'ocr-food-name':'Synthetic Zero Drink','ocr-food-brand':'Fixture Brand'});await photo(page,'Ingredients: water.');
  assert.match(await page.locator('#capture-field-issues').innerText(),/could not read enough.*Enter the values from the packet/);assert.equal(await page.locator('.ocr-raw-details').evaluate(n=>n.open),false);await page.locator('.ocr-raw-details').evaluate(n=>n.open=true);assert.match(await page.locator('#capture-parse-text').innerText(),/Retry.*Optional/);await page.locator('.ocr-raw-details').evaluate(n=>n.open=false);
  await page.locator('#capture-manual').click();await fill(page,{'ocr-selected-basis':'per100','ocr-per100-unit':'mL','ocr100-calories':'  '});await page.locator('#ocr-package-confirmed').check();assert(await action(page,'save').isDisabled());assert.match(await page.locator('#ocr-review-status').innerText(),/Enter energy for 100 mL from the packet/);
  await page.locator('#capture-manual').click();assert.equal(await page.evaluate(()=>document.activeElement.id),'ocr100-energy-kj');await fill(page,{'ocr100-energy-kj':0,'ocr100-sodium':0,'ocr100-protein':'  '});await page.locator('#ocr-package-confirmed').check();assert(await action(page,'save').isEnabled());await action(page,'save').click();
  const food=(await stored(page)).customFoods.find(f=>f.name==='Synthetic Zero Drink');assert(food);assert.equal(food.nutrients.calories,0);assert.equal(food.nutrients.sodium,0);assert.equal(food.nutrients.protein,null);assert.equal(food.nutritionBasis.per100.calories,null);assert(Object.values(food.nutritionBasis.perServing).every(v=>v===null));assert.equal(food.nutritionBasis.per100Unit,'mL');
  qa.requireEvidence(report);
 }finally{await browser.close();}
});
