const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const ROOT=path.resolve(__dirname,'..');
const auditModule=require('../scripts/audit_open_food_facts_au.js');
const catalogue=require('../food-catalogue.js');
const guided=require('../guided-product-resolution.js');
const manifest=auditModule.read('manifest.json');
const products=auditModule.allProducts(manifest);
let audit;
test.before(async()=>{audit=await auditModule.runAudit();});

test('1. complete Australian source subset meets production scale',()=>assert.ok(manifest.australianSourceRecords>=40000));
test('2. complete global source was scanned',()=>assert.equal(manifest.globalRecordsScanned,4532767));
test('3. source IDs are stable off barcode identities',()=>assert.ok(products.every(x=>x.id===`off:${x.barcode}`&&x.sourceId===x.id)));
test('4. no duplicate same-source barcode records exist',()=>assert.equal(new Set(products.map(x=>x.barcode)).size,products.length));
test('5. every record retains source provenance',()=>assert.ok(products.every(x=>x.source==='Open Food Facts'&&x.provenanceClass==='australian-external-catalogue')));
test('6. explicit Australian country scope is preserved',()=>assert.ok(products.every(x=>x.countries.includes('en:australia'))));
test('7. completeness classifications are exhaustive',()=>assert.equal(manifest.completeNutrition+manifest.partialNutrition+manifest.identityOnly,manifest.importedProducts));
test('8. exact barcode lookup resolves the source product',async()=>{const p=products.find(x=>x.name);assert.equal((await auditModule.api.lookupBarcode(p.barcode)).id,p.id);});
test('9. exact brand lookup exposes the measured brand universe',async()=>assert.equal((await auditModule.api.search('Flora')).total,30));
test('10. brand spacing normalization is generic',async()=>assert.equal((await auditModule.api.search('Meadow Lea')).total,(await auditModule.api.search('MeadowLea')).total));
test('11. product-name tokens retrieve real products',async()=>assert.ok((await auditModule.api.search('mini dim sim')).foods.some(x=>/mini dim sim/i.test(x.name))));
test('12. brand plus product finds a real exact identity',async()=>assert.ok((await auditModule.api.search('Golden Wok mini dim sim')).foods.some(x=>/golden wok/i.test(x.brand))));
test('13. generic terms retain thousands-scale results while adding category members',async()=>assert.ok((await auditModule.api.search('milk')).total>=3120));
test('14. serving sizes never create duplicate product IDs',()=>assert.equal(new Set(products.map(x=>x.id)).size,products.length));
test('15. generated active records contain no non-Australian country-only row',()=>assert.ok(products.every(x=>x.countries.some(v=>v==='en:australia'))));
test('16. company/source text cannot create consumer-brand membership',()=>{const entity={type:'brand',id:'flora',name:'Flora',aliases:[],familyAliases:[]};assert.equal(catalogue.consumerBrandMembership(entity,{brand:'Becel',source:'Flora Food Group'}).matches,false);});
test('17. real imported Flora member count is measured',()=>assert.equal(audit.queries.Flora.count,30));
test('18. every eligible Flora member is accessible',async()=>{const r=await auditModule.api.search('Flora',{limit:500});assert.equal(r.foods.length,r.total);});
test('19. safe cross-source barcode duplicates consolidate only in federation',()=>{const ext=auditModule.api.toFood(products.find(x=>x.name));const curated={...ext,id:'curated-copy',sourceReferences:[{source:'HEC'}]};assert.equal(auditModule.api.federate([curated],[ext]).length,1);});
test('20. Flora serving is absent before exact identity',async()=>{const foods=(await auditModule.api.search('Flora',{limit:10})).foods;const s=guided.createSession(foods,'Flora');assert.equal(s.selectedMeasure,null);assert.equal(s.amount,null);});
test('21. real Meadow Lea member count is measured',()=>assert.equal(audit.queries['Meadow Lea'].count,6));
test('22. MeadowLea and Meadow Lea resolve identically',()=>assert.equal(audit.queries.MeadowLea.count,audit.queries['Meadow Lea'].count));
test('23. deterministic retrieval audit samples 1000 real products',()=>assert.equal(audit.retrieval.sampled,1000));
test('24. strong identity top-10 retrieval exceeds 98 percent',()=>assert.ok(audit.retrieval.top10Percent>=98));
test('25. deterministic brand completeness audit samples 100 brands',()=>assert.equal(audit.brands.sampled,100));
test('26. all audited brand members remain accessible without contamination',async()=>{assert.equal(audit.brands.complete,100);assert.equal(audit.brands.contamination,0);let largest=null;for(const shard of manifest.brandShards)for(const [key,value] of Object.entries(auditModule.read(shard.path).brands))if(!largest||value.refs.length>largest.refs.length)largest={key,...value};const ids=new Set();for(let offset=0;offset<largest.refs.length;offset+=500){const page=await auditModule.api.search(largest.name,{offset,limit:500});assert.equal(page.total,largest.refs.length);page.foods.forEach(food=>{assert.equal(food.brandKey,largest.key);ids.add(food.id);});}assert.equal(ids.size,largest.refs.length);});
test('27. retail package size is identity metadata, not selected consumption',()=>{const food=auditModule.api.toFood(products.find(x=>x.quantity));assert.ok(food.packageSize);assert.notEqual(food.packageSize,food.amount);});
test('28. nutrition basis does not become selected amount',()=>{const record=products.find(x=>x.nutrients.calories&&x.nutrients.sodium!=null),food=auditModule.api.toFood(record),s=guided.createSession([food],food.name);assert.equal(s.amount,null);assert.equal(food.units.g,.01);assert.equal(food.nutrients.sodium,record.nutrients.sodium*1000);});
test('29. multi-product identity precedes serving',async()=>{const s=guided.createSession((await auditModule.api.search('Flora',{limit:20})).foods,'Flora');assert.equal(s.stage,guided.stages.IDENTITY);});
test('30. incomplete products never receive invented calories',()=>{const food=auditModule.api.toFood(products.find(x=>x.nutritionCompleteness==='identity-only'));assert.equal(food.nutrients.calories,undefined);});
test('31. full catalogue is not loaded or precached at startup',()=>{const sw=fs.readFileSync(path.join(ROOT,'service-worker.js'),'utf8');assert.doesNotMatch(sw,/products\/.*\.json/);});
test('32. product and search shards are loaded on demand',()=>{const source=fs.readFileSync(path.join(ROOT,'off-catalogue.js'),'utf8');assert.match(source,/load\(`products\/\$\{shard\}\.json`\)/);assert.match(source,/load\(`search\/\$\{prefix\(token\)\}\.json`\)/);});
test('33. runtime catalogue caching uses the active installation cache',()=>assert.match(fs.readFileSync(path.join(ROOT,'service-worker.js'),'utf8'),/OFF_CATALOGUE_PATH[\s\S]*cacheFirst/));
test('34. catalogue caching introduces no My Data cache name',()=>assert.doesNotMatch(fs.readFileSync(path.join(ROOT,'off-catalogue.js'),'utf8'),/my-data|HEC-MY-DATA/i));
test('35. Big Mac authoritative catalogue remains present',()=>assert.match(fs.readFileSync(path.join(ROOT,'mcdonalds-au-catalogue-data.js'),'utf8'),/Big Mac/));
test('36. McDonald’s sized Fries remain present',()=>assert.match(fs.readFileSync(path.join(ROOT,'mcdonalds-au-catalogue-data.js'),'utf8'),/"n":"Fries"[\s\S]*?"Large","sides\/large-fries\.html"/));
test('37. Hotcakes complete-meal contract remains present',()=>assert.match(fs.readFileSync(path.join(ROOT,'product-serving-semantics.js'),'utf8'),/complete-meal/));
test('38. Bunnings natural-item correction remains present',()=>assert.match(fs.readFileSync(path.join(ROOT,'alpha06.js'),'utf8'),/Bunnings-Style Sausage In Bread/));
test('39. Chiko canonical duplicate protection remains present',()=>{
  const chiko={id:'a',canonicalId:'local:chiko-roll',name:'Chiko Roll',brand:'Chiko',nutrients:{calories:313}};
  assert.equal(catalogue.dedupe([chiko,{...chiko,id:'b'}]).length,1);
});
test('40. generic Fries AFCD resolution remains present',()=>assert.match(fs.readFileSync(path.join(ROOT,'food-catalogue.js'),'utf8'),/generic-au-fries/));
test('41. focused mobile search remains bounded and paginated',()=>{const css=fs.readFileSync(path.join(ROOT,'styles.css'),'utf8'),runtime=fs.readFileSync(path.join(ROOT,'alpha06.js'),'utf8');assert.match(css,/food-search-compact/);assert.match(css,/off-load-more/);assert.match(runtime,/preview\.total<=500/);assert.match(runtime,/data-off-load-more/);});
test('42. Weight foundation is untouched and still loaded',()=>assert.match(fs.readFileSync(path.join(ROOT,'index.html'),'utf8'),/weight-progress-foundation\.js/));
