'use strict';

const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const catalogue=require('../food-catalogue.js');
const semantics=require('../product-serving-semantics.js');
const serving=require('../serving-foundation.js');
const conversation=require('../conversation-foundation.js');

const ROOT=path.join(__dirname,'..');
const read=file=>fs.readFileSync(path.join(ROOT,file),'utf8');
const runtime=read('alpha06.js'),styles=read('styles.css');
const floraPro={id:'flora-pro',canonicalId:'packaged:flora-proactiv-light-au',recordType:'packaged',name:'Flora ProActiv Light',brand:'Flora',market:'AU',country:'Australia',verified:true,verificationStatus:'verified',aliases:['flora proactiv light','proactiv light'],defaultAmount:1,defaultUnit:'serve',units:{serve:1,g:.1},unitLabels:{serve:'Serve (10 g)',g:'g'},serving:'1 serve (10 g)',manufacturerServing:{amount:10,unit:'g'},nutrients:{calories:37}};
const floraLight={id:'flora-light',canonicalId:'packaged:flora-light-au',recordType:'packaged',name:'Flora Light',brand:'Flora',market:'AU',country:'Australia',verified:true,verificationStatus:'verified',aliases:['flora light'],defaultAmount:1,defaultUnit:'serve',units:{serve:1,g:.1},unitLabels:{serve:'10 g Serve',g:'g'},serving:'1 serve (10 g)',manufacturerServing:{amount:10,unit:'g'},nutrients:{calories:43}};
const floraForeign={id:'flora-foreign',recordType:'online-candidate',name:'Flora Light Imported',brand:'Flora',market:'international',country:'United Kingdom',verified:false,defaultAmount:100,defaultUnit:'g',units:{g:.01},unitLabels:{g:'g'},serving:'100 g reference',nutrients:{calories:400},source:'Open Food Facts · Community Supplied'};
const chiko={id:'aussie-chiko-roll',canonicalId:'local:chiko-roll',name:'Chiko Roll',brand:'Chiko',market:'AU',country:'Australia',aliases:['chiko roll','chicko roll','chico roll','chicco roll','cheeko roll'],defaultAmount:1,defaultUnit:'roll',units:{roll:1,serve:1,g:1/162},unitLabels:{roll:'Roll (162 g)',serve:'Serving (1 roll)',g:'g'},serving:'1 roll (162 g)',nutrients:{calories:313,protein:9,fat:9.8,carbs:45.5,sodium:580},source:'Australian Retail Package Reference — verify current package'};
const bunnings={id:'aussie-bunnings-snag',name:'Bunnings-Style Sausage In Bread',brand:'Australian Sausage Sizzle Estimate',category:'Meals & Takeaway',country:'Australia',market:'AU',aliases:['bunnings sausage','bunnings snag','sausage sizzle'],productSemantics:{type:'single-item',confidence:'high'},foodGroupUnitPolicy:{allowed:false},defaultAmount:1,defaultUnit:'item',units:{item:1,g:1/145},unitLabels:{item:'Sausage in bread',g:'g'},serving:'1 sausage in bread (about 145 g)',nutrients:{calories:285,energyKj:1192,protein:12,carbs:25,fat:15},source:'Australian Sausage-Sizzle Estimate — varies by sausage, bread, onion and sauce',ingredients:'Beef sausage, white bread; onion and sauce may be added'};

function productionFunction(name){const start=runtime.indexOf(`function ${name}(`);assert.notEqual(start,-1,`${name} exists`);let parenDepth=0,brace=-1,quote='',escaped=false;for(let index=runtime.indexOf('(',start);index<runtime.length;index++){const char=runtime[index];if(quote){if(escaped)escaped=false;else if(char==='\\')escaped=true;else if(char===quote)quote='';continue;}if(char==='"'||char==="'"||char==='`'){quote=char;continue;}if(char==='(')parenDepth++;if(char===')'&&--parenDepth===0){brace=runtime.indexOf('{',index);break;}}let depth=0;quote='';escaped=false;for(let index=brace;index<runtime.length;index++){const char=runtime[index];if(quote){if(escaped)escaped=false;else if(char==='\\')escaped=true;else if(char===quote)quote='';continue;}if(char==='"'||char==="'"||char==='`'){quote=char;continue;}if(char==='{')depth++;if(char==='}'&&--depth===0)return runtime.slice(start,index+1);}throw new Error(`Could not extract ${name}`);}
const viewportModel=new Function(`return (${productionFunction('rc6FocusedSearchModel')});`)();

test('1. Flora is recognised as reusable brand-family intent',()=>{const intent=catalogue.queryIntent('Flora');assert.equal(intent.kind,'brand-family');assert.equal(intent.entity.id,'flora');});
test('2. Flora brand-only intent does not substitute Flora Light as an exact product',()=>{const result=catalogue.resolve([floraLight,floraPro],'Flora');assert.equal(result.status,'brand-family');assert.equal(result.food,null);assert.deepEqual(result.candidates.map(food=>food.name),['Flora Light','Flora ProActiv Light']);});
test('3. Flora Light remains exact-first',()=>{const result=catalogue.resolve([floraPro,floraForeign,floraLight],'Flora Light');assert.equal(result.status,'exact');assert.equal(result.food,floraLight);});
test('4. Flora ProActiv Light and ProActiv Light remain exact-first at the 10 g serve',()=>{for(const query of ['Flora ProActiv Light','ProActiv Light']){const result=catalogue.resolve([floraLight,floraPro,floraForeign],query);assert.equal(result.food,floraPro,query);assert.equal(result.food.units.g,.1);}});
test('5. trusted current Australian Flora products exclude weak foreign results from the active guide',()=>{const family=catalogue.brandFamilyResults([floraForeign,floraLight,floraPro],'Flora');assert.deepEqual(family.products.map(food=>food.name),['Flora Light','Flora ProActiv Light']);assert.deepEqual(family.broader,[floraForeign]);assert.equal(family.activeTier,1);});
test('6. McDonald’s source-only intent remains distinct from product intent',()=>{assert.equal(catalogue.queryIntent("McDonald's").kind,'source');assert.equal(catalogue.queryIntent('Big Mac').kind,'product');});

test('7. canonical duplicate evidence identifies a true mirrored product',()=>{const mirror={...chiko,id:'cached-chiko',canonicalId:'barcode:9310081760092',recordType:'online-candidate',barcode:'9310081760092'};const evidence=catalogue.duplicateIdentityEvidence(chiko,mirror);assert.equal(evidence.duplicate,true);assert.equal(evidence.sameIdentity,true);assert.equal(evidence.sameNutrition,true);});
test('8. duplicate Chiko display records collapse without deleting either input',()=>{const mirror={...chiko,id:'cached-chiko',canonicalId:'barcode:9310081760092',recordType:'online-candidate',barcode:'9310081760092'};assert.equal(catalogue.dedupe([mirror,chiko]).length,1);assert.equal(mirror.id,'cached-chiko');assert.equal(chiko.id,'aussie-chiko-roll');});
test('9. same-name records with distinct provenance or nutrition remain separate',()=>{const distinct={...chiko,id:'different',canonicalId:'barcode:999',recordType:'online-candidate',source:'Different reviewed package',sourceUrl:'https://example.invalid/different',nutrients:{...chiko.nutrients,calories:330}};assert.equal(catalogue.duplicateIdentity(chiko,distinct),false);assert.equal(catalogue.dedupe([chiko,distinct]).length,2);assert.equal(catalogue.duplicateAudit([chiko,distinct]).distinctSameName.length,1);});
test('10. Chiko spelling aliases retain the canonical roll while plain Chiko remains a brand family',()=>{assert.equal(catalogue.resolve([chiko],'Chiko').status,'brand-family');for(const query of ['Chiko Roll','Chico Roll','Chicco Roll','Cheeko Roll'])assert.equal(catalogue.resolve([chiko],query).food,chiko,query);});

test('11. a branded composite single item rejects vegetable-serve leakage',()=>{const applied=serving.applyToFood(JSON.parse(JSON.stringify(bunnings)));assert.doesNotMatch(JSON.stringify(applied.unitLabels),/vegetable|australian standard/i);assert.equal(applied.servingPolicy.foodGroupUnitEligibility.allowed,false);});
test('12. a complete meal exposes only its complete-meal unit',()=>{const meal=semantics.applyToFood({name:'Example Meal with Sauce',productSemantics:{type:'complete-meal'},defaultAmount:1,defaultUnit:'standardServe',units:{standardServe:1,serve:1},unitLabels:{standardServe:'Australian standard vegetable serve',serve:'Serve'},serving:'1 meal',nutrients:{calories:400}});assert.deepEqual(meal.units,{meal:1});assert.equal(meal.defaultUnit,'meal');});
test('13. packaged Flora rejects food-group measures but retains serve and grams',()=>{const food={...floraPro,units:{...floraPro.units,standardServe:7.5},unitLabels:{...floraPro.unitLabels,standardServe:'Australian standard vegetable serve (75 g)'},unitOrigins:{standardServe:{origin:'Australian Dietary Guidelines'}}};const applied=serving.applyToFood(food);assert.deepEqual(Object.keys(applied.units).sort(),['g','serve']);});
test('14. a legitimate generic AFCD vegetable retains an explicitly derived guideline unit',()=>{const food=serving.applyToFood({id:'veg',afcd:true,recordType:'afcd',name:'Broccoli, cooked',brand:'Australian Food Composition Database',source:'AFCD',defaultAmount:100,defaultUnit:'g',units:{g:.01},unitLabels:{g:'g'},serving:'Reference per 100 g',nutrients:{calories:35}},{conceptCategory:'vegetable'});assert.equal(food.servingPolicy.allowedUnitFamily,'food-group-reference');assert.match(JSON.stringify(food.unitLabels),/vegetable|standard serve/i);});
test('15. Bunnings becomes one natural item with unchanged nutrient facts',()=>{const applied=serving.applyToFood(JSON.parse(JSON.stringify(bunnings)));assert.equal(applied.semanticType,'single-item');assert.equal(applied.defaultAmount,1);assert.equal(applied.defaultUnit,'item');assert.equal(applied.unitLabels.item,'Sausage in bread');assert.equal(applied.nutrients.calories,285);assert.match(runtime,/nutrient\(285,12,25,15,5,1\.5,5,780\)/);});

test('16. voice-equivalent Bunnings request resolves one natural item',()=>{const pending=conversation.parseRequest("Add one Bunnings sausage for tomorrow's lunch",{today:'2026-08-31',selectedDate:'2026-08-31',selectedMeal:''}),food=serving.applyToFood(JSON.parse(JSON.stringify(bunnings))),resolved=catalogue.resolve([food],pending.foodText);assert.equal(resolved.food.name,'Bunnings-Style Sausage In Bread');assert.equal(pending.quantity.amount,1);assert.equal(food.defaultUnit,'item');});
test('17. Bunnings future-date voice semantics remain tomorrow, Lunch and planned',()=>{const pending=conversation.parseRequest("Add one Bunnings sausage for tomorrow's lunch",{today:'2026-08-31',selectedDate:'2026-08-31',selectedMeal:''});assert.equal(pending.localDate,'2026-09-01');assert.equal(pending.meal,'Lunch');assert.equal(pending.status,'planned');});
test('18. dietary descriptors require explicit trustworthy metadata',()=>{assert.deepEqual(semantics.trustedDietaryDescriptors(bunnings),[]);assert.deepEqual(semantics.trustedDietaryDescriptors({...bunnings,dietaryClaims:['plant-based'],dietaryClaimsVerified:true}),['plant-based']);assert.doesNotMatch(JSON.stringify(serving.applyToFood(JSON.parse(JSON.stringify(bunnings)))),/plant-based|vegetarian|vegan/i);});

test('19. compact focused-search state activates only after a significant mobile VisualViewport reduction',()=>{const model=viewportModel({innerWidth:390,innerHeight:844,visualWidth:390,visualHeight:520,focused:true});assert.equal(model.compact,true);assert.equal(model.keyboardOpen,true);assert.equal(viewportModel({innerWidth:390,innerHeight:844,visualWidth:390,visualHeight:844,focused:true}).compact,false);});
test('20. compact mode removes large session actions and secondary library controls',()=>{assert.match(styles,/food-search-compact[\s\S]*?meal-entry-session-actions\{display:none!important\}/);for(const selector of ['library-scan-shortcuts','library-tabs','online-search-actions','online-food-status'])assert.match(styles,new RegExp(`food-search-compact[^}]*|${selector}`));});
test('21. active meal/date context remains visible as a compact line',()=>{assert.match(styles,/food-search-compact #food-library \.entry-context-banner\{display:block/);assert.match(styles,/entry-context-banner>span\{white-space:nowrap/);assert.match(runtime,/Adding to <strong>/);});
test('22. the first result receives a usable keyboard-visible result height',()=>{for(const [width,layoutHeight,visualHeight] of [[390,844,520],[390,844,460],[430,932,560]]){const model=viewportModel({innerWidth:width,innerHeight:layoutHeight,visualWidth:width,visualHeight,focused:true,contextHeight:34});assert.ok(model.availableHeight>=300,`${width}x${visualHeight}`);}assert.match(styles,/live-match-heading\+ \.live-match-row[\s\S]*?min-height:76px/);});
test('23. automatic positioning is one-shot on the keyboard transition',()=>{const source=productionFunction('rc6SyncFoodSearchViewport');assert.match(source,/!rc6FoodKeyboardWasOpen&&!rc6FoodKeyboardPositioned/);assert.equal((source.match(/scrollIntoView/g)||[]).length,1);assert.doesNotMatch(productionFunction('alpha0630HandleFoodSearchInput'),/scrollIntoView|scrollTo|scrollBy/);});
test('24. blur or keyboard dismissal restores full controls',()=>{assert.equal(viewportModel({innerWidth:390,innerHeight:844,visualWidth:390,visualHeight:520,focused:false}).compact,false);assert.match(runtime,/classList\.toggle\('food-search-compact',model\.compact\)/);assert.match(runtime,/if\(!focused\)rc6FoodKeyboardPositioned=false/);});
test('25. 390×844 layout remains horizontally bounded',()=>{const model=viewportModel({innerWidth:390,innerHeight:844,visualWidth:390,visualHeight:520,focused:true});assert.equal(model.width,390);assert.match(styles,/width:min\(100%,var\(--hec-visual-viewport-width,100vw\)\)/);assert.match(styles,/overflow-x:hidden/);});
test('26. 390×520 keyboard layout keeps result actions bounded',()=>{const model=viewportModel({innerWidth:390,innerHeight:844,visualWidth:390,visualHeight:520,focused:true,contextHeight:34});assert.equal(model.compact,true);assert.ok(model.availableHeight>=300);assert.match(styles,/live-match-row\{width:100%;max-width:100%;min-width:0/);});
test('27. 430×932 device width uses the same compact policy after keyboard shrink',()=>{const model=viewportModel({innerWidth:430,innerHeight:932,visualWidth:430,visualHeight:560,focused:true,contextHeight:34});assert.equal(model.compact,true);assert.equal(model.width,430);});
test('28. compact mode shows only the live surface, preventing cross-surface Chiko duplication',()=>{assert.match(styles,/food-search-compact #food-library #food-results[\s\S]*?display:none!important/);assert.match(runtime,/brandFamilyResults/);});
test('29. incremental Hotcakes, Flora and McMuffin typing does not alter the viewport state machine',()=>{for(const query of ['Hot','Hotc','Hotcakes','Fl','Flor','Flora','Saus','Sausage','Sausage and egg McMuffin'])assert.doesNotThrow(()=>catalogue.queryIntent(query));assert.doesNotMatch(productionFunction('rc6FocusedSearchModel'),/query|value|selection|caret/);});
test('30. exact and close product names retain readable wrapping',()=>{assert.match(styles,/semantic-exact-match[\s\S]*?-webkit-line-clamp:3/);assert.match(styles,/semantic-close-match[\s\S]*?-webkit-line-clamp:2/);assert.match(styles,/overflow-wrap:anywhere/);});
