'use strict';

const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const guided=require('../guided-product-resolution.js');
const serving=require('../serving-foundation.js');
const audit=require('../scripts/audit_progressive_food_resolution.js');

const ROOT=path.resolve(__dirname,'..');
const runtime=fs.readFileSync(path.join(ROOT,'alpha06.js'),'utf8');
const styles=fs.readFileSync(path.join(ROOT,'styles.css'),'utf8');
const policy=fs.readFileSync(path.join(ROOT,'PROGRESSIVE_FOOD_RESOLUTION_AND_PORTION_POLICY.md'),'utf8');
const food=(values={})=>({id:values.id||'fixture',canonicalId:values.id||'fixture',name:'Reviewed Food',brand:'Example',recordType:'packaged',market:'AU',verified:true,source:'Reviewed fixture source',defaultAmount:1,defaultUnit:'g',units:{g:.01},unitLabels:{g:'g'},nutrients:{calories:100,energyKj:418.4,protein:2},...values});
const spread=food({id:'spread',name:'Untested Seed Spread',physicalForm:'spread',category:'Spreads',categories:['Spreads'],units:{g:.01,serve:.1},unitLabels:{g:'g',serve:'Manufacturer Serve (10 g)'},manufacturerServing:{amount:10,unit:'g'}});
const liquid=food({id:'liquid',name:'Untested Fruit Drink',physicalForm:'liquid',category:'Beverages',defaultUnit:'mL',units:{mL:.01},unitLabels:{mL:'mL'},nutritionPer100Unit:'mL'});
const sliced=food({id:'sliced',name:'Untested Sliced Food',physicalForm:'sliced',units:{g:.01,slice:.3},unitLabels:{g:'g',slice:'Slice (30 g)'}});
const countable=food({id:'countable',name:'Untested Biscuit',physicalForm:'countable',defaultUnit:'biscuit',units:{g:.01,biscuit:.12},unitLabels:{g:'g',biscuit:'Biscuit (12 g)'},serving:'1 biscuit (12 g)'});
const profile=value=>serving.servingMeasureProfile(value);
const exact=value=>guided.createSession([value],value.name,{intent:{kind:'exact-product'}});
let scaleReport,untestedReport,generalizationReport;

test('P01 central vocabulary exposes stable IDs',()=>assert.deepEqual(['g','mL','tsp','cup','serve','item','slice'].map(key=>serving.PORTION_VOCABULARY[key].id),['g','mL','tsp','cup','serve','item','slice']));
test('P02 aliases normalize through one engine',()=>assert.deepEqual(['grams','millilitres','servings','slices'].map(serving.normalizeMeasure),['g','mL','serve','slice']));
test('P03 spread physical form is recognized',()=>assert.equal(profile(spread).physicalForm,'spread'));
test('P04 liquid physical form is recognized',()=>assert.equal(profile(liquid).physicalForm,'liquid'));
test('P05 sliced physical form is recognized',()=>assert.equal(profile(sliced).physicalForm,'sliced'));
test('P06 countable physical form is recognized',()=>assert.equal(profile(countable).physicalForm,'countable'));
test('P07 spread profile includes grams',()=>assert.ok(profile(spread).measures.some(item=>item.key==='g')));
test('P08 spread profile includes reviewed teaspoon',()=>assert.ok(profile(spread).measures.some(item=>item.key==='tsp'&&item.conversionToBase.baseQuantity===5)));
test('P09 spread profile includes manufacturer serving additively',()=>assert.ok(profile(spread).measures.some(item=>item.key==='serve'&&item.provenance==='manufacturer')));
test('P10 spread profile excludes volume measures',()=>assert.ok(profile(spread).measures.every(item=>!['mL','L','cup'].includes(item.key))));
test('P11 unvalidated spread thickness remains unavailable',()=>assert.deepEqual(profile(spread).unavailablePresets[0].keys,['thinSpread','regularSpread','thickSpread']));
test('P12 liquid profile includes mL',()=>assert.ok(profile(liquid).measures.some(item=>item.key==='mL')));
test('P13 liquid profile includes a metric cup',()=>assert.equal(profile(liquid).measures.find(item=>item.key==='cup').conversionToBase.baseQuantity,250));
test('P14 liquid profile includes litres',()=>assert.ok(profile(liquid).measures.some(item=>item.key==='L')));
test('P15 liquid profile excludes spread teaspoon',()=>assert.ok(profile(liquid).measures.every(item=>item.key!=='tsp')));
test('P16 sliced profile retains a source slice',()=>assert.ok(profile(sliced).measures.some(item=>item.key==='slice')));
test('P17 countable profile retains a source biscuit',()=>assert.ok(profile(countable).measures.some(item=>item.key==='biscuit')));
test('P18 every choice carries conversion and provenance',()=>{for(const choice of profile(spread).measures){assert.ok(choice.conversionToBase);assert.ok(choice.conversionBasis);assert.ok(choice.provenance);assert.ok(choice.applicability);}});
test('P19 manufacturer serve has a readable label',()=>assert.equal(profile(spread).measures.find(item=>item.key==='serve').label,'Manufacturer serve (10 g)'));
test('P20 singular review label is grammatical',()=>assert.equal(serving.formatPortionAmount(profile(spread).measures.find(item=>item.key==='tsp'),1),'1 teaspoon (5 g)'));
test('P21 plural review label is grammatical',()=>assert.equal(serving.formatPortionAmount(profile(spread).measures.find(item=>item.key==='tsp'),2),'2 teaspoons (10 g)'));
test('P22 decimal review label is clean',()=>assert.equal(serving.formatPortionAmount(profile(spread).measures.find(item=>item.key==='tsp'),.5),'½ teaspoon (2.5 g)'));
test('P23 zero amount is rejected',()=>assert.equal(serving.validateAmount(0),null));
test('P24 negative amount is rejected',()=>assert.equal(serving.validateAmount(-1),null));
test('P25 positive decimal amount is accepted',()=>assert.equal(serving.validateAmount(.25),.25));
test('P26 fraction parsing shares stable measure IDs',()=>assert.deepEqual(guided.parseConsumption('add 1/2 teaspoon Untested Seed Spread'),{identityQuery:'untested seed spread',amount:.5,measure:'tsp',explicit:true,phrase:'1/2 tsp',consumedQuantity:.5,productVariantCount:null,packageNameCount:null}));
test('P27 measure always precedes amount',()=>{const session=exact(spread);guided.selectAmount(session,1);assert.equal(session.stage,guided.stages.MEASURE);guided.selectMeasure(session,'tsp');assert.equal(session.stage,guided.stages.AMOUNT);});
test('P28 amount starts blank in state and markup',()=>{assert.equal(exact(spread).amount,null);assert.doesNotMatch(runtime,/data-gpr-amount[^>]*value="1"/);assert.match(runtime,/placeholder="Enter amount"/);});
test('P29 amount selection reaches confirmation',()=>{const session=exact(spread);guided.selectMeasure(session,'tsp');guided.selectAmount(session,.5);assert.equal(session.stage,guided.stages.CONFIRMATION);assert.equal(guided.reviewLabel(session),'½ teaspoon (2.5 g)');});
test('P30 edit amount preserves identity and measure',()=>{const session=exact(spread);guided.selectMeasure(session,'tsp');guided.selectAmount(session,1);guided.editAmount(session);assert.equal(session.exactProduct,spread);assert.equal(session.selectedMeasure.key,'tsp');assert.equal(session.amount,null);});
test('P31 edit measure clears only downstream state',()=>{const session=exact(spread);guided.selectMeasure(session,'tsp');guided.selectAmount(session,1);guided.editMeasure(session);assert.equal(session.exactProduct,spread);assert.equal(session.selectedMeasure,null);assert.equal(session.stage,guided.stages.MEASURE);});
test('P32 cancel clears active downstream state',()=>{const session=exact(spread);guided.selectMeasure(session,'g');guided.cancel(session);assert.equal(session.cancelled,true);assert.equal(session.selectedMeasure,null);assert.equal(session.searchLock.locked,false);});
test('P33 compact answer history is rendered and wraps without clipping',()=>{assert.match(runtime,/guided-resolution-answer-summary/);assert.match(styles,/guided-resolution-answer-summary\{[^}]*flex-wrap:wrap[^}]*overflow:visible/);assert.match(styles,/guided-resolution-answer-summary b\{[^}]*white-space:normal/);});
test('P34 choice auto-advance has no identity Continue gate',()=>{const block=runtime.slice(runtime.indexOf('if(session.stage===GUIDED_PRODUCTS.stages.IDENTITY)'),runtime.indexOf('const product=session.exactProduct'));assert.doesNotMatch(block,/data-gpr-continue/);assert.match(runtime,/GUIDED_PRODUCTS\.answerDistinction\(session,key,value\);[^}]{0,240}ps34RenderGuided\(\)/);});
test('P35 active-card positioning is transition-scoped',()=>{assert.match(runtime,/signature===ps34PositionSignature/);assert.equal((runtime.match(/function ps34PositionActiveCard/g)||[]).length,1);});
test('P36 responsive controls stay bounded and tappable',()=>{assert.match(styles,/guided-resolution-choice\{[^}]*min-height:48px/);assert.match(styles,/progressive-food-resolution-active #food-results\{max-width:100%;overflow-x:hidden/);});
test('P37 policy marks thickness values NOT YET VALIDATED',()=>assert.match(policy,/NOT YET VALIDATED[\s\S]*2\.5 g \/ 5 g \/ 7 g/));
test('P38 vocabulary audit is complete and human readable',()=>{const report=audit.portionVocabularyAudit();assert.equal(report.entries.length,Object.keys(serving.PORTION_VOCABULARY).length);assert.ok(report.entries.every(item=>item.displayLabel&&item.physicalFamily&&item.conversion&&item.applicableForms.length));});
test('P39 200-product audit meets required mix',()=>{scaleReport||=audit.portionProfileScaleAudit(200);assert.equal(scaleReport.sampled,200);assert.ok(scaleReport.requiredMix.spread>=25);assert.ok(scaleReport.requiredMix.liquid>=25);assert.ok(scaleReport.requiredMix.slicedCountable>=25);});
test('P40 200-product audit yields safe source-backed profiles',()=>{scaleReport||=audit.portionProfileScaleAudit(200);assert.equal(scaleReport.safe,200);assert.deepEqual(scaleReport.failures,[]);});
test('P41 20 unmentioned foods generalize safely',()=>{untestedReport||=audit.untestedFoodAudit(20);assert.equal(untestedReport.sampled,20);assert.equal(untestedReport.safe,20);assert.equal(untestedReport.explicitExampleNamesExcluded,true);});
test('P42 deterministic generalization spans 100 shards',()=>{generalizationReport||=audit.randomGeneralizationAudit(100);assert.equal(generalizationReport.sampled,100);assert.equal(generalizationReport.shardsSampled,100);});
test('P43 deterministic generalization has no nonsense failures',()=>{generalizationReport||=audit.randomGeneralizationAudit(100);assert.equal(generalizationReport.safe,100);assert.deepEqual(generalizationReport.failures,[]);});
test('P44 portion benchmark executes 500 central profiles',()=>{const result=audit.portionPerformance(500);assert.equal(result.iterations,500);assert.ok(result.p95Ms<100);});
test('P45 no production brand-specific portion branch exists',()=>{const production=fs.readFileSync(path.join(ROOT,'serving-foundation.js'),'utf8');assert.doesNotMatch(production,/if\s*\([^)]*(?:Flora|Meadow Lea)/i);});
test('P46 architecture stays on Alpha 0.6.33',()=>{assert.equal(guided.version,'0.6.33');assert.equal(serving.version,'0.6.33');});
