'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),R=require('../retailer-catalogue'),adapter=require('../retailer-source'),F=require('./fixtures/retailer-catalogue');
const fixture=()=>F.fixture({retailerId:'example-grocer',name:'Example Grocer',extraProducts:0});
test('every actual retailer category and house brand has eligible products and settles with exactly those identities',async()=>{const r=await require('../scripts/audit_retailer_loading').run();assert.equal(r.routes.length,115);assert.deepEqual(r.retailers,{aldi:{visible:222,loggable:222,restricted:0,categories:16,brands:32},woolworths:{visible:362,loggable:347,restricted:15,categories:20,brands:11},coles:{visible:417,loggable:417,restricted:0,categories:18,brands:15}});});
test('stale category, stale brand and empty intersection settle empty without offering zero choices',async()=>{const d=R.directory('aldi');assert(!d.categories.some(c=>c.id==='desserts'));for(const options of [{categoryId:'stale-category'},{categoryId:'*',brandKey:'stale-brand'},{categoryId:'cheese',brandKey:'seasonspride'}]){const s=R.createSession('aldi');await R.load(s,options);assert.equal(s.loading,false);assert.equal(s.error,'');assert.equal(s.result.total,0);assert.deepEqual(s.result.foods,[]);}});
test('unresolved adapter is bounded; late result cannot refill caches or overwrite retry',async()=>{const f=fixture();let release;R.registerCatalogue({...f,loadRecords:ids=>new Promise(resolve=>{release=()=>resolve(ids.map(id=>f.records.find(r=>r.id===id)));})});const s=R.createSession('example-grocer');await R.load(s,{categoryId:'bread',timeoutMs:20});assert.equal(s.loading,false);assert.match(s.error,/too long/);assert.equal(s.result,null);release();await new Promise(r=>setImmediate(r));assert.equal(s.result,null);assert(![...R.loadedFoods.values()].some(f=>f.id==='synthetic-house'));R.registerCatalogue({...f,loadRecords:async ids=>ids.map(id=>f.records.find(r=>r.id===id))});await R.load(s,{categoryId:'bread'});assert.equal(s.error,'');assert(s.result.foods.length);R.unregisterCatalogue('example-grocer');});
test('shard deadline aborts stalled read, evicts rejected promise and allows real retry',async()=>{const f=fixture(),index={...f,entries:f.entries.map(e=>({...e,shard:'facts.json'})),files:[{path:'facts.json'}]};let stalled=true,signal,calls=0;adapter.register(index,{timeoutMs:10,loadJSON:async(_file,options)=>{calls++;signal=options.signal;if(stalled)return new Promise(()=>{});return {records:f.records};}});const s=R.createSession('example-grocer');await R.load(s,{categoryId:'bread'});assert.equal(s.loading,false);assert.match(s.error,/too long/);assert(signal.aborted);stalled=false;await R.load(s,{categoryId:'bread'});assert.equal(s.error,'');assert(s.result.foods.length);assert.equal(calls,2);R.unregisterCatalogue('example-grocer');});
test('loader rejection and catalogue replacement terminate as errors',async()=>{const f=fixture();R.registerCatalogue({...f,loadRecords:async()=>{throw Error('synthetic missing shard')}});const s=R.createSession('example-grocer');await R.load(s,{categoryId:'bread'});assert.equal(s.loading,false);assert.match(s.error,/missing shard/);let release;R.registerCatalogue({...f,loadRecords:ids=>new Promise(resolve=>{release=()=>resolve(ids.map(id=>f.records.find(r=>r.id===id)));})});const pending=R.load(s,{categoryId:'bread'});R.registerCatalogue({...f,loadRecords:async ids=>ids.map(id=>f.records.find(r=>r.id===id))});release();await pending;assert.equal(s.loading,false);assert.match(s.error,/changed while loading/);R.unregisterCatalogue('example-grocer');});
test('timeout from an old request cannot finish a newer request',async()=>{const f=fixture(),pending=[];R.registerCatalogue({...f,loadRecords:ids=>new Promise(resolve=>pending.push(()=>resolve(ids.map(id=>f.records.find(r=>r.id===id)))))});const s=R.createSession('example-grocer'),old=R.load(s,{categoryId:'bread',timeoutMs:10}),newer=R.load(s,{categoryId:'cereal',timeoutMs:1000});await old;assert.equal(s.loading,true);assert.equal(s.error,'');pending[1]();await newer;assert.equal(s.loading,false);assert.equal(s.result.categoryId,'cereal');pending[0]();R.unregisterCatalogue('example-grocer');});
