'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),C=require('../food-catalogue'),G=require('../guided-product-resolution'),OFF=require('../off-catalogue'),R=require('../retailer-catalogue'),F=require('./fixtures/retailer-catalogue');
const gtin='9300633476823',base=()=>F.food('synthetic-a',{barcode:gtin,name:'Fixture Baked Beans Original',brand:'Fixture Foods',physicalForm:'solid',pack:{amount:420,unit:'g'},sourceProvenance:{...F.evidence('a'),trustClass:'official-au-manufacturer'}});
function pair(extra={}){const a=base(),b={...base(),id:'synthetic-b',recordType:'external-catalogue',sourceProvenance:F.evidence('b'),...extra};return [a,b];}
function blocked(records){const result=C.canonicaliseRecords(records);assert.equal(result.length,1);const food=result[0];assert.equal(food.barcode,gtin);assert.equal(C.productEligibility(food).addability.normalLoggingAllowed,false);assert(food.evidenceConflicts.some(c=>c.code==='same-gtin-identity-conflict'&&c.resolution==='unresolved'));assert.equal(food.canonicalEvidence.length,2);const session=G.createSession(result,food.name,{intent:{kind:'exact-product'}});assert.equal(session.addability.normalLoggingAllowed,false);return food;}
for(const [label,left,right]of [
  ['punctuation and casing','Fixture Baked Beans Original','FIXTURE: baked beans — original'],
  ['harmless wording refresh','Fixture Baked Beans Original','Fixture Original Baked Beans Australian Recipe'],
  ['retailer wording and word order','Fixture Baked Beans Original','Original Baked Beans by Fixture Foods'],
  ['duplicated pack wording','Fixture Baked Beans Original','Fixture Baked Beans Original 420 g'],
  ['current verified title','Product','Product Current']
])test('compatible title '+label+' retains authority, aliases and original source titles',()=>{const [a,b]=pair({name:left});a.name=right;const [food]=C.canonicaliseRecords([b,a]);assert.equal(food.id,a.id);assert.equal(food.name,right);assert(food.aliases.includes(left));assert.deepEqual(new Set(food.canonicalEvidence.map(e=>e.name)),new Set([left,right]));assert.equal(food.evidenceConflicts.length,0);assert.equal(C.productEligibility(food).addability.normalLoggingAllowed,true);assert.deepEqual(food.nutrients,a.nutrients);});
test('equally trusted compatible titles use existing publication currentness',()=>{const [a,b]=pair({recordType:'packaged'});b.sourceProvenance={...a.sourceProvenance,recordId:b.id,publishedDate:'2026-08-01'};a.sourceProvenance.publishedDate='2025-08-01';b.name='Fixture Original Baked Beans Australian Recipe';const [food]=C.canonicaliseRecords([a,b]);assert.equal(food.name,b.name);assert(food.aliases.includes(a.name));assert.equal(food.canonicalEvidence.length,2);});
for(const [label,left,right]of [
  ['Original versus Chocolate','Fixture Product Original','Fixture Product Chocolate'],
  ['Full Cream versus Reduced Fat','Fixture Milk Full Cream','Fixture Milk Reduced Fat'],
  ['regular versus Gluten Free','Fixture Bread Regular','Fixture Bread Gluten Free'],
  ['title pack 420 g versus 840 g','Fixture Product 420 g','Fixture Product 840 g'],
  ['6 Pack versus 12 Pack','Fixture Product 6 Pack','Fixture Product 12 Pack'],
  ['salt formulation','Fixture Product Salted','Fixture Product Salt Reduced'],
  ['sweetening','Fixture Product Sweetened','Fixture Product Unsweetened'],
  ['title size','Fixture Product Small','Fixture Product Large'],
  ['product family','Fixture Bread','Fixture Milk']
])test('material title '+label+' remains unresolved',()=>{const records=pair();records[0].name=left;records[1].name=right;blocked(records);});
test('structured pack versus title-only pack cannot bypass identity checking',()=>{const records=pair({name:'Fixture Baked Beans Original 840 g',pack:null});blocked(records);});
test('compatible same-GTIN evidence still corroborates with manufacturer authority and both sources',()=>{const [a,b]=pair(),before=JSON.stringify([a,b]),[food]=C.canonicaliseRecords([b,a]);assert.equal(food.id,a.id);assert.deepEqual(food.nutrients,a.nutrients);assert.equal(food.canonicalEvidence.length,2);assert.equal(C.productEligibility(food).addability.normalLoggingAllowed,true);assert.equal(JSON.stringify([a,b]),before);});
test('same GTIN 420 g versus 840 g is inspectable identity conflict even with stronger manufacturer evidence',()=>{const food=blocked(pair({pack:{amount:840,unit:'g'}}));assert(food.evidenceConflicts[0].fields.includes('pack'));assert.deepEqual(food.canonicalEvidence.map(e=>e.pack.amount),[420,840]);assert.equal(C.strongDuplicateEvidence(...pair({pack:{amount:840,unit:'g'}})).duplicate,false);});
for(const [label,extra]of [['flavour',{name:'Fixture Baked Beans Chilli'}],['brand',{brand:'Other Manufacturer'}],['physical form',{physicalForm:'liquid'}],['explicit variant',{productVariant:'Gluten Free'}],['count',{semanticCount:12}],['size',{size:'Large'}]])test('incompatible same-GTIN '+label+' blocks ordinary logging',()=>{const records=pair(extra);if(label==='explicit variant')records[0].productVariant='Regular';if(label==='count')records[0].semanticCount=6;if(label==='size')records[0].size='Small';blocked(records);});
test('same-GTIN identity conflict cannot be cleared by re-canonicalising with the preferred clean source',()=>{const [a,b]=pair({pack:{amount:840,unit:'g'}}),food=blocked([a,b]),again=C.canonicaliseRecords([a,food])[0];assert.equal(C.productEligibility(again).addability.normalLoggingAllowed,false);assert(again.evidenceConflicts.some(c=>c.code==='same-gtin-identity-conflict'&&c.resolution==='unresolved'));});
test('equal-authority nutrition conflict remains blocked and never averaged',()=>{const [a,b]=pair({recordType:'packaged',sourceProvenance:{...F.evidence('b'),trustClass:'official-au-manufacturer'},nutritionPer100:{energyKj:1600,protein:3,carbs:50,fat:10}}),food=C.canonicaliseRecords([a,b])[0];assert.equal(food.loggable,false);assert.equal(food.nutritionPer100.energyKj,836);assert(food.evidenceConflicts.some(c=>c.code==='cross-source-nutrition-conflict'&&c.resolution==='unresolved'));});
test('different GTINs remain distinct without manufacturing or replacing barcodes',()=>{const records=pair({barcode:'9339687257034'}),result=C.canonicaliseRecords(records);assert.equal(result.length,2);assert.deepEqual(result.map(f=>f.barcode),records.map(f=>f.barcode));});
test('all shared dedupe surfaces retain the same-GTIN conflict instead of choosing a clean rank winner',()=>{const records=pair({pack:{amount:840,unit:'g'}});for(const foods of [C.dedupe(records),C.dedupeRanked(records.map((food,i)=>({food,rank:100+i}))).map(i=>i.food),OFF.federate([records[0]],[records[1]])]){assert.equal(foods.length,1);assert.equal(C.productEligibility(foods[0]).addability.normalLoggingAllowed,false);}assert.equal(C.duplicateIdentityEvidence(...records).duplicate,false);});
test('retailer index loads all same-GTIN evidence on the same page before permitting selection',async()=>{const f=F.fixture({extraProducts:0}),records=pair({pack:{amount:840,unit:'g'}}).map(record=>({...record,retailerMemberships:[F.membership('woolworths',record.id)]})),calls=[];R.registerCatalogue({...f,entries:records,loadRecords:async ids=>{calls.push(ids);return ids.map(id=>records.find(r=>r.id===id))}});try{const result=await R.page('woolworths',{limit:1});assert.equal(result.total,1);assert.equal(calls[0].length,2);assert.equal(result.foods.length,1);assert.equal(C.productEligibility(result.foods[0]).addability.normalLoggingAllowed,false);}finally{R.unregisterCatalogue('woolworths')}});

test('unlisted OFF evidence for a listed GTIN is retained for conflict analysis without creating another retailer product',async()=>{const f=F.fixture({extraProducts:0}),[a,b]=pair({pack:{amount:840,unit:'g'},recordType:'external-catalogue'});a.retailerMemberships=[F.membership('woolworths',a.id)];const records=[a,b,F.food('synthetic-unlisted')];R.registerCatalogue({...f,entries:records,loadRecords:async ids=>ids.map(id=>records.find(r=>r.id===id))});try{const result=await R.page('woolworths');assert.equal(result.total,1);assert.equal(result.foods[0].canonicalEvidence.length,2);assert.equal(C.retailerMembership(result.foods[0],'woolworths').length,1);assert.equal(C.productEligibility(result.foods[0]).addability.normalLoggingAllowed,false);}finally{R.unregisterCatalogue('woolworths')}});
