'use strict';
const test=require('node:test'),assert=require('node:assert/strict');require('../packaged-foods');require('../product-serving-semantics');require('../serving-foundation');const C=require('../food-catalogue'),X=require('../capture-foundation'),f=require('./fixtures/barcode-confirmation');
const saved=()=>X.buildBarcodeFood({food:f.food,id:'synthetic-saved',confirmed:true}).food;
test('empty and partial panels retain same-basis saved nutrition without mutating baseline',()=>{const food=saved(),before=JSON.stringify(food);for(const text of ['', 'Ingredients: Milk, vanilla.', 'Per serving\nEnergy 670 kJ\nFat 5.1 g']){const parsed=X.parseNutritionPanel(text),m=X.mergePanelBaseline(food,parsed.model);assert.equal(m.perServing.protein,3.3);assert.equal(m.perServing.fat,text.includes('5.1')?5.1:5.3);assert.equal(m.servingAmount,170);}assert.equal(JSON.stringify(food),before);});
test('changed serving or metric column never inherits incompatible old cells',()=>{const food=saved(),panel=X.parseNutritionPanel('Serving size 250 mL\nPer serving Per 100 mL\nEnergy 500 kJ 200 kJ').model,m=X.mergePanelBaseline(food,panel);assert.equal(m.perServing.protein,null);assert.equal(m.per100.protein,null);assert.equal(m.perServing.energyKj,500);});
test('explicit zero replaces saved cell and an energy edit does not keep conflicting energy conversion',()=>{const food=saved(),p=X.parseNutritionPanel('Per serving\nEnergy 100 Cal\nFat 0 g').model,m=X.mergePanelBaseline(food,p);assert.equal(m.perServing.fat,0);assert.equal(m.perServing.calories,100);assert.equal(m.perServing.energyKj,418.40000000000003);});
for(const [size,pack,amount,unit,count] of [['170 g',1,170,'g',null],['125 g',6,125,'g',null],['250 mL',4,250,'mL',null],['1 piece',2,null,'',1]])test('serving and pack distinct: '+size,()=>{const p=X.parseNutritionPanel('Servings per package '+pack+'\nServing size '+size+'\nPer serving\nEnergy 400 kJ');assert.equal(p.servingsPerPack,pack);assert.equal(p.servingAmount,amount);assert.equal(p.servingUnit,unit);assert.equal(p.servingCount,count);});
for(const value of [5.3,3.3,.8,12.5,1.7,.3,33])test('decimal literal preserved: '+value,()=>assert.equal(X.parseNutritionPanel('Per serving\nFat '+value+' g').perServing.fat,value));
function geometry({fat='5.3',confidence=95,reverse=false,split=false}={}){let words=[];const word=(text,x,y,c=95)=>({text,confidence:c,bbox:{x0:x,y0:y,x1:x+text.length*10,y1:y+20}});const header=reverse?['100','g','Serving']:['Serving','100','g'];words.push(word('Per',500,100),word(header[0],540,100));if(reverse)words.push(word('g',580,100));words.push(word('Per',900,100),word(reverse?'Serving':'100',940,100));if(!reverse)words.push(word('g',980,100));words.push(word('Fat',20,160),word('(g)',80,160));if(split){words.push(word('5',540,160),word('.',553,160),word('3',564,160));}else words.push(word(fat,540,160,confidence));words.push(word('3.12',940,160));return {text:'Per Serving Per 100 g\nFat (g) '+fat+' 3.12',confidence:92,blocks:words.map(w=>({paragraphs:[{lines:[{text:w.text,words:[w]}]}]}))};}
test('table geometry associates words across column blocks and preserves missing-cell ownership',()=>{let p=X.parseOcrResult(geometry());assert.equal(p.perServing.fat,5.3);assert.equal(p.per100.fat,3.12);assert(p.tableEvidence);p=X.parseOcrResult(geometry({fat:'?',confidence:40}));assert.equal(p.perServing.fat,null);assert.equal(p.per100.fat,3.12);});
test('geometry rejects low confidence integer and split decimal without losing other column',()=>{for(const options of [{fat:'33',confidence:50},{split:true}]){const p=X.parseOcrResult(geometry(options));assert.equal(p.perServing.fat,null);assert.equal(p.per100.fat,3.12);assert(p.questionable);}});
test('geometry respects reversed printed column headings',()=>{const p=X.parseOcrResult(geometry({reverse:true}));assert.equal(p.per100.fat,5.3);assert.equal(p.perServing.fat,3.12);});
test('geometry without supported heading evidence falls back without guessing column',()=>{const data=geometry();data.blocks=data.blocks.filter(b=>!['Per','Serving','100'].includes(b.paragraphs[0].lines[0].words[0].text));data.text='Fat 5.3 3.12';const p=X.parseOcrResult(data);assert.equal(p.perServing.fat,null);assert.equal(p.per100.fat,null);});

test('zero usable nutrients cannot erase a saved column through a misread serving',()=>{const food=saved(),p=X.parseNutritionPanel('Serving size 270 mL\nServings per package 9').model;assert.deepEqual(X.mergePanelBaseline(food,p),X.reviewModelFor(food));});
test('partial per-100 reading selects that populated baseline column for future nutrition',()=>{const food=saved(),p=X.parseNutritionPanel('Per 100 g\nFat 3 g').model,m=X.mergePanelBaseline(food,p);assert.equal(m.selectedBasis,'per100');const next=X.buildPanelFood({id:food.id,name:food.name,model:m,confirmed:true,discrepancyConfirmed:true}).food;assert(next);assert(Math.abs(global.HECPackagedFoods.nutritionForFood(next,{amount:1,unit:'serve'}).fat-5.1)<.00001);});
