'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const P=require('../packaged-foods');require('../product-serving-semantics');const S=require('../serving-foundation'),X=require('../capture-foundation'),fixtures=require('./fixtures/shared-product-capture');
function product(f,extra={}){const parsed=X.parseOcrResult({text:f.text,confidence:95}),model={...parsed.model,...extra},result=X.buildPanelFood({id:'fixture-'+f.unit,name:f.name,brand:f.brand,barcode:f.barcode,model,confirmed:true,discrepancyConfirmed:true,extracted:parsed});assert(result.food,JSON.stringify(result.status));return result.food;}
for(const key of ['crispbread','bread','sachet'])test(key+' packet count uses the shared measure registry and exact base quantity',()=>{const f=fixtures[key],food=product(f),profile=S.servingMeasureProfile(food),measure=profile.measures.find(m=>m.key===f.unit);assert(measure);assert(!profile.measures.some(m=>['mL','L'].includes(m.key)));const portion=S.consumedPortionState({food,measure,amount:1});assert.equal(portion.baseQuantity,f.grams);assert.equal(P.nutritionForFood(food,{amount:1,unit:f.unit}).calories,f.calories);assert.equal(JSON.parse(JSON.stringify(food)).nutritionBasis.servingCount,key==='sachet'?1:2);});
test('serving/pack metadata and split energy rows survive OCR mapping',()=>{const p=X.parseOcrResult({text:fixtures.bread.text,confidence:95});assert.equal(p.servingsPerPack,10.5);assert.equal(p.servingAmount,67);assert.equal(p.servingCount,2);assert.equal(p.perServing.energyKj,697);assert.equal(p.perServing.calories,166);assert.equal(p.per100.energyKj,1040);assert.equal(p.per100.calories,248);});
test('milk accepts energy, sodium and calcium while damaged decimal rows stay unknown',()=>{const food=product(fixtures.milk),m=food.nutritionBasis;assert.equal(m.servingsPerPack,4);assert.equal(m.servingUnit,'mL');assert.equal(m.per100Unit,'mL');assert.equal(m.perServing.calories,115);assert.equal(m.per100.sodium,43);assert.equal(m.perServing.calcium,315);for(const key of ['protein','fat','satFat','carbs','sugar']){assert.equal(m.perServing[key],null);assert.equal(m.per100[key],null);}const units=S.servingMeasureProfile(food).measures.map(m=>m.key);assert(units.includes('mL'));for(const key of ['g','slice','cracker','crispbread','sachet'])assert(!units.includes(key));});
test('as-prepared reference cannot become powder mass or a water amount',()=>{const food=product(fixtures.sachet,{waterPreparation:true}),m=food.nutritionBasis;assert.equal(m.per100Context,'as-prepared');assert.equal(m.servingUnit,'g');assert.equal(m.per100Unit,'mL');assert.equal(food.preparation.usualWaterMl,null);assert.equal(P.calculatedServingFrom100(m).calories,null);assert.deepEqual(P.basisDiscrepancies(m),[]);assert(X.reviewStatus({name:food.name,model:{...m,selectedBasis:'per100'},confirmed:true}).missing.includes('prepared-reference'));for(const amountMl of [200,250,300]){assert.equal(P.nutritionForFood(food,{amount:1,unit:'sachet'}).calories,47);assert.equal(X.preparationWater(food,{amountMl}).fluidMl,amountMl);assert.equal(X.preparationWater(food,{amountMl,alreadyLoggedSeparately:true}).fluidMl,0);}});
test('printed energy pairs and less-than limits remain distinct from derived values and exact nutrients',()=>{const food=product(fixtures.crispbread),m=food.nutritionBasis;assert.equal(food.nutrients.energyKj,182);assert.equal(food.nutrients.calories,44);assert.equal(m.energyProvenance.perServing.energyKj,'printed');assert.equal(m.energyProvenance.perServing.calories,'printed');assert.equal(food.nutrients.satFat,null);assert.deepEqual(food.nutrientQualifiers.satFat,{operator:'<',limit:.1});const snap=P.diarySnapshot(food,{amount:1,unit:'crispbread'});assert.deepEqual(snap.nutrientQualifiers.satFat,{operator:'<',limit:.05});const one=X.parseNutritionPanel('Per serving\nEnergy 200 kJ');assert.equal(one.energyProvenance.perServing.calories,'derived-from-kj');assert(!X.comparePanel(food,one.model).rows.some(row=>row.key==='calories'));});
test('saved baseline survives weak read and historical models need no new fields',()=>{const food=product(fixtures.bread),before=JSON.stringify(food);const old=JSON.parse(before);delete old.nutritionBasis.qualifiers;delete old.nutritionBasis.energyProvenance;delete old.nutritionBasis.per100Context;assert.equal(X.reviewModelFor(old).perServing.calories,166);assert.equal(X.mergePanelBaseline(food,X.parseOcrResult({text:'Serving size 99 mL\nIngredients: wheat.',confidence:95}).model).perServing.calories,166);assert.equal(JSON.stringify(food),before);assert.equal(X.preparationWater(old,{amountMl:250}),null);});
test('front identity excludes health-star, origin, pack-count and marketing copy',()=>{const p=X.frontIdentity({text:'HEALTH STAR RATING\n3.5\nAUSTRALIAN\nNO ADDED SUGAR\nBAKERS OVEN\nWHITE SANDWICH\n700 g',confidence:95});assert.equal(p.brand,'BAKERS OVEN');assert.equal(p.name,'WHITE SANDWICH');assert.equal(X.frontIdentity({text:'health star\nno added sugar\n100% Australian'}).name,'');assert.equal(X.frontIdentity({text:'GARBLED WORDS',confidence:30}).name,'');assert.equal(X.frontIdentity({text:'OTHER WORDS'},{name:'Known Product',brand:'Known Brand'}).name,'Known Product');});
test('ordinary gram, mL and manufacturer serving models still work',()=>{for(const unit of ['g','mL']){const f=X.buildPanelFood({name:'Fixture Product',model:P.basisModel({per100:{calories:100},per100Unit:unit,selectedBasis:'per100'}),confirmed:true}).food;assert(f);assert.equal(P.nutritionForFood(f,{amount:50,unit}).calories,50);}assert.equal(P.nutritionForFood(product(fixtures.crispbread),{amount:1,unit:'serve'}).calories,44);});

test('saved comparison preserves printed serving values and sparse rereads retain the prepared reference',()=>{
 for(const f of Object.values(fixtures)){const food=product(f),comparison=X.comparePanel(food,X.parseOcrResult({text:f.text,confidence:95}).model);assert.equal(comparison.status,'compatible');assert(comparison.rows.every(row=>row.catalogue===row.panel));}
 const food=product(fixtures.sachet,{waterPreparation:true}),m=X.mergePanelBaseline(food,X.parseNutritionPanel('Per serving\nSodium 52 mg').model);
 assert.equal(m.per100Context,'as-prepared');assert.equal(m.per100Unit,'mL');assert.equal(m.servingUnit,'g');assert.equal(m.perServing.sodium,52);assert.equal(m.perServing.calories,47);
 const legacy={...food,nutritionBasis:{...food.nutritionBasis,qualifiers:null,energyProvenance:null}};assert.equal(X.mergePanelBaseline(legacy,X.parseNutritionPanel('Per serving\nSodium 52 mg').model).perServing.calories,47);
});

test('OCR geometry keeps independent energy cells, limits and split serving metadata',()=>{
 const words=[],word=(text,x,y,confidence=95)=>words.push({text,confidence,bbox:{x0:x,x1:x+text.length*9,y0:y,y1:y+20}});
 word('Per Serving',500,100);word('Per 100 g',900,100);
 word('Energy',20,160);word('697',510,160);word('kJ',550,160);word('166',610,160);word('Cal',650,160,40);word('1040',900,160);word('kJ',950,160);word('248',990,160);word('Cal',1030,160);
 word('Fat',20,210);word('(g)',70,210);word('?',530,210,40);word('2.4',950,210);
 word('Saturated fat',20,260);word('<1.0',530,260);word('g',580,260);word('<1.0',950,260);word('g',1000,260);
 const data={confidence:95,text:'Serving size:\n67 g (2 slices)\nPer Serving Per 100 g\nEnergy 697 kJ 1040 kJ\n166 Cal 248 Cal\nFat (g) ? 2.4\nSaturated fat <1.0 g <1.0 g',blocks:words.map(w=>({paragraphs:[{lines:[{text:w.text,words:[w]}]}]}))};
 const p=X.parseOcrResult(data);assert.equal(p.perServing.energyKj,697);assert.equal(p.energyProvenance.perServing.calories,'derived-from-kj');assert.equal(p.per100.calories,248);assert.equal(p.energyProvenance.per100.calories,'printed');assert.equal(p.perServing.fat,null);assert.equal(p.per100.fat,2.4);assert.equal(p.qualifiers.perServing.satFat.limit,1);assert.equal(p.servingAmount,67);assert.equal(p.servingCount,2);assert.equal(p.manufacturerServing,true);
});
