'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const qa=require('../scripts/audit_physical_form_measures_edge'),{returningProfile}=require('../scripts/audit_navigation_startup_edge');
require('../packaged-foods');require('../product-serving-semantics');require('../serving-foundation');require('../food-catalogue');const X=require('../capture-foundation'),fixtures=require('./fixtures/shared-product-capture');
const make=(key)=>{const f=fixtures[key],model=X.parseOcrResult({text:f.text,confidence:95}).model;return X.buildPanelFood({id:'capture-fixture-'+key,name:f.name,brand:f.brand,barcode:f.barcode,model:{...model,waterPreparation:key==='sachet'},confirmed:true,discrepancyConfirmed:true}).food;};

test('production capture amount → Review → stored Diary keeps natural units, nutrition, water and snapshots', {timeout:180000}, async()=>{
 const report=qa.evidence(),{chromium,edge}=qa.browserTools(),browser=await chromium.launch({headless:true,executablePath:edge});let page;
 try{
  // Exercise the regenerated SOURCE files through isolated local routing.
  // Never connect a personal browser profile or a live deployed service.
  const context=await qa.contextFor(browser,{width:390,height:844},report);await context.addInitScript(returningProfile);
  const foods=['crispbread','bread','milk','sachet'].map(make);assert(foods.every(Boolean));
  await context.addInitScript(foods=>{if(location.origin!=='https://mlwes-hec-test.github.io'||localStorage.getItem('shared-capture-fixtures'))return;localStorage.setItem('healthyEatingCompanionTestAlpha06Functional',JSON.stringify({customFoods:foods,savedFoodIds:foods.map(f=>f.id),onlineFoods:[],ui:{}}));localStorage.setItem('shared-capture-fixtures','yes');},foods);
  page=await context.newPage();await page.goto(qa.ORIGIN+'/');await page.waitForFunction(()=>HECRelease.snapshot().state==='ready');
  const state=()=>page.evaluate(()=>JSON.parse(localStorage.getItem(HEC_APP.functionalStorageKey)));
  const open=async key=>{await page.evaluate(()=>openAlpha05Feature('food-library'));await page.locator('[data-library-tab="saved"]').click();await page.locator('#food-results [data-food-save="capture-fixture-'+key+'"]').locator('..').locator('.resource-main').click();await page.locator('[data-review-product-nutrition="capture-fixture-'+key+'"]:visible').click();await page.locator('#capture-value-choice').selectOption('catalogue');await page.locator('#ocr-package-confirmed').check();if(await page.locator('#ocr-discrepancy-confirm-row').isVisible())await page.locator('#ocr-discrepancy-confirmed').check();await page.locator('[data-capture-source="ocr"][data-capture-action="both"]').click();await page.locator('#capture-amount').waitFor();};
  const log=async(key,amount,unit,{water=null,separate=false,reviewUnit=null,remember=false}={})=>{
   const beforeCount=Object.values((await state()).diary||{}).flat().length;await open(key);const offered=await page.locator('#capture-amount-unit option').evaluateAll(nodes=>nodes.map(n=>n.value));if(key==='milk')for(const u of ['g','slice','cracker','sachet'])assert(!offered.includes(u));else assert(!offered.includes('mL'));
   await page.locator('#capture-amount').fill(String(amount));await page.locator('#capture-amount-unit').selectOption(unit);
   if(water!==null)await page.locator('#capture-water-amount').fill(String(water));if(separate)await page.locator('#capture-water-separate').check();
   await page.locator('#capture-amount-review').click();await page.locator('#food-entry-editor.active').waitFor();assert.equal(await page.locator('#entry-unit').inputValue(),unit);assert.equal(await page.locator('#entry-amount').inputValue(),String(amount));
   if(reviewUnit)await page.locator('#entry-unit').selectOption(reviewUnit);
   if(water!==null)assert.equal(await page.locator('#entry-water-amount').inputValue(),String(water));if(remember)await page.locator('#entry-remember-water').check();
   if(key==='crispbread'&&unit==='serve')assert.match(await page.locator('#entry-selection-summary').innerText(),/11\.4 g/);
   await page.locator('#entry-meal').selectOption('Lunch');await page.locator('#save-food-entry').click();await page.waitForFunction(count=>Object.values(JSON.parse(localStorage.getItem(HEC_APP.functionalStorageKey)).diary||{}).flat().length===count+1,beforeCount);return Object.values((await state()).diary).flat().at(-1);
  };
  for(const key of ['crispbread','bread','sachet']){const f=fixtures[key],entry=await log(key,1,f.unit);assert.equal(entry.amount,1);assert.equal(entry.unit,f.unit);assert.equal(entry.consumedPortion.measureId,f.unit);assert.equal(entry.consumedPortion.baseQuantity,f.grams);assert.equal(entry.nutrients.calories,f.calories);assert.equal(entry.foodSnapshot.selection.unit,f.unit);assert.equal(entry.foodSnapshot.consumedPortion.baseQuantity,f.grams);}
  const twice=await log('bread',2,'slice');assert.equal(twice.amount,2);assert.equal(twice.metricEquivalent.value,67);assert.equal(twice.nutrients.calories,166);
  assert.equal((await log('crispbread',1,'serve')).metricEquivalent.value,11.4);
  assert.equal((await log('bread',1,'slice',{reviewUnit:'serve'})).nutrients.calories,166);
  const milk=await log('milk',250,'mL');assert.equal(milk.nutrients.calories,115);assert.equal(milk.consumedPortion.baseUnit,'mL');
  for(const water of [200,250,300]){const entry=await log('sachet',1,'sachet',{water,remember:water===250});assert.equal(entry.nutrients.calories,47);assert.equal(entry.nutrients.energyKj,200);assert.equal(entry.waterMl,water);assert.equal(entry.hydrationType,'drink');assert.equal(entry.foodSnapshot.preparationWater.amountMl,water);}
  assert.equal((await state()).customFoods.find(f=>f.id==='capture-fixture-sachet').preparation.usualWaterMl,250);
  const separate=await log('sachet',1,'sachet',{water:250,separate:true});assert.equal(separate.waterMl,0);assert.equal(separate.preparationWater.alreadyLoggedSeparately,true);
  const unknown=await log('sachet',1,'sachet',{water:''});assert.equal(unknown.preparationWater.amountMl,null);assert.equal(unknown.waterMl,null);
  await page.reload();await page.waitForFunction(()=>HECRelease.snapshot().state==='ready');const entries=Object.values((await state()).diary).flat();assert.equal(entries.length,12);assert.equal(entries.filter(e=>e.foodId==='capture-fixture-sachet').reduce((sum,e)=>sum+(e.waterMl||0),0),750);assert(!entries.some(e=>e.foodId==='water'));
  await page.evaluate(()=>openAlpha05Feature('daily-progress'));assert.match(await page.locator('#daily-fluid-card-summary').innerText(),/750 mL from Diary drinks/);
  await open('sachet');assert.equal(await page.locator('#capture-water-amount').inputValue(),'250');await page.locator('#capture-amount').fill('1');await page.locator('#capture-water-amount').fill('-10');await page.locator('#capture-amount-review').click();assert.equal(await page.locator('#capture-amount').isVisible(),true);assert.equal(await page.locator('#capture-water-amount').evaluate(n=>n.validity.rangeUnderflow),true);
  qa.requireEvidence(report);
 }catch(error){console.error(JSON.stringify({pageErrors:report.pageErrors,consoleErrors:report.consoleErrors.slice(-8)},null,2));if(page){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'hec-shared-capture-failure-'));await page.screenshot({path:path.join(dir,'failure.png'),fullPage:true});console.error('Failure screenshot: '+dir);}throw error;}finally{await browser.close();}
});

test('production panel workflow: truthful baseline, photo read, partial cells, manual focus and saved fallback', {timeout:180000}, async()=>{
 const report=qa.evidence(),{chromium,edge}=qa.browserTools(),browser=await chromium.launch({headless:true,executablePath:edge});let page;
 try{
  const context=await qa.contextFor(browser,{width:390,height:844},report);await context.addInitScript(returningProfile);
  await context.route('**/api/v2/product/**',route=>route.fulfill({json:route.request().url().includes('9900000000455')?{status:1,product:{code:'9900000000455',product_name:'Fixture Lite Milk',brands:'Fixture Dairy',serving_size:'250 ml',serving_quantity:250,product_quantity:1000,nutriments:{}}}:{status:0}}));
  page=await context.newPage();await page.goto(qa.ORIGIN+'/');await page.waitForFunction(()=>HECRelease.snapshot().state==='ready');await page.evaluate(()=>openAlpha05Feature('scan-centre'));await page.locator('[data-scan-mode="barcode"]').click();await page.locator('#manual-barcode-details').evaluate(n=>n.open=true);await page.locator('#scan-barcode-input').fill('9900000000456');await page.locator('#lookup-barcode').click();await page.locator('#capture-unknown-panel').click();
  assert.equal(await page.locator('#ocr-review').isVisible(),false);assert.doesNotMatch(await page.locator('#scan-centre').innerText(),/Panel Read Value|Package Values Match Closely/);
  await page.locator('#capture-manual').click();assert.equal(await page.evaluate(()=>document.activeElement.id),'ocr-food-name');await page.locator('#ocr-food-name').fill(fixtures.bread.name);await page.locator('#ocr-food-brand').fill(fixtures.bread.brand);
  await page.evaluate(text=>{window.Tesseract={createWorker:async()=>({setParameters:async()=>{},recognize:async()=>({data:{text,confidence:95}}),terminate:async()=>{}})};},fixtures.bread.text);
  const image=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64');await page.locator('#scan-image').setInputFiles({name:'synthetic.png',mimeType:'image/png',buffer:image});await page.waitForFunction(()=>document.activeElement.id==='run-label-ocr');await page.locator('#run-label-ocr').click();await page.waitForFunction(()=>document.querySelector('#ocr-serving-amount').value==='67');
  assert.equal(await page.locator('#ocr-serving-count').inputValue(),'2');assert.equal(await page.locator('#ocr-serving-count-unit').inputValue(),'slice');assert.equal(await page.locator('#ocr-energy-kj').inputValue(),'697');assert.equal(await page.locator('#ocr-calories').inputValue(),'166');assert.equal(await page.locator('#ocr-sat-fat').inputValue(),'<1');assert.equal(await page.locator('.ocr-raw-details').evaluate(n=>n.open),false);
  await page.locator('#ocr-calories').fill('166');assert.equal(await page.locator('#ocr-energy-kj').inputValue(),'697');await page.locator('#ocr-energy-kj').fill('697');assert.equal(await page.locator('#ocr-calories').inputValue(),'166');
  await page.locator('#ocr-package-confirmed').check();await page.locator('[data-capture-source="ocr"][data-capture-action="both"]').click();await page.locator('#capture-amount').fill('1');await page.locator('#capture-amount-unit').selectOption('slice');await page.locator('#capture-amount-review').click();assert.equal(await page.locator('#entry-unit').inputValue(),'slice');await page.locator('#entry-meal').selectOption('Lunch');await page.locator('#save-food-entry').click();
  const state=await page.evaluate(()=>JSON.parse(localStorage.getItem(HEC_APP.functionalStorageKey))),entry=Object.values(state.diary).flat().at(-1);assert.equal(entry.nutrients.calories,83);assert.equal(entry.foodSnapshot.nutrientQualifiers.satFat.limit,.5);const food=state.customFoods.find(f=>f.id===entry.foodId);assert(food);
  await page.evaluate(()=>openAlpha05Feature('food-library'));await page.locator('[data-library-tab="saved"]').click();await page.locator('#food-results [data-food-save="'+food.id+'"]').locator('..').locator('.resource-main').click();await page.locator('[data-review-product-nutrition="'+food.id+'"]:visible').click();assert.doesNotMatch(await page.locator('#capture-comparison').innerText(),/Panel Read Value|Package Values Match Closely/);
  await page.locator('.ocr-raw-details').evaluate(n=>n.open=true);await page.locator('#ocr-text').fill('Serving size 99 mL\nIngredients: wheat.');await page.locator('#capture-parse-text').click();assert.equal(await page.locator('#ocr-energy-kj').inputValue(),'697');assert.equal(await page.locator('#ocr-serving-amount').inputValue(),'67');
  await page.locator('#capture-new-active').click();await page.locator('[data-scan-mode="barcode"]').click();await page.locator('#manual-barcode-details').evaluate(n=>n.open=true);await page.locator('#scan-barcode-input').fill('9900000000455');await page.locator('#lookup-barcode').click();await page.locator('[data-compare-barcode-panel]').waitFor();assert.doesNotMatch(await page.locator('#barcode-package-confirmed').locator('..').innerText(),/nutrition values match/);await page.locator('[data-compare-barcode-panel]').click();assert.doesNotMatch(await page.locator('#capture-comparison').innerText(),/Panel Read Value|Package Values Match Closely/);assert.equal(await page.locator('#ocr-review').isVisible(),false);
  await page.evaluate(text=>{window.Tesseract={createWorker:async()=>({setParameters:async()=>{},recognize:async()=>({data:{text,confidence:95}}),terminate:async()=>{}})};},fixtures.milk.text);await page.locator('#scan-image').setInputFiles({name:'milk-fixture.png',mimeType:'image/png',buffer:image});await page.locator('#run-label-ocr').click();await page.waitForFunction(()=>document.querySelector('#ocr-servings-per-pack').value==='4');assert.equal(await page.locator('#ocr-serving-unit').inputValue(),'mL');assert.equal(await page.locator('#ocr-calories').inputValue(),'115');assert.equal(await page.locator('#ocr-sodium').inputValue(),'108');assert.equal(await page.locator('#ocr-calcium').inputValue(),'315');assert.equal(await page.locator('#ocr-fat').inputValue(),'');assert.match(await page.locator('#ocr-100-column').innerText(),/mL/);
  qa.requireEvidence(report);
 }catch(error){console.error(JSON.stringify({pageErrors:report.pageErrors,consoleErrors:report.consoleErrors.slice(-8)},null,2));if(page){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'hec-panel-workflow-failure-'));await page.screenshot({path:path.join(dir,'failure.png'),fullPage:true});console.error('Failure screenshot: '+dir);}throw error;}finally{await browser.close();}
});
