'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const search=require('../search-foundation'),catalogue=require('../food-catalogue'),guided=require('../guided-product-resolution'),serving=require('../serving-foundation');
const {afcdFoods}=require('../scripts/audit_progressive_food_resolution');
const sources=require('../food-sources');require('../mcdonalds-au-catalogue');require('../kfc-au-catalogue');
const records=[...afcdFoods,...sources.foodRecords()];
for(const query of ['Bread','Milk','Hash Brown'])test(`${query}: bounded shortlist starts with its base concept`,()=>{const intent=search.interpretFoodIntent(query),model=catalogue.conceptShortlist(records,intent);assert.equal(model.groups[0].items[0].name,query);assert.equal(model.groups[0].items[0].kind,'generic-concept');assert(model.total>1&&model.total<=20);for(const item of model.groups.flatMap(g=>g.items).filter(i=>i.food)){assert(item.addability.status);assert(!/sausage in bread|banana bread|milk chocolate|milkshake|breast milk/i.test(item.name));}});
test('Bread relationships identify crumbs, rolls and common prepared foods without equating them',()=>{for(const [name,group] of [['Breadcrumbs, white','direct'],['Bread roll, from white flour','direct'],['Bread and butter pudding','related'],['French toast','related'],['Corn bread','related']]){const food={...afcdFoods[0],id:name,name},model=catalogue.conceptShortlist([food],search.interpretFoodIntent('Bread'));assert(model.groups.find(g=>g.key===group)?.items.some(i=>i.recordId===name));assert(!search.conceptCompatibility(food,'bread').compatible);}});
test('Bread commercial entry offers four source classes and retains wholemeal',()=>{const intent=search.interpretFoodIntent('Whole meal bread');assert.equal(search.nextConceptQuestion(intent,records).key,'breadOrigin');intent.known.breadOrigin='commercial';assert.deepEqual(search.nextConceptQuestion(intent,records).options.map(o=>o.value),['bakery','restaurant','brand','supermarket']);assert.equal(intent.known.breadType,'Wholemeal');});
test('Missing explicit restaurant and brand identities do not match another source',()=>{const hash=records.find(f=>f.foodSourceId&&search.conceptCompatibility(f,'hash-brown').compatible);assert(hash);for(const query of ['KFC hash brown',"Hungry Jack's hash brown",'Unlisted Brand hash brown'])assert(!catalogue.explicitIdentityMatch(hash,query));assert(catalogue.explicitIdentityMatch(hash,"McDonald's hash brown"));});
test('Big Mac capability requires Standard, blocks unsupported extras and preserves nutrition',()=>{const food=records.find(f=>f.name==='Big Mac'),session=guided.createSession([food],'Big Mac',{intent:{kind:'exact-product'}});assert.equal(session.stage,guided.stages.CUSTOMISATION);assert.equal(session.amount,null);guided.chooseCustomisation(session,'extras');guided.selectAmount(session,2);assert.equal(session.stage,guided.stages.UNSUPPORTED);assert.equal(session.nutrition,null);assert.equal(session.amount,null);assert.deepEqual(session.customisationProfile.components,[]);guided.chooseCustomisation(session,'standard');assert.equal(session.stage,guided.stages.AMOUNT);assert.equal(session.selectedMeasure.key,'burger');guided.selectAmount(session,1);assert.equal(session.nutrition.energyKj,2600);});
test('Diary hides bulk units while central safe mass and volume remain available',()=>{for(const [name,bulk,small] of [['Bread, from wholemeal flour','kg','g'],['Milk, cow, fluid, regular fat','L','mL']]){const food=afcdFoods.find(f=>f.name.startsWith(name));assert(food);const central=serving.servingMeasureProfile(food),diary=guided.servingProfile(food);if(bulk==='kg')assert(central.measures.some(m=>m.key===bulk));assert.deepEqual(serving.servingMeasureProfile(food).measures,central.measures);assert(!diary.measures.some(m=>m.key===bulk));assert(diary.measures.some(m=>m.key===small));}});
test('Flora current acceptance uses evidenced measures without requiring thickness',()=>{const profile=guided.servingProfile({name:'Flora ProActiv Light',brand:'Flora',ingredients:'Water, vegetable oils, phytosterol esters',category:'Spreads',recordType:'packaged',physicalForm:'spread',defaultUnit:'serve',serving:'1 serve (10 g)',units:{g:.1,serve:1},unitLabels:{serve:'10 g Serve'},manufacturerServing:{amount:10,unit:'g'},nutritionBasis:{manufacturerServing:true},nutrients:{calories:37,energyKj:154}});for(const key of ['tsp','tbsp','serve','g'])assert(profile.measures.some(m=>m.key===key));assert(!profile.measures.some(m=>/thinSpread|thickSpread/.test(m.key)));});

test('explicit missing brand products use the absence path while brand-only and source-only queries retain their hubs',()=>{assert(catalogue.isExplicitProductRequest('Flora unicorn product',{kind:'ambiguous'}));assert(catalogue.isExplicitProductRequest('KFC hash brown',{kind:'brand-product'}));assert(!catalogue.isExplicitProductRequest('Flora',{kind:'exact-product'}));assert(!catalogue.isExplicitProductRequest('KFC',{kind:'exact-product'}));for(const name of ['Banana','Orange','Potato'])assert(!catalogue.isExplicitProductRequest(name,{kind:'exact-product'}));assert(!catalogue.isExplicitProductRequest('Bread',{kind:'generic-concept',generic:true}));});

test('explicit brand concept queries reject containing dishes while preserving exact compound intent',()=>{const dish={name:'Hash brown quiche',brand:'McCain',recordType:'packaged'},query='McCain hash brown';assert(!catalogue.explicitIdentityMatch(dish,query,catalogue.queryIntent(query),search.interpretFoodIntent(query)));const exact='McCain hash brown quiche';assert(catalogue.explicitIdentityMatch(dish,exact,catalogue.queryIntent(exact),search.interpretFoodIntent(exact)));});

test('plural exact identity survives lexical filtering while consumed quantity stays separate',()=>{const food=records.find(f=>f.name==='Big Mac');for(const query of ['two Big Macs',"two McDonald's Big Macs"]){const model=catalogue.submittedResultModel(records,query);assert.equal(model.groups[0].key,'best');assert.equal(model.groups[0].items[0].recordId,food.id);assert.equal(model.quantity.consumedQuantity,2);}const model=catalogue.submittedResultModel(records,'two KFC 6 Wicked Wings');assert.equal(model.groups[0].key,'best');assert.equal(model.groups[0].items[0].name,'6 Wicked Wings');assert.equal(model.quantity.consumedQuantity,2);assert.equal(model.quantity.productVariantCount,6);});

test('unrelated loaded packs cannot reclassify consumed quantity as an exact product count',()=>{const mixed=[...records,{id:'unrelated-count',name:'2 Strawberry Tarts',productSemantics:{count:2}}];for(const query of ['two Big Macs',"two McDonald's Big Macs"]){const intent=search.interpretFoodIntent(query,{records:mixed,sourceIntent:catalogue.queryIntent(query)});assert.equal(intent.quantity.consumedQuantity,2);assert.equal(intent.quantity.productVariantCount,null);assert.equal(intent.kind,'exact-product');}const intent=search.parseQuantityLanguage('two KFC 6 Wicked Wings',{candidates:mixed});assert.equal(intent.consumedQuantity,2);assert.equal(intent.productVariantCount,6);});
