'use strict';
const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict'),qa=require('./audit_physical_form_measures_edge'),{returningProfile}=require('./audit_navigation_startup_edge'),{instrument,settled}=require('./profile_search_typing');
async function ready(p){await settled(p);await p.waitForFunction(()=>!HEC_AU_CATALOGUE_TEST.brandState()?.loading&&!HEC_FOOD_CONCEPT_TEST.state()?.loading);}
async function clear(p){if(await p.locator('[data-gpr-cancel]:visible').count())await p.locator('[data-gpr-cancel]:visible').click();await p.locator('#clear-food-search').click();await p.locator('#food-search').click();await ready(p);}
async function type(p,q){await clear(p);await p.locator('#food-search').pressSequentially(q,{delay:20});await ready(p);}
async function labels(p){return p.locator('#food-live-results [data-alpha0627-prediction]').evaluateAll(ns=>ns.filter(n=>n.querySelector('small').innerText==='Food suggestion').map(n=>n.querySelector('strong').innerText));}
async function gate(p){await p.evaluate(()=>{const timer=setTimeout,cancel=clearTimeout,g=window.__prefixGate={pending:[],id:-1};window.setTimeout=(fn,delay,...args)=>{if(delay===120){const task={id:g.id--,fn:()=>fn(...args)};g.pending.push(task);return task.id;}return timer(fn,delay,...args);};window.clearTimeout=id=>{if(id>=0)cancel(id);};g.release=async()=>{window.setTimeout=timer;window.clearTimeout=cancel;for(const t of g.pending)await t.fn();};});}
async function release(p){await p.evaluate(()=>__prefixGate.release());await ready(p);}
async function run({outputDirectory=fs.mkdtempSync(path.join(os.tmpdir(),'hec-live-prefix-'))}={}){fs.mkdirSync(outputDirectory,{recursive:true});const r={pass:false,viewport:{width:390,height:844},diagnostic:qa.evidence(),prefixes:[],ownership:[]},{chromium,edge}=qa.browserTools(),b=await chromium.launch({headless:true,executablePath:edge});let p;try{const c=await qa.contextFor({newContext:o=>b.newContext({...o,isMobile:true,hasTouch:true})},r.viewport,r.diagnostic);await c.addInitScript(returningProfile);await c.addInitScript(instrument);await c.addInitScript(()=>{window.__prefixClicks=[];document.addEventListener("click",e=>{const button=e.target.closest?.("button");if(button)__prefixClicks.push({trusted:e.isTrusted,button:button.outerHTML.slice(0,500)});},true);});p=await c.newPage();await p.goto(qa.ORIGIN+'/');await p.locator('#home [data-room="database"]').click();await p.evaluate(()=>__typing.begin());const compare=new Intl.Collator('en-AU',{sensitivity:'base',numeric:true});for(let repeat=0;repeat<2;repeat++)for(const q of ['Ba','Ban','Bac']){await type(p,q);const values=await labels(p);assert(values.length);assert.deepEqual(values,[...values].sort(compare.compare));assert(values.every(v=>v.toLowerCase().startsWith(q.toLowerCase())));if(q==='Bac')assert.deepEqual(values,['Bacon']);if(repeat)assert.deepEqual(values,r.prefixes.find(x=>x.query===q).labels);r.prefixes.push({query:q,repeat,labels:values});}await type(p,'Ba');await p.screenshot({path:path.join(outputDirectory,'ba.png'),fullPage:true});
 for(const next of ['Ban','Bac','clear','home']){await clear(p);await gate(p);await p.locator('#food-search').pressSequentially('Ba',{delay:20});const old=await p.evaluate(()=>HEC_SEARCH_SESSION_TEST.state().revision);if(next==='clear')await p.locator('#clear-food-search').click();else if(next==='home')await p.locator('#food-library [data-go="home"]').click();else await p.locator('#food-search').pressSequentially(next.slice(2),{delay:20});await release(p);assert.equal(await p.evaluate(rev=>HEC_SEARCH_SESSION_TEST.current(rev,'Ba'),old),false);if(next==='home'){await p.locator('#home.active').waitFor();assert.equal(await labels(p).then(x=>x.length),0);await p.locator('#home [data-room="database"]').click();}else if(next==='clear')assert.equal(await labels(p).then(x=>x.length),0);else assert((await labels(p)).every(x=>x.toLowerCase().startsWith(next.toLowerCase())));r.ownership.push({next,obsoleteRejected:true});}
 await type(p,'Banana');await p.locator('[data-alpha0623-guide="Banana"]:visible').click();await p.locator('#food-entry-editor.active').waitFor();r.banana=await p.evaluate(()=>({text:document.querySelector('#food-entry-editor').innerText,unit:document.querySelector('#entry-unit').value,amount:document.querySelector('#entry-amount').value,units:[...document.querySelector('#entry-unit').options].map(o=>({value:o.value,label:o.text})),nutrition:document.querySelector('#entry-nutrition-preview').innerText}));fs.writeFileSync(path.join(outputDirectory,'banana-state.json'),JSON.stringify(r.banana,null,2));assert.match(r.banana.text,/Banana, frozen/);assert.equal(r.banana.unit,'g');assert.equal(Number(r.banana.amount),1);assert.match(r.banana.nutrition,/1 Cal/);assert(!r.banana.units.some(o=>['ml','l'].includes(o.value.toLowerCase())));await p.screenshot({path:path.join(outputDirectory,'banana.png'),fullPage:true});await p.locator('#food-entry-editor').getByRole('button',{name:'← Back',exact:true}).click();
 // A complete indexed brand owns its audited directory; legacy seeds cannot
 // replace it merely because they matched an earlier partial prefix.
 await p.mouse.wheel(0,-5000);await p.locator('#food-library [data-go="home"]').click();await p.locator('#home [data-room="database"]').click();await clear(p);let prior='';r.weet=[];
 const expectedWeet=require('../brand-au-catalogue').entries.filter(e=>e.brandKeys.includes('weetbix')).map(e=>e.id).sort();assert.equal(expectedWeet.length,2);
 for(const q of ['Weet','Weet-b','Weet-bi','Weet-bix']){await p.locator('#food-search').pressSequentially(q.slice(prior.length),{delay:20});await ready(p);if(q==='Weet-bix'){const state=await p.evaluate(()=>HEC_AU_CATALOGUE_TEST.brandState());assert.equal(state.ownerQuery,q);assert.equal(state.model.total,expectedWeet.length);assert.deepEqual((await p.locator('#food-live-results [data-universal-result]').evaluateAll(ns=>ns.map(n=>n.dataset.universalResult))).sort(),expectedWeet);}else assert.match(await p.locator('#food-live-results').innerText(),/Weet-Bix Original/);r.weet.push(q);prior=q;}
 await p.locator('#submit-food-search').click();await p.locator('[data-au-brand-category="*"]').click();await ready(p);const cereal=await p.locator('[data-universal-result]').first().getAttribute('data-universal-result');assert(expectedWeet.includes(cereal));const cerealFood=await p.evaluate(id=>HEC_CANONICAL_CACHE_TEST.food(id),cereal);await p.locator('[data-universal-result="'+cereal+'"]').first().click();await p.locator('[data-gpr-measure="g"]:visible').click();await p.locator('[data-gpr-amount]:visible').fill('35');await p.locator('[data-gpr-amount]:visible').press('Enter');await p.locator('#food-entry-editor.active').waitFor();assert((await p.locator('#entry-nutrition-preview').innerText()).includes(Math.round(cerealFood.nutrients.calories*cerealFood.units.g*35)+' Cal'));await p.locator('#food-entry-editor').getByRole('button',{name:'← Back',exact:true}).click();

 r.brands=[];for(const q of ['Nescafe','Nescafé']){await type(p,q);const brand=await p.evaluate(()=>({text:document.querySelector('#food-live-results').innerText,state:HEC_AU_CATALOGUE_TEST.brandState()}));assert.match(brand.text,/Nescafé/i);assert(brand.state&&!brand.state.loading);r.brands.push({q,...brand});}
 // Current audited brand admission suppresses these incomplete products from
 // ordinary exact choice; the older test expected unaudited completion rows.
 r.nescafe=[];for(const q of ['Nescafe cappuccino','Nescafé cappuccino','Nescafé cappuccino strong']){await type(p,q);await p.locator('#submit-food-search').click();await p.locator('.universal-search-empty').waitFor();assert.equal(await p.locator('#food-results [data-universal-result]').count(),0);assert.equal(await p.locator('[data-gpr-measure]:visible,[data-gpr-amount]:visible,#food-entry-editor.active').count(),0);r.nescafe.push({q,incompleteSuppressed:true});}
 await p.mouse.wheel(0,-5000);await p.locator('#food-library [data-hec-back]').click();await p.locator('#home.active').waitFor();await ready(p);assert.equal((await labels(p)).length,0);r.final=await p.evaluate(()=>({diary:JSON.parse(localStorage.getItem(HEC_APP.functionalStorageKey)||'{}').diary||{},rejections:__navigationRejections,events:__navigationEvents,clicks:__prefixClicks}));assert.deepEqual(r.final.diary,{});assert.deepEqual(r.final.rejections,[]);assert(r.final.clicks.some(e=>e.trusted&&e.button.includes('data-alpha0623-guide')));qa.requireEvidence(r.diagnostic);r.pass=true;return r;}catch(e){r.error={message:e.message,stack:e.stack};if(p)await p.screenshot({path:path.join(outputDirectory,'failure.png'),fullPage:true}).catch(()=>{});throw e;}finally{await b.close();fs.writeFileSync(path.join(outputDirectory,'live-prefix.json'),JSON.stringify(r,null,2));console.log('Live prefix evidence: '+outputDirectory);}}
module.exports={run};if(require.main===module)run({outputDirectory:process.argv[2]}).then(r=>console.log(JSON.stringify({pass:r.pass,prefixes:r.prefixes}))).catch(e=>{console.error(e);process.exitCode=1;});
