'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const qa=require('./audit_physical_form_measures_edge'),{returningProfile}=require('./audit_navigation_startup_edge');
async function submit(page,query){await page.locator('#food-search').fill(query);await page.locator('#submit-food-search').click();await page.waitForFunction(q=>HEC_SEARCH_SESSION_TEST.state().rawQuery===q&&HEC_SEARCH_SESSION_TEST.state().mode==='explicit-committed',query);await settled(page);}
async function settled(page){await page.waitForFunction(()=>!HEC_RETAILER_TEST.state()?.loading&&!HEC_FOOD_CONCEPT_TEST.state()?.loading&&!HEC_AU_CATALOGUE_TEST.brandState()?.loading&&!/^Checking the Australian catalogue/.test(document.querySelector('#food-results')?.textContent.trim()||''));}
async function fresh(page){if(await page.locator('#a05-modal:not(.hidden)').count())await page.locator('#a05-modal-close').click();await page.evaluate(()=>openAlpha05Feature('food-library',{freshSearch:true}));}
async function review(page,sample){
  const id='woolworths-au:'+sample.id;await submit(page,sample.query);const row=page.locator(`[data-universal-result="${id}"]`);await row.waitFor();assert.match(await row.innerText(),new RegExp(sample.brand.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));
  const before=await page.evaluate(id=>{const f=HEC_CANONICAL_CACHE_TEST.food(id);return {brand:f.brand,nutrients:f.nutrients,membership:HECFoodCatalogue.retailerMembership(f,'woolworths'),pack:f.pack,source:HECFoodCatalogue.sourceEvidence(f)};},id);assert.equal(before.brand,sample.brand);assert(before.membership.length);await row.click();
  const unit=sample.unit||'g',control=page.locator(`[data-gpr-measure="${unit}"]:visible`);await control.waitFor();const measures=await page.locator('[data-gpr-measure]:visible').evaluateAll(ns=>ns.map(n=>({key:n.dataset.gprMeasure,label:n.innerText})));if(unit==='g')assert(!measures.some(m=>['mL','L','cup'].includes(m.key)));
  await control.click();const amount=page.locator('[data-gpr-amount]:visible');await amount.waitFor();assert.equal(await amount.inputValue(),'');await amount.fill('50');await amount.press('Enter');await page.locator('#food-entry-editor.active').waitFor();assert.equal(await page.locator('.screen.active').count(),1);assert.equal(await page.locator('#entry-amount').inputValue(),'50');assert.equal(await page.locator('#entry-unit').inputValue(),unit);assert.equal(await page.locator('[data-gpr-amount]:visible').count(),0);
  if(process.env.HEC_REVIEW_ONLY==='1'){const preview=await page.locator('#entry-nutrition-preview').innerText();assert(preview.includes(Math.round(before.nutrients.calories*.5).toLocaleString('en-AU')+' Cal'));await fresh(page);return {id,query:sample.query,brand:before.brand,measures,amount:50,unit,calories:before.nutrients.calories*.5,reviewCount:1,diarySaved:false};}
  if(await page.locator('#save-food-entry').innerText()==='Save Food'){await page.locator('#save-food-entry-and-food').click();await page.locator('#entry-meal:visible').waitFor();await page.locator('#entry-meal').selectOption('Lunch');await page.locator('#save-food-entry-and-food').click();}else{await page.locator('#entry-meal').selectOption('Lunch');await page.locator('#save-food-entry').click();}
  await page.waitForFunction(id=>Object.values(JSON.parse(localStorage.getItem(HEC_INSTALLATION.functionalStorageKey)||'{}').diary||{}).flat().some(e=>e.foodId===id),id);
  const entry=await page.evaluate(id=>Object.values(JSON.parse(localStorage.getItem(HEC_INSTALLATION.functionalStorageKey)||'{}').diary||{}).flat().find(e=>e.foodId===id),id);assert.equal(entry.foodSnapshot.brand,sample.brand);assert(Math.abs(entry.nutrients.calories-before.nutrients.calories*.5)<1);for(const [key,value] of Object.entries(before.nutrients))if(value===null)assert.equal(entry.nutrients[key],null);assert.equal(entry.consumedPortion.baseQuantity,50);assert.equal(entry.consumedPortion.baseUnit,unit);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await fresh(page);return {id,query:sample.query,brand:before.brand,source:before.source,pack:before.pack,measures,amount:50,unit,calories:entry.nutrients.calories,reviewCount:1};
}
async function run({outputDirectory=fs.mkdtempSync(path.join(os.tmpdir(),'hec-woolworths-'))}={}){
  fs.mkdirSync(outputDirectory,{recursive:true});const {chromium,edge}=qa.browserTools(),browser=await chromium.launch({headless:true,executablePath:edge}),report={pass:false,browser:browser.version(),contexts:[]};let page;
  try{for(const viewport of [{width:390,height:844},{width:375,height:812}]){
    const diagnostic=qa.evidence(),context=await qa.contextFor({newContext:options=>browser.newContext({...options,isMobile:true,hasTouch:true})},viewport,diagnostic);await context.addInitScript(returningProfile);
    const index=require('../woolworths-au-catalogue').index,cached=index.files.flatMap(file=>require('../data/woolworths-au/'+file.path).records).find(food=>food.id==='off:9300650664012');
    await context.addInitScript(food=>{if(location.origin==='https://mlwes-hec-test.github.io')localStorage.setItem('healthyEatingCompanionTestAlpha06Functional',JSON.stringify({onlineFoods:[food],ui:{},savedFoodIds:[]}));},cached);
    page=await context.newPage();await qa.openLibrary(page);const result={viewport,diagnostic,scenarios:[],reviews:[],restricted:[]};report.contexts.push(result);
    assert.equal(await page.evaluate(()=>HECRetailerCatalogue.directory('woolworths').total),923);assert.equal(diagnostic.routes.filter(r=>/woolworths-au\/products/.test(r.url)).length,0);await submit(page,'Woolworths');assert.equal(await page.locator('[data-retailer-category]').count(),21);assert.equal(diagnostic.routes.filter(r=>/woolworths-au\/products/.test(r.url)).length,0);await page.screenshot({path:path.join(outputDirectory,viewport.width+'-directory.png'),fullPage:true});result.scenarios.push('registered directory, 20 food categories plus All Items, zero startup hydration');
    await submit(page,'Hash Brown');const genericProduct=await page.evaluate(()=>HEC_CANONICAL_CACHE_TEST.food('off:9310174025084'));assert.equal(genericProduct.id,'woolworths-au:98299');assert.equal(genericProduct.nutrients.energyKj,724);result.scenarios.push('cold generic enrichment keeps the official canonical McCain record');
    await submit(page,'Woolworths');await page.locator('[data-retailer-category="*"]').click();await settled(page);assert.equal(await page.locator('[data-universal-result]').count(),20);await page.locator('[data-retailer-more]').click();await settled(page);assert.equal(await page.locator('[data-universal-result]').count(),20);await page.locator('[data-retailer-more]').click();await settled(page);assert.equal(await page.locator('[data-universal-result]').count(),20);await page.locator('[data-retailer-previous]').click();await settled(page);assert.equal(await page.locator('[data-universal-result]').count(),20);result.scenarios.push('20/20/20 canonical pagination and Previous');
    await submit(page,'Woolworths');await page.locator('[data-retailer-category="bread"]').click();await settled(page);assert.equal(await page.locator('[data-universal-result]').count(),20);assert.match(await page.locator('#food-results').innerText(),/Homestyle Bake/);assert.equal(await page.locator('#food-search').inputValue(),'Woolworths');result.scenarios.push('root retailer bread includes its actual national brand');
    for(const query of ['Bread','Milk','Carrot']){await submit(page,query);assert.equal(await page.evaluate(()=>HEC_RETAILER_TEST.state()),null);assert.equal(await page.locator('[data-fc-base],[data-universal-generic]').count(),1);assert.match(await page.locator('[data-fc-base],[data-universal-generic]').innerText(),new RegExp(query,'i'));result.scenarios.push(query+' stays concept first after retailer browse');}
    await submit(page,'Bread');await page.locator('[data-fc-base]').click();await page.locator('[data-fc-answer="breadOrigin"][data-fc-value="commercial"]').click();await page.locator('[data-fc-answer="breadSource"][data-fc-value="supermarket"]').click();await page.locator('[data-fc-answer="retailerIdentity"][data-fc-value="woolworths"]').click();await settled(page);assert.equal(await page.locator('[data-universal-result]').count(),9);assert(!/Homestyle Bake/.test(await page.locator('#food-results').innerText()));await page.screenshot({path:path.join(outputDirectory,viewport.width+'-guided-bread.png'),fullPage:true});result.scenarios.push('guided Woolworths commercial bread contains only verified private identities');
    await submit(page,"Kellogg's Corn Flakes");assert.equal(await page.evaluate(()=>HEC_RETAILER_TEST.state()),null);const corn=page.locator('[data-universal-result="off:8801083672700"]');await corn.waitFor();assert.match(await corn.innerText(),/Kellogg's/);result.scenarios.push('national cereal remains Kellogg’s and leaves retailer scope');
    for(const query of ['Woolworths bread','Woolworths milk']){await submit(page,query);const ids=await page.locator('[data-universal-result]').evaluateAll(ns=>ns.map(n=>n.dataset.universalResult));assert(ids.some(id=>id.startsWith('woolworths-au:')));result.scenarios.push(query+' includes verified production products');}
    const samples=[{id:'353871',query:'Woolworths Bread Wholemeal',brand:'Woolworths'},{id:'382738',query:'Woolworths Lite Milk',brand:'Woolworths',unit:'mL'},{id:'321220',query:'Woolworths Rolled Traditional Oats',brand:'Woolworths'},{id:'158188',query:'La Gina Baked Beans',brand:'La Gina'},{id:'233922',query:'Woolworths Smooth Peanut Butter',brand:'Woolworths'},{id:'36009',query:"Arnott's Milk Arrowroot Biscuits",brand:"Arnott's"},{id:'98299',query:'McCain Hash Browns',brand:'McCain'},{id:'825528',query:'Woolworths Orange Juice',brand:'Woolworths',unit:'mL'},{id:'756826',query:'The Natural Chip Co Sea Salt',brand:'The Natural Chip Co'},{id:'208679',query:'The Odd Bunch Apple',brand:'The Odd Bunch'},{id:'905257',query:'Woolworths Peri Peri Chicken',brand:'Woolworths'}];
    for(const sample of samples){result.reviews.push(await review(page,sample));console.log(JSON.stringify({viewport:viewport.width,reviewed:sample.id}));}
    for(const sample of [{id:'288440',query:'The Odd Bunch Carrots'},{id:'69286',query:'Bega Peanut Butter Smooth'},{id:'248249',query:'Uncle Tobys Muesli Bars Chewy Choc Chip'}]){const id='woolworths-au:'+sample.id;await submit(page,'Woolworths');const categoryId={288440:'produce',69286:'spreads',248249:'snacks'}[sample.id];await page.locator('[data-retailer-category="'+categoryId+'"]').click();await settled(page);while(!await page.locator('[data-universal-result="'+id+'"]').count()){assert(await page.locator('[data-retailer-more]').count(),'Restricted record must remain in its evidenced retailer category');await page.locator('[data-retailer-more]').click();await settled(page);}await page.locator(`[data-universal-result="${id}"]`).click();assert.equal(await page.locator('[data-gpr-measure]:visible,[data-gpr-amount]:visible,#food-entry-editor.active').count(),0);result.restricted.push({id,text:await page.locator('#food-results').innerText()});if(sample.id==='69286'){await page.locator('[data-food-details]:visible').click();const evidence=await page.locator('.identity-source-conflict').innerText();assert(evidence.includes('Bega')&&evidence.includes('Kraft'));await page.screenshot({path:path.join(outputDirectory,viewport.width+'-real-conflict.png'),fullPage:true});}await fresh(page);}
    const barcode=await page.evaluate(()=>HEC_LARGE_CATALOGUE_TEST.barcode('9300650664012'));assert.equal(barcode.brand,'Bega');assert.equal(barcode.loggable,false);assert(barcode.canonicalEvidence.some(e=>e.brand==='Kraft'));result.scenarios.push('barcode consumer retains the real Bega/Kraft identity conflict');
    await page.evaluate(()=>HEC_CANONICAL_CACHE_TEST.render('Bega Peanut Butter Smooth'));assert.equal(await page.locator('#food-results .resource-row').count(),1);assert.equal(await page.locator('#food-results [data-food-add]').isDisabled(),true);assert.match(await page.locator('#food-results').innerText(),/Bega/);result.scenarios.push('real cached renderer retains official brand and blocks the conflicting raw OFF representative');
    qa.requireEvidence(diagnostic);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await context.close();
  }report.pass=true;return report;}catch(error){report.error={message:error.message,stack:error.stack};throw error;}finally{if(page&&!page.isClosed())await page.screenshot({path:path.join(outputDirectory,'last-state.png'),fullPage:true}).catch(()=>{});await browser.close();fs.writeFileSync(path.join(outputDirectory,'woolworths-rendered.json'),JSON.stringify(report,null,2));}
}
if(require.main===module)run({outputDirectory:process.argv[2]}).then(r=>console.log(JSON.stringify({pass:r.pass,contexts:r.contexts.map(c=>({viewport:c.viewport,scenarios:c.scenarios.length,reviews:c.reviews.length,restricted:c.restricted.length}))}))).catch(error=>{console.error(error);process.exitCode=1});
module.exports={run};
