#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'),base=require('./audit_open_food_facts_au.js'),packaged=require('../packaged-foods.js'),serving=require('../serving-foundation.js'),guided=require('../guided-product-resolution.js');
const manifest=base.read('manifest.json'),products=base.allProducts(manifest),DATA=base.DATA;
const nutrientValues=record=>({calories:record.nutrients?.calories,energyKj:record.nutrients?.energyKj,protein:record.nutrients?.protein,carbs:record.nutrients?.carbs,fat:record.nutrients?.fat,fibre:record.nutrients?.fibre});
async function genericAudit(count=50){const entries=[];for(const shard of manifest.intelligenceShards||[]){const data=base.read(shard.path);for(const [key,value] of Object.entries(data.concepts||{}))if(value.refs.length>=20)entries.push({key,count:value.refs.length});}entries.sort((a,b)=>a.key.localeCompare(b.key));const sample=base.sampleEvenly(entries,count);let correct=0;const failures=[];for(const concept of sample){const result=await base.api.search(concept.key,{limit:10}),pass=result.intent.kind==='generic-category'&&result.foods.length>0&&result.foods.every(food=>food.searchGroup==='primary');if(pass)correct++;else failures.push({concept:concept.key,intent:result.intent.kind,total:result.total,primary:result.groups.primary});}return {sampled:sample.length,correct,accuracyPercent:+(correct*100/sample.length).toFixed(2),failures};}
function nutritionAudit(){const eligible=products.filter(product=>product.nutritionCompleteness!=='identity-only'),counts={usable:0,partial:0,suspect:0,'identity-only':0,energyPairConflict:0,macroEnergySuspect:0,missingRequired:0};for(const product of eligible){const result=packaged.nutritionIntegrity(nutrientValues(product));counts[result.status]++;if(result.energy.status==='conflict')counts.energyPairConflict++;if(result.macro.status==='suspect')counts.macroEnergySuspect++;if(result.missing.length)counts.missingRequired++;}return {audited:eligible.length,...counts,downgraded:counts.partial+counts.suspect+counts['identity-only']};}
function energyAudit(count=1000){const eligible=products.filter(product=>product.nutrients?.calories!=null||product.nutrients?.energyKj!=null),sample=base.sampleEvenly(eligible,count);let mismatches=0,sourceConflicts=0;for(const product of sample){const result=packaged.scaleNormalised(nutrientValues(product),.37);if(result.integrity.status==='conflict')sourceConflicts++;const kcal=result.nutrients.calories,kj=result.nutrients.energyKj;if(kcal!=null&&kj!=null&&Math.abs(kcal*4.184-kj)/Math.max(Math.abs(kj),20)>.01)mismatches++;}return {sampled:sample.length,displayMismatches:mismatches,sourceConflicts};}
function servingAudit(){const seen=new Set(),rows=[];for(const record of products){const food=base.api.toFood(record),profile=guided.servingProfile(food),form=profile?.physicalForm||serving.physicalForm(food).form;if(!profile?.measures?.length)continue;const group=form==='liquid'?(profile.measures.some(item=>item.key==='serve')?'liquid-beverage':'volume-only'):form;if(seen.has(group))continue;const measure=profile.measures[0],session=guided.createSession([food],food.name,{intent:{kind:'exact-product'}});guided.selectMeasure(session,measure.key);guided.selectAmount(session,1.25);rows.push({form:group,id:food.id,name:food.name,measures:profile.measures.map(item=>item.key),amount:session.amount,scaled:!!session.nutrition});seen.add(group);if(seen.size>=7)break;}return {sampled:rows.length,forms:[...seen],rows};}
async function realProbes(){const out={};for(const query of ['Flora','Meadow Lea','MeadowLea','Milk','Pauls',"Paul's",'Trim Milk','Pauls Trim Milk']){const result=await base.api.search(query,{limit:10});out[query]={intent:result.intent.kind,total:result.total,primary:result.groups.primary,examples:result.foods.slice(0,5).map(food=>`${food.brand} — ${food.name}`),facets:(result.facets||[]).slice(0,5)};}return out;}
async function run(){const [retrieval,brands,generics,performance,probes]=await Promise.all([base.retrievalAudit(products,1000),base.brandAudit(manifest,100),genericAudit(50),base.performanceAudit(products,500),realProbes()]),nutrition=nutritionAudit(),energy=energyAudit(1000),servings=servingAudit(),architecture={
  newBrandWithoutCode:manifest.searchIntelligence?.brands===manifest.uniqueBrands,newFamilyWithoutWizard:/category/.test(fs.readFileSync(path.join(base.ROOT,'guided-product-resolution.js'),'utf8')),newLiquidProfile:serving.physicalForm({physicalForm:'liquid'}).form==='liquid',newSpreadProfile:serving.physicalForm({physicalForm:'spread'}).form==='spread',categoryOutranksIncidental:generics.correct===generics.sampled,onlineDoesNotReorderLocal:/all-resources-online/.test(fs.readFileSync(path.join(base.ROOT,'alpha06.js'),'utf8')),missingRemainsUnknown:packaged.scale({calories:1},1).protein===null,energyOneNormalisedAmount:energy.displayMismatches===0,allProductsAccessible:manifest.importedProducts===73300,servingAfterExactProduct:guided.createSession([base.api.toFood(products.find(product=>product.name))],'product',{intent:{kind:'exact-product'}}).stage===guided.stages.MEASURE
  };return {catalogue:{snapshot:manifest.sourceSnapshotDate,sourceSha256:manifest.sourceSha256,products:manifest.importedProducts,brands:manifest.uniqueBrands,intelligenceFiles:manifest.searchIntelligence.files,intelligenceBytes:manifest.searchIntelligence.bytes,manifestBytes:fs.statSync(path.join(DATA,'manifest.json')).size},probes,retrieval,brands,generics,servings,energy,nutrition,performance,architecture,allArchitectureYes:Object.values(architecture).every(Boolean)};}
if(require.main===module)run().then(result=>{console.log(JSON.stringify(result,null,2));if(result.retrieval.top10Percent<98||result.brands.complete!==100||result.brands.contamination||result.generics.correct!==50||result.energy.displayMismatches||!result.allArchitectureYes)process.exitCode=1;}).catch(error=>{console.error(error);process.exit(1);});
module.exports={genericAudit,nutritionAudit,energyAudit,servingAudit,realProbes,run};
