'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const qa=require('./audit_physical_form_measures_edge'),t=require('./audit_brand_wave_edge');
async function run(out){
 fs.mkdirSync(out,{recursive:true});const report={pass:false,generation:require('../release-manifest.json').generation,queries:[],navigation:[],diagnostic:qa.evidence()}, {chromium,edge}=qa.browserTools(),browser=await chromium.launch({headless:true,executablePath:edge});let p;
 try{
  for(const viewport of [{width:390,height:844},{width:375,height:812},{width:320,height:568}]){
   const context=await qa.contextFor(browser,viewport,report.diagnostic);p=await context.newPage();await qa.openLibrary(p);
   for(const query of ['Pepsi','Pepsi Max','Pepsi Max 2L','Coca-Cola','Coke','Coca-Cola Classic','Diet Coke','Coke Zero','Coca-Cola Zero Sugar','Black & Gold Cola Zero Sugar','Sprite','Lipton','Berg','Berg honey ham',"Kellogg's",'Woolworths','Woolies','Coles','Aldi','IGA','Super IGA']){
    await t.fresh(p);await t.submit(p,query);const rows=await p.locator('#food-results [data-universal-result]').count(),text=await p.locator('#food-results').innerText();
    assert(rows>0,query+' has no direct products: '+text);assert(rows<=24,query+' unbounded rendering');assert(!/Open Food Facts AU|Nutrition Reference per 100g|Loggable now/.test(text));await t.geometry(p);
    report.queries.push({query,...viewport,rows});
    if(['Pepsi','Berg','IGA','Woolworths'].includes(query))await p.screenshot({path:path.join(out,viewport.width+'-'+query+'.png'),fullPage:true});
   }
   await t.fresh(p);await t.submit(p,'IGA');await p.locator('[data-retailer-brand="communityco"]').click();await t.settled(p);
   await p.locator('[data-discovery-filter]').fill('sourdough');await p.waitForFunction(()=>document.querySelectorAll('#food-results [data-universal-result]').length===1);const before=await p.evaluate(()=>{const data=JSON.parse(localStorage.getItem(HEC_APP.functionalStorageKey)||'{}');return JSON.stringify(data.diary||{});});
   await p.locator('#food-results [data-universal-result]').click();await p.locator('[data-gpr-measure="serve"]:visible').click();await p.locator('[data-gpr-amount]:visible').fill('1');await p.locator('[data-gpr-continue]:visible').click();await p.locator('#food-entry-editor.active').waitFor();await p.screenshot({path:path.join(out,viewport.width+'-review.png'),fullPage:true});
   await p.locator('#entry-editor-back').click();await p.locator('[data-gpr-amount]:visible').waitFor();await p.locator('[data-gpr-amount]:visible').fill('1');await p.locator('[data-gpr-continue]:visible').click();await p.locator('[data-discovery-review-cancel]:visible').click();
   await p.waitForFunction(()=>document.querySelector('[data-discovery-filter]')?.value==='sourdough');assert.equal(await p.locator('#food-results [data-universal-result]').count(),1);const state=await p.evaluate(()=>HEC_RETAILER_TEST.state());assert.equal(state.brandKey,'communityco');assert.equal(await p.evaluate(()=>{const data=JSON.parse(localStorage.getItem(HEC_APP.functionalStorageKey)||'{}');return JSON.stringify(data.diary||{});}),before,'Cancel changed Diary');await t.geometry(p);report.navigation.push({...viewport,retailer:state.retailerId,brand:state.brandKey,filter:'sourdough',reviewBackToAmount:true,cancelReturnsToCatalogue:true});
   await t.fresh(p);await t.submit(p,"Kellogg's");const initialBrand=await p.locator('#food-results [data-universal-result]').allTextContents();await p.locator('[data-au-brand-more]').click();assert((await p.locator('#food-results [data-universal-result]').count())<=20);assert.notDeepEqual(await p.locator('#food-results [data-universal-result]').allTextContents(),initialBrand);await p.locator('[data-discovery-filter]').fill('corn flakes');await p.waitForFunction(()=>document.querySelector('[data-discovery-filter]')?.value==='corn flakes'&&[...document.querySelectorAll('#food-results [data-universal-result]')].every(e=>/corn flakes/i.test(e.textContent)));assert((await p.locator('#food-results [data-universal-result]').count())>0);await p.locator('[data-discovery-clear]').click();await p.waitForFunction(()=>document.querySelector('[data-discovery-filter]')?.value===''&&document.querySelectorAll('#food-results [data-universal-result]').length===20);await t.geometry(p);
   // Brand amount Back returns through one meaningful step, retaining the query.
   await t.fresh(p);await t.submit(p,'Pepsi');await p.locator('#food-results [data-universal-result]').first().click();const measure=p.locator('[data-gpr-measure="mL"]:visible');if(await measure.count())await measure.click();await p.locator('[data-gpr-amount]:visible').waitFor();await p.locator('[data-gpr-back]:visible').click();if(await p.locator('[data-gpr-back]:visible').count())await p.locator('[data-gpr-back]:visible').click();await p.locator('[data-discovery-brand-browse]').waitFor();assert.equal(await p.locator('#food-search').inputValue(),'Pepsi');
   // Retailer category / filter / final Review cancellation preserves context.
   await t.fresh(p);await t.submit(p,'Woolworths');await p.locator('[data-discovery-retailer-browse]').click();await t.settled(p);await p.locator('[data-retailer-category="bread"]').click();await t.settled(p);await p.locator('[data-discovery-filter]').fill('bread');await p.waitForTimeout(220);await t.settled(p);await p.locator('#food-results [data-universal-result]').first().click();const grams=p.locator('[data-gpr-measure="g"]:visible');if(await grams.count())await grams.click();await p.locator('[data-gpr-amount]:visible').fill('40');await p.locator('[data-gpr-continue]:visible').click();await p.locator('#food-entry-editor.active').waitFor();
   // Controls remain reachable in a reduced viewport, approximating an open keyboard.
   await p.setViewportSize({width:viewport.width,height:Math.max(360,viewport.height-250)});for(const selector of ['#entry-editor-back','[data-discovery-review-cancel]','#save-food-entry']){const r=await p.locator(selector).boundingBox();assert(r&&r.x>=0&&r.x+r.width<=viewport.width+1&&r.y>=0&&r.y+r.height<=Math.max(360,viewport.height-250)+1,'Unreachable action '+selector);}await p.setViewportSize(viewport);
   await p.locator('[data-discovery-review-cancel]:visible').click();await p.waitForFunction(()=>document.querySelector('[data-discovery-filter]')?.value==='bread');assert.equal(await p.evaluate(()=>HEC_RETAILER_TEST.state().categoryId),'bread');report.navigation.push({...viewport,retailerCategoryCancel:true,brandAmountBack:true,keyboardControlsReachable:true,diaryUnchanged:true});
   await context.close();
  }
  qa.requireEvidence(report.diagnostic);
  const diagnostic=qa.evidence(),context=await qa.contextFor(browser,{width:390,height:844},diagnostic);p=await context.newPage();await qa.openLibrary(p);const paths=await p.evaluate(()=>HECBrandCatalogue.rowsFor('pepsi').map(e=>e.shard).filter(Boolean));let release;const gate=new Promise(r=>release=r),held=[];await p.route('**/data/brand-au/products/**',async route=>{if(paths.some(file=>route.request().url().endsWith(file))){held.push(route.request().url());await gate;}await route.fallback();});await p.locator('#food-search').fill('Pepsi');await p.locator('#submit-food-search').click();await p.waitForFunction(()=>HEC_AU_CATALOGUE_TEST.status()?.loading);await p.waitForTimeout(100);assert(held.length);await t.submit(p,'Berg');release();await p.waitForLoadState('networkidle');assert.equal(await p.evaluate(()=>HEC_AU_CATALOGUE_TEST.status()?.query),'Berg');assert.match(await p.locator('#food-results').innerText(),/Honey Leg Ham/);qa.requireEvidence(diagnostic);report.lateResult={held:held.length,preservedQuery:'Berg',diagnostic};await context.close();report.pass=true;
 }catch(e){report.error={message:e.message,stack:e.stack};if(p&&!p.isClosed())await p.screenshot({path:path.join(out,'failure.png'),fullPage:true});throw e;}
 finally{await browser.close();fs.writeFileSync(path.join(out,'rendered.json'),JSON.stringify(report,null,2)+'\n');}
 return report;
}
if(require.main===module)run(process.argv[2]||'data/catalogue-wave-5a/rendered').then(r=>console.log(JSON.stringify({pass:r.pass,queries:r.queries.length,navigation:r.navigation.length}))).catch(e=>{console.error(e);process.exitCode=1;});
module.exports={run};
