'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),qa=require('./audit_physical_form_measures_edge'),{returningProfile}=require('./audit_navigation_startup_edge'),f=require('../tests/fixtures/barcode-confirmation');require('../packaged-foods');require('../product-serving-semantics');require('../serving-foundation');require('../food-catalogue');const X=require('../capture-foundation');
const output=process.argv[2]||'data/saved-nutrition-repair/flows';
async function run(){fs.mkdirSync(output,{recursive:true});const r={pass:false,checks:[],diagnostic:qa.evidence()},{chromium,edge}=qa.browserTools(),browser=await chromium.launch({headless:true,executablePath:edge});let p;
try{const c=await qa.contextFor({newContext:o=>browser.newContext({...o,isMobile:true,hasTouch:true})},{width:390,height:844},r.diagnostic);await c.addInitScript(returningProfile);const food=X.buildBarcodeFood({food:f.food,id:'synthetic-saved-review',confirmed:true}).food;food.customNotes='Synthetic retained note';food.createdAt='2026-01-01T00:00:00.000Z';food.foodGroups={dairy:1};
const plain={...structuredClone(food),id:'synthetic-normal-private',name:'Synthetic Plain Private',barcode:'9900000000202'};delete plain.captureEvidence;plain.source='User Created';
await c.addInitScript(foods=>{if(location.origin!=='https://mlwes-hec-test.github.io'||localStorage.getItem('synthetic-review-seeded'))return;localStorage.setItem('healthyEatingCompanionTestAlpha06Functional',JSON.stringify({customFoods:foods,savedFoodIds:foods.map(f=>f.id),onlineFoods:[],ui:{}}));localStorage.setItem('synthetic-review-seeded','yes');},[food,plain]);p=await c.newPage();await p.goto(qa.ORIGIN+'/');await p.waitForFunction(()=>HECRelease.snapshot().state==='ready');
const state=()=>p.evaluate(()=>JSON.parse(localStorage.getItem(HEC_APP.functionalStorageKey))),saved=async()=> (await state()).customFoods.find(x=>x.id===food.id),diary=async()=>JSON.stringify((await state()).diary||{});
const snap=async name=>{assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await p.screenshot({path:path.join(output,name+'.png'),fullPage:true});r.checks.push(name);};
const library=async()=>{await p.evaluate(()=>openAlpha05Feature('food-library'));await p.locator('[data-library-tab="saved"]').click();};
const open=async(id=food.id)=>{await library();await p.locator('#food-results [data-food-save="'+id+'"]').locator('..').locator('.resource-main').click();};
const review=async()=>{await open();const action=p.locator('[data-review-product-nutrition="'+food.id+'"]:visible');await action.waitFor({state:'visible'});assert.match(await action.innerText(),/Review \/ Update Nutrition/);const rect=await action.boundingBox();assert(rect.x>=0&&rect.x+rect.width<=391&&rect.y>=0&&rect.y+rect.height<844);await action.click();await p.locator('#scan-centre.active').waitFor();};
const text=async value=>{await p.locator('.ocr-raw-details').evaluate(n=>n.open=true);await p.locator('#ocr-text').fill(value);await p.locator('#capture-parse-text').click();};
const save=async choice=>{await p.locator('#capture-value-choice').selectOption(choice);await p.locator('#ocr-package-confirmed').check();if(await p.locator('#ocr-discrepancy-confirm-row').isVisible())await p.locator('#ocr-discrepancy-confirmed').check();await p.locator('[data-capture-source="ocr"][data-capture-action="save"]').click();await p.locator('#food-library.active').waitFor();};
const log=async()=>{await require('./capture_amount_test_helper')(p);await p.locator('#food-entry-editor.active').waitFor();assert.equal(await p.locator('.screen.active').count(),1);await p.locator('#entry-meal').selectOption('Lunch');await p.locator('#entry-amount').fill('1');await p.locator('#save-food-entry').click();};
await open();await snap('01-saved-normal-action');await log();const history=await diary(),before=JSON.stringify(await saved());assert.equal(Object.values(JSON.parse(history)).flat()[0].nutrients.fat,5.3);
await review();assert.equal(await p.locator('#ocr-fat').inputValue(),'5.3');assert.equal(await p.locator('#ocr-food-brand').inputValue(),food.brand);assert.equal(await p.locator('#ocr-food-name').inputValue(),food.name);assert.equal(await p.locator('#ocr-serving-amount').inputValue(),'170');assert.equal(await p.locator('#ocr-pack-size').inputValue(),'170 g');await snap('02-saved-baseline');
await text('Ingredients: Milk, vanilla.');assert.equal(await p.locator('#ocr-fat').inputValue(),'5.3');assert.match(await p.locator('#capture-field-issues').innerText(),/No usable nutrition/);assert.equal(await p.locator('#ocr-ingredients').inputValue(),'Milk, vanilla.');await snap('03-zero-ocr');await p.locator('#ocr-fat').fill('9');await p.locator('#capture-cancel').click();await p.locator('#food-library.active').waitFor();assert.equal(JSON.stringify(await saved()),before);assert.equal(await diary(),history);r.checks.push('cancel-no-partial-write');
await review();await text('Per serving\nEnergy 670 kJ\nFat 33 g');assert.equal(await p.locator('#ocr-protein').inputValue(),'3.3');await save('catalogue');assert.equal((await saved()).nutrients.fat,5.3);assert.equal(await diary(),history);r.checks.push('keep-existing');
await review();await text('Per serving\nEnergy 670 kJ\nFat 5.1 g');assert.equal(await p.locator('#ocr-fat').inputValue(),'5.1');assert.equal(await p.locator('#ocr-protein').inputValue(),'3.3');assert.match(await p.locator('#capture-comparison').innerText(),/Saved Value 5.3 → Panel Read Value 5.1/);assert.match(await p.locator('#capture-comparison').innerText(),/Differ From Saved Values/);assert.doesNotMatch(await p.locator('#capture-comparison').innerText(),/protein/);await snap('04-partial-comparison');await save('panel');const updated=await saved();assert.equal(updated.id,food.id);assert.equal(updated.barcode,food.barcode);assert.equal(updated.name,food.name);assert.equal(updated.brand,food.brand);assert.equal(updated.nutrients.fat,5.1);assert.equal(updated.customNotes,food.customNotes);assert.equal(updated.createdAt,food.createdAt);assert.deepEqual(updated.foodGroups,food.foodGroups);assert(updated.captureEvidence.previous);assert.equal((await state()).customFoods.length,2);assert.equal(await diary(),history);r.checks.push('same-id-no-duplicate-history-intact');
await p.reload();await p.waitForFunction(()=>HECRelease.snapshot().state==='ready');await open();await log();const entries=Object.values((await state()).diary).flat();assert.equal(entries.length,2);assert.equal(entries[0].nutrients.fat,5.3);assert.equal(entries[0].foodSnapshot.nutrients.fat,5.3);assert.equal(entries[1].nutrients.fat,5.1);assert.equal(entries[1].foodSnapshot.nutrients.fat,5.1);r.checks.push('future-diary-updated-after-reload');
await review();await p.evaluate(()=>{window.Tesseract={createWorker:async()=>({setParameters:async()=>{},recognize:async()=>({data:{text:'Ingredients: Milk, vanilla.\nPer serving\nEnergy 670 kJ\nFat 5.2 g',confidence:95}}),terminate:async()=>{}})};});await p.locator('#scan-image').setInputFiles(path.resolve('data/saved-nutrition-repair/ocr/clean-flat-original.png'));await p.locator('#run-label-ocr').click();await p.waitForFunction(()=>document.querySelector('#ocr-fat').value==='5.2');await snap('05-photo-extraction');await p.locator('#capture-retry').click();assert.equal(await p.locator('#ocr-fat').inputValue(),'5.1');assert.equal(await p.locator('#ocr-food-name').inputValue(),food.name);assert.equal(await p.locator('#ocr-text').inputValue(),'');r.checks.push('retry-saved-identity-baseline');
// Hold an old OCR attempt, reset the attempt, then deliver the stale result.
await p.evaluate(()=>{window.Tesseract={createWorker:async()=>({setParameters:async()=>{},recognize:()=>new Promise(resolve=>window.syntheticOcrResolve=resolve),terminate:async()=>{}})};});await p.locator('#scan-image').setInputFiles(path.resolve('data/saved-nutrition-repair/ocr/clean-flat-original.png'));await p.locator('#run-label-ocr').click();await p.waitForFunction(()=>typeof window.syntheticOcrResolve==='function');await p.locator('#capture-retry').click();await p.evaluate(()=>window.syntheticOcrResolve({data:{text:'Per serving\nEnergy 670 kJ\nFat 99 g'}}));await p.waitForFunction(()=>document.querySelector('#ocr-fat').value==='5.1');await p.locator('#capture-new-active').click();assert.equal(await p.locator('#ocr-food-name').inputValue(),'');assert.equal(await p.locator('#ocr-fat').inputValue(),'');assert.match(await p.locator('#scan-mode-copy').innerText(),/New capture/);r.checks.push('late-ocr-discarded-start-new-clears-context');
await p.locator('#capture-manual').click();await p.locator('#ocr-food-name').fill('Synthetic New Standalone');await text('Servings per package 2\nServing size 1 piece\nPer serving\nEnergy 400 kJ\nFat 1.7 g\nIngredients: Oats.');await p.locator('#ocr-package-confirmed').check();await p.locator('[data-capture-source="ocr"][data-capture-action="save"]').click();await p.locator('#food-library.active').waitFor();const fresh=(await state()).customFoods.find(x=>x.name==='Synthetic New Standalone');assert(fresh);assert.notEqual(fresh.id,food.id);assert.equal(fresh.barcode,'');assert.equal(fresh.ingredients,'Oats.');assert.equal((await saved()).nutrients.fat,5.1);r.checks.push('standalone-fixed-serve-ingredients-new-id');
await open(plain.id);await p.locator('#food-entry-editor.active').waitFor();const normalAction=p.locator('#entry-saved-nutrition-action [data-review-product-nutrition="'+plain.id+'"]');await normalAction.waitFor({state:'visible'});await normalAction.click();assert.equal(await p.locator('#ocr-food-name').inputValue(),plain.name);await p.locator('#capture-cancel').click();r.checks.push('normal-private-review-controller-action');
qa.requireEvidence(r.diagnostic);r.pass=true;
}catch(e){r.error={message:e.message,stack:e.stack};if(p)await p.screenshot({path:path.join(output,'failure.png'),fullPage:true});throw e;}finally{await browser.close();fs.writeFileSync(path.join(output,'flows.json'),JSON.stringify(r,null,2));}console.log(JSON.stringify({pass:r.pass,checks:r.checks}));}
run().catch(e=>{console.error(e);process.exitCode=1;});
