'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),qa=require('./audit_physical_form_measures_edge'),{returningProfile}=require('./audit_navigation_startup_edge'),f=require('../tests/fixtures/barcode-confirmation');
const output=process.argv[2]||'data/barcode-panel-repair/flows';
async function run(){fs.mkdirSync(output,{recursive:true});const r={pass:false,steps:[],diagnostic:qa.evidence()},{chromium,edge}=qa.browserTools(),browser=await chromium.launch({headless:true,executablePath:edge});let p;
try{const c=await qa.contextFor({newContext:o=>browser.newContext({...o,isMobile:true,hasTouch:true})},{width:390,height:844},r.diagnostic);await c.addInitScript(returningProfile);
 await c.route('**/api/v2/product/**',route=>route.fulfill({json:{status:1,product:f.product}}));
 p=await c.newPage();await p.goto(qa.ORIGIN+'/');await p.waitForFunction(()=>HECRelease.snapshot().state==='ready');
 const evidence=st=>JSON.stringify(st.onlineFoods.map(({createdAt,updatedAt,__alpha0615Units,...food})=>food));
 const state=()=>p.evaluate(()=>JSON.parse(localStorage.getItem(HEC_APP.functionalStorageKey)));
 const snap=async name=>{assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);const controls=await p.locator('#scan-centre button:visible,#scan-centre select:visible,#scan-centre input:visible').evaluateAll(ns=>ns.filter(n=>{const b=n.getBoundingClientRect();return b.left<0||b.right>innerWidth+1;}).map(n=>n.id));assert.deepEqual(controls,[]);await p.screenshot({path:path.join(output,name+'.png'),fullPage:true});r.steps.push(name);};
 const scan=async()=>{await p.evaluate(()=>openAlpha05Feature('scan-centre'));await p.locator('[data-scan-mode="barcode"]').click();await p.locator('#manual-barcode-details').evaluate(n=>n.open=true);await p.locator('#scan-barcode-input').fill(f.code);await p.locator('#lookup-barcode').click();await p.locator('[data-compare-barcode-panel]').waitFor();};
 const diary=async id=>{await require('./capture_amount_test_helper')(p);await p.locator('#food-entry-editor.active').waitFor();assert.equal(await p.locator('.screen.active').count(),1);await p.locator('#entry-amount').fill('1');await p.locator('#entry-meal').selectOption('Lunch');await p.locator('#save-food-entry').click();const entries=Object.values((await state()).diary).flat();assert.equal(entries.at(-1).foodId,id);return entries.length;};
 await scan();assert(await p.locator('[data-capture-source="barcode"][data-capture-action="both"]').isDisabled());await p.locator('#barcode-package-confirmed').check();assert(await p.locator('[data-capture-source="barcode"][data-capture-action="both"]').isEnabled());await snap('01-checked-barcode');let onlineBefore=evidence(await state());
 await p.locator('[data-capture-source="barcode"][data-capture-action="both"]').click();let st=await state(),food=st.customFoods.find(x=>x.barcode===f.code);assert(food);assert.equal(food.recordType,'private');assert.equal(food.nutrients.fat,5.3);const id=food.id;assert.equal(Object.values(st.diary||{}).flat().length,0);assert.equal(await diary(id),1);r.directBoth=true;
 await scan();await p.locator('#barcode-package-confirmed').check();await p.locator('[data-capture-source="barcode"][data-capture-action="save"]').click();st=await state();assert.equal(st.customFoods.filter(x=>x.barcode===f.code).length,1);assert.equal(Object.values(st.diary).flat().length,1);assert.equal(st.customFoods.find(x=>x.barcode===f.code).id,id);r.saveOnly=true;
 await p.evaluate(()=>openAlpha05Feature('home'));await p.reload();await p.waitForFunction(()=>HECRelease.snapshot().state==='ready');await p.evaluate(()=>openAlpha05Feature('food-library'));await p.locator('[data-library-tab="saved"]').click();await p.locator('#food-results [data-food-save="'+id+'"]').locator('..').locator('.resource-main').click();assert.equal(await diary(id),2);r.reopenDiary=true;
 await scan();await p.locator('[data-compare-barcode-panel]').click();assert.equal(await p.locator('#ocr-fat').inputValue(),'5.3');
 const text=async value=>{await p.locator('.ocr-raw-details').evaluate(n=>n.open=true);await p.locator('#ocr-text').fill(value);await p.locator('#capture-parse-text').click();};
 onlineBefore=evidence(await state());await text(f.badText);assert.equal(await p.locator('#ocr-fat').inputValue(),'33');await snap('02-bad-ocr-comparison');await p.locator('#capture-value-choice').selectOption('catalogue');assert.equal(await p.locator('#ocr-fat').inputValue(),'5.3');assert.equal(await p.locator('#ocr-protein').inputValue(),'3.3');await p.locator('#ocr-package-confirmed').check();assert(await p.locator('[data-capture-source="ocr"][data-capture-action="save"]').isEnabled());await snap('03-barcode-selected');await p.locator('[data-capture-source="ocr"][data-capture-action="both"]').click();assert.equal(await diary(id),3);st=await state();food=st.customFoods.find(x=>x.id===id);assert.equal(food.nutrients.fat,5.3);assert.equal(food.captureEvidence.extracted.perServing.fat,33);assert.equal(evidence(st),onlineBefore);r.barcodeChoice=true;
 await scan();await p.locator('[data-compare-barcode-panel]').click();await text(f.badText);await p.locator('#capture-value-choice').selectOption('panel');await p.locator('#ocr-fat').fill('5.1');await p.locator('#ocr-package-confirmed').check();await p.locator('[data-capture-source="ocr"][data-capture-action="both"]').click();assert.equal(await diary(id),4);food=(await state()).customFoods.find(x=>x.id===id);assert.equal(food.nutrients.fat,5.1);assert.equal(food.captureEvidence.catalogue.nutrients.fat,5.3);r.physicalChoice=true;
 // Empty OCR must still allow a whole barcode choice, with no retyping.
 await scan();await p.locator('[data-compare-barcode-panel]').click();await text('Unrecognised synthetic photo');assert.equal(await p.locator('#ocr-fat').inputValue(),'5.3');await p.locator('#capture-value-choice').selectOption('catalogue');await p.locator('#ocr-package-confirmed').check();assert(await p.locator('[data-capture-source="ocr"][data-capture-action="save"]').isEnabled());r.emptyOcrBaseline=true;
 await p.locator('#capture-new-active').click();assert(!(await p.locator('#ocr-review').isVisible()));assert.match(await p.locator('#scan-mode-copy').innerText(),/New capture/);await snap('04-new-capture');
 await p.locator('#capture-manual').click();await p.locator('#ocr-food-name').fill('Disposable');await p.locator('#capture-cancel').click();await p.locator('#home.active').waitFor();await p.evaluate(()=>openAlpha05Feature('scan-centre'));assert.equal(await p.locator('#ocr-food-name').inputValue(),'');r.cancel=true;
 // Legacy online wrapper, already saved: bounded explicit review replaces only
 // its saved reference, preserving evidence and unrelated records.
 const legacy={...f.food,id:'synthetic-legacy-online',barcode:'9900000000110'};
 await p.evaluate(old=>{const st=JSON.parse(localStorage.getItem(HEC_APP.functionalStorageKey));st.onlineFoods.push(old);st.savedFoodIds.push(old.id);localStorage.setItem(HEC_APP.functionalStorageKey,JSON.stringify(st));},legacy);await p.reload();await p.waitForFunction(()=>HECRelease.snapshot().state==='ready');await p.evaluate(()=>openAlpha05Feature('food-library'));await p.locator('[data-library-tab="saved"]').click();await p.locator('[data-food-details="'+legacy.id+'"]').click();await p.locator('[data-review-product-nutrition="'+legacy.id+'"]').click();await p.locator('#capture-value-choice').selectOption('catalogue');await p.locator('#ocr-package-confirmed').check();await p.locator('[data-capture-source="ocr"][data-capture-action="save"]').click();st=await state();const repaired=st.customFoods.find(x=>x.barcode===legacy.barcode);assert(repaired);assert(!st.savedFoodIds.includes(legacy.id));assert(st.onlineFoods.some(x=>x.id===legacy.id));await p.reload();await p.waitForFunction(()=>HECRelease.snapshot().state==='ready');await p.evaluate(()=>openAlpha05Feature('food-library'));await p.locator('[data-library-tab="saved"]').click();await p.locator('#food-results [data-food-save="'+repaired.id+'"]').locator('..').locator('.resource-main').click();assert.equal(await diary(repaired.id),5);r.legacyRepair=true;
 qa.requireEvidence(r.diagnostic);r.pass=true;
}catch(e){r.error={message:e.message,stack:e.stack};if(p)await p.screenshot({path:path.join(output,'failure.png'),fullPage:true});throw e;}finally{await browser.close();fs.writeFileSync(path.join(output,'flows.json'),JSON.stringify(r,null,2));}console.log(JSON.stringify({pass:r.pass,steps:r.steps,flows:{directBoth:r.directBoth,saveOnly:r.saveOnly,reopenDiary:r.reopenDiary,barcodeChoice:r.barcodeChoice,physicalChoice:r.physicalChoice,legacyRepair:r.legacyRepair}}));}
run().catch(e=>{console.error(e);process.exitCode=1;});
