#!/usr/bin/env node
'use strict';

const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const ROOT=path.resolve(__dirname,'..');
const modules=process.env.HEC_WORKSPACE_NODE_MODULES;
const qa=require('./audit_physical_form_measures_edge.js'),{chromium,edge:requiredEdge}=qa.browserTools(),playwright={chromium};
const routeReports=[];
async function localPage(browser,options){const diagnostic=qa.evidence(),context=await qa.contextFor(browser,options.viewport,diagnostic);routeReports.push(diagnostic);return context.newPage();}
function requireRouting(){for(const diagnostic of routeReports)qa.requireEvidence(diagnostic);}
const edgeCandidates=['C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe','C:/Program Files/Microsoft/Edge/Application/msedge.exe'];
const executablePath=edgeCandidates.find(fs.existsSync);
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.ico':'image/x-icon','.webmanifest':'application/manifest+json'};

async function activeAudit(page,label){await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));return page.evaluate(label=>{const visible=[...document.querySelectorAll('.guided-resolution-card,.off-catalogue-results,.universal-search-submitted')].filter(node=>{const r=node.getBoundingClientRect();return r.width>0&&r.height>0&&getComputedStyle(node).display!=='none';}),card=visible.find(node=>node.matches('.guided-resolution-card:not(.guided-resolution-compact)'))||visible[0],controls=card?[...card.querySelectorAll('button,input')]:[],rects=controls.map(node=>({label:(node.textContent||node.placeholder||node.getAttribute('aria-label')||'').trim(),rect:node.getBoundingClientRect().toJSON(),height:node.getBoundingClientRect().height})),overlaps=[];for(let i=0;i<rects.length;i++)for(let j=i+1;j<rects.length;j++){const a=rects[i].rect,b=rects[j].rect,area=Math.max(0,Math.min(a.right,b.right)-Math.max(a.left,b.left))*Math.max(0,Math.min(a.bottom,b.bottom)-Math.max(a.top,b.top));if(area>.5)overlaps.push([rects[i].label,rects[j].label]);}const cardRect=card?.getBoundingClientRect(),viewportHeight=visualViewport?.height||innerHeight,visibleHeight=cardRect?Math.max(0,Math.min(cardRect.bottom,viewportHeight)-Math.max(cardRect.top,0)):0,amount=card?.querySelector('[data-gpr-amount]'),search=document.querySelector('#food-search');return {label,viewport:{width:innerWidth,height:innerHeight,visualWidth:visualViewport?.width||innerWidth,visualHeight:viewportHeight},cards:visible.length,catalogueResults:!!card?.matches('.off-catalogue-results,.universal-search-submitted'),stage:window.HEC_GUIDED_PRODUCT_TEST?.ui?.().stage||'',state:window.HEC_GUIDED_PRODUCT_TEST?.ui?.().state||'',product:window.HEC_GUIDED_PRODUCT_TEST?.ui?.().product||'',bodyOverflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,cardOverflow:card?card.scrollWidth>card.clientWidth:false,visibleRatio:cardRect?.height?Number((visibleHeight/cardRect.height).toFixed(2)):0,amountFocused:document.activeElement===amount,searchFocused:document.activeElement===search,searchCaret:document.activeElement===search?search.selectionStart:null,shortControls:rects.filter(item=>item.height<44&&item.height>0),overlaps,answerSummary:card?.querySelectorAll('.guided-resolution-answer-summary span').length||0,text:card?.innerText||'',surfaceText:document.querySelector('#food-results')?.innerText||document.querySelector('#food-live-results')?.innerText||''};},label);}
async function finalReviewAudit(page,label){return page.evaluate(label=>{const editor=document.querySelector('#food-entry-editor'),visible=!!editor?.classList.contains('active'),controls=[...editor.querySelectorAll('button,input,select')].filter(node=>{const r=node.getBoundingClientRect();return r.width>0&&r.height>0;}),footer=editor.querySelector('.quick-action-row:has(#save-food-entry)'),f=footer.getBoundingClientRect(),paddingBottom=parseFloat(getComputedStyle(editor.querySelector('.page')).paddingBottom)||0;return {label,finalReview:true,reviewVisible:visible,cards:0,bodyOverflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,cardOverflow:editor.scrollWidth>editor.clientWidth,visibleRatio:1,amountFocused:document.activeElement===document.querySelector('#entry-amount'),searchFocused:false,searchCaret:null,shortControls:controls.filter(node=>node.getBoundingClientRect().height<44).map(node=>({label:node.id,height:node.getBoundingClientRect().height})),overlaps:[],answerSummary:0,text:editor.innerText,footer:{left:f.left,right:f.right,bottom:f.bottom,height:f.height,paddingBottom,viewportWidth:innerWidth,viewportHeight:innerHeight}};},label);}
async function openLibrary(page){await page.goto(page.url().replace(/[^/]+$/,'index.html'),{waitUntil:'networkidle'});await page.waitForFunction(()=>window.HEC_GUIDED_PRODUCT_TEST&&typeof window.openAlpha05Feature==='function');await page.evaluate(()=>window.openAlpha05Feature('food-library',{freshSearch:true}));await page.locator('#food-search').waitFor({state:'visible'});}
async function search(page,value){const input=page.locator('#food-search');await input.fill(value);await input.focus();await input.dispatchEvent('input');await page.waitForTimeout(450);}
async function click(page,label){const deadline=Date.now()+10000;while(Date.now()<deadline){const controls=page.locator('.guided-resolution-card button:visible');for(let index=0;index<await controls.count();index++){const control=controls.nth(index),text=(await control.innerText()).trim().replace(/\s*›$/,'').trim();if(text===label){await control.click();await page.waitForTimeout(80);return;}}await page.waitForTimeout(50);}throw new Error(`${label} unavailable: ${JSON.stringify(await activeAudit(page,'missing control'))}`);}
async function margarineFlow(page,shots,prefix){await search(page,'margarine');const reports=[await activeAudit(page,'generic margarine recognition preview')];await click(page,'Resolve This Food');if(await page.locator('[data-fc-base]').count())await page.locator('[data-fc-base]').click();reports.push(await activeAudit(page,'generic margarine identity'));await click(page,'Monounsaturated');reports.push(await activeAudit(page,'generic margarine auto advance'));await click(page,'Reduced fat');await click(page,'Regular salt');reports.push(await activeAudit(page,'generic margarine portion'));await click(page,'Teaspoon (5 g)');let amount=page.locator('#food-results [data-gpr-amount]');await amount.focus();reports.push(await activeAudit(page,'generic margarine amount focus'));await amount.fill('0.5');await click(page,'← Back');reports.push(await activeAudit(page,'generic margarine Back'));await click(page,'Teaspoon (5 g)');amount=page.locator('#food-results [data-gpr-amount]');await amount.fill('0.5');await click(page,'Continue');await page.locator('#food-entry-editor.active').waitFor({state:'visible'});reports.push(await finalReviewAudit(page,'generic margarine one final Review'));await page.screenshot({path:path.join(shots,`${prefix}-margarine-review.png`),fullPage:true});const finalAmount=page.locator('#entry-amount');await finalAmount.fill('0.75');await finalAmount.focus();reports.push(await finalReviewAudit(page,'generic margarine final edit amount focus'));return reports;}
async function shortcut(page,query,expected,{chooseSubmitted=false}={}){await openLibrary(page);await search(page,query);await page.waitForTimeout(1300);const resolver=page.locator('[data-ps33-commit-family]:visible');if(await resolver.count())await resolver.click();else{await page.locator('#submit-food-search:visible').click();await page.waitForTimeout(120);const submitted=page.locator('[data-universal-result]:visible');if(chooseSubmitted&&await submitted.count())await submitted.first().click();}if(await page.locator('[data-fc-base]').count())await page.locator('[data-fc-base]').click();let report=await activeAudit(page,query),hasExpected=()=>!expected||`${report.text}\n${report.surfaceText}`.toLowerCase().includes(expected.toLowerCase());const catalogueProducts=page.locator('[data-gpr-catalogue-product]:visible');if(!hasExpected()&&await catalogueProducts.count()){await catalogueProducts.first().click();report=await activeAudit(page,query);}if(!hasExpected())throw new Error(`${query}: expected ${expected}; visible text=${JSON.stringify((report.text||report.surfaceText).slice(0,900))}`);return report;}

async function run(){const shots=path.join(os.tmpdir(),'hec-progressive-responsive-qa');fs.mkdirSync(shots,{recursive:true});const browser=await chromium.launch({headless:true,...(executablePath?{executablePath}: {})}),reports=[],errors=[],isolatedExternal=[];try{for(const viewport of [{width:390,height:844},{width:390,height:520},{width:430,height:932}]){const page=await localPage(browser,{viewport});page.on('pageerror',error=>errors.push(`${viewport.width}x${viewport.height}: ${error.message}`));page.on('console',message=>{if(message.type()==='error'&&!/^Failed to load resource: net::ERR_BLOCKED_BY_CLIENT/.test(message.text()))errors.push(`${viewport.width}x${viewport.height}: console: ${message.text()}`);});await page.goto(qa.ORIGIN+'/index.html',{waitUntil:'networkidle'});await page.waitForFunction(()=>window.HEC_GUIDED_PRODUCT_TEST&&typeof window.openAlpha05Feature==='function');await page.evaluate(()=>window.openAlpha05Feature('food-library',{freshSearch:true}));reports.push(...await margarineFlow(page,shots,`${viewport.width}x${viewport.height}`));await page.close();}
    const page=await localPage(browser,{viewport:{width:390,height:844}});page.on('pageerror',error=>errors.push(`scenario: ${error.message}`));page.on('console',message=>{if(message.type()==='error'&&!/^Failed to load resource: net::ERR_BLOCKED_BY_CLIENT/.test(message.text()))errors.push(`scenario console: ${message.text()}${message.location().url?` · ${message.location().url}`:''}`);});page.on('requestfailed',request=>{if(!/ERR_BLOCKED_BY_CLIENT/.test(request.failure()?.errorText||''))errors.push(`scenario request: ${request.url()} · ${request.failure()?.errorText||'failed'}`);});await page.goto(qa.ORIGIN+'/index.html',{waitUntil:'networkidle'});reports.push(await shortcut(page,'Flora','Which exact product?'));reports.push(await shortcut(page,'Meadow Lea','Meadowlea Original Canola Butter'));reports.push(await shortcut(page,'milk','What type of milk?'));reports.push(await shortcut(page,'bread','Home Made or Commercial?'));reports.push(await shortcut(page,'Bega Almond Spread Crunchy','How are you measuring it?',{chooseSubmitted:true}));await page.screenshot({path:path.join(shots,'390x844-shortcut.png'),fullPage:true});await page.close();
  }finally{await browser.close();requireRouting();}
  const failures=reports.filter(item=>item.bodyOverflow||item.cardOverflow||item.shortControls.length||item.overlaps.length||(/amount focus/.test(item.label)&&!item.amountFocused)||(/question$/.test(item.label)&&(!item.searchFocused||item.searchCaret===null))||(item.finalReview?(!item.reviewVisible||item.footer.left<0||item.footer.right>item.footer.viewportWidth+.6||item.footer.bottom>item.footer.viewportHeight+.6||item.footer.paddingBottom<item.footer.height):(item.cards!==1||(!item.catalogueResults&&item.visibleRatio<.5))));const result={viewports:['390x844','390x520','430x932'],scenarios:reports.length,failures,errors,routing:routeReports,network:{liveExternalFallthrough:0,isolatedExternalRequests:isolatedExternal.length},screenshots:shots,reports};process.stdout.write(`${JSON.stringify(result,null,2)}\n`);if(failures.length||errors.length)process.exitCode=1;
}
if(require.main===module)run().catch(error=>{console.error(error);process.exit(1);});
module.exports={run};
