'use strict';
// Read-only audit of raw snapshots, derived products and the shared contract.
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const C=require('../food-catalogue'),S=require('../serving-foundation'),G=require('../guided-product-resolution'),off=require('./audit_open_food_facts_au'),sources=require('../food-sources');
require('../mcdonalds-au-catalogue');require('../kfc-au-catalogue');const supplemental=require('../australian-catalogue-data');C.registerBrandDirectory(supplemental.brands);
const hash=value=>crypto.createHash('sha256').update(typeof value==='string'?value:JSON.stringify(value)).digest('hex');
const sampled=(rows,count)=>[...rows].sort((a,b)=>hash(a.id||a.name).localeCompare(hash(b.id||b.name))).slice(0,count);
const increment=(counts,key)=>counts[key]=(counts[key]||0)+1;
async function run({quick=false,output=path.join(os.tmpdir(),'hec-australian-catalogue-audit.json')}={}){
  const manifest=off.read('manifest.json'),raw=off.allProducts(manifest),before=hash(raw),input=require('../data/australian-catalogue/supplemental.json'),derived=require('../data/australian-catalogue/build-report.json'),runtime=fs.readFileSync(path.join(__dirname,'../alpha06.js'),'utf8'),critical=[];
  const selected=quick?sampled(raw,500):raw,foods=selected.map(off.api.toFood),sourceFoods=sources.foodRecords(),newFoods=supplemental.packagedProducts,all=[...foods,...sourceFoods,...newFoods],canonical=C.canonicaliseRecords(all),counts={sources:{},verification:{},addability:{},forms:{},trust:{},current:{},gtins:0,sourceConflicts:0,unresolvedConflicts:0,foreignFacing:0,knownSolidLiquidExposure:0},brands=new Set(),families=new Set();
  const lookup=new Map(all.map(food=>[food.id,food])),duplicates=[],clusters=new Map(),eligibility=new Map();
  for(const food of canonical){
    const e=C.productEligibility(food),form=S.physicalForm(food).form;eligibility.set(food.id,e);increment(counts.sources,food.foodSourceId||food.sourceCatalogueId||C.recordType(food));increment(counts.verification,e.verificationStatus);increment(counts.addability,e.addability.status);increment(counts.forms,form);increment(counts.trust,e.source.trustClass);increment(counts.current,food.currentState||'unknown');if(food.barcode)counts.gtins++;if(food.brand)brands.add(C.brandKey(food.brand));families.add(C.brandKey(food.brand)+'|'+(food.productFamily||C.canonicalName(food)));if(e.conflicts.length)counts.sourceConflicts++;
    if(e.conflicts.some(item=>item.severity==='material'&&(!item.resolution||item.resolution==='unresolved'))){counts.unresolvedConflicts++;if(e.addability.normalLoggingAllowed)critical.push({id:food.id,code:'unresolved-conflict-loggable'});}
    if(e.candidate&&e.verified||C.recordType(food)==='external-catalogue'&&C.provenance(food).verified)critical.push({id:food.id,code:'candidate-falsely-verified'});
    if(e.previewEligible!==e.searchEligible)critical.push({id:food.id,code:'preview-search-eligibility-mismatch'});
    if(food.legacyPreviewOnly&&(e.previewEligible||e.searchEligible||e.addability.normalLoggingAllowed))critical.push({id:food.id,code:'legacy-identity-promoted'});
    if(!['liquid','spread','unknown'].includes(form)){const profile=S.servingMeasureProfile(food);if(profile.measures.some(item=>['mL','L','cup'].includes(item.key))){counts.knownSolidLiquidExposure++;critical.push({id:food.id,code:'solid-exposes-liquid'});}}
    if(C.sourceQuality(food).foreignFacing)counts.foreignFacing++;
    const key=C.brandKey(food.brand)+'|'+C.canonicalName(food),cluster=clusters.get(key)||[];cluster.push(food);clusters.set(key,cluster);
    if(food.mergedRecordIds?.length>1){const evidence=food.mergedRecordIds.map(id=>lookup.get(id)).filter(Boolean),gtins=new Set(evidence.map(item=>item.barcode).filter(Boolean));if(gtins.size>1)critical.push({id:food.id,code:'distinct-gtins-merged',gtins:[...gtins]});duplicates.push({id:food.id,merged:food.mergedRecordIds,conflicts:e.conflicts.map(item=>({code:item.code,resolution:item.resolution}))});}
  }
  const unresolved=[...clusters.entries()].filter(([,rows])=>rows.length>1).map(([key,rows])=>({id:key,products:rows.map(food=>({id:food.id,gtin:food.barcode,pack:food.packageSize||food.quantity||food.pack||null})),pairs:rows.slice(0,10).flatMap((food,index)=>rows.slice(index+1,10).map(other=>({a:food.id,b:other.id,evidence:C.strongDuplicateEvidence(food,other)})))}));
  const brandNames=['McCain','Meadow Lea','Flora','Tip Top','Norco',...sampled(supplemental.brands.filter(brand=>brand.count>=3&&brand.count<=30),15).map(brand=>brand.name)],brandAudit=[];
  for(const query of brandNames){const result=await off.api.search(query,{limit:500}),records=[...newFoods,...result.foods],model=C.brandResultModel(records,query);if(!model){critical.push({query,code:'indexed-brand-not-recognised'});continue;}const items=model.groups.flatMap(group=>group.items),bad=items.filter(item=>!C.consumerBrandMembership(model.intent.entity,item.food).matches);if(bad.length)critical.push({query,code:'brand-contamination'});if(items.some(item=>item.addability.normalLoggingAllowed)&&!items[0].addability.normalLoggingAllowed)critical.push({query,code:'weak-brand-first'});brandAudit.push({query,indexTotal:result.total,canonicalLoaded:model.loaded,first:items.slice(0,5).map(item=>({id:item.id,name:item.name,status:item.addability.status,verified:item.provenance.verified}))});}
  const chosen=sampled(canonical.filter(food=>eligibility.get(food.id).addability.normalLoggingAllowed&&C.exactProductQuality(food).exactEligible),40),consistency=[];
  for(const food of chosen){const query=[food.brand,food.name].filter(Boolean).join(' '),model=C.submittedResultModel([food],query),item=model.groups.flatMap(group=>group.items).find(item=>item.id===C.canonicalKey(food)),e=eligibility.get(food.id),guided=G.createSession([food],query,{intent:{kind:'exact-product'}});if(!item||item.addability.status!==e.addability.status||guided.addability?.status!==e.addability.status)critical.push({id:food.id,query,code:'selection-contract-mismatch',preview:e.addability.status,search:item?.addability.status,guided:guided.addability?.status});consistency.push({id:food.id,query,canonicalId:e.canonicalId,status:e.addability.status,restaurantEligible:e.restaurantEligible});}
  const stalePatterns=['ALPHA0618_CHAIN_MENUS','function alpha0618ChainItem','data-alpha0618-chain-item'],stale=stalePatterns.filter(pattern=>runtime.includes(pattern));if(stale.length)critical.push({code:'stale-preview-registry',patterns:stale});
  assert.equal(hash(raw),before);assert.equal(raw.length,73300);assert.equal(manifest.sourceSha256.toUpperCase(),'F72687EE8BC6522054FE69DBFDA6B91902C16AF1EC2E043CDE27BC6C29AD8176');
  const report={pass:critical.length===0,quick,protectedRaw:{off:{records:raw.length,searchable:manifest.searchableProducts,brands:manifest.uniqueBrands,gtins:manifest.validGtins,sourceHash:manifest.sourceSha256,normalisedHash:before},restaurants:Object.fromEntries(['mcdonalds-au','kfc-au'].map(id=>[id,{canonical:sourceFoods.filter(food=>food.foodSourceId===id).length}]))},supplemental:{...derived,retrievalDates:[...new Set(input.records.map(row=>row.provenance.retrievedAt.slice(0,10)))],families:[...new Set(input.records.map(row=>row.sourceId+'|'+(row.family||row.category)))],sourceTypes:Object.fromEntries(input.sources.map(source=>[source.id,source.sourceType]))},audited:{rawInputs:all.length,canonical:canonical.length,brands:brands.size,families:families.size,duplicatesMerged:all.length-canonical.length,...counts},deduplication:{mergedClusters:duplicates.length,unresolvedClusters:unresolved.length,sampledMerged:sampled(duplicates,50),sampledUnresolved:sampled(unresolved,50)},brandAudit,consistency,stalePreviewIdentities:stale,criticalViolations:critical};
  fs.writeFileSync(output,JSON.stringify(report,null,2));return report;
}
if(require.main===module)run({quick:process.argv.includes('--quick'),...(process.argv[2]&&!process.argv[2].startsWith('--')?{output:process.argv[2]}:{})}).then(report=>{console.log(JSON.stringify({...report,brandAudit:report.brandAudit.map(row=>({query:row.query,count:row.canonicalLoaded})),consistency:{samples:report.consistency.length},deduplication:{mergedClusters:report.deduplication.mergedClusters,unresolvedClusters:report.deduplication.unresolvedClusters}},null,2));if(!report.pass)process.exitCode=1;}).catch(error=>{console.error(error);process.exitCode=1;});
module.exports={run};
