#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'),base=require('./audit_open_food_facts_au.js'),packaged=require('../packaged-foods.js'),serving=require('../serving-foundation.js'),guided=require('../guided-product-resolution.js');
const manifest=base.read('manifest.json'),products=base.allProducts(manifest),DATA=base.DATA;
const nutrientValues=record=>({calories:record.nutrients?.calories,energyKj:record.nutrients?.energyKj,protein:record.nutrients?.protein,carbs:record.nutrients?.carbs,fat:record.nutrients?.fat,fibre:record.nutrients?.fibre});
async function genericAudit(count=50){const entries=[];for(const shard of manifest.intelligenceShards||[]){const data=base.read(shard.path);for(const [key,value] of Object.entries(data.concepts||{}))if(value.refs.length>=20)entries.push({key,count:value.refs.length});}entries.sort((a,b)=>a.key.localeCompare(b.key));const sample=base.sampleEvenly(entries,count);let correct=0;const failures=[];for(const concept of sample){const result=await base.api.search(concept.key,{limit:10}),pass=result.intent.kind==='generic-category'&&result.foods.length>0&&result.foods.every(food=>food.searchGroup==='primary');if(pass)correct++;else failures.push({concept:concept.key,intent:result.intent.kind,total:result.total,primary:result.groups.primary});}return {sampled:sample.length,correct,accuracyPercent:+(correct*100/sample.length).toFixed(2),failures};}
function nutritionAudit(){const eligible=products.filter(product=>product.nutritionCompleteness!=='identity-only'),counts={usable:0,partial:0,suspect:0,'identity-only':0,energyPairConflict:0,macroEnergySuspect:0,missingRequired:0};for(const product of eligible){const result=packaged.nutritionIntegrity(nutrientValues(product));counts[result.status]++;if(result.energy.status==='conflict')counts.energyPairConflict++;if(result.macro.status==='suspect')counts.macroEnergySuspect++;if(result.missing.length)counts.missingRequired++;}return {audited:eligible.length,...counts,downgraded:counts.partial+counts.suspect+counts['identity-only']};}
function energyAudit(count=1000){const eligible=products.filter(product=>product.nutrients?.calories!=null||product.nutrients?.energyKj!=null),sample=base.sampleEvenly(eligible,count);let mismatches=0,sourceConflicts=0;for(const product of sample){const result=packaged.scaleNormalised(nutrientValues(product),.37);if(result.integrity.status==='conflict')sourceConflicts++;const kcal=result.nutrients.calories,kj=result.nutrients.energyKj;if(kcal!=null&&kj!=null&&Math.abs(kcal*4.184-kj)/Math.max(Math.abs(kj),20)>.01)mismatches++;}return {sampled:sample.length,displayMismatches:mismatches,sourceConflicts};}
function servingAudit(){const seen=new Set(),rows=[];for(const record of products){const food=base.api.toFood(record),profile=guided.servingProfile(food),form=profile?.physicalForm||serving.physicalForm(food).form;if(!profile?.measures?.length)continue;const group=form==='liquid'?(profile.measures.some(item=>item.key==='serve')?'liquid-beverage':'volume-only'):form;if(seen.has(group))continue;const measure=profile.measures[0],session=guided.createSession([food],food.name,{intent:{kind:'exact-product'}});guided.selectMeasure(session,measure.key);guided.selectAmount(session,1.25);rows.push({form:group,id:food.id,name:food.name,measures:profile.measures.map(item=>item.key),amount:session.amount,scaled:!!session.nutrition});seen.add(group);if(seen.size>=7)break;}return {sampled:rows.length,forms:[...seen],rows};}
async function realProbes(){const out={};for(const query of ['Flora','Meadow Lea','MeadowLea','Milk','Pauls',"Paul's",'Trim Milk','Pauls Trim Milk']){const result=await base.api.search(query,{limit:10});out[query]={intent:result.intent.kind,total:result.total,primary:result.groups.primary,examples:result.foods.slice(0,5).map(food=>`${food.brand} — ${food.name}`),facets:(result.facets||[]).slice(0,5)};}return out;}
function brandEntries(min,max){const entries=[];for(const shard of manifest.brandShards){for(const [key,value] of Object.entries(base.read(shard.path).brands)){if(value.refs.length>=min&&value.refs.length<=max)entries.push({key,...value});}}return entries.sort((a,b)=>a.key.localeCompare(b.key));}
async function brandUxAudit({minimum,maximum,count,label}){
  const sample=base.sampleEvenly(brandEntries(minimum,maximum),count),modes={'direct-products':0,'useful-facet':0,'paginated-products':0,'identity-completion':0,'exact-product':0,none:0},rejectionReasons={},acceptedFacets={},examples=[],failures=[];let weakExactPrevented=0,accessible=0;
  for(const brand of sample){
    const result=await base.api.search(brand.name,{limit:500}),session=guided.createSession(result.foods,brand.name,{intent:result.intent}),mode=guided.presentationForSession(session);modes[mode]=(modes[mode]||0)+1;
    if(result.total===brand.refs.length&&result.foods.length===brand.refs.length)accessible++;
    else failures.push({brand:brand.name,expected:brand.refs.length,total:result.total,loaded:result.foods.length,reason:'brand-members-not-all-accessible'});
    weakExactPrevented+=session.allCandidates.filter(food=>!require('../food-catalogue.js').exactProductQuality(food,{candidates:session.allCandidates}).exactEligible).length;
    if(mode==='useful-facet'){const quality=session.nextQuestion?.facetQuality;if(!quality?.accepted)failures.push({brand:brand.name,reason:'unqualified-facet-rendered'});else acceptedFacets[quality.key]=(acceptedFacets[quality.key]||0)+1;}
    for(const key of guided.dimensions){const quality=guided.facetQuality(key,session.candidates,session.knownAttributes);if(!quality.accepted)for(const reason of quality.reasons)rejectionReasons[reason]=(rejectionReasons[reason]||0)+1;}
    if(examples.length<8)examples.push({brand:brand.name,products:brand.refs.length,mode,question:session.nextQuestion?.key||'',options:session.nextQuestion?.options?.length||0});
  }
  return {label,band:`${minimum}-${maximum}`,sampled:sample.length,accessible,directPercent:sample.length?+(modes['direct-products']*100/sample.length).toFixed(2):0,modes,acceptedFacets,rejectionReasons,weakExactPrevented,examples,failures:failures.slice(0,20)};
}
async function run(){const [retrieval,brands,generics,performance,probes,smallBrands,mediumBrands,largeBrands]=await Promise.all([base.retrievalAudit(products,1000),base.brandAudit(manifest,100),genericAudit(50),base.performanceAudit(products,500),realProbes(),brandUxAudit({minimum:2,maximum:10,count:100,label:'small'}),brandUxAudit({minimum:11,maximum:50,count:50,label:'medium'}),brandUxAudit({minimum:51,maximum:500,count:20,label:'large'})]),nutrition=nutritionAudit(),energy=energyAudit(1000),servings=servingAudit(),runtime=fs.readFileSync(path.join(base.ROOT,'alpha06.js'),'utf8'),sampleFood=base.api.toFood(products.find(product=>product.name)),barcodeShell={name:'Barcode 9354237000328',barcode:'9354237000328',recordType:'external-catalogue',market:'AU'},brandShell={name:'Example',brand:'Example',recordType:'external-catalogue',market:'AU'},localState=require('../food-catalogue.js').newFederatedSearchState(),architecture={
  catalogueIntact:manifest.importedProducts===73300,
  onlineCannotReorderLocal:/all-resources-online/.test(runtime)&&/renderAllResourcesOnlineAppendOnly/.test(runtime),
  staleAsyncIgnored:/psSearchRevisionCurrent/.test(runtime)&&/token!==psLargeSearchToken/.test(runtime),
  fixedQueryDeterministic:require('../food-catalogue.js').beginQueryRevision(localState,'same query')===require('../food-catalogue.js').beginQueryRevision(localState,'same query'),
  smallBrandsDirect:smallBrands.modes['useful-facet']===0&&smallBrands.modes['paginated-products']===0,
  facetsQualityGated:/facetQuality\(key,candidates/.test(fs.readFileSync(path.join(base.ROOT,'guided-product-resolution.js'),'utf8')),
  barcodeCannotBeExact:require('../food-catalogue.js').exactProductQuality(barcodeShell,{candidates:[barcodeShell]}).exactEligible===false,
  brandFamilyCannotBeExact:require('../food-catalogue.js').exactProductQuality(brandShell,{candidates:[brandShell,sampleFood]}).exactEligible===false,
  exactPrecedesServing:guided.createSession([sampleFood],'product',{intent:{kind:'exact-product'}}).stage===guided.stages.MEASURE,
  servingPrecedesAmount:guided.createSession([sampleFood],'product',{intent:{kind:'exact-product'}}).amount===null,
  nutritionIntegrityPreserved:packaged.scale({calories:1},1).protein===null&&energy.displayMismatches===0,
  liquidProfilesPreserved:serving.physicalForm({physicalForm:'liquid'}).form==='liquid',
  keyboardSearchPreserved:/setSelectionRange\(caret,caret\)/.test(runtime)
  };return {catalogue:{snapshot:manifest.sourceSnapshotDate,sourceSha256:manifest.sourceSha256,products:manifest.importedProducts,brands:manifest.uniqueBrands,intelligenceFiles:manifest.searchIntelligence.files,intelligenceBytes:manifest.searchIntelligence.bytes,manifestBytes:fs.statSync(path.join(DATA,'manifest.json')).size},probes,retrieval,brands,generics,brandUx:{small:smallBrands,medium:mediumBrands,large:largeBrands},servings,energy,nutrition,performance,architecture,allArchitectureYes:Object.values(architecture).every(Boolean)};}
if(require.main===module)run().then(result=>{console.log(JSON.stringify(result,null,2));const ux=Object.values(result.brandUx);if(result.retrieval.top10Percent<98||result.brands.complete!==100||result.brands.contamination||result.generics.correct!==50||result.energy.displayMismatches||ux.some(item=>item.sampled<(item.label==='small'?100:item.label==='medium'?50:20)||item.accessible!==item.sampled||item.failures.length)||!result.allArchitectureYes)process.exitCode=1;}).catch(error=>{console.error(error);process.exit(1);});
module.exports={genericAudit,nutritionAudit,energyAudit,servingAudit,realProbes,brandEntries,brandUxAudit,run};
