#!/usr/bin/env node
"use strict";
const fs=require("fs"),path=require("path"),{performance}=require("perf_hooks");
const ROOT=path.resolve(__dirname,".."),DATA=path.join(ROOT,"data","open-food-facts-au");
global.fetch=async url=>{const file=path.resolve(ROOT,String(url).replace(/^\.\//,""));try{return{ok:true,status:200,json:async()=>JSON.parse(fs.readFileSync(file,"utf8"))};}catch{return{ok:false,status:404,json:async()=>({})};}};
const api=require(path.join(ROOT,"off-catalogue.js"));
const read=relative=>JSON.parse(fs.readFileSync(path.join(DATA,relative),"utf8"));
function allProducts(manifest=read("manifest.json")){return manifest.productShards.flatMap(item=>read(item.path).products);}
function sampleEvenly(values,count){const out=[];for(let i=0;i<Math.min(count,values.length);i++)out.push(values[Math.floor(i*values.length/Math.min(count,values.length))]);return out;}
async function queryReport(queries){const out={};for(const query of queries){const result=await api.search(query,{limit:5});out[query]={count:result.total,examples:result.foods.map(food=>`${food.brand} — ${food.name}`)};}return out;}
async function retrievalAudit(products,count=1000){const eligible=products.filter(x=>x.name&&x.brand),sample=sampleEvenly(eligible,count);let found=0,top10=0,textTop10=0,barcodeFallback=0;const failures=[];for(const product of sample){const query=`${product.brand} ${product.name}`,result=await api.search(query,{limit:10});const index=result.foods.findIndex(food=>food.id===product.id);if(index>=0){found++;top10++;textTop10++;continue;}const exact=await api.lookupBarcode(product.barcode);if(exact?.id===product.id){found++;top10++;barcodeFallback++;}else if(failures.length<20)failures.push({id:product.id,query,barcode:product.barcode});}return{sampled:sample.length,found,top10,textTop10,barcodeFallback,retrievalPercent:+(found*100/sample.length).toFixed(2),top10Percent:+(top10*100/sample.length).toFixed(2),textTop10Percent:+(textTop10*100/sample.length).toFixed(2),failures};}
async function brandAudit(manifest,count=100){const candidates=[];for(const shard of manifest.brandShards){for(const [key,value] of Object.entries(read(shard.path).brands))if(value.refs.length>=2&&value.refs.length<=500)candidates.push({key,...value});}candidates.sort((a,b)=>a.key.localeCompare(b.key));const sample=sampleEvenly(candidates,count);let complete=0,contamination=0;const failures=[];for(const brand of sample){const result=await api.search(brand.name,{limit:500});const ids=new Set(result.foods.map(food=>food.brandKey));if(result.total===brand.refs.length&&result.foods.length===brand.refs.length)complete++;else failures.push({brand:brand.name,expected:brand.refs.length,total:result.total,loaded:result.foods.length});for(const key of ids)if(key!==brand.key)contamination++;}return{sampled:sample.length,complete,contamination,failures:failures.slice(0,20)};}
async function performanceAudit(products,count=500){const sample=sampleEvenly(products.filter(x=>x.name),count),times=[];for(const product of sample){const start=performance.now();await api.search([product.brand,product.name].filter(Boolean).join(" "),{limit:10});times.push(performance.now()-start);}times.sort((a,b)=>a-b);return{queries:times.length,medianMs:+times[Math.floor(times.length*.5)].toFixed(3),p95Ms:+times[Math.floor(times.length*.95)].toFixed(3),worstMs:+times[times.length-1].toFixed(3)};}
async function runAudit(){const manifest=read("manifest.json"),products=allProducts(manifest),queries=await queryReport(["Flora","Meadow Lea","MeadowLea","Vegemite","Kellogg's","Arnott's","milk","cereal","peanut butter","dim sim","mini dim sim"]),retrieval=await retrievalAudit(products),brands=await brandAudit(manifest),performance=await performanceAudit(products);return{source:{snapshot:manifest.sourceSnapshotDate,sha256:manifest.sourceSha256,country:manifest.scope,global:manifest.globalRecordsScanned,australian:manifest.australianSourceRecords},size:{imported:manifest.importedProducts,searchable:manifest.searchableProducts,complete:manifest.completeNutrition,partial:manifest.partialNutrition,identityOnly:manifest.identityOnly,brands:manifest.uniqueBrands,validGtins:manifest.validGtins},queries,retrieval,brands,performance,files:{generatedMB:+(manifest.generatedBytes/1048576).toFixed(2),shards:manifest.generatedShardCount,largestMB:+(manifest.largestShardBytes/1048576).toFixed(3),manifestKB:+(fs.statSync(path.join(DATA,"manifest.json")).size/1024).toFixed(2)}};}
if(require.main===module)runAudit().then(value=>{console.log(JSON.stringify(value,null,2));if(value.retrieval.top10Percent<98||value.brands.complete!==value.brands.sampled||value.brands.contamination)process.exitCode=1;}).catch(error=>{console.error(error);process.exit(1);});
module.exports={ROOT,DATA,api,read,allProducts,sampleEvenly,queryReport,retrievalAudit,brandAudit,performanceAudit,runAudit};
