#!/usr/bin/env node
'use strict';

const fs=require('node:fs');
const http=require('node:http');
const os=require('node:os');
const path=require('node:path');
const ROOT=path.resolve(__dirname,'..');
const modules=process.env.HEC_WORKSPACE_NODE_MODULES;
const {chromium}=modules?require(path.join(modules,'playwright')):require('playwright');
const edgeCandidates=['C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe','C:/Program Files/Microsoft/Edge/Application/msedge.exe'];
const executablePath=edgeCandidates.find(fs.existsSync);
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.ico':'image/x-icon','.webmanifest':'application/manifest+json'};

function server(){return http.createServer((request,response)=>{const pathname=decodeURIComponent(new URL(request.url,'http://localhost').pathname);if(pathname==='/favicon.ico'){response.writeHead(204);response.end();return;}const relative=pathname==='/'?'index.html':pathname.replace(/^\/+/,''),file=path.resolve(ROOT,relative);if(!file.startsWith(ROOT)||!fs.existsSync(file)||fs.statSync(file).isDirectory()){response.writeHead(404);response.end('Not found');return;}response.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream','Cache-Control':'no-store'});fs.createReadStream(file).pipe(response);});}
async function activeAudit(page,label){return page.evaluate(label=>{const card=document.querySelector('#food-results .guided-resolution-card:not(.guided-resolution-compact)')||document.querySelector('.guided-resolution-card'),all=[...document.querySelectorAll('.guided-resolution-card')].filter(node=>{const style=getComputedStyle(node);return style.display!=='none'&&node.getBoundingClientRect().width>0;}),controls=card?[...card.querySelectorAll('button,input')]:[],rects=controls.map(node=>({label:(node.textContent||node.placeholder||node.getAttribute('aria-label')||'').trim(),rect:node.getBoundingClientRect().toJSON(),height:node.getBoundingClientRect().height})),overlaps=[];for(let i=0;i<rects.length;i++)for(let j=i+1;j<rects.length;j++){const a=rects[i].rect,b=rects[j].rect,area=Math.max(0,Math.min(a.right,b.right)-Math.max(a.left,b.left))*Math.max(0,Math.min(a.bottom,b.bottom)-Math.max(a.top,b.top));if(area>.5)overlaps.push([rects[i].label,rects[j].label]);}const cardRect=card?.getBoundingClientRect(),viewportHeight=visualViewport?.height||innerHeight,visibleHeight=cardRect?Math.max(0,Math.min(cardRect.bottom,viewportHeight)-Math.max(cardRect.top,0)):0,amount=card?.querySelector('[data-gpr-amount]'),search=document.querySelector('#food-search');return {label,viewport:{width:innerWidth,height:innerHeight,visualWidth:visualViewport?.width||innerWidth,visualHeight:viewportHeight},cards:all.length,stage:window.HEC_GUIDED_PRODUCT_TEST?.ui?.().stage||'',state:window.HEC_GUIDED_PRODUCT_TEST?.ui?.().state||'',product:window.HEC_GUIDED_PRODUCT_TEST?.ui?.().product||'',bodyOverflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,cardOverflow:card?card.scrollWidth>card.clientWidth:false,visibleRatio:cardRect?.height?Number((visibleHeight/cardRect.height).toFixed(2)):0,amountFocused:document.activeElement===amount,searchFocused:document.activeElement===search,searchCaret:document.activeElement===search?search.selectionStart:null,shortControls:rects.filter(item=>item.height<44&&item.height>0),overlaps,answerSummary:card?.querySelectorAll('.guided-resolution-answer-summary span').length||0,text:card?.innerText||''};},label);}
async function openLibrary(page){await page.goto(page.url().replace(/[^/]+$/,'index.html'),{waitUntil:'networkidle'});await page.waitForFunction(()=>window.HEC_GUIDED_PRODUCT_TEST&&typeof window.openAlpha05Feature==='function');await page.evaluate(()=>window.openAlpha05Feature('food-library',{freshSearch:true}));await page.locator('#food-search').waitFor({state:'visible'});}
async function search(page,value){const input=page.locator('#food-search');await input.fill(value);await input.focus();await input.dispatchEvent('input');await page.waitForTimeout(450);}
async function click(page,label){const deadline=Date.now()+10000;while(Date.now()<deadline){const controls=page.locator('.guided-resolution-card button:visible');for(let index=0;index<await controls.count();index++){const control=controls.nth(index),text=(await control.innerText()).trim().replace(/\s*›$/,'').trim();if(text===label){await control.click();await page.waitForTimeout(80);return;}}await page.waitForTimeout(50);}throw new Error(`${label} unavailable: ${JSON.stringify(await activeAudit(page,'missing control'))}`);}
async function margarineFlow(page,shots,prefix){await search(page,'margarine');const reports=[await activeAudit(page,'generic margarine question')];await click(page,'Monounsaturated');reports.push(await activeAudit(page,'generic margarine auto advance'));await click(page,'Reduced fat');await click(page,'Regular salt');reports.push(await activeAudit(page,'generic margarine portion'));await click(page,'Teaspoon (5 g)');const amount=page.locator('#food-results [data-gpr-amount]');await amount.focus();reports.push(await activeAudit(page,'generic margarine amount focus'));await amount.fill('0.5');await click(page,'Continue');reports.push(await activeAudit(page,'generic margarine review'));await page.screenshot({path:path.join(shots,`${prefix}-margarine-review.png`),fullPage:true});await click(page,'Change amount');await page.locator('#food-results [data-gpr-amount]').focus();reports.push(await activeAudit(page,'generic margarine edit amount focus'));await click(page,'← Back');reports.push(await activeAudit(page,'generic margarine Back'));return reports;}
async function shortcut(page,query,expected){await openLibrary(page);await search(page,query);const report=await activeAudit(page,query);if(expected&&!report.text.includes(expected))throw new Error(`${query}: expected ${expected}`);return report;}

async function run(){const app=server();await new Promise(resolve=>app.listen(0,'127.0.0.1',resolve));const port=app.address().port,shots=path.join(os.tmpdir(),'hec-progressive-responsive-qa');fs.mkdirSync(shots,{recursive:true});const browser=await chromium.launch({headless:true,...(executablePath?{executablePath}: {})}),reports=[],errors=[];try{for(const viewport of [{width:390,height:844},{width:390,height:520},{width:430,height:932}]){const page=await browser.newPage({viewport});page.on('pageerror',error=>errors.push(`${viewport.width}x${viewport.height}: ${error.message}`));page.on('console',message=>{if(message.type()==='error')errors.push(`${viewport.width}x${viewport.height}: console: ${message.text()}`);});await page.goto(`http://127.0.0.1:${port}/index.html`,{waitUntil:'networkidle'});await page.waitForFunction(()=>window.HEC_GUIDED_PRODUCT_TEST&&typeof window.openAlpha05Feature==='function');await page.evaluate(()=>window.openAlpha05Feature('food-library',{freshSearch:true}));reports.push(...await margarineFlow(page,shots,`${viewport.width}x${viewport.height}`));await page.close();}
    const page=await browser.newPage({viewport:{width:390,height:844}});page.on('pageerror',error=>errors.push(`scenario: ${error.message}`));page.on('console',message=>{if(message.type()==='error')errors.push(`scenario console: ${message.text()}`);});await page.goto(`http://127.0.0.1:${port}/index.html`,{waitUntil:'networkidle'});reports.push(await shortcut(page,'Flora','Which exact product?'));reports.push(await shortcut(page,'Meadow Lea','Which exact product?'));reports.push(await shortcut(page,'milk','What fat level?'));reports.push(await shortcut(page,'bread','What bread or grain type?'));reports.push(await shortcut(page,'Bega Almond Spread Crunchy','How are you measuring it?'));await page.screenshot({path:path.join(shots,'390x844-shortcut.png'),fullPage:true});await page.close();
  }finally{await browser.close();await new Promise(resolve=>app.close(resolve));}
  const failures=reports.filter(item=>item.bodyOverflow||item.cardOverflow||item.cards!==1||item.visibleRatio<.5||item.shortControls.length||item.overlaps.length||(/amount focus/.test(item.label)&&!item.amountFocused)||(/question$/.test(item.label)&&(!item.searchFocused||item.searchCaret===null)));const result={viewports:['390x844','390x520','430x932'],scenarios:reports.length,failures,errors,screenshots:shots,reports};process.stdout.write(`${JSON.stringify(result,null,2)}\n`);if(failures.length||errors.length)process.exitCode=1;
}
if(require.main===module)run().catch(error=>{console.error(error);process.exit(1);});
module.exports={run};
