'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const qa=require('./audit_physical_form_measures_edge'),t=require('./audit_brand_wave_edge'),{returningProfile}=require('./audit_navigation_startup_edge'),fixture=require('../tests/fixtures/product-capture');
const output=process.argv[2]||'data/product-capture-repair/cases';
async function run(){
 fs.mkdirSync(output,{recursive:true});const report={pass:false,diagnostic:qa.evidence(),cases:[]},{chromium,edge}=qa.browserTools(),browser=await chromium.launch({headless:true,executablePath:edge});let p;
 try{
  const c=await qa.contextFor({newContext:o=>browser.newContext({...o,isMobile:true,hasTouch:true})},{width:390,height:844},report.diagnostic);await c.addInitScript(returningProfile);
  await c.addInitScript(old=>{if(location.origin!=='https://mlwes-hec-test.github.io'||localStorage.getItem('synthetic-cases-seeded'))return;localStorage.setItem('healthyEatingCompanionTestAlpha06Functional',JSON.stringify({customFoods:[old],savedFoodIds:[old.id],onlineFoods:[],ui:{}}));localStorage.setItem('synthetic-cases-seeded','yes');},fixture.broken());
  await c.route('**/api/v2/product/**',route=>{const code=route.request().url().match(/product\/(\d+)/)[1];return route.fulfill({json:code.endsWith('4')?{status:0}:{status:1,product:{code,product_name:'Synthetic Vanilla Custard '+code.slice(-1),brands:'Synthetic Fixture',serving_size:'125 g',serving_quantity:125,serving_quantity_unit:'g',nutriments:{'energy-kj_100g':500,'energy-kj_serving':625,proteins_100g:4,proteins_serving:5,carbohydrates_100g:16,carbohydrates_serving:20,fat_100g:4,fat_serving:5,sugars_100g:12,sugars_serving:15,sodium_100g:.06,sodium_serving:.075}}}});});
  p=await c.newPage();await p.goto(qa.ORIGIN+'/');await p.waitForFunction(()=>HECRelease.snapshot().state==='ready');
  const state=()=>p.evaluate(()=>JSON.parse(localStorage.getItem(HEC_APP.functionalStorageKey)));
  const readText=async text=>{await p.locator('.ocr-raw-details').evaluate(n=>n.open=true);await p.locator('#ocr-text').fill(text);await p.locator('#capture-parse-text').click();};
  const confirmSave=async choice=>{if(await p.locator('#capture-value-choice').isVisible())await p.locator('#capture-value-choice').selectOption(choice);await p.locator('#ocr-package-confirmed').check();if(await p.locator('#ocr-discrepancy-confirm-row').isVisible())await p.locator('#ocr-discrepancy-confirmed').check();assert(await p.locator('[data-capture-source="ocr"][data-capture-action="save"]').isEnabled(),await p.locator('#ocr-review-status').innerText());await p.locator('[data-capture-source="ocr"][data-capture-action="save"]').click();await p.locator('#food-library.active').waitFor();};
  const scan=async code=>{await p.evaluate(()=>openAlpha05Feature('scan-centre'));await p.locator('[data-scan-mode="barcode"]').click();await p.locator('#manual-barcode-details').evaluate(n=>n.open=true);await p.locator('#scan-barcode-input').fill(code);await p.locator('#lookup-barcode').click();if(code.endsWith('4')){await p.locator('#capture-unknown-panel').click();await p.locator('#ocr-food-name').fill('Synthetic Unknown Custard');}else await p.locator('[data-compare-barcode-panel]').click();};
  for(const item of [{code:'9900000000002',choice:'panel',kind:'compatible',energy:625},{code:'9900000000003',choice:'panel',kind:'different',energy:800},{code:'9900000000003',choice:'catalogue',kind:'different',energy:625},{code:'9900000000004',choice:'panel',kind:'unknown',energy:625}]){
   await scan(item.code);const before=JSON.stringify((await state()).onlineFoods);await readText(item.kind==='different'?fixture.solidText.replace('625 kJ 500 kJ','800 kJ 640 kJ'):fixture.solidText);
   if(item.kind!=='unknown'){const text=await p.locator('#capture-comparison').innerText();assert.match(text,item.kind==='compatible'?/Match Closely/:/Differ From/);assert(!(await p.locator('[data-capture-source="ocr"][data-capture-action="save"]').isEnabled()));}
   await confirmSave(item.choice);let st=await state(),foods=st.customFoods.filter(f=>f.barcode===item.code);assert.equal(foods.length,1);assert(Math.abs(foods[0].nutrients.energyKj-item.energy)<.001);assert.equal(JSON.stringify(st.onlineFoods),before);assert.equal(foods[0].captureEvidence.choice,item.choice);
   report.cases.push({...item,id:foods[0].id,catalogueUnchanged:true,privateCount:foods.length});
   const row=p.locator('#food-results [data-food-save="'+foods[0].id+'"]').locator('..');await row.locator('.resource-main').click();await require('./capture_amount_test_helper')(p);await p.locator('#food-entry-editor.active').waitFor();await p.locator('#entry-meal').selectOption('Lunch');await p.locator('#entry-amount').fill('1');await p.locator('#save-food-entry').click();
   st=await state();assert(Object.values(st.diary).flat().some(e=>e.foodId===foods[0].id));
  }
  // Repair a saved old-style record through the visible, bounded review path.
  await p.evaluate(()=>openAlpha05Feature('food-library'));await p.locator('[data-library-tab="saved"]').click();
  await p.locator('#food-results [data-food-details="synthetic-old-private"]').click();await p.locator('[data-review-product-nutrition="synthetic-old-private"]').click();assert.equal(await p.locator('#ocr100-energy-kj').inputValue(),'500');await confirmSave('panel');
  const repaired=(await state()).customFoods.find(f=>f.id==='synthetic-old-private');assert.equal(repaired.loggable,true);assert.equal(repaired.nutrients.energyKj,500);assert.equal(repaired.recognisedOnly,false);report.legacyReview=true;

  for(const scenario of [{name:'Synthetic per-100 solid',basis:'per100',unit:'g',field:'ocr100-energy-kj',energy:'500'},{name:'Synthetic per-100 liquid drink',basis:'per100',unit:'mL',field:'ocr100-energy-kj',energy:'200'},{name:'Synthetic fixed serving',basis:'perServing',unit:'serve',field:'ocr-energy-kj',energy:'400'}]){
   await p.evaluate(()=>openAlpha05Feature('scan-centre'));await p.locator('[data-scan-mode="label"]').click();await p.locator('#capture-manual').click();await p.locator('#ocr-food-name').fill(scenario.name);await p.locator('#ocr-selected-basis').selectOption(scenario.basis);if(scenario.basis==='per100')await p.locator('#ocr-per100-unit').selectOption(scenario.unit);await p.locator('#'+scenario.field).fill(scenario.energy);await confirmSave('panel');
   const saved=(await state()).customFoods.find(f=>f.name===scenario.name);assert(saved);assert.equal(saved.waterMl,null);assert.equal(saved.ingredients,'');assert.deepEqual(saved.foodGroups,{});assert.equal(saved.nutrients.protein,null);
   await p.reload();await p.waitForFunction(()=>HECRelease.snapshot().state==='ready');await p.evaluate(()=>openAlpha05Feature('food-library'));await p.locator('[data-library-tab="saved"]').click();await p.locator('#food-results [data-food-save="'+saved.id+'"]').locator('..').locator('.resource-main').click();await require('./capture_amount_test_helper')(p);await p.locator('#food-entry-editor.active').waitFor();const offered=await p.locator('#entry-unit option').evaluateAll(ns=>ns.map(n=>n.value));assert(offered.includes(scenario.unit));if(await p.locator('#entry-unit').isVisible())await p.locator('#entry-unit').selectOption(scenario.unit);else assert.equal(await p.locator('#entry-unit').inputValue(),scenario.unit);if(scenario.unit==='serve')assert.deepEqual(await p.locator('#entry-unit option').evaluateAll(ns=>ns.map(n=>n.value)),['serve']);await p.locator('#entry-meal').selectOption('Lunch');await p.locator('#entry-amount').fill(scenario.unit==='serve'?'1':'100');await p.locator('#save-food-entry').click();const logged=Object.values((await state()).diary).flat().find(e=>e.foodId===saved.id);assert(logged);assert(Math.abs(logged.nutrients.calories-Number(scenario.energy)/4.184)<.01);assert.equal(logged.nutrients.protein,null);assert.deepEqual(logged.foodGroups,{});assert.equal(logged.waterMl,null);report.cases.push({...scenario,saveReopenDiary:true,optionalUnknown:true});
  }
  // A genuinely missing energy basis remains blocked with a targeted message.
  await p.evaluate(()=>openAlpha05Feature('scan-centre'));await p.locator('[data-scan-mode="label"]').click();await p.locator('#capture-manual').click();await p.locator('#ocr-food-name').fill('Synthetic incomplete');await p.locator('#ocr-selected-basis').selectOption('per100');await p.locator('#ocr-per100-unit').selectOption('g');await p.locator('#ocr100-protein').fill('5');await p.locator('#ocr-package-confirmed').check();assert(!(await p.locator('[data-capture-source="ocr"][data-capture-action="save"]').isEnabled()));assert.match(await p.locator('#ocr-review-status').innerText(),/energy for 100 g/);report.incompleteTargeted=true;await p.locator('#capture-cancel').click();
  // Required bounded search/Diary controls only; no retailer route campaign.
  for(const q of ['Bread','Milk','Hash Brown']){await t.fresh(p);assert.equal(await p.locator('#food-search').inputValue(),'');await t.submit(p,q);assert(await p.locator('[data-fc-base]').count());report.cases.push({query:q,conceptFirst:true});}
  await t.fresh(p);await t.submit(p,'Big Mac');const exact=await p.locator('[data-universal-result] strong').allInnerTexts();assert.equal(exact[0],'Big Mac');report.bigMac=true;
  const big=p.locator('[data-universal-result]').first();await big.click();if(await p.locator('[data-gpr-customisation="standard"]:visible').count())await p.locator('[data-gpr-customisation="standard"]:visible').click();const measure=p.locator('[data-gpr-measure]:visible');if(await measure.count())await measure.first().click();const qty=p.locator('[data-gpr-amount]:visible');await qty.fill('1');await qty.press('Enter');await require('./capture_amount_test_helper')(p);await p.locator('#food-entry-editor.active').waitFor();await p.locator('#entry-meal').selectOption('Lunch');await p.locator('#save-food-entry').click();report.centralFoodDiary=true;
  await t.fresh(p);await t.submit(p,'McCain Hash Browns');await p.waitForFunction(()=>[...document.querySelectorAll('[data-universal-result]')].some(n=>HEC_CANONICAL_CACHE_TEST.food(n.dataset.universalResult)?.barcode==='9310174025084'));
  const protectedId=await p.evaluate(()=>[...document.querySelectorAll('[data-universal-result]')].find(n=>HEC_CANONICAL_CACHE_TEST.food(n.dataset.universalResult)?.barcode==='9310174025084').dataset.universalResult);await p.locator('[data-universal-result="'+protectedId+'"]').first().click();const food=await p.evaluate(()=>HEC_GUIDED_PRODUCT_TEST.food());assert.equal(food.id,'woolworths-au:98299');if(await p.locator('[data-gpr-measure="g"]:visible').count())await p.locator('[data-gpr-measure="g"]:visible').click();await p.locator('[data-gpr-amount]:visible').fill('75');await p.locator('[data-gpr-amount]:visible').press('Enter');await require('./capture_amount_test_helper')(p);await p.locator('#food-entry-editor.active').waitFor();const preview=await p.locator('#entry-nutrition-preview').innerText();assert(preview.includes('130 Cal')&&preview.includes('543 kJ'));assert.equal(await p.locator('.screen.active').count(),1);report.mccain={id:food.id,barcode:food.barcode,amount:75,unit:'g',calories:130,kJ:543,oneReview:true};await p.screenshot({path:path.join(output,'mccain-review.png'),fullPage:true});
  await t.fresh(p);assert.equal(await p.locator('#food-search').inputValue(),'');report.newSearchBlank=true;
  qa.requireEvidence(report.diagnostic);report.pass=true;
 }catch(e){report.error={message:e.message,stack:e.stack};if(p)await p.screenshot({path:path.join(output,'failure.png'),fullPage:true});throw e;}finally{await browser.close();fs.writeFileSync(path.join(output,'cases.json'),JSON.stringify(report,null,2));}
 console.log(JSON.stringify({pass:report.pass,cases:report.cases,legacyReview:report.legacyReview,mccain:report.mccain}));
}
run().catch(e=>{console.error(e);process.exitCode=1;});

