'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const typing=require('./profile_search_typing');
const qa=require('./audit_physical_form_measures_edge'),F=require('../tests/fixtures/retailer-catalogue'),{returningProfile}=require('./audit_navigation_startup_edge');
async function submit(page,query){await page.locator('#food-search').fill(query);await page.locator('#submit-food-search').click();await page.waitForFunction(q=>HEC_SEARCH_SESSION_TEST.state().rawQuery===q&&HEC_SEARCH_SESSION_TEST.state().mode==='explicit-committed',query);}
async function settled(page){await page.waitForFunction(()=>!HEC_RETAILER_TEST.state()?.loading&&!HEC_FOOD_CONCEPT_TEST.state()?.loading&&!HEC_AU_CATALOGUE_TEST.brandState()?.loading&&document.querySelector('#food-results')?.textContent.trim()!=='Checking the Australian catalogue…');}
async function install(page,fixture){await page.evaluate(f=>{window.__retailerLoads=[];window.__retailerHeld=[];window.__retailerHold=false;HECRetailerCatalogue.registerCatalogue({...f,loadRecords:async ids=>{__retailerLoads.push(ids);if(__retailerHold)await new Promise(resolve=>__retailerHeld.push(resolve));return ids.map(id=>f.records.find(record=>record.id===id));}});},fixture);}
async function category(page,id){await page.locator(`[data-retailer-category="${id}"]`).click();await settled(page);}
async function commercialChoices(page,expected){
  // The controller renders eligible catalogue registration order, not alphabetical
  // order. Compare the complete provider list; future supported retailers remain
  // eligible without changing an exclusive two-retailer allowlist.
  const options=await page.evaluate(()=>HECRetailerCatalogue.commercialOptions('bread'));
  if(expected)assert.deepEqual(options,expected);
  assert.equal(new Set(options.map(option=>option.id)).size,options.length);
  for(const [id,label] of [['woolworths','Woolworths'],['coles','Coles']])assert.equal(options.find(option=>option.id===id)?.label,label);
  const rendered=await page.locator('[data-fc-answer="retailerIdentity"]').evaluateAll(nodes=>nodes.map(node=>({id:node.dataset.fcValue,label:node.querySelector('span').textContent})));
  assert.deepEqual(rendered,options.map(({id,label})=>({id,label})));
  assert.equal(await page.evaluate(()=>HEC_RETAILER_TEST.state()),null);
  for(const option of options){
    // Directory reads must not prime the hydration cache before UI selection.
    const directory=await page.evaluate(id=>HECRetailerCatalogue.directory(id,{scope:'commercial-identity',conceptId:'bread'}),option.id);
    assert.equal(directory.retailer.name,option.label);assert.equal(directory.total,option.count);assert(option.count>0);
  }
  return options;
}
async function switchCommercialChoices(page,options,fixture){
  for(const option of options){
    await page.locator(`[data-fc-answer="retailerIdentity"][data-fc-value="${option.id}"]`).click();await settled(page);
    const state=await page.evaluate(()=>HEC_RETAILER_TEST.state());
    assert.equal(state.retailerId,option.id);assert.equal(state.scope,'commercial-identity');assert.equal(state.ownerQuery,'Bread');assert.equal(state.error,'');assert.equal(state.result.retailer.id,option.id);assert.equal(state.result.retailer.name,option.label);assert.equal(state.result.conceptId,'bread');assert.equal(state.result.total,option.count);
    assert.equal(await page.locator('#food-search').inputValue(),'Bread');assert.equal(await page.locator('[data-retailer-scope="commercial-identity"]').count(),1);
    const ids=await page.locator('[data-universal-result]').evaluateAll(nodes=>nodes.map(node=>node.dataset.universalResult));
    assert.deepEqual(ids,state.result.foods.map(food=>food.id));assert.equal(new Set(ids).size,ids.length);
    assert(ids.length>0);assert(await page.evaluate(()=>{
      const state=HEC_RETAILER_TEST.state(),C=HECFoodCatalogue,entity=HECRetailerCatalogue.entity(state.retailerId);
      return state.result.foods.every(food=>C.commercialIdentityMembership(entity,food).matches&&(entity.collectionMode==='source-declared-brand'?C.privateLabelCollectionMembership(food,entity.id).length>0:C.retailerMembership(food,entity.id).length>0));
    }),option.id+' requires admissible private-label evidence after UI hydration');
    if(option.id===fixture.retailer.id)assert.deepEqual(ids,[fixture.house.id,fixture.privateLabel.id]);
    else assert(!ids.some(id=>fixture.records.some(food=>food.id===id)),'another retailer cannot inherit Woolworths fixture identities');
    await page.locator('[data-retailer-back]').click();await commercialChoices(page,options);
  }
  await page.locator(`[data-fc-answer="retailerIdentity"][data-fc-value="${fixture.retailer.id}"]`).click();await settled(page);
  assert.deepEqual(await page.locator('[data-universal-result]').evaluateAll(nodes=>nodes.map(node=>node.dataset.universalResult)),[fixture.house.id,fixture.privateLabel.id]);
}
function cachedFixtures(){const strong=F.food('synthetic-cache-strong',{barcode:'2000000000022',name:'Fixture Original Loaf Updated',verified:true,sourceProvenance:{...F.evidence('synthetic-cache-strong'),trustClass:'official-au-manufacturer'}}),weak={...strong,id:'synthetic-cache-weak',name:'Fixture Original Loaf',verified:false,sourceProvenance:F.evidence('synthetic-cache-weak')},a=F.food('synthetic-cache-conflict-a',{barcode:'2000000000039',name:'Fixture Cache Beans Original',pack:{amount:420,unit:'g'}}),b={...a,id:'synthetic-cache-conflict-b',pack:{amount:840,unit:'g'},sourceProvenance:F.evidence('synthetic-cache-conflict-b')};return [strong,weak,a,b];}
async function cachedRendered(page,result,outputDirectory){
  // Exercise the retained production renderer directly; fixtures were seeded in
  // this disposable context before startup. No renderer or lookup is replaced.
  await page.evaluate(()=>HEC_CANONICAL_CACHE_TEST.render('Fixture Original Loaf'));
  assert.equal(await page.locator('#food-results .resource-row').count(),1);assert.match(await page.locator('#food-results .resource-row').innerText(),/Fixture Original Loaf Updated/);
  const food=await page.evaluate(()=>HEC_CANONICAL_CACHE_TEST.food('synthetic-cache-weak'));assert.equal(food.id,'synthetic-cache-strong');assert.equal(food.canonicalEvidence.length,2);assert.equal(food.nutrients.calories,200);assert.equal(await page.locator('[data-food-add="synthetic-cache-strong"]').isEnabled(),true);assert.equal(await page.locator('[data-food-add="synthetic-cache-weak"]').count(),0);
  await page.screenshot({path:path.join(outputDirectory,result.viewport.width+'-cached-canonical.png'),fullPage:true});result.scenarios.push('compatible cached production renderer displays exactly one enriched 200 Cal product');
  await page.evaluate(()=>HEC_CANONICAL_CACHE_TEST.render('Fixture Cache Beans Original'));assert.equal(await page.locator('#food-results .resource-row').count(),1);assert.equal(await page.locator('#food-results [data-food-add]').isDisabled(),true);await page.locator('#food-results [data-food-details]').click();const details=await page.locator('.identity-source-conflict').innerText();assert(details.includes('420 g')&&details.includes('840 g'));assert.equal(await page.locator('.identity-source-conflict a').count(),2);assert.equal(await page.locator('#food-entry-editor.active').count(),0);result.scenarios.push('cached conflict retains both packs through Details and blocks Add');
  await page.locator('#a05-modal-close').click();await page.evaluate(()=>openAlpha05Feature('food-library',{freshSearch:true}));
}
async function review(page,id,expectedBrand){
  await page.locator(`[data-universal-result="${id}"]`).click();await page.locator('[data-gpr-measure="g"]:visible').waitFor();
  const measures=await page.locator('[data-gpr-measure]:visible').evaluateAll(ns=>ns.map(n=>n.dataset.gprMeasure));assert(!measures.some(key=>['mL','L','cup'].includes(key)));
  await page.locator('[data-gpr-measure="g"]:visible').click();const amount=page.locator('[data-gpr-amount]:visible');await amount.waitFor();assert.equal(await amount.inputValue(),'');await amount.fill('50');await amount.press('Enter');await page.locator('#food-entry-editor.active').waitFor();
  assert.equal(await page.locator('.screen.active').count(),1);assert.equal(await page.locator('[data-gpr-amount]:visible').count(),0);assert.equal(await page.locator('#entry-amount').inputValue(),'50');assert.equal(await page.locator('#entry-unit').inputValue(),'g');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);
  if(await page.locator('#save-food-entry').innerText()==='Save Food'){await page.locator('#save-food-entry-and-food').click();await page.locator('#entry-meal:visible').waitFor();await page.locator('#entry-meal').selectOption('Lunch');await page.locator('#save-food-entry-and-food').click();}else{await page.locator('#entry-meal').selectOption('Lunch');await page.locator('#save-food-entry').click();}await page.waitForFunction(id=>Object.values(JSON.parse(localStorage.getItem(HEC_INSTALLATION.functionalStorageKey)||'{}').diary||{}).flat().some(entry=>entry.foodId===id),id);
  const entry=await page.evaluate(id=>Object.values(JSON.parse(localStorage.getItem(HEC_INSTALLATION.functionalStorageKey)||'{}').diary||{}).flat().find(entry=>entry.foodId===id),id);assert.equal(entry.foodSnapshot.brand,expectedBrand);assert.equal(entry.nutrients.calories,100);assert.equal(entry.nutrients.fibre,null);
  await page.evaluate(()=>openAlpha05Feature('food-library',{freshSearch:true}));return {id,brand:expectedBrand,measures,amount:50,unit:'g',calories:entry.nutrients.calories};
}
async function run({outputDirectory=fs.mkdtempSync(path.join(os.tmpdir(),'hec-retailer-architecture-'))}={}){
  fs.mkdirSync(outputDirectory,{recursive:true});const {chromium,edge}=qa.browserTools(),browser=await chromium.launch({headless:true,executablePath:edge}),report={pass:false,browser:browser.version(),contexts:[]};let page;
  try{for(const viewport of [{width:390,height:844},{width:375,height:812}]){
    const diagnostic=qa.evidence(),context=await qa.contextFor({newContext:options=>browser.newContext({...options,isMobile:true,hasTouch:true})},viewport,diagnostic);await context.addInitScript(returningProfile);await context.addInitScript(typing.instrument);await context.addInitScript(foods=>{if(location.origin==='https://mlwes-hec-test.github.io')localStorage.setItem('healthyEatingCompanionTestAlpha06Functional',JSON.stringify({onlineFoods:foods,ui:{},savedFoodIds:[]}));},cachedFixtures());page=await context.newPage();await qa.openLibrary(page);
    const result={viewport,diagnostic,scenarios:[],reviews:[]};report.contexts.push(result);
    await cachedRendered(page,result,outputDirectory);
    await submit(page,'KFC');await settled(page);assert.match(await page.locator('#food-results').innerText(),/KFC/);assert(await page.locator('[data-rc5-source-category]').count()>0);result.scenarios.push('ordinary KFC restaurant source remains available after cached results');await page.evaluate(()=>openAlpha05Feature('food-library',{freshSearch:true}));
    await page.evaluate(()=>HECRetailerCatalogue.unregisterCatalogue('woolworths'));await submit(page,'Woolworths');await settled(page);assert.match(await page.locator('#food-results').innerText(),/No verified retailer food catalogue/);assert.equal(await page.locator('[data-retailer-more],[data-universal-result]').count(),0);result.scenarios.push('empty unregistered retailer');
    const fixture=F.fixture();await install(page,fixture);await page.locator('#food-search').fill('');await page.evaluate(()=>__typing.begin());await page.locator('#food-search').pressSequentially('Woolworths',{delay:20});await typing.settled(page);result.typing=await page.evaluate(()=>__typing.events.map(e=>({value:e.value,frameMs:e.frameMs,eventDelay:e.eventDelay,stable:e.stable,focused:e.focused})));assert(result.typing.every(e=>e.stable&&e.focused));await page.waitForFunction(()=>document.querySelector('#food-live-results')?.textContent.includes('Search to browse foods with verified retailer listing evidence.'));assert.equal(await page.evaluate(()=>__retailerLoads.length),0);result.scenarios.push('live recognition does not hydrate retailer index');
    await submit(page,'Woolworths');await settled(page);assert.equal(await page.locator('[data-retailer-category]').count(),3);assert.equal(await page.evaluate(()=>__retailerLoads.length),0);assert(!await page.locator('#food-results').innerText().then(t=>t.includes('Household')));await page.screenshot({path:path.join(outputDirectory,viewport.width+'-categories.png'),fullPage:true});result.scenarios.push('food-only category overview with All Items');
    await category(page,'*');assert.equal(await page.locator('[data-universal-result]').count(),20);const ids1=await page.locator('[data-universal-result]').evaluateAll(ns=>ns.map(n=>n.dataset.universalResult));await page.locator('[data-retailer-more]').click();await settled(page);const ids2=await page.locator('[data-universal-result]').evaluateAll(ns=>ns.map(n=>n.dataset.universalResult));assert.equal(ids2.length,7);assert.equal(new Set([...ids1,...ids2]).size,27);assert(![...ids1,...ids2].some(id=>['synthetic-no-membership','synthetic-nonfood','synthetic-community-only'].includes(id)));await page.locator('[data-retailer-previous]').click();await settled(page);assert.deepEqual(await page.locator('[data-universal-result]').evaluateAll(ns=>ns.map(n=>n.dataset.universalResult)),ids1);result.scenarios.push('bounded pagination, previous page, evidence and non-food exclusion');
    await page.locator('[data-retailer-back]').click();await settled(page);assert.equal(await page.locator('#food-search').inputValue(),'Woolworths');await category(page,'cereal');assert.equal(await page.locator('[data-universal-result]').count(),1);assert.match(await page.locator('[data-universal-result]').innerText(),/Kellogg's/);result.reviews.push(await review(page,fixture.national.id,"Kellogg's"));result.scenarios.push('national brand category, amount and one final Review with synthetic Diary save');
    await submit(page,'Woolworths');await settled(page);await submit(page,'Bread');await settled(page);assert.equal(await page.evaluate(()=>HEC_RETAILER_TEST.state()),null);await page.locator('[data-fc-base]').waitFor();assert.match(await page.locator('#food-results').innerText(),/BASE FOOD CONCEPT/);await page.locator('[data-fc-base]').click();await page.locator('[data-fc-answer="breadOrigin"][data-fc-value="commercial"]').click();await page.locator('[data-fc-answer="breadSource"][data-fc-value="supermarket"]').click();const choices=await commercialChoices(page);await page.locator('[data-fc-answer="retailerIdentity"][data-fc-value="woolworths"]').click();await settled(page);assert.equal(await page.locator('#food-search').inputValue(),'Bread');assert.equal(await page.locator('[data-retailer-scope="commercial-identity"]').count(),1);assert.deepEqual(await page.locator('[data-universal-result]').evaluateAll(ns=>ns.map(n=>n.dataset.universalResult)),[fixture.house.id,fixture.privateLabel.id]);assert.equal(await page.locator('[data-fc-answer="breadType"]').count(),0);await page.screenshot({path:path.join(outputDirectory,viewport.width+'-commercial-identity.png'),fullPage:true});await page.locator('[data-retailer-back]').click();await commercialChoices(page,choices);await switchCommercialChoices(page,choices,fixture);result.retailerChoices=choices;result.reviews.push(await review(page,fixture.privateLabel.id,'Fixture Pantry'));result.scenarios.push('guided commercial identity excludes national bread, preserves Back and private-label Review');
    await install(page,fixture);await submit(page,'Woolworths');await settled(page);await page.evaluate(()=>__retailerHold=true);await page.locator('[data-retailer-category="bread"]').click();await page.waitForFunction(()=>__retailerHeld.length===1);await submit(page,'Bread');await settled(page);await page.evaluate(()=>{__retailerHold=false;__retailerHeld.splice(0).forEach(resolve=>resolve())});await settled(page);assert.equal(await page.evaluate(()=>HEC_RETAILER_TEST.state()),null);assert.equal(await page.locator('[data-fc-base]').count(),1);result.scenarios.push('late retailer response cannot replace new generic query');
    await install(page,fixture);await submit(page,'Woolworths');await settled(page);await page.evaluate(()=>__retailerHold=true);await page.locator('[data-retailer-category="bread"]').click();await page.waitForFunction(()=>__retailerHeld.length===1);await submit(page,"Kellogg's");await page.evaluate(()=>{__retailerHold=false;__retailerHeld.splice(0).forEach(resolve=>resolve())});await page.waitForFunction(()=>HEC_AU_CATALOGUE_TEST.brandState()?.model?.brand?.name&& !HEC_AU_CATALOGUE_TEST.brandState().loading);await settled(page);assert.equal(await page.evaluate(()=>HEC_RETAILER_TEST.state()),null);assert.equal(await page.locator('#food-search').inputValue(),"Kellogg's");assert.equal(await page.locator('[data-retailer-id]').count(),0);result.scenarios.push('late retailer response cannot replace new consumer-brand query');
    await install(page,F.fixture({retailerId:'example-grocer',name:'Example Grocer'}));await submit(page,'Example Grocer');await settled(page);await category(page,'cereal');assert.equal(await page.locator('[data-retailer-id="example-grocer"]').count(),1);assert.match(await page.locator('[data-universal-result]').innerText(),/Kellogg's/);await page.locator('[data-retailer-exit]').click();assert.equal(await page.locator('#food-search').inputValue(),'');assert.equal(await page.evaluate(()=>HEC_RETAILER_TEST.state()),null);result.scenarios.push('second retailer same controller and Cancel resets intent');
    const restricted=F.fixture({extraProducts:0}),a=F.food('synthetic-conflict-a',{barcode:'2000000000008',name:'Fixture Original Bread',serving:'40 g serving',pack:{amount:420,unit:'g'},retailerMemberships:[F.membership('woolworths','synthetic-conflict-a')]}),b={...a,id:'synthetic-conflict-b',sourceProvenance:F.evidence('synthetic-conflict-b'),retailerMemberships:[F.membership('woolworths','synthetic-conflict-b')],pack:{amount:840,unit:'g'}};restricted.records=[a,b];restricted.entries=restricted.records;await install(page,restricted);await submit(page,'Woolworths');await settled(page);await category(page,'bread');assert.equal(await page.locator('[data-universal-result]').count(),1);assert.match(await page.locator('[data-universal-result]').innerText(),/Product Identity Conflict/);await page.locator('[data-universal-result]').click();assert.equal(await page.locator('[data-gpr-measure]:visible,[data-gpr-amount]:visible,#food-entry-editor.active').count(),0);await page.locator('[data-food-details]:visible').click();const evidence=await page.locator('.identity-source-conflict').innerText();assert(evidence.includes('420 g')&&evidence.includes('840 g'));assert.equal(await page.locator('.identity-source-conflict a').count(),2);await page.screenshot({path:path.join(outputDirectory,viewport.width+'-identity-conflict.png'),fullPage:true});result.scenarios.push('same-GTIN incompatible pack remains blocked on actual product selection');
    result.loadSizes=await page.evaluate(()=>__retailerLoads.map(ids=>ids.length));qa.requireEvidence(diagnostic);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await context.close();
  }report.pass=true;return report;}catch(error){report.error={message:error.message,stack:error.stack};throw error;}finally{if(page&&!page.isClosed())await page.screenshot({path:path.join(outputDirectory,'last-state.png'),fullPage:true}).catch(()=>{});await browser.close();fs.writeFileSync(path.join(outputDirectory,'retailer-rendered.json'),JSON.stringify(report,null,2));}
}
if(require.main===module)run({outputDirectory:process.argv[2]}).then(r=>console.log(JSON.stringify({pass:r.pass,contexts:r.contexts.map(c=>({viewport:c.viewport,scenarios:c.scenarios.length,reviews:c.reviews}))}))).catch(error=>{console.error(error);process.exitCode=1});
module.exports={run};
