'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),qa=require('./audit_physical_form_measures_edge'),{returningProfile}=require('./audit_navigation_startup_edge');
async function settled(page){await page.waitForFunction(()=>!HEC_RETAILER_TEST.state()?.loading&&!HEC_FOOD_CONCEPT_TEST.loading()&&!HEC_AU_CATALOGUE_TEST.status()?.loading&&!/^Checking the Australian catalogue/.test(document.querySelector('#food-results')?.textContent.trim()||''));}
async function submit(page,q){await page.locator('#food-search').fill(q);await page.locator('#submit-food-search').click();await page.waitForFunction(q=>HEC_SEARCH_SESSION_TEST.state().rawQuery===q&&HEC_SEARCH_SESSION_TEST.state().mode==='explicit-committed',q);await settled(page);}
async function fresh(page){if(await page.locator('#a05-modal:not(.hidden)').count())await page.locator('#a05-modal-close').click();await page.evaluate(()=>openAlpha05Feature('food-library',{freshSearch:true}));}
async function geometry(page){assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,'Horizontal overflow');const rows=page.locator('#food-results button:visible');let checked=0;for(let i=0;i<await rows.count();i++){const b=rows.nth(i);await b.scrollIntoViewIfNeeded();const r=await b.evaluate(n=>{const r=n.getBoundingClientRect();return {text:n.innerText,left:r.left,right:r.right,width:innerWidth,clipped:n.scrollWidth>n.clientWidth+1};});assert(r.left>=-1&&r.right<=r.width+1&&!r.clipped,JSON.stringify(r));checked++;}return {checked,horizontalOverflow:false,clippedControls:0};}
const samples=[
  {role:'cereal / new brand-browse identity',id:'off:9310055536579',query:"Kellogg's Crunchy Nut Corn Flakes",unit:'serve',amount:1},
  {role:'frozen potato',id:'off:9310174025084',query:'McCain Hash Browns',unit:'g',amount:75},
  {role:'soup / canned',id:'off:9300644700702',query:"Campbell's Chunky Beef & Veg",unit:'g',amount:250},
  {role:'coffee',id:'off:93625302',query:'Nescafe café nescafé gold original',unit:'serve',amount:1},
  {role:'liquid drink',id:'off:0613008753481',query:'Arizona ice tea with peach flavour',unit:'mL',amount:250},
  {role:'countable solid',id:'off:8852756327694',query:"Kellogg's Nutrigrain Bar Original",unit:'bar',amount:1},
  {role:'retailer overlap / slices',id:'off:4061462249464',query:'Bakers Life White Bakehouse Gluten Free',unit:'slice',amount:2},
  {role:'gram-based packaged food',id:'off:4088700157008',query:'Westacre Dairy Light Tasty Cheese Shredded',unit:'g',amount:40}
];
// UI record IDs may change when a higher-trust retailer record owns a GTIN.
async function resolveRenderedProduct(page,id){
  const barcode=id.replace(/^off:/,'');
  await page.waitForFunction(barcode=>[...document.querySelectorAll('[data-universal-result]')].some(n=>HEC_CANONICAL_CACHE_TEST.food(n.dataset.universalResult)?.barcode===barcode),barcode,{timeout:20000});
  return page.evaluate(barcode=>{const node=[...document.querySelectorAll('[data-universal-result]')].find(n=>HEC_CANONICAL_CACHE_TEST.food(n.dataset.universalResult)?.barcode===barcode),food=HEC_CANONICAL_CACHE_TEST.food(node.dataset.universalResult);return {id:node.dataset.universalResult,food,canonicalKey:HECFoodCatalogue.canonicalKey(food)};},barcode);
}
function HECSourceBrandMatch(food,expected){return require('../food-catalogue').consumerBrandMembership({type:'brand',name:expected.brand},food).matches;}
async function review(page,sample,out,width){await fresh(page);await submit(page,sample.query);const selection=await resolveRenderedProduct(page,sample.id),row=page.locator(`[data-universal-result="${selection.id}"]`).first();let food=selection.food;const expected=require('../brand-au-catalogue').entries.find(f=>f.id===sample.id);assert.equal(food.barcode,sample.id.slice(4));assert(HECSourceBrandMatch(food,expected));assert.equal(food.categoryId,expected.categoryId);await row.click();food=await page.evaluate(()=>HEC_GUIDED_PRODUCT_TEST.food());assert.equal(food.barcode,sample.id.slice(4));const measure=page.locator(`[data-gpr-measure="${sample.unit}"]:visible`);if(await measure.count())await measure.click();else assert(Object.keys(food.units).length===1&&sample.unit in food.units);const input=page.locator('[data-gpr-amount]:visible');await input.waitFor();assert.equal(await input.inputValue(),'');await input.fill(String(sample.amount));await input.press('Enter');await page.locator('#food-entry-editor.active').waitFor();assert.equal(await page.locator('.screen.active').count(),1);assert.equal(await page.locator('[data-gpr-amount]:visible').count(),0);assert.equal(await page.locator('#entry-unit').inputValue(),sample.unit);assert.equal(await page.locator('#entry-amount').inputValue(),String(sample.amount));const nutrition=await page.locator('#entry-nutrition-preview').innerText(),scale=food.units[sample.unit]*sample.amount,calories=food.nutrients.calories*scale;assert(nutrition.includes(Math.round(calories).toLocaleString('en-AU')+' Cal'),nutrition);assert(nutrition.includes(Math.round(food.nutrients.energyKj*scale).toLocaleString('en-AU')+' kJ'),nutrition);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await page.screenshot({path:path.join(out,width+'-review-'+sample.id.slice(4)+'.png'),fullPage:true});return {...sample,renderedId:selection.id,canonicalKey:selection.canonicalKey,name:food.name,brand:food.brand,sourceBrands:food.sourceBrands,barcode:food.barcode,category:food.category,nutrients:food.nutrients,measures:food.units,baseQuantity:scale*100,calories,energyKj:food.nutrients.energyKj*scale,reviewCount:1,diarySaved:false};}
async function run(out){fs.mkdirSync(out,{recursive:true});const report={pass:false,generation:require('../release-manifest.json').generation,contexts:[]},{chromium,edge}=qa.browserTools(),browser=await chromium.launch({headless:true,executablePath:edge});let page;try{for(const viewport of [{width:390,height:844},{width:320,height:568},{width:768,height:1024}]){const diagnostic=qa.evidence(),context=await qa.contextFor({newContext:opts=>browser.newContext({...opts,isMobile:true,hasTouch:true})},viewport,diagnostic);await context.addInitScript(returningProfile);page=await context.newPage();await qa.openLibrary(page);const r={viewport,diagnostic,reviews:[],checks:[]};report.contexts.push(r);assert.equal(await page.locator('#food-search').inputValue(),'');
  await submit(page,'Bread');assert(await page.locator('[data-fc-base]').count());r.generic=await geometry(page);
  await submit(page,"Kellogg's");assert(await page.locator('[data-au-brand-category]').count()>1);r.directory=await geometry(page);await page.screenshot({path:path.join(out,viewport.width+'-brand-directory.png'),fullPage:true});await page.locator('[data-au-brand-category="cereal"]').click();assert(await page.locator('[data-universal-result]').count()>0);r.products=await geometry(page);await page.locator('[data-au-brand-back]').click();assert(await page.locator('[data-au-brand-category]').count()>1);await page.locator('[data-au-brand-category="*"]').click();assert(await page.locator('[data-universal-result]').count()<=20);r.checks.push('Exact brand categories, All Items, bounded product page and Back');
  await submit(page,'Cereal');await page.locator('[data-fc-base]').click();await page.locator('[data-fc-answer="catalogueOrigin"][data-fc-value="commercial"]').click();await page.locator('[data-fc-answer="catalogueSource"][data-fc-value="brand"]').click();assert(await page.locator('[data-fc-answer="brandIdentity"][data-fc-value="kelloggs"]').count());assert.equal(await page.locator('[data-fc-answer="brandIdentity"][data-fc-value="nescafe"]').count(),0);r.narrowing=await geometry(page);await page.screenshot({path:path.join(out,viewport.width+'-cereal-brands.png'),fullPage:true});await page.locator('[data-fc-answer="brandIdentity"][data-fc-value="kelloggs"]').click();await settled(page);assert(await page.locator('.brand-catalogue [data-universal-result]').count());await page.locator('[data-au-brand-back]').click();assert(await page.locator('[data-fc-answer="brandIdentity"]').count());r.checks.push('Concept-specific brands and Back');
  if(viewport.width===390){for(const q of ['Woolworths','Coles','Aldi']){await submit(page,q);assert(await page.locator('[data-retailer-category]').count()>1);if(q==='Aldi'){assert.equal(await page.locator('[data-retailer-category]').count(),11);assert.match(await page.locator('#food-results').innerText(),/All Items \(20\)/);}}await submit(page,'Bread');assert.equal(await page.evaluate(()=>HEC_RETAILER_TEST.state()),null);await page.locator('[data-fc-base]').click();await page.locator('[data-fc-answer="breadOrigin"][data-fc-value="commercial"]').click();await page.locator('[data-fc-answer="breadSource"][data-fc-value="supermarket"]').click();assert.deepEqual(await page.locator('[data-fc-answer="retailerIdentity"]').evaluateAll(n=>n.map(e=>e.dataset.fcValue)),['woolworths','coles','aldi']);r.checks.push('Retailer roots, Aldi 10 + All Items 20, generic Bread clears scope and three retailer choices');}
  for(const sample of viewport.width===390?samples:[samples[0]])r.reviews.push(await review(page,sample,out,viewport.width));await fresh(page);assert.equal(await page.locator('#food-search').inputValue(),'');r.checks.push('New search opens blank');r.unhandledRejections=await page.evaluate(()=>__navigationRejections);assert.deepEqual(r.unhandledRejections,[]);qa.requireEvidence(diagnostic);await context.close();}report.pass=true;return report;}catch(e){report.error={message:e.message,stack:e.stack};throw e;}finally{if(page&&!page.isClosed())await page.screenshot({path:path.join(out,'last-state.png'),fullPage:true}).catch(()=>{});await browser.close();fs.writeFileSync(path.join(out,'brand-rendered.json'),JSON.stringify(report,null,2));}}
if(require.main===module)run(process.argv[2]).then(r=>console.log(JSON.stringify({pass:r.pass,contexts:r.contexts.length,reviews:r.contexts.reduce((n,c)=>n+c.reviews.length,0)}))).catch(e=>{console.error(e);process.exitCode=1;});module.exports={run,submit,settled,geometry,fresh,review,samples,resolveRenderedProduct};
