'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const qa=require('./audit_physical_form_measures_edge'),{returningProfile}=require('./audit_navigation_startup_edge'),{instrument,settled,stats}=require('./profile_search_typing');
function controlEvents(){window.__postKfcClicks=[];for(const type of ['pointerdown','pointerup','click'])window.addEventListener(type,event=>{const button=event.target.closest?.('button');if(button)__postKfcClicks.push({type,trusted:event.isTrusted,control:button.outerHTML});},true);}
async function ready(page){await settled(page);await page.waitForFunction(()=>!HEC_AU_CATALOGUE_TEST.brandState()?.loading&&!HEC_FOOD_CONCEPT_TEST.state()?.loading);}
async function surface(page){return page.evaluate(()=>{
  const visible=n=>!!n&&n.getBoundingClientRect().height>0&&getComputedStyle(n).visibility!=='hidden',nodes=['food-live-results','food-results'].map(id=>document.getElementById(id)).filter(visible),ui=JSON.parse(localStorage.getItem(HEC_INSTALLATION.functionalStorageKey)||'{}').ui;
  return {query:document.querySelector('#food-search').value,text:nodes.map(n=>n.innerText).join('\n'),ids:nodes.flatMap(n=>[...n.querySelectorAll('[data-universal-result],[data-food-review],[data-food-add]')]).map(n=>n.dataset.universalResult||n.dataset.foodReview||n.dataset.foodAdd),session:HEC_SEARCH_SESSION_TEST.state(),source:ui.foodSourceBrowse||null,meal:ui.pendingMeal,overflow:document.documentElement.scrollWidth>innerWidth+1,brand:HEC_AU_CATALOGUE_TEST.brandState()};
});}
async function clear(page){const cancel=page.locator('[data-gpr-cancel]:visible');if(await cancel.count())await cancel.click();await page.locator('#clear-food-search').click();await ready(page);await page.locator('#food-search').click();}
async function type(page,query){await clear(page);await page.locator('#food-search').pressSequentially(query,{delay:20});await ready(page);assert.equal(await page.locator('#food-search').inputValue(),query);}
async function homeLibrary(page,meal=false){await page.goto(qa.ORIGIN+'/',{waitUntil:'load'});await page.locator('#home.active').waitFor();if(meal){await page.locator('#home [data-room="diary"]').click();await page.locator('[data-add-to-meal="Breakfast"]').click();}else await page.locator('#home [data-room="database"]').click();await page.locator('#food-search').waitFor();await page.evaluate(()=>__typing.begin());await ready(page);}
async function review(page,id,unit,amount,calories){
  await page.locator(`[data-universal-result="${id}"]`).click();const measures=page.locator('[data-gpr-measure]:visible');if(await measures.count())await page.locator(`[data-gpr-measure="${unit}"]:visible`).click();
  const input=page.locator('[data-gpr-amount]:visible');await input.waitFor();assert.equal(await input.inputValue(),'');await input.fill(String(amount));await input.press('Enter');await page.locator('#food-entry-editor.active').waitFor();assert.equal(await page.locator('.screen.active').count(),1);assert.equal(await page.locator('[data-gpr-amount]:visible').count(),0);assert.equal(await page.locator('#entry-unit').inputValue(),unit);assert.equal(Number(await page.locator('#entry-amount').inputValue()),amount);const nutrition=await page.locator('#entry-nutrition-preview').innerText();assert(nutrition.replaceAll(',','').includes(String(calories)+' Cal'),nutrition);await page.locator('#food-entry-editor').getByRole('button',{name:'← Back',exact:true}).click();return {id,unit,amount,nutrition,oneReview:true};
}
async function run({outputDirectory=fs.mkdtempSync(path.join(os.tmpdir(),'hec-post-kfc-'))}={}){
  fs.mkdirSync(outputDirectory,{recursive:true});const {chromium,edge}=qa.browserTools(),browser=await chromium.launch({headless:true,executablePath:edge}),report={pass:false,viewport:{width:390,height:844},diagnostic:qa.evidence(),scenarios:[],typing:[]};let page;
  try{const context=await qa.contextFor({newContext:options=>browser.newContext({...options,isMobile:true,hasTouch:true})},report.viewport,report.diagnostic);await context.addInitScript(returningProfile);await context.addInitScript(instrument);await context.addInitScript(controlEvents);page=await context.newPage();page.setDefaultTimeout(30000);
    for(const meal of [false,true])for(const action of ['Search','Enter','Browse']){
      await homeLibrary(page,meal);await type(page,'Mcdonalds');const preview=await surface(page);assert.match(preview.text,/Restaurant source recognised/);assert.equal(preview.session.sourceCommitted,false);
      if(action==='Search')await page.locator('#submit-food-search').click();else if(action==='Enter')await page.locator('#food-search').press('Enter');else await page.getByRole('button',{name:/Browse McDonald.*Australia/}).click();await ready(page);const hub=await surface(page);assert.equal(hub.query,'Mcdonalds');assert.match(hub.text,/211 loaded products/);assert.equal(hub.meal,meal?'Breakfast':'');
      await page.locator('[data-rc5-source-category="Burgers"]').click();await ready(page);const category=await surface(page);assert.equal(category.source.sourceId,'mcdonalds-au');assert.equal(category.source.category,'Burgers');assert.match(category.text,/Big Mac/);assert.equal(category.query,'');assert.equal(category.session.rawQuery,'');assert.equal(category.meal,hub.meal);
      await page.locator('[data-rc5-back-categories]').click();await ready(page);const returned=await surface(page);assert.match(returned.text,/211 loaded products/);assert.equal(returned.session.sourceCommitted,true);assert.equal(returned.source.category,undefined);assert.equal(returned.meal,hub.meal);
      await page.locator('[data-rc4-leave-source]').click();await ready(page);const left=await surface(page);assert.equal(left.source,null);assert.equal(left.query,'');assert.match(left.text,/Find A Food/);assert.equal(left.meal,hub.meal);report.scenarios.push({kind:'restaurant',meal,action,preview,hub,category,returned,left});
    }
    for(const phase of ['fresh','loaded']){
      await homeLibrary(page);if(phase==='loaded')await type(page,'Flora');
      await clear(page);let previous='';for(const query of ['Weet','Weet-b','Weet-bi','Weet-bix']){await page.locator('#food-search').pressSequentially(query.slice(previous.length),{delay:20});await ready(page);const row=await surface(page);assert(!/Sweetcorn|Sweet Potato/.test(row.text));assert.equal(row.session.guidedCommitted,false);if(query==='Weet-bix'){const accepted=require('../brand-au-catalogue').entries.filter(e=>e.brandKeys.includes('weetbix')).map(e=>e.id).sort();assert.deepEqual([...new Set(row.ids)].sort(),accepted,'Exact generated-brand preview uses admitted identities only');}else assert(row.ids.includes('weetbix-au'));report.scenarios.push({phase,kind:'weet-prefix',...row});previous=query;}
      await page.locator('#submit-food-search').click();await ready(page);const allItems=page.locator('[data-au-brand-category="*"]');if(await allItems.count())await allItems.click();const admittedWeet=require('../brand-au-catalogue').entries.filter(e=>e.brandKeys.includes('weetbix')).map(e=>e.id).sort();assert.deepEqual((await surface(page)).ids.sort(),admittedWeet);await page.screenshot({path:path.join(outputDirectory,'weet-'+phase+'.png'),fullPage:true});
      // The curated original stays reachable by its explicit product query,
      // independently of the generated brand's two admitted GTIN identities.
      await type(page,'Sanitarium Weet-Bix Original');await page.locator('#submit-food-search').click();await ready(page);assert((await surface(page)).ids.includes('weetbix-au'));report.scenarios.push({phase,kind:'weet-review',...await review(page,'weetbix-au','biscuit',2,110)});
      await type(page,'Weet-Bix Bites Honey Crunch');await page.locator('#submit-food-search').click();await ready(page);let row=await surface(page);assert.match(row.text,/isn’t currently in HEC’s verified catalogue/);assert(!row.ids.includes('off:9300652801309'),'The frozen Honey Crunch energy pair exceeds the wave’s 5% gate');assert(!row.ids.includes('weetbix-au'),'An excluded variant must never fall back to original Weet-Bix');report.scenarios.push({phase,kind:'explicit-variant',...row});
      await clear(page);previous='';for(const query of ['Nesc','Nesca','Nescaf','Nescafe']){await page.locator('#food-search').pressSequentially(query.slice(previous.length),{delay:20});await ready(page);row=await surface(page);assert.equal(row.query,query);assert.match(row.text,/Nescafé/);assert.equal(row.session.guidedCommitted,false);report.scenarios.push({phase,kind:'nesc-prefix',...row});previous=query;}
      for(const query of ['Nescafé cap','Nescafé cappuccino','Nescafé cappuccino strong','Nescafé strong cappuccino']){
        await type(page,query);const preview=await surface(page);if(query==='Nescafé cappuccino')assert(!/Exact Product Match[\s\S]*Iced cappuccino Salted caramel[\s\S]*Close Product Matches/.test(preview.text));
        await page.locator('#submit-food-search').click();await ready(page);const submitted=await surface(page);assert.equal(submitted.session.mode,'explicit-committed');assert.equal(submitted.query,query);
        if(query==='Nescafé cappuccino'){assert(!await page.locator('[data-universal-group="best"] [data-universal-result="off:9300605137424"]').count());assert(!submitted.ids.includes('off:9300605137424'),'The audited wave excludes this conflicting energy pair');}
        if(query.includes('strong')){assert(!submitted.ids.includes('off:9300605156852'),'Conflict records remain internal, outside ordinary brand choices');assert.equal(await page.locator('[data-gpr-measure]:visible,[data-gpr-amount]:visible').count(),0);assert.equal(await page.locator('#food-entry-editor.active').count(),0);}
        report.scenarios.push({phase,kind:'nesc-product',query,preview,submitted});
      }
      const typing=await page.evaluate(()=>({events:__typing.events,tasks:__typing.tasks,longTasks:__typing.longTasks}));report.typing.push({phase,summary:{inputDelay:stats(typing.events.map(e=>e.eventDelay)),inputHandlers:stats(typing.tasks.filter(t=>t.kind==='handler'&&t.type==='input').map(t=>t.duration)),frameProxy:stats(typing.events.map(e=>e.frameMs)),longTasks:stats(typing.longTasks.map(t=>t.duration))}});
      await clear(page);row=await surface(page);assert.equal(row.query,'');assert.equal(row.source,null);assert.equal(row.session.guidedCommitted,false);await page.screenshot({path:path.join(outputDirectory,'clear-'+phase+'.png'),fullPage:true});
    }
    // Shared restaurant helper also retains another source and distinguishes a
    // deliberate filter clear from leaving that source.
    await type(page,'KFC');await page.locator('#submit-food-search').click();await ready(page);await page.locator('[data-rc5-source-category="Burgers"]').click();await ready(page);assert.equal((await surface(page)).source.sourceId,'kfc-au');await page.locator('[data-rc5-back-categories]').click();await ready(page);assert.match((await surface(page)).text,/148 loaded products/);
    // The app may dispatch its own follow-up clicks (for example Enter to
    // Review). Confirm trusted initiating clicks on the actual task controls;
    // synthetic follow-up events do not replace those acceptance actions.
    // Universal product rows activate on pointerup and replace themselves before
    // click; require both trusted pointer events on those initiating buttons.
    const stored=await page.evaluate(()=>{const data=JSON.parse(localStorage.getItem(HEC_INSTALLATION.functionalStorageKey)||'{}'),events=__postKfcClicks;return {diary:data.diary||{},trustedControls:['data-rc5-source-category','data-rc5-back-categories','weetbix-au','submit-food-search'].map(key=>({key,trusted:(['weetbix-au','off:9300605156852'].includes(key)?['pointerdown','pointerup']:['click']).every(type=>events.some(e=>e.type===type&&e.trusted&&e.control.includes(key)))})),syntheticFollowups:events.filter(e=>!e.trusted),profile:JSON.parse(localStorage.getItem('healthyEatingCompanionTestAlpha06')).personal.givenName};});assert.deepEqual(stored.diary,{});assert(stored.trustedControls.every(c=>c.trusted),JSON.stringify(stored.trustedControls));assert.equal(stored.profile,'Navigation fixture');report.disposable=stored;
    assert(report.scenarios.every(s=>!s.overflow));qa.requireEvidence(report.diagnostic);report.pass=true;await context.close();return report;
  }catch(error){report.error={message:error.message,stack:error.stack};if(page)await page.screenshot({path:path.join(outputDirectory,'failure.png'),fullPage:true}).catch(()=>{});throw error;}finally{await browser.close();fs.writeFileSync(path.join(outputDirectory,'post-kfc-search.json'),JSON.stringify(report,null,2));console.log('Post-KFC rendered evidence: '+outputDirectory);}
}
if(require.main===module)run({outputDirectory:process.argv[2]}).then(r=>console.log(JSON.stringify({pass:r.pass,scenarios:r.scenarios.length,typing:r.typing}))).catch(e=>{console.error(e);process.exitCode=1;});
module.exports={run};
