const fs=require('fs'),path=require('path'),crypto=require('crypto'),C=require('../food-catalogue'),B=require('../brand-au-catalogue'),R=require('../retailer-catalogue'),X=require('./catalogue-round-two');
const ROOT=path.resolve(__dirname,'..'),BASE=path.join(ROOT,'data/catalogue-round-three'),read=n=>JSON.parse(fs.readFileSync(path.join(BASE,n),'utf8').replace(/^\uFEFF/,'')),write=(n,v)=>fs.writeFileSync(path.join(BASE,n),JSON.stringify(v,null,2)+'\n'),hash=s=>crypto.createHash('sha256').update(s).digest('hex');
function snapshot(){const indices=Object.fromEntries(['woolworths','coles','aldi'].map(k=>[k,require('../'+k+'-au-catalogue').index]));const retailers=Object.fromEntries(Object.entries(indices).map(([k,i])=>[k,{keys:i.entries.filter(e=>e.browseEligible!==false&&X.membership(e,k).length).map(C.canonicalKey),visible:R.directory(k).total}]));return {retailers,brandKeys:B.entries.map(C.canonicalKey),brands:B.brands.map(b=>({key:b.key,name:b.name,count:b.count})),generation:require('../release-manifest.json').generation};}
function evidence(){const sources=read('public-evidence.json');
 // The ordinary Coles HTTP request returned a challenge document. The separate
 // public web-reader rendered the official directory; retain reviewed facts,
 // explicitly hashing those facts rather than mislabelling the challenge hash.
 const coles=sources.find(s=>s.id==='coles-brands');coles.directHttpUsable=false;coles.webReaderCheckedAt='2026-09-18';coles.webReaderFacts={title:'Brands exclusive to Coles',url:coles.url,brands:coles.brands,observation:'Official retailer directory explicitly introduces these as exclusive Our Brand product lines. Non-food brands omitted.'};coles.webReaderFactsSha256=hash(JSON.stringify(coles.webReaderFacts));
 const add=(id,url,brands,relationship)=>sources.push({id,url,retrievedAt:'2026-09-18',retrievalPrecision:'date-only',method:'Reviewed public web-reader facts',brands,relationship,webReaderFacts:{url,brands,relationship},webReaderFactsSha256:hash(JSON.stringify({url,brands,relationship}))});
 add('woolworths-portfolio','https://www.woolworthsgroup.com.au/content/dam/wwg/investors/reports/2023/f23-full-year/Woolworths%20Group%202023%20Annual%20Report.pdf',['Thomas Dux','COOK','BBQ','Macro Wholefoods'],'Official FY2023 own brand portfolio; historical relationship, individual current product status unknown.');
 add('woolworths-plantitude','https://www.woolworthsgroup.com.au/content/dam/wwg/sustainability/reports/195991_2021-sustainability-report.pdf',['Plantitude'],'Official 2021 sustainability report identifies Woolworths Plantitude launch in 2019.');
 add('woolworths-plantitude-current','https://www.woolworths.com.au/shop/productdetails/176084/plantitude-meatballs',['Plantitude'],'Official current Australian Plantitude Meatballs 280g page with nutrition. Existing record linkage requires separate product review; no panel imported by this family audit.');
 add('woolworths-thomas-current','https://www.woolworths.com.au/shop/productdetails/6065657/thomas-dux-pepperoni',['Thomas Dux'],'Official current Australian Thomas Dux Pepperoni 200g product page.');
 add('woolworths-essentials','https://www.woolworthsgroup.com.au/au/en/our-newsroom/media-releases/latest-news/2025/woolworths-expands-lower-shelf-price-to-nearly-700-everyday-esse.html',['Essentials'],'Official August 2025 Essentials presence; individual food stock unverified.');
 add('woolworths-historical','https://www.woolworthsgroup.com.au/content/dam/wwg/investors/reports/2016/185967_corporate-responsibility-report-2016.pdf',['Farmers Own','Macro','Select','Homebrand','Gold'],'Official 2016 report identifies these Woolworths own ranges; historical relationship only.');
 add('woolworths-farmers-current','https://www.woolworths.com.au/shop/productdetails/757826',['Farmers Own'],'Official Australian Farmers Own Full Cream Homogenised 2L product page.');
 return sources;}
function audit(){if(!fs.existsSync(path.join(BASE,'baseline.json')))write('baseline.json',snapshot());const before=read('baseline.json'),sources=evidence();write('reviewed-evidence.json',sources);
 const audit=require('../data/catalogue-round-two/audit.json'),inputs=new Map(require('../data/catalogue-round-two/off-input.json').records.map(r=>[r.record.id,r.record]));const foods=B.files.flatMap(s=>require('../data/brand-au/'+s.path).records),map=new Map();
 function family(retailer,name,sourceIds=[],status='uncertain',note=''){const key=C.brandKey(name),id=retailer+':'+key,old=map.get(id);if(old){old.evidenceIds=[...new Set([...old.evidenceIds,...sourceIds])];if(status==='current'||status==='legacy')old.status=status;return old;}const value={retailer,key,displayBrand:before.brands.find(b=>b.key===key)?.name||name,status,evidenceIds:sourceIds,notes:note||'Exact existing brand key only. Different source keys are not merged.'};map.set(id,value);return value;}
 for(const s of sources){if(s.id.startsWith('aldi-'))for(const name of s.brands){if(s.brandPresence&&s.brandPresence[name]===false)continue;const relation=['aldi-2025','aldi-2026','aldi-products'].includes(s.id);const f=family('aldi',name,[s.id],s.id==='aldi-2025'?'uncertain':'current');if(relation)f.relationshipVerified=true;}}
 // Westacre is separately evidenced as ALDI's cheese brand in its own ACCC
 // submission; do not collapse it into the Westacre Dairy key.
 sources.push({id:'aldi-historical',url:'https://www.accc.gov.au/system/files/081%20%28revised%29%20-%20Aldi%20%2818%20pages%29.pdf',retrievedAt:'2026-09-18',method:'Reviewed public web-reader facts',relationship:'ALDI submission names own brands Westacre, Ocean Rise and Choceur.',brands:['Westacre','Ocean Rise','Choceur'],webReaderFactsSha256:hash('ALDI submission: own brands Westacre, Ocean Rise, Choceur; reviewed 2026-09-18')});
 for(const name of ['Westacre','Ocean Rise','Choceur']){const f=family('aldi',name,['aldi-historical']);f.relationshipVerified=true;}
 for(const name of sources.find(s=>s.id==='coles-brands').brands)family('coles',name,['coles-brands'],'current').relationshipVerified=true;
 const ww=[['Woolworths',['woolworths-health'],'current'],['Woolworths Bakery',['woolworths-health'],'current'],['Macro',['woolworths-macro'],'current'],['Macro Wholefoods Market',['woolworths-portfolio','woolworths-macro'],'current'],['Macro Wholefoods',['woolworths-portfolio'],'uncertain'],['Woolworths Macro',['woolworths-macro'],'uncertain'],['Thomas Dux',['woolworths-portfolio','woolworths-thomas-current'],'current'],['Plantitude',['woolworths-plantitude','woolworths-plantitude-current'],'current'],['Woolworths Plantitude',['woolworths-plantitude','woolworths-plantitude-current'],'current'],['Farmers Own',['woolworths-historical','woolworths-farmers-current'],'current'],['Essentials',['woolworths-essentials'],'uncertain'],['Woolworths Essentials',['woolworths-essentials'],'uncertain'],['Woolworths Select',['woolworths-history','select-legacy'],'legacy'],['Woolworths Home Brand',['woolworths-history','select-legacy'],'legacy'],['Homebrand',['woolworths-history','select-legacy'],'legacy'],['Woolworths Gold',['woolworths-historical'],'uncertain'],['The Odd Bunch',['woolworths-health'],'current']];for(const [name,ids,status]of ww)family('woolworths',name,ids,status).relationshipVerified=true;
 // Material source variants are separate audit rows, not fuzzy brand aliases.
 const extraAldi=['Aldi','New Season','Farmdale','Remano','Bramwells','Market Fare','Sweet Valley','Portview','HASNO','Chefs Cupboard','Casa Barelli','Brannans Butchery','Karidale Farm Fresh','Asia Specialities','Stonemill','Corale','Garden Greens','Simplee','Dairy Dream','Forresters','Delicio','Delaney Orchards','Oh So Natural Wholefoods','Sweet Vine','Beautifully Butterfully','Applebys Farm','FRUIMA','Lyttos','Lodge Farms','The Soup Co','Oktoberfest','Cowbelle','The Cake Stall','Just Organic','Belmont','Northbrook','Westcliff','The Fishmonger','Berg Smallgoods','Brookdale','Oh So Natural Foods','Asia Specialties','Hillcrest (Aldi)','Oh So Natural Organic','Oh So Natural Gluten Free'];for(const n of extraAldi)family('aldi',n);
 for(const row of audit.off)for(const name of row.brand.split(',').map(s=>s.trim())){if(!name)continue;const key=C.brandKey(name);if(/^coles/.test(key))family('coles',name);if(/^woolworth/.test(key)||['minimacro'].includes(key))family('woolworths',name);}
 for(const name of ["Select","Free From Gluten","Free From Lactose","Hillview","Bell Farms","COOK","BBQ","Good to Go","Snackable Woolworths","Woolies","Cook (Woolworths)","Macro Organic"])family('woolworths',name,[],name==='Select'?'legacy':'uncertain','Retained source association does not by itself prove ownership; standalone spelling kept separate.');
 const rows=[];for(const f of [...map.values()].sort((a,b)=>(a.retailer+a.key).localeCompare(b.retailer+b.key))){const raw=audit.off.filter(r=>r.brand.split(',').some(n=>C.brandKey(n)===f.key));const accepted=foods.filter(p=>(p.sourceBrandTokens||[{key:C.brandKey(p.brand)}]).some(t=>t.key===f.key));const startingRetailer=new Set(before.retailers[f.retailer].keys);f.sourceSpellings=[...new Set(raw.flatMap(r=>r.brand.split(',').map(n=>n.trim()).filter(n=>C.brandKey(n)===f.key)))].sort();f.startingAcceptedCount=new Set(accepted.map(C.canonicalKey)).size;f.startingRetailerCount=accepted.filter(p=>startingRetailer.has(C.canonicalKey(p))).length;f.candidateAdditionalCount=raw.filter(r=>!startingRetailer.has('barcode:'+r.gtin)).length;f.admittedAdditionalCount=0;f.newOrdinaryCount=0;f.heldCount=0;f.principalHoldReasons={};const decisions=[];
 for(const r of raw){if(startingRetailer.has('barcode:'+r.gtin))continue;const p=accepted.find(p=>C.canonicalKey(p)==='barcode:'+r.gtin),reasons=[...r.reasons];if(!f.relationshipVerified)reasons.push('house-brand-relationship-unverified');if(p&&C.brandKey(p.brand)!==f.key)reasons.push('source-brand-token-is-not-consumer-brand');if(f.retailer==='coles'&&['off:9300601000562','off:9300601340828','off:9310645091334'].includes(r.id))reasons.push('protected-retailer-internal-record');const input=inputs.get(r.id);if(p&&(!input||input.countries.length!==1||input.countries[0]!=='en:australia'))reasons.push('AU-only-product-corroboration-required');if(!p&&!reasons.length)reasons.push('not-in-current-accepted-brand-projection');const unique=[...new Set(reasons)];for(const reason of unique)f.principalHoldReasons[reason]=(f.principalHoldReasons[reason]||0)+1;decisions.push({id:r.id,gtin:r.gtin,name:r.name,brand:r.brand,canonicalKey:'barcode:'+r.gtin,eligible:unique.length===0,reasons:unique});}
 f.heldCount=decisions.filter(d=>!d.eligible).length;f.eligibleRetailerAdditions=decisions.filter(d=>d.eligible).length;f.endingAcceptedCount=f.startingAcceptedCount;f.endingRetailerCount=f.startingRetailerCount;f.decisions=decisions;rows.push(f);}
 write('reviewed-evidence.json',sources);write('family-audit-before.json',{phase:'before admission',date:'2026-09-18',scope:'Pinned Australian OFF and accepted brand/retailer catalogues, then bounded official relationship research. Not a claim of complete national inventory.',rows});
 const table=['# House-brand completeness audit — before admission','','Brand keys remain separate. Global accepted counts and retailer counts are distinct. Current means a current official family listing, not current stock or a new panel. Uncertain means currentness or relationship is unresolved; relationship proof is tracked separately. No products admitted by this audit stage.','','| Retailer | Brand / key | Status | Relationship proved | Accepted | Retailer | Candidate additional | Eligible retailer additions | Held | Main hold reasons |','|---|---|---|---|---:|---:|---:|---:|---:|---|',...rows.map(f=>`| ${f.retailer} | ${f.displayBrand} / ${f.key} | ${f.status} | ${!!f.relationshipVerified} | ${f.startingAcceptedCount} | ${f.startingRetailerCount} | ${f.candidateAdditionalCount} | ${f.eligibleRetailerAdditions} | ${f.heldCount} | ${Object.entries(f.principalHoldReasons).sort((a,b)=>b[1]-a[1]).slice(0,3).map(([k,v])=>k+': '+v).join('; ')} |`)];fs.writeFileSync(path.join(ROOT,'HOUSE_BRAND_AUDIT_BEFORE.md'),table.join('\n')+'\n');console.log(JSON.stringify({families:rows.length,byRetailer:Object.fromEntries(['aldi','woolworths','coles'].map(k=>[k,{families:rows.filter(f=>f.retailer===k).length,eligible:rows.filter(f=>f.retailer===k).reduce((n,f)=>n+f.eligibleRetailerAdditions,0)}]))},null,2));}
if(require.main===module)audit();module.exports={read,write,hash,BASE,ROOT};
