#!/usr/bin/env node
'use strict';

const fs=require('node:fs');
const http=require('node:http');
const path=require('node:path');
const ROOT=path.resolve(__dirname,'..'),modules=process.env.HEC_WORKSPACE_NODE_MODULES;
const {chromium}=modules?require(path.join(modules,'playwright')):require('playwright');
const edge=['C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe','C:/Program Files/Microsoft/Edge/Application/msedge.exe'].find(fs.existsSync);
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.ico':'image/x-icon','.webmanifest':'application/manifest+json'};

function server(){return http.createServer((request,response)=>{const pathname=decodeURIComponent(new URL(request.url,'http://localhost').pathname);if(pathname==='/favicon.ico'){response.writeHead(204);response.end();return;}const relative=pathname==='/'?'index.html':pathname.replace(/^\/+/,''),file=path.resolve(ROOT,relative);if(!file.startsWith(ROOT)||!fs.existsSync(file)||fs.statSync(file).isDirectory()){response.writeHead(404);response.end('Not found');return;}response.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream','Cache-Control':'no-store'});fs.createReadStream(file).pipe(response);});}
async function openLibrary(page,url){await page.goto(url,{waitUntil:'load'});await page.waitForFunction(()=>window.HEC_SEARCH_SESSION_TEST&&typeof window.openAlpha05Feature==='function');await page.evaluate(()=>window.openAlpha05Feature('food-library',{freshSearch:true}));await page.locator('#food-search').waitFor({state:'visible'});}
async function typeContinuously(page,value){const input=page.locator('#food-search');await input.click();for(const character of value)await input.type(character,{delay:4});await page.waitForTimeout(220);return input.evaluate(node=>({focused:document.activeElement===node,value:node.value,caret:node.selectionStart,sameNode:node===document.querySelector('#food-search')}));}
async function submit(page,value,{button=true}={}){const input=page.locator('#food-search');await input.fill(value);await input.dispatchEvent('input');if(button)await page.locator('#submit-food-search').click();else await input.press('Enter');await page.waitForTimeout(250);}
async function layout(page,label){return page.evaluate(label=>{const visible=node=>{if(!node)return false;const rect=node.getBoundingClientRect(),style=getComputedStyle(node);return style.display!=='none'&&style.visibility!=='hidden'&&rect.width>0&&rect.height>0;},surfaces=['food-live-results','food-results'].map(id=>document.getElementById(id)).filter(visible),controls=[...document.querySelectorAll('#food-library button:enabled,#food-library input,#food-library select')].filter(visible),outside=controls.filter(node=>{const rect=node.getBoundingClientRect();return rect.left<-.6||rect.right>innerWidth+.6||document.activeElement===node&&rect.bottom>innerHeight+.6;}).map(node=>node.id||node.textContent.trim().slice(0,50)),shortPrimary=controls.filter(node=>/primary|guided-resolution-choice|universal-search-result/.test(node.className)&&node.getBoundingClientRect().height<43.5).map(node=>node.textContent.trim().slice(0,50));return {label,viewport:`${innerWidth}x${innerHeight}`,surfaceCount:surfaces.length,bodyOverflow:document.documentElement.scrollWidth>document.documentElement.clientWidth+1,surfaceOverflow:surfaces.some(node=>node.scrollWidth>node.clientWidth+1),outside,shortPrimary,searchVisible:visible(document.querySelector('#submit-food-search')),text:surfaces.map(node=>node.innerText).join('\n')};},label);}
function requireReport(report,{include=[]}={}){const failures=[];if(report.surfaceCount!==1)failures.push(`primary surfaces=${report.surfaceCount}`);if(report.bodyOverflow||report.surfaceOverflow)failures.push('horizontal overflow');if(report.outside.length)failures.push(`outside: ${report.outside.join(', ')}`);if(report.shortPrimary.length)failures.push(`short primary: ${report.shortPrimary.join(', ')}`);if(!report.searchVisible)failures.push('Search button hidden');for(const text of include)if(!report.text.includes(text))failures.push(`missing ${text}`);if(failures.length)throw new Error(`${report.viewport} ${report.label}: ${failures.join('; ')}; visible text=${JSON.stringify(report.text.slice(0,700))}`);return report;}
async function genericScenario(page,url,query,include){await openLibrary(page,url);await submit(page,query);await page.locator('[data-universal-generic]').waitFor({state:'visible'});return requireReport(await layout(page,query),{include});}
async function simpleSkipScenario(page,url){await openLibrary(page,url);await submit(page,'Banana');await page.locator('[data-universal-generic]').click();await page.waitForTimeout(100);const report=requireReport(await layout(page,'Banana simple-source skip'),{include:['Banana']});if(await page.locator('[data-universal-source]').count()||/Where did it come from/i.test(report.text))throw new Error('simple whole food opened a source chooser');return {...report,sourceChoices:0};}
async function sourceScenarios(page,url){const rows=[];await openLibrary(page,url);await submit(page,'Hash Brown');await page.locator('[data-universal-generic]').click();await page.waitForTimeout(100);const keys=await page.locator('[data-universal-source]').evaluateAll(nodes=>nodes.map(node=>node.dataset.universalSource));if(keys.join('|')!=='home-prepared|ready-to-eat|packaged-frozen|typical')throw new Error(`source keys ${keys.join(',')}; state=${JSON.stringify(await page.evaluate(()=>window.HEC_SEARCH_SESSION_TEST.state()))}; visible text=${JSON.stringify((await page.locator('#food-results').innerText()).slice(0,900))}`);
  await page.locator('[data-universal-source="home-prepared"]').click();if(!/Build From Ingredients/.test(await page.locator('#food-results').innerText()))throw new Error('home handoff missing');await page.locator('[data-universal-back-source]').click();
  await page.locator('[data-universal-source="ready-to-eat"]').click();await page.waitForTimeout(100);rows.push(requireReport(await layout(page,'Hash Brown restaurant'),{include:["McDonald's",'Hash Brown']}));await page.locator('[data-universal-back-source]').click();
  await page.locator('[data-universal-source="packaged-frozen"]').click();await page.waitForTimeout(700);rows.push(requireReport(await layout(page,'Hash Brown packaged'),{include:['McCain','Scan Barcode','Read Nutrition Panel']}));await page.locator('[data-universal-back-source]').click();
  await page.locator('[data-universal-source="typical"]').click();rows.push(requireReport(await layout(page,'Hash Brown typical'),{include:['No reliable loaded Australian nutrition record']}));await page.locator('[data-universal-back-source]').click();
  const restored=await page.locator('[data-universal-source]').count();if(restored!==4)throw new Error(`source Back restored ${restored} choices`);return {keys,backRestored:restored,rows};}
async function physicalFormScenario(page){return page.evaluate(()=>{
  const profile=food=>window.HECServingFoundation.servingMeasureProfile(food),keys=value=>value.measures.map(item=>item.key);
  const spread=profile({id:'edge-spread',name:'Reviewed spread',physicalForm:'spread',units:{tsp:.05,g:.01},unitLabels:{tsp:'Teaspoon',g:'g'},nutrients:{calories:100}});
  const sliced=profile({id:'edge-sliced',name:'Reviewed bread',physicalForm:'sliced',units:{regularSlice:1,g:.01},unitLabels:{regularSlice:'Regular slice',g:'g'},nutrients:{calories:100}});
  const restaurantFood=window.HECFoodSources.foodRecords({sourceId:'kfc-au'}).find(food=>food.name==='Regular Chips'),restaurant=profile(restaurantFood);
  const result={spread:keys(spread),sliced:keys(sliced),restaurant:{name:restaurantFood?.name||'',measures:keys(restaurant)}};
  if(!result.spread.includes('tsp')||!result.sliced.includes('regularSlice')||!result.restaurant.measures.includes('portion'))throw new Error(`extended physical-form audit failed: ${JSON.stringify(result)}`);
  return result;
});}
async function amountScenario(page,url){
  await openLibrary(page,url);
  await submit(page,'Flora ProActiv Light',{button:false});
  const result=page.locator('[data-universal-result]').first();
  if(await result.count())await result.click();
  await page.locator('[data-gpr-measure]').first().waitFor({state:'visible'});
  const measure=page.locator('[data-gpr-measure]').first(),measureLabel=(await measure.innerText()).trim();
  await measure.click();
  const amount=page.locator('[data-gpr-amount]:visible');
  await amount.waitFor();
  const focus=await amount.evaluate(node=>({focused:document.activeElement===node,value:node.value,inputmode:node.getAttribute('inputmode'),enterkeyhint:node.getAttribute('enterkeyhint')}));
  if(!focus.focused||focus.value!==''||focus.inputmode!=='decimal'||focus.enterkeyhint!=='done')throw new Error(`amount focus ${JSON.stringify(focus)}`);
  const quick=await page.locator('[data-gpr-quick-amount]:visible').count();
  await amount.fill('1.75');
  const livePreview=(await page.locator('[data-gpr-amount-preview]:visible').innerText()).trim();
  if(!livePreview.includes('Nutrition preview'))throw new Error(`live nutrition preview missing: ${JSON.stringify(livePreview)}`);
  await amount.press('Enter');
  await page.locator('#food-entry-editor.active').waitFor({state:'visible'});
  const review=await page.locator('#food-entry-editor').innerText();
  if(!review.includes('1.75'))throw new Error(`decimal amount missing from Review: ${JSON.stringify(review.slice(0,1200))}`);
  return {measureLabel,quickAmounts:quick,focus,livePreview,review:true};
}

async function run(){
  const app=server();await new Promise(resolve=>app.listen(0,'127.0.0.1',resolve));const url=`http://127.0.0.1:${app.address().port}/index.html`,browser=await chromium.launch({headless:true,...(edge?{executablePath:edge}:{})}),viewports=process.env.HEC_EDGE_QUICK?[{width:390,height:844}]:[{width:390,height:844},{width:390,height:520},{width:430,height:932},{width:834,height:1194},{width:1194,height:834}],reports=[],pageErrors=[],consoleErrors=[],assetFailures=[],thirdPartyDiagnostics=[];
  try{
    for(const viewport of viewports){const page=await browser.newPage({viewport});page.on('pageerror',error=>pageErrors.push(`${viewport.width}x${viewport.height}: ${error.message}`));page.on('console',message=>{if(message.type()==='error')consoleErrors.push(`${viewport.width}x${viewport.height}: ${message.text()}`);});page.on('response',response=>{if(response.url().startsWith(url.replace('/index.html',''))&&response.status()>=400&&!/favicon\.ico/.test(response.url()))assetFailures.push(`${response.status()} ${response.url()}`);});reports.push(await genericScenario(page,url,'Hash Brown',['GENERIC','RESTAURANT','Hash Brown']));reports.push(await genericScenario(page,url,'Hamburger',['GENERIC','Burger']));reports.push(await genericScenario(page,url,'Chips',['GENERIC','Chips']));await page.close();}
    const interaction=await browser.newPage({viewport:{width:390,height:844}});const typingUrl=url;await openLibrary(interaction,typingUrl);const typing=await typeContinuously(interaction,'KFC');if(!typing.focused||typing.caret!==3||!typing.sameNode)throw new Error(`typing state ${JSON.stringify(typing)}`);const sources=await sourceScenarios(interaction,url),simpleSkip=await simpleSkipScenario(interaction,url);const amount=await amountScenario(interaction,url);await openLibrary(interaction,url);await submit(interaction,'McCain Hash Browns');await interaction.waitForTimeout(700);const branded=await layout(interaction,'McCain Hash Browns');if(!/McCain|Packaged|Broader/.test(branded.text))thirdPartyDiagnostics.push('The committed local OFF snapshot did not expose a McCain row in this isolated search run; barcode/panel handoff remained available.');const semantics=await interaction.evaluate(()=>{const candidates=window.HECFoodSources.foodRecords({sourceId:'kfc-au'}),quantity=['six Wicked Wings','KFC 6 Wicked Wings','two KFC 6 Wicked Wings','three hash browns','1.75 servings pizza','half a serving soup'].map(query=>({query,...window.HECSearchFoundation.parseQuantityLanguage(query,{candidates})})),solid=window.HECServingFoundation.servingMeasureProfile({id:'solid',name:'Reviewed potato patty',physicalForm:'solid-countable',units:{item:1,g:.01,mL:.01},unitLabels:{item:'Item',g:'g',mL:'mL'},nutrients:{calories:100}}),liquid=window.HECServingFoundation.servingMeasureProfile({id:'liquid',name:'Reviewed drink',physicalForm:'liquid',units:{mL:.01},unitLabels:{mL:'mL'},nutrients:{calories:20}}),sample=document.createElement('div');sample.className='guided-resolution-answer-summary';sample.innerHTML='<span><small>Source or context with a long label</small><b>Purchased Packaged / Frozen</b></span>';document.body.append(sample);const answer={flexWrap:getComputedStyle(sample).flexWrap,labelWhiteSpace:getComputedStyle(sample.querySelector('b')).whiteSpace};sample.remove();return {quantity,solid:{measures:solid.measures.map(item=>item.key),rejected:solid.rejectedMeasures.map(item=>item.key)},liquid:liquid.measures.map(item=>item.key),answer};});if(semantics.quantity[0].productVariantCount!==6||semantics.quantity[0].consumedQuantity!==1||semantics.quantity[2].consumedQuantity!==2||semantics.quantity[3].consumedQuantity!==3||semantics.quantity[4].consumedQuantity!==1.75||semantics.quantity[5].consumedQuantity!==.5)throw new Error('quantity browser audit failed');if(semantics.solid.measures.includes('mL')||!semantics.solid.rejected.includes('mL')||!semantics.liquid.includes('mL'))throw new Error('physical-form browser audit failed');if(semantics.answer.flexWrap!=='wrap'||semantics.answer.labelWhiteSpace!=='normal')throw new Error('answer-history browser audit failed');await interaction.close();
    const physicalPage=await browser.newPage({viewport:{width:390,height:844}});await openLibrary(physicalPage,url);const physicalForms=await physicalFormScenario(physicalPage);await physicalPage.close();
    const result={browser:edge?'Microsoft Edge':'Playwright Chromium fallback',viewports:viewports.map(viewport=>`${viewport.width}x${viewport.height}`),layoutScenarios:reports.length,typing,sources,simpleSkip,amount,semantics,physicalForms,pageErrors,consoleErrors,assetFailures,thirdPartyDiagnostics,failures:[]};if(pageErrors.length||consoleErrors.length||assetFailures.length)throw new Error(`browser diagnostics: page=${pageErrors.length}, console=${consoleErrors.length}, assets=${assetFailures.length}`);process.stdout.write(`${JSON.stringify(result,null,2)}\n`);return result;
  }finally{await browser.close();await new Promise(resolve=>app.close(resolve));}
}

if(require.main===module)run().catch(error=>{console.error(error);process.exit(1);});
module.exports={run};
