'use strict';
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),qa=require('./audit_physical_form_measures_edge'),t=require('./audit_brand_wave_edge'),{returningProfile}=require('./audit_navigation_startup_edge'),C=require('../food-catalogue'),B=require('../brand-au-catalogue');
const foods=B.files.flatMap(s=>require('../data/brand-au/'+s.path).records),byId=new Map(foods.map(f=>[f.id,f]));
const specifications=[['Aldi countable solid','off:4061463000316','aldi','piece',3,'retailer'],['Aldi Elmsbury solid','off:4088700087008','aldi','g',75,'brand'],['Woolworths house brand','off:9300633203061','woolworths','g',37,'brand'],['Coles house brand','off:9300601401826','coles','g',75,'brand'],['Retained liquid control','off:9300633473686','woolworths','mL',250,'brand']];
function diaryCount(){return Object.values(JSON.parse(localStorage.getItem(window.HEC_INSTALLATION.functionalStorageKey)||'{}').diary||{}).flat().length;}
async function review(page,sample,out){const [role,id,retailer,unit,amount,route]=sample,f=byId.get(id);assert(f,id);const key=C.canonicalKey(f);await t.fresh(page);if(route==='retailer'){await t.submit(page,retailer);await page.locator('[data-retailer-category="'+f.categoryId+'"]').click();await t.settled(page);for(let step=0;step<30;step++){const has=await page.evaluate(key=>[...document.querySelectorAll('[data-universal-result]')].some(n=>HECFoodCatalogue.canonicalKey(HEC_CANONICAL_CACHE_TEST.food(n.dataset.universalResult))===key),key);if(has)break;await page.locator('[data-retailer-more]').click();await t.settled(page);}}else await t.submit(page,f.brand+' '+f.name);
 await page.waitForFunction(key=>[...document.querySelectorAll('[data-universal-result]')].some(n=>{const f=HEC_CANONICAL_CACHE_TEST.food(n.dataset.universalResult);return f&&HECFoodCatalogue.canonicalKey(f)===key;}),key,{timeout:30000});const rendered=await page.evaluate(key=>[...document.querySelectorAll('[data-universal-result]')].find(n=>HECFoodCatalogue.canonicalKey(HEC_CANONICAL_CACHE_TEST.food(n.dataset.universalResult))===key).dataset.universalResult,key);await page.locator('[data-universal-result="'+rendered+'"]').first().click();const selected=await page.evaluate(()=>HEC_GUIDED_PRODUCT_TEST.food());assert.equal(C.canonicalKey(selected),key);assert.equal(selected.brand,f.brand);assert(C.privateLabelCollectionMembership(selected,retailer).length||C.sourceDeclaredRetailerMembership(selected,retailer).length||C.retailerMembership(selected,retailer).length,'retailer membership preserved '+id);const measure=page.locator('[data-gpr-measure="'+unit+'"]:visible');if(await measure.count())await measure.click();else assert(unit in selected.units);const input=page.locator('[data-gpr-amount]:visible');await input.waitFor();assert.equal(await input.inputValue(),'');await input.fill(String(amount));await input.press('Enter');await page.locator('#food-entry-editor.active').waitFor();assert.equal(await page.locator('.screen.active').count(),1);assert.equal(await page.locator('[data-gpr-amount]:visible').count(),0);assert.equal(await page.locator('#entry-unit').inputValue(),unit);assert.equal(Number(await page.locator('#entry-amount').inputValue()),amount);const factor=selected.units[unit]*amount,calories=selected.nutrients.calories*factor,energyKj=selected.nutrients.energyKj*factor,text=await page.locator('#entry-nutrition-preview').innerText();assert(text.includes(Math.round(calories).toLocaleString('en-AU')+' Cal'),text);assert(text.includes(Math.round(energyKj).toLocaleString('en-AU')+' kJ'),text);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await page.screenshot({path:path.join(out,'review-'+id.slice(4)+'.png'),fullPage:true});return {role,route,retailer,id:rendered,canonicalKey:key,gtin:selected.barcode,brand:selected.brand,name:selected.name,unit,amount,calories,energyKj,nutrients:selected.nutrients,measures:selected.units,reviewCount:1,diarySaves:0};}
async function run(out){fs.mkdirSync(out,{recursive:true});const report={pass:false,generation:require('../release-manifest.json').generation,viewport:{width:320,height:568},diagnostic:qa.evidence(),retailers:[],brands:[],concepts:[],reviews:[]};const {chromium,edge}=qa.browserTools(),browser=await chromium.launch({headless:true,executablePath:edge});let page;try{const context=await qa.contextFor({newContext:opts=>browser.newContext({...opts,isMobile:true,hasTouch:true})},report.viewport,report.diagnostic);await context.addInitScript(returningProfile);page=await context.newPage();await qa.openLibrary(page);const before=await page.evaluate(diaryCount);assert.equal(await page.locator('#food-search').inputValue(),'');
 for(const [name,total]of [['Woolworths',362],['Coles',417],['Aldi',222]]){await t.fresh(page);await t.submit(page,name);assert(await page.locator('[data-retailer-category]').count()>1);assert((await page.locator('#food-results').innerText()).includes('All Items ('+total+')'));await t.geometry(page);await page.screenshot({path:path.join(out,name.toLowerCase()+'-root.png'),fullPage:true});await page.locator('[data-retailer-category="*"]').click();await t.settled(page);assert(await page.locator('[data-universal-result]').count()<=20);report.retailers.push({name,total,root:true,paged:true,geometry:await t.geometry(page)});}
 report.houseBrandNavigation=[];
 for(const key of ['seasonspride','elmsbury']){await t.fresh(page);await t.submit(page,'Aldi');await page.locator('[data-retailer-brands]').click();await page.locator('[data-retailer-brand="'+key+'"]').waitFor();await t.geometry(page);await page.locator('[data-retailer-brand="'+key+'"]').click();await t.settled(page);const products=await page.evaluate(()=>[...document.querySelectorAll('[data-universal-result]')].map(n=>{const f=HEC_CANONICAL_CACHE_TEST.food(n.dataset.universalResult);return {id:f.id,key:HECFoodCatalogue.canonicalKey(f),name:f.name,brand:f.brand};}));assert(products.length);assert(products.every(f=>C.brandKey(f.brand)===key));await page.screenshot({path:path.join(out,'aldi-'+key+'.png'),fullPage:true});report.houseBrandNavigation.push({key,products,geometry:await t.geometry(page)});await page.locator('[data-retailer-back]').click();assert(await page.locator('[data-retailer-brand="'+key+'"]').count());await page.locator('[data-retailer-back]').click();assert(await page.locator('[data-retailer-category]').count());}
 report.categoryPlacements=[];
 for(const [category,id]of [['biscuits','off:4061459674262'],['biscuits','off:4061464959002'],['bread','off:4069365112922']]){await t.fresh(page);await t.submit(page,'Aldi');await page.locator('[data-retailer-category="'+category+'"]').click();await t.settled(page);assert(await page.locator('[data-universal-result="'+id+'"]').count(),id);report.categoryPlacements.push({id,category,geometry:await t.geometry(page)});await page.screenshot({path:path.join(out,'aldi-'+category+'.png'),fullPage:true});}
 report.aliasSearch=[];
 for(const query of ['Potato Jewel','Potato Jewels','Potato Gem','Potato Gems','Seasons Pride Potato Jewels']){await t.fresh(page);await t.submit(page,query);await page.waitForFunction(()=>[...document.querySelectorAll('[data-universal-result]')].some(n=>HEC_CANONICAL_CACHE_TEST.food(n.dataset.universalResult)?.barcode==='4061463000316'));const keys=await page.evaluate(()=>[...document.querySelectorAll('[data-universal-result]')].map(n=>HECFoodCatalogue.canonicalKey(HEC_CANONICAL_CACHE_TEST.food(n.dataset.universalResult))));assert.equal(new Set(keys).size,keys.length);report.aliasSearch.push({query,keys,geometry:await t.geometry(page)});}
 for(const query of ['Pepsi Max',"Kellogg's",'McCain','John West']){await t.fresh(page);await t.submit(page,query);assert(await page.locator('[data-universal-result],[data-au-brand-category]').count(),query);}
 for(const name of ['Seasons Pride','Elmsbury','Westacre Dairy','Hillcrest','Macro','Coles Finest','Coles Kitchen']){await t.fresh(page);await t.submit(page,name);assert(await page.locator('[data-au-brand-category]').count(),name);await page.locator('[data-au-brand-category="*"]').click();await t.settled(page);assert(await page.locator('[data-universal-result]').count());report.brands.push({name,geometry:await t.geometry(page)});}
 for(const [query,id]of [['Bread','bread'],['Milk','milk'],['Cereal','cereal'],['Hash Brown','hash-brown']]){await t.fresh(page);await t.submit(page,query);assert(await page.locator('[data-fc-base]').count(),query);const text=await page.locator('#food-results').innerText();if(query==='Milk')assert(!/milk chocolate|milk rolls/i.test(text));await t.geometry(page);report.concepts.push({query,baseFirst:true,text});}
 await t.fresh(page);await t.submit(page,'Big Mac');const exact=await page.locator('[data-universal-result] strong').allInnerTexts();assert.equal(exact[0],'Big Mac');report.concepts.push({query:'Big Mac',first:exact[0]});
 await t.fresh(page);await t.submit(page,'Bread');await page.locator('[data-fc-base]').click();await page.locator('[data-fc-answer="breadOrigin"][data-fc-value="commercial"]').click();await page.locator('[data-fc-answer="breadSource"][data-fc-value="supermarket"]').click();assert.deepEqual(await page.locator('[data-fc-answer="retailerIdentity"]').evaluateAll(ns=>ns.map(n=>n.dataset.fcValue)),['woolworths','coles','aldi']);await page.locator('[data-fc-answer="retailerIdentity"][data-fc-value="aldi"]').click();await t.settled(page);assert(await page.locator('[data-universal-result]').count());assert(!/cucumbers/i.test(await page.locator('#food-results').innerText()));report.breadNarrowing={pass:true,geometry:await t.geometry(page)};
 await t.fresh(page);await t.submit(page,'Hash Brown');await page.locator('[data-fc-base]').click();const choices=await page.locator('[data-fc-answer="sourceContext"]').evaluateAll(ns=>ns.map(n=>n.dataset.fcValue));assert(choices.includes('ready-to-eat')&&choices.includes('packaged-frozen'));report.hashBrownSources=choices;
 for(const s of specifications)report.reviews.push(await review(page,s,out));
 await t.fresh(page);await t.submit(page,'McCain Hash Browns');await page.waitForFunction(()=>[...document.querySelectorAll('[data-universal-result]')].some(n=>HEC_CANONICAL_CACHE_TEST.food(n.dataset.universalResult)?.barcode==='9310174025084'));const protectedId=await page.evaluate(()=>[...document.querySelectorAll('[data-universal-result]')].find(n=>HEC_CANONICAL_CACHE_TEST.food(n.dataset.universalResult)?.barcode==='9310174025084').dataset.universalResult);await page.locator('[data-universal-result="'+protectedId+'"]').first().click();const protectedFood=await page.evaluate(()=>HEC_GUIDED_PRODUCT_TEST.food());assert.equal(protectedFood.id,'woolworths-au:98299');const gram=page.locator('[data-gpr-measure="g"]:visible');if(await gram.count())await gram.click();await page.locator('[data-gpr-amount]:visible').fill('75');await page.locator('[data-gpr-amount]:visible').press('Enter');await page.locator('#food-entry-editor.active').waitFor();const preview=await page.locator('#entry-nutrition-preview').innerText();assert(preview.includes('130 Cal')&&preview.includes('543 kJ'));report.protectedMcCain={id:protectedFood.id,gtin:protectedFood.barcode,amount:75,unit:'g',calories:130,energyKj:543};await t.fresh(page);assert.equal(await page.locator('#food-search').inputValue(),'');assert.equal(await page.evaluate(diaryCount),before);report.diarySaves=0;qa.requireEvidence(report.diagnostic);report.pass=true;await context.close();return report;}catch(e){report.error={message:e.message,stack:e.stack};throw e;}finally{if(page&&!page.isClosed())await page.screenshot({path:path.join(out,'last-state.png'),fullPage:true}).catch(()=>{});await browser.close();fs.writeFileSync(path.join(out,'house-brand-rendered.json'),JSON.stringify(report,null,2)+'\n');}}
if(require.main===module)run(process.argv[2]).then(r=>console.log(JSON.stringify({pass:r.pass,reviews:r.reviews.length,diarySaves:r.diarySaves}))).catch(e=>{console.error(e);process.exitCode=1;});module.exports={run};
