
'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),qa=require('./audit_physical_form_measures_edge'),t=require('./audit_brand_wave_edge'),round=require('./audit_catalogue_round_two_edge'),C=require('../food-catalogue'),{returningProfile}=require('./audit_navigation_startup_edge');
async function run(out){fs.mkdirSync(out,{recursive:true});const {chromium,edge}=qa.browserTools(),browser=await chromium.launch({headless:true,executablePath:edge}),diagnostic=qa.evidence(),report={pass:false,generation:require('../release-manifest.json').generation,viewport:{width:320,height:568},retailers:[],diagnostic};try{const context=await qa.contextFor(browser,report.viewport,diagnostic);await context.addInitScript(returningProfile);const page=await context.newPage();await qa.openLibrary(page);
for(const [name,total] of [['Woolworths',923],['Coles',860],['Aldi',87]]){await t.fresh(page);await t.submit(page,name);assert.equal(await page.evaluate(id=>HECRetailerCatalogue.directory(id).total,name.toLowerCase()),total);await t.geometry(page);await page.screenshot({path:path.join(out,name+'-root.png'),fullPage:true});await page.locator('[data-retailer-category="other-food"]').click();await t.settled(page);assert(await page.locator('[data-universal-result]').count()>0);await t.geometry(page);await t.fresh(page);await t.submit(page,name);await page.locator('[data-retailer-category="*"]').click();await t.settled(page);assert.equal(await page.locator('[data-universal-result]').count(),20);report.retailers.push({name,total,otherFoodCategory:true,allItems:true,geometry:await t.geometry(page)});}
await t.fresh(page);await t.submit(page,'McCain');assert.equal(await page.evaluate(()=>HECBrandCatalogue.directory('mccain').total),108);await page.locator('[data-au-brand-category="*"]').click();await t.settled(page);assert(!/Barcode (null|undefined)/.test(await page.locator('#food-results').innerText()));await t.geometry(page);
await t.fresh(page);await t.submit(page,'Cereal');await page.locator('[data-fc-base]').click();await page.locator('[data-fc-answer="catalogueOrigin"][data-fc-value="commercial"]').click();await page.locator('[data-fc-answer="catalogueSource"][data-fc-value="brand"]').click();await page.locator('[data-fc-answer="brandIdentity"][data-fc-value="kelloggs"]').click();await t.settled(page);assert(await page.locator('.brand-catalogue [data-universal-result]').count());await t.geometry(page);
const food=require('../data/catalogue-round-two/approved-products.json').records.find(f=>f.id==='off:0224203717477');assert.equal(food.categoryId,'other-food');report.review=await round.review(page,{role:'New neutral-category food',food,key:C.canonicalKey(food),query:food.brand+' '+food.name,unit:'g',amount:37},out,320);await t.fresh(page);assert.equal(await page.locator('#food-search').inputValue(),'');qa.requireEvidence(diagnostic);report.pass=true;return report;}catch(e){report.error={message:e.message,stack:e.stack};throw e;}finally{await browser.close();fs.writeFileSync(path.join(out,'category-final.json'),JSON.stringify(report,null,2));}}
if(require.main===module)run(process.argv[2]).then(r=>console.log(JSON.stringify({pass:r.pass,review:r.review}))).catch(e=>{console.error(e);process.exitCode=1;});module.exports={run};
