'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{performance}=require('node:perf_hooks');
const {allProducts}=require('./audit_open_food_facts_au.js'),off=require('../off-catalogue.js'),serving=require('../serving-foundation.js'),guided=require('../guided-product-resolution.js');
const digest=value=>crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex');
const sample=(rows,n)=>[...rows].sort((a,b)=>digest('physical-form-0.6.33:'+a.id).localeCompare(digest('physical-form-0.6.33:'+b.id))).slice(0,n);
function stats(values){const sorted=[...values].sort((a,b)=>a-b);return {samples:sorted.length,median:sorted[Math.floor(sorted.length/2)]||0,p95:sorted[Math.min(sorted.length-1,Math.floor(sorted.length*.95))]||0,worst:sorted.at(-1)||0};}
function independentlyExpected(record){const cats=(record.categories||[]).map(x=>serving.norm(x)),text=serving.norm(record.name);if(cats.some(c=>/\bpowder(?:ed|s)?\b/.test(c)))return 'solid';if(cats.some(c=>/\b(?:biscuits?|crackers?|bars?|wafers?|croquettes?|nuggets?|patties|dumplings?|frozen meals?|potato preparations?|chocolates?|confectionery|crisps?|flours?|powders?)$/.test(c)))return 'solid';if(cats.some(c=>/\b(?:spreads?|nut butters?|margarines?)$/.test(c)))return 'spread';if(cats.some(c=>/\b(?:fruit juices?|soft drinks?|milks?|mineral waters?)$/.test(c)))return 'liquid';return '';}
function runAudit(output){const start=performance.now(),products=allProducts(),rawHash=digest(products),counts={products:0,forms:{},solidCountable:0,solidRawVolume:0,volumeMeasuresQuarantined:0,solidExposingMl:0,solidExposingL:0,solidExposingCup:0,liquidsRetainingVolume:0,spreadsRetainingHousehold:0,unknown:0,basisConflicts:0,safelyDowngraded:0,noValidMeasure:0},rows=[],classificationIssues=[],measureIssues=[],timings={catalogueProduct:[],physicalForm:[],portionChoice:[],compatibility:[],reviewEditing:[]};
  for(const record of products){const t0=performance.now(),rawForm=serving.physicalForm(record);timings.physicalForm.push(performance.now()-t0);const food=off.toFood(record),t1=performance.now(),profile=serving.servingMeasureProfile(food),elapsed=performance.now()-t1,form=profile.physicalForm,solid=!['liquid','spread','unknown'].includes(form),keys=profile.measures.map(m=>m.key),rawVolume=/(?:\d\s*(?:ml|l)\b|\b(?:millilitres?|litres?|liters?|cups?)\b)/i.test(`${record.quantity||''} ${record.servingSize||''}`),expected=independentlyExpected(record);timings.portionChoice.push(elapsed);counts.products++;counts.forms[form]=(counts.forms[form]||0)+1;if(solid){counts.solidCountable++;if(rawVolume)counts.solidRawVolume++;if(keys.includes('mL'))counts.solidExposingMl++;if(keys.includes('L'))counts.solidExposingL++;if(keys.includes('cup'))counts.solidExposingCup++;}if(form==='liquid'&&keys.includes('mL'))counts.liquidsRetainingVolume++;if(form==='spread'&&keys.some(k=>['tsp','tbsp'].includes(k)))counts.spreadsRetainingHousehold++;if(form==='unknown')counts.unknown++;if(profile.nutritionBasisConflict)counts.basisConflicts++;if(food.loggable===false&&record.nutritionCompleteness==='complete')counts.safelyDowngraded++;if(!keys.length)counts.noValidMeasure++;counts.volumeMeasuresQuarantined+=profile.rejectedMeasures.filter(m=>/volume|household/.test(m.rejectionReason)).length;
    if(expected==='solid'&&['liquid','unknown'].includes(form)||expected==='spread'&&form!=='spread'||expected==='liquid'&&form!=='liquid')classificationIssues.push({id:record.id,name:record.name,categories:record.categories,expected,actual:form,rawForm});
    if(solid&&keys.some(k=>['mL','L','cup'].includes(k)))measureIssues.push({id:record.id,form,keys});
    timings.catalogueProduct.push(performance.now()-t0);rows.push({id:record.id,name:record.name,brand:record.brand,categories:record.categories,servingSize:record.servingSize,quantity:record.quantity,form,rawVolume,complete:record.nutritionCompleteness==='complete',keys,rejected:profile.rejectedMeasures.map(m=>({key:m.key,reason:m.rejectionReason})),defaultMeasure:profile.preferredMeasure,sourceNutritionBasis:food.sourceNutritionBasis});
  }
  const selectedIds=new Set(),take=(pool,n)=>{const picked=sample(pool.filter(row=>!selectedIds.has(row.id)),n);for(const row of picked)selectedIds.add(row.id);return picked;},groups={solid:take(rows.filter(r=>!['liquid','spread','unknown'].includes(r.form)),200),liquid:take(rows.filter(r=>r.form==='liquid'),100),spread:take(rows.filter(r=>r.form==='spread'),50),slicedCountable:take(rows.filter(r=>['sliced','countable','solid-countable'].includes(r.form)),50),unknownIncomplete:take(rows.filter(r=>r.form==='unknown'||!r.complete),50)},lookup=new Map(products.map(r=>[r.id,r])),random=[];
  for(const [group,items] of Object.entries(groups)){assert.equal(items.length,{solid:200,liquid:100,spread:50,slicedCountable:50,unknownIncomplete:50}[group]);for(const row of items){const food=off.toFood(lookup.get(row.id)),profile=serving.servingMeasureProfile(food),session=guided.createSession([food],food.name,{intent:{kind:'exact-product'}}),t=performance.now(),edited=serving.servingMeasureProfile(profile.resolvedFood);timings.reviewEditing.push(performance.now()-t);const tf=performance.now();serving.finalCompatibilityFirewall(structuredClone(food),profile.measures);timings.compatibility.push(performance.now()-tf);if(!['liquid','spread','unknown'].includes(profile.physicalForm)){const contaminated=serving.servingMeasureProfile({...food,units:{...food.units,mL:.01,L:10,cup:2.5}});assert(!contaminated.measures.some(m=>['mL','L','cup'].includes(m.key)));for(const key of ['mL','L','cup'])assert(contaminated.rejectedMeasures.some(m=>m.key===key));}assert(!session.amount);assert(!session.consumedPortion);assert.deepEqual(edited.measures.map(m=>m.key),profile.measures.map(m=>m.key));assert(['product-identity','serving-measure'].includes(session.stage),`Unexpected stage ${session.stage}`);if(!profile.measures.length)assert.equal(food.loggable,false);random.push({group,id:row.id,form:row.form,keys:row.keys,stage:session.stage,exactProduct:session.exactProduct?.id||null,completion:session.identityIssue||''});}}
  assert.equal(new Set(random.map(row=>row.id)).size,450);const selectors={frozen:r=>r.complete&&r.form!=='liquid'&&r.form!=='unknown'&&r.categories?.some(c=>/frozen/i.test(c)),biscuit:r=>r.complete&&r.categories?.some(c=>/biscuits|crackers/i.test(c)),bar:r=>r.complete&&r.categories?.some(c=>/\bbars\b/i.test(c)),milk:r=>r.complete&&r.form==='liquid'&&r.categories?.some(c=>/^(?:en:)?milks?$/i.test(c)),juice:r=>r.complete&&r.form==='liquid'&&r.categories?.some(c=>/juices/i.test(c)),nutSpread:r=>r.complete&&r.form==='spread'&&r.categories?.some(c=>/nut butter|nut spread|peanut butter|seed butter/i.test(c))},controls=Object.fromEntries(Object.entries(selectors).map(([key,fn])=>[key,sample(rows.filter(r=>fn(r)&&/^[a-z]/i.test(r.name)),1)[0]]));
  assert.equal(digest(products),rawHash,'Audit mutated source records');const report={pass:!classificationIssues.length&&!measureIssues.length,seed:'physical-form-0.6.33',rawCatalogueSha256:rawHash,counts,classificationIssues,measureIssues,random,randomDistinctProducts:new Set(random.map(row=>row.id)).size,randomGroupCounts:Object.fromEntries(Object.entries(groups).map(([k,v])=>[k,v.length])),controls,unrelatedVolumeMetadataControls:sample(rows.filter(r=>r.rawVolume&&!['liquid','spread','unknown'].includes(r.form)),20),performance:Object.fromEntries(Object.entries(timings).map(([k,v])=>[k,stats(v)])),durationMs:performance.now()-start,rows};if(output){fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,JSON.stringify(report,null,2));}return report;}
if(require.main===module){try{const r=runAudit(process.argv[2]);console.log(JSON.stringify({...r,rows:undefined,random:undefined},null,2));if(!r.pass)process.exitCode=1;}catch(e){console.error(e);process.exitCode=1;}}
module.exports={runAudit,stats,sample,independentlyExpected};
