#!/usr/bin/env node
"use strict";
const fs=require("fs"),path=require("path"),{performance}=require("perf_hooks");
const ROOT=path.resolve(__dirname,".."),DATA=path.join(ROOT,"data","open-food-facts-au");
global.fetch=async url=>{const file=path.resolve(ROOT,String(url).replace(/^\.\//,""));try{return{ok:true,status:200,json:async()=>JSON.parse(fs.readFileSync(file,"utf8"))};}catch{return{ok:false,status:404,json:async()=>({})};}};
const api=require(path.join(ROOT,"off-catalogue.js"));
const read=relative=>JSON.parse(fs.readFileSync(path.join(DATA,relative),"utf8"));
function allProducts(manifest=read("manifest.json")){return manifest.productShards.flatMap(item=>read(item.path).products);}
function sampleEvenly(values,count){const out=[];for(let i=0;i<Math.min(count,values.length);i++)out.push(values[Math.floor(i*values.length/Math.min(count,values.length))]);return out;}
async function queryReport(queries){const out={};for(const query of queries){const result=await api.search(query,{limit:5});out[query]={count:result.total,examples:result.foods.map(food=>`${food.brand} — ${food.name}`)};}return out;}
async function retrievalAudit(products,count=1000){const eligible=products.filter(x=>x.name&&x.brand),sample=sampleEvenly(eligible,count);let found=0,top10=0,textTop10=0,barcodeFallback=0;const failures=[];for(const product of sample){const query=`${product.brand} ${product.name}`,result=await api.search(query,{limit:10});const index=result.foods.findIndex(food=>food.id===product.id);if(index>=0){found++;top10++;textTop10++;continue;}const exact=await api.lookupBarcode(product.barcode);if(exact?.id===product.id){found++;top10++;barcodeFallback++;}else if(failures.length<20)failures.push({id:product.id,query,barcode:product.barcode});}return{sampled:sample.length,found,top10,textTop10,barcodeFallback,retrievalPercent:+(found*100/sample.length).toFixed(2),top10Percent:+(top10*100/sample.length).toFixed(2),textTop10Percent:+(textTop10*100/sample.length).toFixed(2),failures};}
function historicalBrands(manifest){return manifest.brandShards.flatMap(shard=>Object.entries(read(shard.path).brands).map(([key,value])=>({key,...value})));}
function expectedBrandFamily(brand,brands){
  const registry=require('../entity-registry'),spelling=value=>registry.brandSearchText(value).replace(/\s/g,''),evidence=registry.brandSearchEquivalences.find(record=>record.spellings.some(name=>spelling(name)===spelling(brand.name))),allowed=new Set((evidence?.spellings||[brand.name]).map(spelling));
  return {evidence:evidence?.type||'exact-source-spelling',brands:brands.filter(entry=>allowed.has(spelling(entry.name)))};
}
async function brandAudit(manifest,count=100){
  const brands=historicalBrands(manifest),candidates=brands.filter(value=>value.refs.length>=2&&value.refs.length<=500).sort((a,b)=>a.key.localeCompare(b.key)),sample=sampleEvenly(candidates,count),shards=new Map(),rawFor=ref=>{const [key,index]=ref.split(':');if(!shards.has(key))shards.set(key,read('products/'+key+'.json').products);return shards.get(key)[Number(index)];};
  let complete=0,contamination=0,exactQueries=0;const failures=[],families=[];
  for(const brand of sample){
    const family=expectedBrandFamily(brand,brands),expected=new Map(family.brands.flatMap(entry=>entry.refs).map(ref=>{const raw=rawFor(ref);return [raw.id,raw];})),foods=[];let total=0;
    for(let offset=0;;offset+=500){const page=await api.search(brand.name,{offset,limit:500});total=page.total;foods.push(...page.foods);if(!page.hasMore)break;}
    const actual=new Set(foods.map(food=>food.id)),missing=[...expected.keys()].filter(id=>!actual.has(id)),unexpected=foods.filter(food=>!expected.has(food.id)).map(food=>food.id),changed=foods.filter(food=>{const raw=expected.get(food.id);return raw&&(food.barcode!==raw.barcode||food.brand!==raw.brand||food.sourceName!==raw.name||require('../food-catalogue').canonicalKey(food)!=='barcode:'+raw.barcode);}).map(food=>food.id);
    const probe=rawFor(brand.refs[0]),query=brand.name+' '+probe.name,exact=await api.search(query,{limit:500});exactQueries++;const exactMissing=!exact.foods.some(food=>food.id===probe.id);
    contamination+=unexpected.length;
    const passed=!missing.length&&!unexpected.length&&!changed.length&&actual.size===foods.length&&total===expected.size&&!exactMissing;
    if(passed)complete++;else failures.push({brand:brand.name,historicalExpected:brand.refs.length,expected:expected.size,total,loaded:foods.length,missing,unexpected,changed,exactMissing:exactMissing?{query,id:probe.id}:null});
    families.push({query:brand.name,evidence:family.evidence,historicalCount:brand.refs.length,expected:expected.size,returned:foods.length,complete:passed});
  }
  return {sampled:sample.length,complete,contamination,exactQueries,failures:failures.slice(0,20),families};
}
async function performanceAudit(products,count=500){const sample=sampleEvenly(products.filter(x=>x.name),count),timings=[];for(const product of sample){const query=[product.brand,product.name].filter(Boolean).join(" "),start=performance.now();await api.search(query,{limit:10});timings.push({milliseconds:performance.now()-start,query,id:product.id});}timings.sort((a,b)=>a.milliseconds-b.milliseconds);const times=timings.map(item=>item.milliseconds),worst=timings[timings.length-1];return{queries:times.length,medianMs:+times[Math.floor(times.length*.5)].toFixed(3),p95Ms:+times[Math.floor(times.length*.95)].toFixed(3),worstMs:+worst.milliseconds.toFixed(3),worstQuery:worst.query,worstProductId:worst.id};}
async function runAudit(){const manifest=read("manifest.json"),products=allProducts(manifest),queries=await queryReport(["Flora","Meadow Lea","MeadowLea","Vegemite","Kellogg's","Arnott's","milk","cereal","peanut butter","dim sim","mini dim sim"]),retrieval=await retrievalAudit(products),brands=await brandAudit(manifest),performance=await performanceAudit(products);return{source:{snapshot:manifest.sourceSnapshotDate,sha256:manifest.sourceSha256,country:manifest.scope,global:manifest.globalRecordsScanned,australian:manifest.australianSourceRecords},size:{imported:manifest.importedProducts,searchable:manifest.searchableProducts,complete:manifest.completeNutrition,partial:manifest.partialNutrition,identityOnly:manifest.identityOnly,brands:manifest.uniqueBrands,validGtins:manifest.validGtins},queries,retrieval,brands,performance,files:{generatedMB:+(manifest.generatedBytes/1048576).toFixed(2),shards:manifest.generatedShardCount,largestMB:+(manifest.largestShardBytes/1048576).toFixed(3),manifestKB:+(fs.statSync(path.join(DATA,"manifest.json")).size/1024).toFixed(2)}};}
if(require.main===module)runAudit().then(value=>{console.log(JSON.stringify(value,null,2));if(value.retrieval.top10Percent<98||value.brands.complete!==value.brands.sampled||value.brands.contamination)process.exitCode=1;}).catch(error=>{console.error(error);process.exit(1);});
module.exports={ROOT,DATA,api,read,allProducts,sampleEvenly,historicalBrands,expectedBrandFamily,queryReport,retrievalAudit,brandAudit,performanceAudit,runAudit};
