'use strict';

const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const ROOT=path.resolve(__dirname,'..'),ORIGIN='https://mlwes-hec-test.github.io';
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.webmanifest':'application/manifest+json','.ico':'image/x-icon','.mp3':'audio/mpeg'};
function browserTools(){const modules=process.env.HEC_WORKSPACE_NODE_MODULES||path.resolve(path.dirname(process.execPath),'../node_modules'),edge=['C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe','C:/Program Files/Microsoft/Edge/Application/msedge.exe'].find(fs.existsSync);assert(edge,'Microsoft Edge is required');return {chromium:require(path.join(modules,'playwright')).chromium,edge};}
async function contextFor(browser,viewport,report){const context=await browser.newContext({viewport,serviceWorkers:'block'});const routed=new Set();
  context.on('request',r=>{if(new URL(r.url()).origin===ORIGIN)report.sameOriginRequests++;});
  context.on('page',p=>{p.on('pageerror',e=>report.pageErrors.push(e.message));p.on('console',m=>{if(m.type()==='error')report.consoleErrors.push({text:m.text(),url:m.location().url});else if(m.type()==='warning')report.warnings.push(m.text());});});
  context.on('requestfailed',r=>{const item={url:r.url(),error:r.failure()?.errorText};(new URL(r.url()).origin===ORIGIN?report.failedAssets:report.external).push(item);});
  context.on('response',r=>{if(new URL(r.url()).origin!==ORIGIN)return;if(!routed.has(r.request())||r.fromServiceWorker())report.liveFallthrough++;if(r.status()>=400)report.failedAssets.push({url:r.url(),status:r.status()});});
  await context.route('**/*',async route=>{const request=route.request(),url=new URL(request.url());if(url.origin!==ORIGIN){report.external.push({url:request.url(),action:'aborted'});await route.abort('blockedbyclient');return;}try{const decoded=decodeURIComponent(url.pathname);assert(!decoded.includes('\\')&&!decoded.includes('\0')&&!decoded.split('/').includes('..'),'Unsafe path');let relative=decoded==='/'?'index.html':decoded.replace(/^\/+/, '');if(relative==='installation-config.js'||relative==='manifest.webmanifest')relative='deployment/test/'+relative;const file=path.resolve(ROOT,relative);assert(file.startsWith(ROOT+path.sep)&&fs.statSync(file).isFile(),'Missing local asset');assert(fs.realpathSync(file).startsWith(fs.realpathSync(ROOT)+path.sep),'Unsafe symlink');const contentType=mime[path.extname(file)];assert(contentType,'Unknown asset MIME type');const body=fs.readFileSync(file);routed.add(request);report.routes.push({url:request.url(),file,contentType,sha256:crypto.createHash('sha256').update(body).digest('hex')});await route.fulfill({status:200,contentType,headers:{'Cache-Control':'no-store'},body});report.localFulfilled++;}catch(e){report.failedAssets.push({url:request.url(),error:e.message});await route.fulfill({status:502,body:e.message});}});return context;
}
function evidence(){return {sameOriginRequests:0,localFulfilled:0,liveFallthrough:0,pageErrors:[],consoleErrors:[],warnings:[],failedAssets:[],external:[],routes:[]};}
function requireEvidence(r){const aborts=new Set(r.external.filter(e=>e.action==='aborted').map(e=>e.url)),applicationErrors=r.consoleErrors.filter(e=>!(aborts.has(e.url)&&/^Failed to load resource: net::ERR_BLOCKED_BY_CLIENT/.test(e.text)));assert.equal(r.sameOriginRequests,r.localFulfilled);assert.equal(r.liveFallthrough,0);assert.deepEqual(r.pageErrors,[]);assert.deepEqual(applicationErrors,[]);assert.deepEqual(r.failedAssets,[]);}
async function openLibrary(page){await page.goto(ORIGIN+'/',{waitUntil:'load',timeout:30000});await page.waitForFunction(()=>window.HEC_SEARCH_SESSION_TEST&&typeof window.openAlpha05Feature==='function');await page.evaluate(()=>window.openAlpha05Feature('food-library',{freshSearch:true}));await page.locator('#food-search').waitFor({state:'visible'});}
async function selectCatalogueProduct(page,{query,id}){const input=page.locator('#food-search');await input.fill(query);await page.waitForFunction(id=>window.HECOpenFoodFactsAU?.getLoaded(id),id,{timeout:30000});await input.press('Enter');await page.locator(`[data-universal-result="${id}"]`).waitFor({state:'visible'});const before=await page.evaluate(id=>{const food=window.HECOpenFoodFactsAU.getLoaded(id),profile=window.HECServingFoundation.servingMeasureProfile(food);return {food,form:window.HECServingFoundation.physicalForm(food),profile};},id);await page.locator(`[data-universal-result="${id}"]`).click();await page.waitForTimeout(100);const rendered=await page.evaluate(()=>({origin:location.origin,role:window.HEC_APP.installationRole,guide:window.HEC_GUIDED_PRODUCT_TEST.ui(),measures:[...document.querySelectorAll('[data-gpr-measure]')].map(n=>({key:n.dataset.gprMeasure,label:n.innerText})),text:document.querySelector('#food-results')?.innerText,overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth+1}));return {before,rendered};}
async function regression({outputDirectory=fs.mkdtempSync(path.join(os.tmpdir(),'hec-measure-edge-'))}={}){fs.mkdirSync(outputDirectory,{recursive:true});const report={...evidence(),outputDirectory,pass:false};const {chromium,edge}=browserTools(),browser=await chromium.launch({headless:true,executablePath:edge});let page;try{const context=await contextFor(browser,{width:390,height:844},report);page=await context.newPage();await openLibrary(page);report.product=await selectCatalogueProduct(page,{query:'McCain Hash Browns',id:'off:9310174025084'});assert.equal(report.product.rendered.guide.product,'Hash Browns');assert(!report.product.rendered.measures.some(m=>['mL','L','cup'].includes(m.key)),'Real catalogue solid product exposes cup/L/mL');assert(!report.product.rendered.overflow);requireEvidence(report);report.pass=true;return report;}catch(e){report.error={message:e.message,stack:e.stack};throw e;}finally{if(page)await page.screenshot({path:path.join(outputDirectory,'rendered.png'),fullPage:true});await browser.close();fs.writeFileSync(path.join(outputDirectory,'regression.json'),JSON.stringify(report,null,2));}}
if(require.main===module)regression({outputDirectory:process.argv[2]}).then(r=>console.log(JSON.stringify({pass:r.pass,outputDirectory:r.outputDirectory,measures:r.product.rendered.measures}))).catch(e=>{console.error(e);process.exitCode=1;});
module.exports={ROOT,ORIGIN,browserTools,contextFor,evidence,requireEvidence,openLibrary,selectCatalogueProduct,regression};
