'use strict';
const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict');
const qa=require('./audit_physical_form_measures_edge'),{returningProfile}=require('./audit_navigation_startup_edge'),{fixture}=require('../tests/fixtures/my-foods-management');
const clone=x=>JSON.parse(JSON.stringify(x));
async function library(p){await p.locator('#home [data-room="database"]').click();await p.locator('[data-library-tab="saved"]').click();}
function removeButton(p,id){return p.locator('#food-results [data-food-save]').and(p.locator(`[data-food-save="${id}"]`));}
async function state(p){return p.evaluate(()=>({ext:JSON.parse(localStorage.getItem(HEC_APP.functionalStorageKey)),protected:JSON.parse(localStorage.getItem(HEC_APP.protectedLibraryKey)),screen:document.querySelector('.screen.active')?.id}));}
async function mirror(p,id,exists){await p.waitForFunction(async({id,exists})=>{const db=await new Promise((resolve,reject)=>{const r=indexedDB.open(HEC_APP.mirrorDatabaseName,1);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});try{const raw=await new Promise((resolve,reject)=>{const r=db.transaction('kv').objectStore('kv').get(HEC_APP.functionalStorageKey);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});const e=JSON.parse(raw||'{}');return (e.customFoods||[]).some(f=>f.id===id)===exists&&(exists||(e.savedFoodIds||[]).every(x=>x!==id));}finally{db.close();}},{id,exists});}
async function review(p,id,amount,calories){const row=removeButton(p,id).locator('..');await row.locator('.resource-main').tap();await p.locator('#food-entry-editor.active').waitFor();assert.equal(await p.locator('.screen.active').count(),1);const units=await p.locator('#entry-unit option').evaluateAll(ns=>ns.map(n=>n.value));const selected=await p.locator('#entry-unit').inputValue();assert.notEqual(selected,'kg');assert.notEqual(units[0],'kg');if(id==='legacy-first')assert(!units.includes('kg'));else assert.equal(selected,'g');const locked=!(await p.locator('#entry-unit').isVisible());if(locked)assert.equal(selected,'serve');else await p.locator('#entry-unit').selectOption('g');const actualAmount=locked?amount/100:amount;await p.locator('#entry-amount').fill(String(actualAmount));await p.locator('#entry-amount').dispatchEvent('input');assert.match(await p.locator('#entry-nutrition-preview').innerText(),new RegExp(calories+' Cal'));await p.locator('#food-entry-editor').getByRole('button',{name:'← Back',exact:true}).click();return {id,amount:actualAmount,unit:locked?'serve':'g',equivalentGrams:amount,calories,units};}
async function run({outputDirectory=fs.mkdtempSync(path.join(os.tmpdir(),'hec-my-foods-'))}={}){
  fs.mkdirSync(outputDirectory,{recursive:true});const report={pass:false,diagnostic:qa.evidence(),removals:[],reviews:[],viewport:{width:390,height:844}},seed=fixture(),{chromium,edge}=qa.browserTools(),browser=await chromium.launch({headless:true,executablePath:edge});let p;
  try{
    const c=await qa.contextFor({newContext:o=>browser.newContext({...o,isMobile:true,hasTouch:true})},report.viewport,report.diagnostic);
    await c.addInitScript(returningProfile);await c.addInitScript(seed=>{if(location.origin!=='https://mlwes-hec-test.github.io'||localStorage.getItem('hec-management-seeded'))return;localStorage.setItem('healthyEatingCompanionTestAlpha06Functional',JSON.stringify(seed.ext));localStorage.setItem('healthyEatingCompanionTestProtectedLibrary',JSON.stringify(seed.protectedLibrary));localStorage.setItem('hec-management-seeded','yes');},seed);
    p=await c.newPage();await p.clock.setFixedTime(new Date('2026-09-10T02:00:00.000Z'));await p.goto(qa.ORIGIN+'/');await p.locator('#home [data-room="diary"]').click();await p.locator('[data-entry-edit="diary-sentinel"]').click();await p.locator('#food-entry-editor.active').waitFor();report.legacyMass={unit:await p.locator('#entry-unit').inputValue(),amount:await p.locator('#entry-amount').inputValue(),nutrition:await p.locator('#entry-nutrition-preview').innerText()};assert.equal(report.legacyMass.unit,'g');assert.equal(Number(report.legacyMass.amount),500);assert.match(report.legacyMass.nutrition,/615 Cal/);await p.screenshot({path:path.join(outputDirectory,'legacy-mass-review.png'),fullPage:true});await p.locator('#food-entry-editor [data-go="home"]').click();await library(p);report.before=await state(p);const unkeyed=report.before.ext.customFoods.find(f=>f.name===seed.ext.customFoods.at(-1).name);assert(unkeyed.id);report.migratedId=unkeyed.id;
    // Existing explicit IDs and nutrition survive the normal load/migration path.
    for(const food of seed.ext.customFoods.filter(f=>f.id)){const loaded=report.before.ext.customFoods.find(f=>f.id===food.id);for(const key of ['id','name','nutrients','units'])assert.deepEqual(loaded[key],food[key]);}
    assert.equal(await removeButton(p,'custom-current').innerText(),'✓');assert.match(await removeButton(p,'custom-current').getAttribute('aria-label'),/Remove from My Foods/);
    report.reviews.push(await review(p,'custom-current',100,123));report.reviews.push(await review(p,'legacy-first',500,615));
    await p.screenshot({path:path.join(outputDirectory,'my-foods-before-remove.png'),fullPage:true});
    const unchanged=clone((await state(p)).ext.customFoods.find(f=>f.id==='legacy-first'));
    for(const id of ['legacy-second','custom-current',unkeyed.id,'protected-only']){
      const before=await state(p),record=before.ext.customFoods.find(f=>f.id===id);assert(record);const button=removeButton(p,id);assert.equal(await button.count(),1);await button.scrollIntoViewIfNeeded();
      const hit=await button.evaluate(n=>{const r=n.getBoundingClientRect(),target=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return n===target||n.contains(target);});assert(hit,'Removal control must be unobscured');
      const eventStart=await p.evaluate(()=>__navigationEvents.length);if(id==='custom-current'){await button.focus();await button.press('Enter');}else await button.tap();
      assert.equal(await p.locator('#food-entry-editor.active').count(),0,'Remove must not open Review');assert.equal(await p.locator('#food-library.active').count(),1);
      await mirror(p,id,false);const after=await state(p);for(const store of [after.ext,after.protected]){assert(!store.customFoods.some(f=>f.id===id));assert(!store.savedFoodIds.includes(id));}
      assert.deepEqual(after.ext.customFoods.find(f=>f.id==='legacy-first'),unchanged,'Same-name record must remain byte-for-byte unchanged');
      assert.deepEqual(after.ext.diary,before.ext.diary);assert.deepEqual(after.ext.recipes,before.ext.recipes);
      await p.locator('[data-library-tab="all"]').click();await p.locator('[data-library-tab="saved"]').click();assert.equal(await removeButton(p,id).count(),0);
      const events=await p.evaluate(start=>__navigationEvents.slice(start),eventStart);assert(events.some(e=>e.trusted&&e.type==='click'&&e.target.includes('data-food-save')));report.removals.push({id,name:record.name,events,isolated:true,navigationAbsent:true,primaryAbsent:true,protectedAbsent:true,mirrorAbsent:true});
    }
    // Existing Undo must restore the exact object and both persistence copies.
    await removeButton(p,'legacy-first').tap();await mirror(p,'legacy-first',false);await p.locator('#a05-toast-action').click();await mirror(p,'legacy-first',true);const undone=await state(p);assert.deepEqual(undone.ext.customFoods.find(f=>f.id==='legacy-first'),unchanged);assert.deepEqual(undone.protected.customFoods.find(f=>f.id==='legacy-first'),unchanged);report.undo=true;
    // Non-custom saved references keep their original save/remove/undo contract.
    await removeButton(p,'online-bookmark').tap();assert.equal(await removeButton(p,'online-bookmark').count(),0);await p.locator('#a05-toast-action').click();assert.equal(await removeButton(p,'online-bookmark').count(),1);assert((await state(p)).protected.savedFoodIds.includes('online-bookmark'));await removeButton(p,'online-bookmark').tap();report.bookmark=true;
    await p.reload();await library(p);const reloaded=await state(p);for(const {id} of report.removals)assert.equal(await removeButton(p,id).count(),0);assert.equal(await removeButton(p,'online-bookmark').count(),0);assert.deepEqual(reloaded.ext.customFoods.find(f=>f.id==='legacy-first'),unchanged);report.reload=true;
    await p.close();p=await c.newPage();await p.clock.setFixedTime(new Date('2026-09-10T02:00:00.000Z'));await p.goto(qa.ORIGIN+'/');await library(p);const reopened=await state(p);for(const {id} of report.removals)assert.equal(await removeButton(p,id).count(),0);assert.deepEqual(reopened.ext.customFoods.find(f=>f.id==='legacy-first'),unchanged);report.reopen=true;
    report.reviews.push(await review(p,'legacy-first',500,615));report.final=await state(p);assert.deepEqual(report.final.ext.diary,report.before.ext.diary);assert.deepEqual(report.final.ext.recipes,report.before.ext.recipes);assert.deepEqual(await p.evaluate(()=>__navigationRejections),[]);assert(report.removals.every(r=>r.events.some(e=>e.trusted&&e.type==='click'&&e.target.includes('data-food-save'))));
    await p.screenshot({path:path.join(outputDirectory,'my-foods-after-reopen.png'),fullPage:true});qa.requireEvidence(report.diagnostic);report.pass=true;return report;
  }catch(e){report.error={message:e.message,stack:e.stack};if(p&&!p.isClosed())await p.screenshot({path:path.join(outputDirectory,'failure.png'),fullPage:true}).catch(()=>{});throw e;}finally{await browser.close();fs.writeFileSync(path.join(outputDirectory,'my-foods-management.json'),JSON.stringify(report,null,2));}
}
module.exports={run};if(require.main===module)run({outputDirectory:process.argv[2]}).then(r=>console.log(JSON.stringify({pass:r.pass,removals:r.removals,reload:r.reload,reopen:r.reopen,undo:r.undo}))).catch(e=>{console.error(e);process.exitCode=1;});
