'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),qa=require('./audit_physical_form_measures_edge'),{returningProfile}=require('./audit_navigation_startup_edge'),f=require('../tests/fixtures/barcode-confirmation');
const output='data/barcode-panel-repair/late-central';
async function run(){fs.mkdirSync(output,{recursive:true});const r={pass:false,diagnostic:qa.evidence(),actions:[]},{chromium,edge}=qa.browserTools(),browser=await chromium.launch({headless:true,executablePath:edge});let p;
try{const c=await qa.contextFor(browser,{width:390,height:844},r.diagnostic);await c.addInitScript(returningProfile);await c.route('**/api/v2/product/**',route=>route.fulfill({json:{status:1,product:f.product}}));p=await c.newPage();await p.goto(qa.ORIGIN+'/');await p.waitForFunction(()=>HECRelease.snapshot().state==='ready');
const scan=async code=>{await p.evaluate(()=>openAlpha05Feature('scan-centre'));await p.locator('[data-scan-mode="barcode"]').click();await p.locator('#manual-barcode-details').evaluate(n=>n.open=true);await p.locator('#scan-barcode-input').fill(code);await p.locator('#lookup-barcode').click();await p.locator('[data-compare-barcode-panel]').waitFor();};
for(const action of ['capture-new-active','capture-retry']){await scan(f.code);await p.locator('[data-compare-barcode-panel]').click();await p.evaluate(()=>{window.__done=false;window.Tesseract={createWorker:async()=>({setParameters:async()=>{},recognize:()=>new Promise(resolve=>window.__resolveOld=resolve),terminate:async()=>window.__done=true})};});const png=await p.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=100;canvas.height=100;return canvas.toDataURL().split(',')[1];});await p.locator('#scan-image').setInputFiles({name:'synthetic.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});await p.locator('#run-label-ocr').click();await p.waitForFunction(()=>typeof __resolveOld==='function');await p.locator('#'+action).click();await p.evaluate(text=>__resolveOld({data:{text,confidence:99}}),f.badText);await p.waitForFunction(()=>__done);assert.equal(await p.locator('#ocr-fat').inputValue(),action==='capture-retry'?'5.3':'');assert.equal(await p.locator('#scan-image').inputValue(),'');if(action==='capture-retry'){assert.equal(await p.locator('#ocr-food-name').inputValue(),f.food.name);assert.match(await p.locator('#ocr-progress').innerText(),/New reading attempt/);}else assert.match(await p.locator('#scan-mode-copy').innerText(),/New capture/);await p.screenshot({path:path.join(output,action+'.png'),fullPage:true});await p.locator('#capture-cancel').click();r.actions.push({action,lateIgnored:true});}
await scan('9310174025084');assert.match(await p.locator('#scan-food-preview').innerText(),/McCain/i);const original=await p.evaluate(()=>JSON.stringify(HEC_CANONICAL_CACHE_TEST.food('woolworths-au:98299')));await p.locator('#barcode-package-confirmed').check();assert(await p.locator('[data-capture-source="barcode"][data-capture-action="both"]').isEnabled(),await p.locator('#scan-review-status').innerText());await p.locator('[data-capture-source="barcode"][data-capture-action="both"]').click();assert.equal(await p.locator('#capture-amount').inputValue(),'');await p.locator('#capture-amount-unit').selectOption('g');await p.locator('#capture-amount').fill('75');await p.screenshot({path:path.join(output,'central-amount.png'),fullPage:true});await p.locator('#capture-amount-review').click();await p.locator('#food-entry-editor.active').waitFor();const preview=await p.locator('#entry-nutrition-preview').innerText();assert(preview.includes('130 Cal')&&preview.includes('543 kJ'),preview);assert.equal(await p.locator('.screen.active').count(),1);await p.locator('#entry-meal').selectOption('Lunch');await p.locator('#save-food-entry').click();assert.equal(await p.evaluate(()=>JSON.stringify(HEC_CANONICAL_CACHE_TEST.food('woolworths-au:98299'))),original);r.centralBarcode={gtin:'9310174025084',alias:'woolworths-au:98299',grams:75,calories:130,kJ:543,unchanged:true};qa.requireEvidence(r.diagnostic);r.pass=true;
}catch(e){r.error=e.stack;if(p)await p.screenshot({path:path.join(output,'failure.png'),fullPage:true});throw e;}finally{await browser.close();fs.writeFileSync(path.join(output,'results.json'),JSON.stringify(r,null,2));}console.log(JSON.stringify({pass:r.pass,actions:r.actions,centralBarcode:r.centralBarcode}));}
run().catch(e=>{console.error(e);process.exitCode=1;});
