'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const qa=require('./audit_physical_form_measures_edge'),{returningProfile}=require('./audit_navigation_startup_edge');
async function settled(page){await page.waitForFunction(()=>!HEC_RETAILER_TEST.state()?.loading&&!HEC_FOOD_CONCEPT_TEST.state()?.loading&&!HEC_AU_CATALOGUE_TEST.brandState()?.loading&&!/^Checking the Australian catalogue/.test(document.querySelector('#food-results')?.textContent.trim()||''));}
async function submit(page,q){await page.locator('#food-search').fill(q);await page.locator('#submit-food-search').click();await page.waitForFunction(q=>HEC_SEARCH_SESSION_TEST.state().rawQuery===q&&HEC_SEARCH_SESSION_TEST.state().mode==='explicit-committed',q);await settled(page);}
async function fresh(page){if(await page.locator('#a05-modal:not(.hidden)').count())await page.locator('#a05-modal-close').click();await page.evaluate(()=>openAlpha05Feature('food-library',{freshSearch:true}));}
async function review(page,{id,category,unit,amount}){
  await submit(page,'Coles');await page.locator(`[data-retailer-category="${category}"]`).click();await settled(page);
  const row=page.locator(`[data-universal-result="${id}"]`);await row.waitFor();const before=await page.evaluate(id=>HEC_CANONICAL_CACHE_TEST.food(id),id);assert.equal(before.privateLabelCollections.length,1);assert.equal(before.retailerMemberships.length,0);await row.click();
  await page.locator(`[data-gpr-measure="${unit}"]:visible`).click();const input=page.locator('[data-gpr-amount]:visible');await input.waitFor();assert.equal(await input.inputValue(),'');await input.fill(String(amount));await input.press('Enter');await page.locator('#food-entry-editor.active').waitFor();assert.equal(await page.locator('.screen.active').count(),1);assert.equal(await page.locator('[data-gpr-amount]:visible').count(),0);assert.equal(await page.locator('#entry-amount').inputValue(),String(amount));assert.equal(await page.locator('#entry-unit').inputValue(),unit);
  const review=await page.locator('#food-entry-editor').innerText();
  if(await page.locator('#save-food-entry').innerText()==='Save Food'){await page.locator('#save-food-entry-and-food').click();await page.locator('#entry-meal:visible').waitFor();await page.locator('#entry-meal').selectOption('Lunch');await page.locator('#save-food-entry-and-food').click();}else{await page.locator('#entry-meal').selectOption('Lunch');await page.locator('#save-food-entry').click();}
  await page.waitForFunction(id=>Object.values(JSON.parse(localStorage.getItem(HEC_INSTALLATION.functionalStorageKey)||'{}').diary||{}).flat().some(e=>e.foodId===id),id);
  const entry=await page.evaluate(id=>Object.values(JSON.parse(localStorage.getItem(HEC_INSTALLATION.functionalStorageKey)||'{}').diary||{}).flat().find(e=>e.foodId===id),id);assert.equal(entry.foodSnapshot.brand,before.brand);assert.equal(entry.meal,'Lunch');const base=unit==='slice'?amount*42:amount;assert.equal(entry.consumedPortion.baseQuantity,base);assert.equal(entry.consumedPortion.baseUnit,unit==='mL'?'mL':'g');assert(Math.abs(entry.nutrients.calories-before.nutrients.calories*base/100)<.01);await fresh(page);return {id,name:before.name,brand:before.brand,unit,amount,baseQuantity:base,meal:entry.meal,nutrients:entry.nutrients,reviewCount:1,review};
}
async function run({outputDirectory=fs.mkdtempSync(path.join(os.tmpdir(),'hec-coles-'))}={}){
  fs.mkdirSync(outputDirectory,{recursive:true});const {chromium,edge}=qa.browserTools(),browser=await chromium.launch({headless:true,executablePath:edge}),report={pass:false,generation:require('../release-manifest.json').generation,contexts:[]};let page;
  try{
    const diagnostic=qa.evidence(),context=await qa.contextFor({newContext:opts=>browser.newContext({...opts,isMobile:true,hasTouch:true})},{width:390,height:844},diagnostic);await context.addInitScript(returningProfile);page=await context.newPage();await qa.openLibrary(page);const result={viewport:{width:390,height:844},diagnostic,scenarios:[],reviews:[]};report.contexts.push(result);
    assert.equal(diagnostic.routes.filter(r=>/coles-au\/products/.test(r.url)).length,0);await submit(page,'Coles');assert.equal(await page.locator('[data-retailer-category]').count(),13);assert.match(await page.locator('#food-results').innerText(),/Private testing|Private-testing/);assert.match(await page.locator('#food-results').innerText(),/Open Food Facts/);assert.equal(diagnostic.routes.filter(r=>/coles-au\/products/.test(r.url)).length,0);await page.screenshot({path:path.join(outputDirectory,'390-directory.png'),fullPage:true});result.scenarios.push('honest 12-category directory plus All Items; no product hydration');
    await page.locator('[data-retailer-category="*"]').click();await settled(page);assert.equal(await page.locator('[data-universal-result]').count(),20);await page.locator('[data-retailer-more]').click();await settled(page);assert.equal(await page.locator('[data-universal-result]').count(),3);await page.locator('[data-retailer-previous]').click();await settled(page);assert.equal(await page.locator('[data-universal-result]').count(),20);await page.locator('[data-retailer-back]').click();await settled(page);assert.equal(await page.locator('[data-retailer-category]').count(),13);result.scenarios.push('20/3 paging, Previous and directory Back');
    await page.locator('[data-retailer-category="bread"]').click();await settled(page);assert.equal(await page.locator('[data-universal-result]').count(),3);assert.equal(await page.locator('[data-universal-result="off:9300601274475"],[data-universal-result="off:9310645254142"]').count(),0);result.scenarios.push('incomplete and conflicting bread absent from ordinary browse');
    await submit(page,'Woolworths');assert.equal(await page.locator('[data-retailer-id="woolworths"]').count(),1);await submit(page,'Bread');assert.equal(await page.evaluate(()=>HEC_RETAILER_TEST.state()),null);assert.equal(await page.locator('[data-fc-base],[data-universal-generic]').count(),1);result.scenarios.push('Coles to Woolworths to generic Bread restores concept-first scope');
    await page.locator('[data-fc-base]').click();await page.locator('[data-fc-answer="breadOrigin"][data-fc-value="commercial"]').click();await page.locator('[data-fc-answer="breadSource"][data-fc-value="supermarket"]').click();await page.locator('[data-fc-answer="retailerIdentity"][data-fc-value="coles"]').click();await settled(page);assert.equal(await page.locator('[data-universal-result]').count(),3);const brands=await page.evaluate(()=>[...document.querySelectorAll('[data-universal-result]')].map(n=>HEC_CANONICAL_CACHE_TEST.food(n.dataset.universalResult).brand));assert(brands.every(b=>b.toLowerCase()==='coles'));await page.screenshot({path:path.join(outputDirectory,'390-guided-bread.png'),fullPage:true});result.scenarios.push('actual guided private-label bread with no national-brand rows');
    await submit(page,'Coles Bread brioche');const exact=page.locator('[data-universal-result="off:9310645290676"]');await exact.waitFor();assert.equal(await page.evaluate(()=>HEC_CANONICAL_CACHE_TEST.food('off:9310645290676').privateLabelCollections.length),1);const barcode=await page.evaluate(()=>HEC_LARGE_CATALOGUE_TEST.barcode('9310645290676'));assert.equal(barcode.id,'off:9310645290676');assert.equal(barcode.privateLabelCollections.length,1);assert.equal(barcode.retailerMemberships.length,0);result.scenarios.push('submitted exact identity and barcode retain enriched canonical OFF object');
    for(const sample of [{id:'off:9310645290676',category:'bread',unit:'slice',amount:2},{id:'off:9310645094656',category:'milk',unit:'mL',amount:250}])result.reviews.push(await review(page,sample));
    await page.reload({waitUntil:'load'});await page.waitForFunction(()=>window.HEC_SEARCH_SESSION_TEST);const saved=await page.evaluate(()=>Object.values(JSON.parse(localStorage.getItem(HEC_INSTALLATION.functionalStorageKey)||'{}').diary||{}).flat());for(const r of result.reviews){const entries=saved.filter(e=>e.foodId===r.id);assert.equal(entries.length,1);assert.equal(entries[0].meal,'Lunch');assert.equal(entries[0].nutrients.calories,r.nutrients.calories);}result.scenarios.push('one entry per review persists after application reopen');
    qa.requireEvidence(diagnostic);await context.close();
    const small=qa.evidence(),c=await qa.contextFor({newContext:opts=>browser.newContext({...opts,isMobile:true,hasTouch:true})},{width:320,height:568},small);await c.addInitScript(returningProfile);page=await c.newPage();await qa.openLibrary(page);await submit(page,'Coles');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await page.locator('[data-retailer-category="*"]').click();await settled(page);await page.locator('[data-retailer-more]').scrollIntoViewIfNeeded();assert(await page.locator('[data-retailer-more]').isVisible());await page.locator('[data-retailer-more]').click();await settled(page);assert(await page.locator('[data-retailer-previous]').isVisible());assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await page.screenshot({path:path.join(outputDirectory,'320-controls.png'),fullPage:true});qa.requireEvidence(small);report.contexts.push({viewport:{width:320,height:568},diagnostic:small,scenarios:['catalogue width and paging controls sanity only']});await c.close();report.pass=true;return report;
  }catch(error){report.error={message:error.message,stack:error.stack};throw error;}finally{if(page&&!page.isClosed())await page.screenshot({path:path.join(outputDirectory,'last-state.png'),fullPage:true}).catch(()=>{});await browser.close();fs.writeFileSync(path.join(outputDirectory,'coles-rendered.json'),JSON.stringify(report,null,2));}
}
if(require.main===module)run({outputDirectory:process.argv[2]}).then(r=>console.log(JSON.stringify({pass:r.pass,contexts:r.contexts.length}))).catch(e=>{console.error(e);process.exitCode=1});
module.exports={run};
