'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const qa=require('./audit_physical_form_measures_edge'),t=require('./audit_brand_wave_edge'),{returningProfile}=require('./audit_navigation_startup_edge'),C=require('../food-catalogue'),B=require('../brand-au-catalogue');
const old=new Set(require('../data/catalogue-round-two/baseline-products.json').records.filter(f=>f.brandAdmission).map(C.canonicalKey));
const added=B.files.flatMap(s=>require('../data/brand-au/'+s.path).records).filter(f=>!old.has(C.canonicalKey(f)));
const aldiBefore=new Set(require('../data/catalogue-round-two/baseline-counts.json').retailers.aldi.keys);
const addedAldi=require('../aldi-au-catalogue').index.files.flatMap(s=>require('../data/aldi-au/'+s.path).records).filter(f=>!aldiBefore.has(C.canonicalKey(f)));
function choose(role,predicate,unit='g',amount=37,pool=added){const food=pool.find(predicate);assert(food,role);return {role,id:food.id,key:C.canonicalKey(food),query:(food.sourceBrandTokens?.[0]?.name||food.brand)+' '+food.name,unit:unit==='natural'?Object.keys(food.units).find(k=>['slice','piece','biscuit','bar','sachet'].includes(k)):unit,amount,food};}
const samples=[choose('Woolworths private label',f=>C.brandKey(f.brand)==='woolworths'&&f.units.g),choose('Coles private label',f=>C.brandKey(f.brand)==='coles'&&f.units.g),choose('Aldi house brand',f=>C.brandKey(f.brand)==='hillcrest'&&C.sourceDeclaredRetailerMembership(f,'aldi').length&&f.units.g,'g',37,addedAldi),choose('McCain official frozen meal',f=>f.id.startsWith('manufacturer:')&&f.categoryId==='meals','serve',1),choose('Kelloggs cereal',f=>f.sourceBrandTokens.some(b=>b.key==='kelloggs')&&f.categoryId==='cereal'&&!/bar/i.test(f.name)&&f.units.g),choose('Biscuit or cracker',f=>f.categoryId==='biscuits'&&f.units.g),choose('Drink / liquid',f=>f.categoryId==='drinks'&&f.units.mL,'mL',250),choose('Dairy yoghurt',f=>f.categoryId==='yoghurt'&&C.brandKey(f.brand)==='chobani'&&f.units.g),choose('Canned soup',f=>f.categoryId==='canned'&&/soup/i.test(f.name)&&f.units.g),choose('Countable food',f=>Object.keys(f.units).some(k=>['slice','piece','biscuit','bar','sachet'].includes(k)),'natural',2)];
async function review(page,sample,out,width){
 await t.fresh(page);await t.submit(page,sample.query);
 const key=sample.key;await page.waitForFunction(key=>[...document.querySelectorAll('[data-universal-result]')].some(n=>{const f=HEC_CANONICAL_CACHE_TEST.food(n.dataset.universalResult);return f&&HECFoodCatalogue.canonicalKey(f)===key;}),key,{timeout:20000});
 const id=await page.evaluate(key=>[...document.querySelectorAll('[data-universal-result]')].find(n=>{const f=HEC_CANONICAL_CACHE_TEST.food(n.dataset.universalResult);return f&&HECFoodCatalogue.canonicalKey(f)===key;}).dataset.universalResult,key);
 await page.locator('[data-universal-result="'+id+'"]').first().click();const food=await page.evaluate(()=>HEC_GUIDED_PRODUCT_TEST.food());assert.equal(C.canonicalKey(food),key);
 const measure=page.locator('[data-gpr-measure="'+sample.unit+'"]:visible');if(await measure.count())await measure.click();else assert(sample.unit in food.units);
 const amount=page.locator('[data-gpr-amount]:visible');await amount.waitFor();assert.equal(await amount.inputValue(),'');await amount.fill(String(sample.amount));await amount.press('Enter');await page.locator('#food-entry-editor.active').waitFor();
 assert.equal(await page.locator('.screen.active').count(),1);assert.equal(await page.locator('[data-gpr-amount]:visible').count(),0);assert.equal(await page.locator('#entry-unit').inputValue(),sample.unit);assert.equal(await page.locator('#entry-amount').inputValue(),String(sample.amount));
 const preview=await page.locator('#entry-nutrition-preview').innerText(),scale=food.units[sample.unit]*sample.amount,calories=food.nutrients.calories*scale,kj=food.nutrients.energyKj*scale;
 assert(preview.includes(Math.round(calories).toLocaleString('en-AU')+' Cal'),preview);assert(preview.includes(Math.round(kj).toLocaleString('en-AU')+' kJ'),preview);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);
 await page.screenshot({path:path.join(out,width+'-review-'+sample.role.replace(/[^a-z0-9]+/ig,'-')+'.png'),fullPage:true});
 return {role:sample.role,id:food.id,canonicalKey:key,name:food.name,brand:food.brand,gtin:food.barcode||null,unit:sample.unit,amount:sample.amount,calories,energyKj:kj,reviewCount:1,diarySaved:false};
}
async function run(out){fs.mkdirSync(out,{recursive:true});const report={pass:false,generation:require('../release-manifest.json').generation,contexts:[]},{chromium,edge}=qa.browserTools(),browser=await chromium.launch({headless:true,executablePath:edge});let page;try{
 for(const viewport of [{width:390,height:844},{width:320,height:568},{width:768,height:1024}]){const diagnostic=qa.evidence(),context=await qa.contextFor(browser,viewport,diagnostic);await context.addInitScript(returningProfile);page=await context.newPage();await qa.openLibrary(page);const r={viewport,diagnostic,retailers:[],reviews:[]};report.contexts.push(r);assert.equal(await page.locator('#food-search').inputValue(),'');
 for(const name of ['Woolworths','Coles','Aldi']){await t.fresh(page);await t.submit(page,name);assert(await page.locator('[data-retailer-category]').count()>10);await t.geometry(page);await page.screenshot({path:path.join(out,viewport.width+'-'+name+'-root.png'),fullPage:true});await page.locator('[data-retailer-category]').first().click();await t.settled(page);assert(await page.locator('[data-universal-result]').count());await t.geometry(page);await t.fresh(page);await t.submit(page,name);await page.locator('[data-retailer-category="*"]').click();await t.settled(page);assert(await page.locator('[data-universal-result]').count()<=20);r.retailers.push({name,root:true,category:true,allItems:true,geometry:await t.geometry(page)});}
 await t.fresh(page);await t.submit(page,'McCain');assert(await page.locator('[data-au-brand-category]').count()>2);await page.locator('[data-au-brand-category="*"]').click();await t.settled(page);r.exactBrand=await t.geometry(page);await page.screenshot({path:path.join(out,viewport.width+'-McCain-all.png'),fullPage:true});
 await t.fresh(page);await t.submit(page,'Cereal');await page.locator('[data-fc-base]').click();await page.locator('[data-fc-answer="catalogueOrigin"][data-fc-value="commercial"]').click();await page.locator('[data-fc-answer="catalogueSource"][data-fc-value="brand"]').click();assert(await page.locator('[data-fc-answer="brandIdentity"][data-fc-value="kelloggs"]').count());r.conceptBrands=await t.geometry(page);await page.locator('[data-fc-answer="brandIdentity"][data-fc-value="kelloggs"]').click();await t.settled(page);assert(await page.locator('.brand-catalogue [data-universal-result]').count());
 for(const sample of viewport.width===390?samples:[samples[3]])r.reviews.push(await review(page,sample,out,viewport.width));
 await t.fresh(page);assert.equal(await page.locator('#food-search').inputValue(),'');qa.requireEvidence(diagnostic);await context.close();}
 report.pass=true;return report;
 }catch(error){report.error={message:error.message,stack:error.stack};throw error;}finally{if(page&&!page.isClosed())await page.screenshot({path:path.join(out,'last-state.png'),fullPage:true}).catch(()=>{});await browser.close();fs.writeFileSync(path.join(out,'round-two-rendered.json'),JSON.stringify(report,null,2));}}
if(require.main===module)run(process.argv[2]).then(r=>console.log(JSON.stringify({pass:r.pass,contexts:r.contexts.length,reviews:r.contexts.flatMap(c=>c.reviews).length}))).catch(e=>{console.error(e);process.exitCode=1;});module.exports={run,samples,review};
