'use strict';
const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict'),cp=require('child_process');
const qa=require('./audit_physical_form_measures_edge');require('../packaged-foods');const X=require('../capture-foundation');
const output=path.resolve(process.argv[2]||'data/barcode-panel-repair/ocr'),modules=path.resolve(path.dirname(process.execPath),'../node_modules'),T=require(path.join(modules,'tesseract.js'));
const source=fs.readFileSync(path.join(qa.ROOT,'alpha06.js'),'utf8'),old=cp.execFileSync('git',['show','227e326:alpha06.js'],{cwd:qa.ROOT,encoding:'utf8',maxBuffer:8e6});
const extract=s=>s.slice(s.indexOf('async function prepareOcrImage(file){'),s.indexOf('\nby("run-label-ocr")',s.indexOf('async function prepareOcrImage(file){')));
async function run(){fs.mkdirSync(output,{recursive:true});const {chromium,edge}=qa.browserTools(),browser=await chromium.launch({headless:true,executablePath:edge}),p=await browser.newPage();let worker;const report={pass:false,synthetic:true,cases:[]};
try{worker=await T.createWorker('eng',1,{cachePath:path.join(os.tmpdir(),'hec-synthetic-ocr-language')});await worker.setParameters({tessedit_pageseg_mode:'6',preserve_interword_spaces:'1',user_defined_dpi:'300'});
 for(const spec of [{name:'clean-flat'},{name:'reduced-contrast',contrast:true},{name:'decimal-rich',decimal:true},{name:'two-column-mass',table:true},{name:'two-column-liquid',liquid:true},{name:'uncertain-field',uncertain:true}]){
  const images=await p.evaluate(async ({spec,before,after})=>{
   const c=document.createElement('canvas');c.width=1600;c.height=950;const g=c.getContext('2d');g.fillStyle=spec.contrast?'#dedede':'white';g.fillRect(0,0,c.width,c.height);g.fillStyle=spec.contrast?'#888888':'black';g.font='bold 36px Arial';g.fillText('NUTRITION INFORMATION',40,65);g.font='32px Arial';g.fillText('Servings per package 1',40,125);g.fillText('Serving size 170 '+(spec.liquid?'mL':'g'),40,185);g.font='28px Arial';g.fillText('Average Quantity per Serving',510,250);g.fillText('Average Quantity per 100 '+(spec.liquid?'mL':'g'),1050,250);
   const rows=[['Energy (kJ)','670','394.12'],['Protein (g)','3.3','1.94'],['Fat, total (g)',spec.uncertain?'?':'5.3','3.12'],['Saturated fat (g)','0.8','0.47'],['Carbohydrate (g)','23','13.53'],['Sugars (g)','12.5','7.35'],['Dietary fibre (g)','1.2','0.71'],['Sodium (mg)','158','92.94']];g.font='32px Arial';rows.forEach((r,i)=>r.forEach((v,j)=>g.fillText(v,(spec.decimal?[40,720,1240]:[40,680,1200])[j],330+i*65)));if(spec.table){g.strokeStyle='#cccccc';for(let i=0;i<8;i++){g.beginPath();g.moveTo(40,350+i*65);g.lineTo(1520,350+i*65);g.stroke();}}
   const blob=await new Promise(r=>c.toBlob(r)),file=new File([blob],'synthetic.png',{type:'image/png'}),result={original:c.toDataURL('image/png')};
   for(const [key,fn] of [['before',before],['after',after]]){const prepare=(0,eval)('('+fn+')');const image=await prepare(file);result[key]=image.toDataURL('image/png');}return result;
  },{spec,before:extract(old),after:extract(source)});
  const item={name:spec.name,results:{}};report.cases.push(item);
  for(const key of ['original','before','after'])fs.writeFileSync(path.join(output,spec.name+'-'+key+'.png'),Buffer.from(images[key].split(',')[1],'base64'));
  for(const key of ['before','after']){await worker.setParameters({tessedit_pageseg_mode:'6'});const result=await worker.recognize(path.join(output,spec.name+'-'+key+'.png'),{}, {text:true,blocks:true});const parsed=X.parseOcrResult(result.data);item.results[key]={confidence:result.data.confidence,text:result.data.text,parsed,detected:0,incorrect:[]};for(const [basis,expected] of [['perServing',{energyKj:670,protein:3.3,fat:spec.uncertain?null:5.3,satFat:.8,carbs:23,sugar:12.5,fibre:1.2,sodium:158}],['per100',{energyKj:394.12,protein:1.94,fat:3.12,satFat:.47,carbs:13.53,sugar:7.35,fibre:.71,sodium:92.94}]])for(const [field,value] of Object.entries(expected)){if(parsed[basis][field]===value&&value!==null)item.results[key].detected++;else if(parsed[basis][field]!==null)item.results[key].incorrect.push({basis,field,expected:value,actual:parsed[basis][field]});}}
  assert.deepEqual(item.results.after.incorrect,[],spec.name+' confident wrong values');assert(item.results.after.detected>=8,spec.name+' detection');assert.equal(item.results.after.parsed.servingAmount,170);assert.equal(item.results.after.parsed.servingsPerPack,1);assert.equal(item.results.after.parsed.per100Unit,spec.liquid?'mL':'g');if(spec.uncertain)assert.equal(item.results.after.parsed.perServing.fat,null);
 }
 report.beforeDetected=report.cases.reduce((n,c)=>n+c.results.before.detected,0);report.afterDetected=report.cases.reduce((n,c)=>n+c.results.after.detected,0);assert(report.afterDetected>report.beforeDetected,'demonstrated general improvement');report.pass=true;
}finally{await worker?.terminate();await browser.close();fs.writeFileSync(path.join(output,'ocr-results.json'),JSON.stringify(report,null,2));}console.log(JSON.stringify({pass:report.pass,before:report.beforeDetected,after:report.afterDetected,cases:report.cases.map(c=>({name:c.name,detected:c.results.after.detected,issues:c.results.after.parsed.issues}))}));}
run().catch(e=>{console.error(e);process.exitCode=1;});
