'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const qa=require('./audit_physical_form_measures_edge'),t=require('./audit_brand_wave_edge'),prior=require('./audit_catalogue_wave_1b_edge'),concept=require('./audit_food_concept_resolution_edge');
async function acceptedGenericMeasures(browser,query){
 const cp=require('node:child_process'),cache=new Map(),diagnostic=qa.evidence(),changed=new Set(cp.execFileSync('git',['diff','--name-only','HEAD'],{cwd:qa.ROOT,encoding:'utf8'}).trim().split('\n'));
 const context=await qa.contextFor(browser,{width:390,height:844},diagnostic,{readBody:(relative,file)=>{if(!changed.has(relative))return fs.readFileSync(file);if(!cache.has(relative))cache.set(relative,cp.execFileSync('git',['show','HEAD:'+relative],{cwd:qa.ROOT,maxBuffer:20*1024*1024}));return cache.get(relative);}});
 try{const p=await context.newPage();await qa.openLibrary(p);await t.submit(p,query);await concept.chooseIdentity(p);const food=await p.evaluate(()=>HEC_GUIDED_PRODUCT_TEST.food()),measures=await p.locator('[data-gpr-measure]:visible').evaluateAll(ns=>ns.map(n=>n.dataset.gprMeasure));qa.requireEvidence(diagnostic);return {head:'c5393ae8d9f09c5feb8a7aa72e4045c927dc9f7d',id:food.id,units:food.units,measures};}finally{await context.close();}
}
async function run(out){fs.mkdirSync(out,{recursive:true});const report={pass:false,generation:require('../release-manifest.json').generation,aliases:[],routes:[],queries:[],reviews:[],diagnostic:qa.evidence()}, {chromium,edge}=qa.browserTools(),browser=await chromium.launch({headless:true,executablePath:edge});let page;
 try{const context=await qa.contextFor(browser,{width:390,height:844},report.diagnostic);page=await context.newPage();await qa.openLibrary(page);
  for(const q of ['IGA','Supa IGA','Super IGA','IGA Local Grocer','IGA X-Press','IGA Xpress']){await t.fresh(page);await t.submit(page,q);assert.equal(await page.evaluate(()=>HEC_RETAILER_TEST.state().retailerId),'iga');assert.match(await page.locator('#food-results').innerText(),/All Items \(8\)/);await t.geometry(page);report.aliases.push({query:q,retailer:'iga',count:8});}
  await page.screenshot({path:path.join(out,'iga-root.png'),fullPage:true});const d=await page.evaluate(()=>HECRetailerCatalogue.directory('iga'));
  for(const choice of [{kind:'category',key:'*',count:8},...d.categories.map(c=>({kind:'category',key:c.id,count:c.count})),...d.brands.map(b=>({kind:'brand',key:b.key,count:b.count}))]){if(choice.kind==='brand')await page.locator('[data-retailer-brands]').click();await page.locator('[data-retailer-'+choice.kind+'="'+choice.key+'"]').click();await t.settled(page);const rows=await prior.rows(page);assert.equal(rows.length,choice.count);assert(rows.every(r=>r.eligible&&['blackandgold','communityco'].includes(r.food.brand.toLowerCase().replace(/&/g,'and').replace(/[^a-z]/g,''))));await t.geometry(page);report.routes.push({...choice,actual:rows.length});if(choice.key==='bread')await page.screenshot({path:path.join(out,'iga-bread.png'),fullPage:true});await page.locator('[data-retailer-back]').click();await t.settled(page);if(choice.kind==='brand')await page.locator('[data-retailer-back]').click();}
  report.empty=[];for(const kind of ['category','brand']){await t.fresh(page);await t.submit(page,'IGA');if(kind==='brand')await page.locator('[data-retailer-brands]').click();const control=page.locator('[data-retailer-'+kind+']').first();await control.evaluate((n,k)=>n.setAttribute('data-retailer-'+k,'missing-reviewed-route'),kind);await control.click();await t.settled(page);assert.match(await page.locator('#food-results').innerText(),/No matching foods/);assert.equal(await page.locator('[data-universal-result]').count(),0);report.empty.push(kind);await page.locator('[data-retailer-back]').click();}
  for(const q of ['Black & Gold','Community Co']){await t.fresh(page);await t.submit(page,q);assert((await page.locator('[data-au-brand-category]').count())||(await page.locator('[data-universal-result]').count()));report.queries.push({query:q,brandReachable:true});}
  for(const [query,gtin,unit,amount]of [['Black & Gold Australian Quick Oats','9310077200755','g',35],['Community Co Colby Cheese','9310246053328','g',25],['Pepsi Max 2L','9313820004518','mL',250]]){await t.fresh(page);await t.submit(page,query);const selected=(await prior.rows(page)).find(r=>r.food.barcode===gtin);assert(selected?.eligible,query);report.reviews.push(await prior.review(page,selected,unit,amount));await page.screenshot({path:path.join(out,gtin+'-review.png'),fullPage:true});}
  for(const query of ['Bread','Milk','Cereal','Crackers','Cheese','Frozen Vegetables','Frozen Chips','Coffee','Sausage','Chicken']){console.log('IGA wave generic '+query);await t.fresh(page);await t.submit(page,query);const first=await concept.capture(page);const choices=await prior.rows(page);assert(await page.locator('[data-fc-base]').count()||choices.some(r=>r.eligible&&r.food.recordType==='afcd'),query+' has no prominent generic route');const identity=await concept.chooseIdentity(page);const food=await page.evaluate(()=>HEC_GUIDED_PRODUCT_TEST.food());assert(food&&await page.evaluate(()=>HECFoodCatalogue.canLog(HEC_GUIDED_PRODUCT_TEST.food())));const liquid=await page.evaluate(()=>HECServingFoundation.physicalForm(HEC_GUIDED_PRODUCT_TEST.food()).form==='liquid'),unit=liquid?'mL':'g',amount=liquid?250:100,measures=await page.locator('[data-gpr-measure]:visible').evaluateAll(ns=>ns.map(n=>n.dataset.gprMeasure));if(measures.length){const control=page.locator('[data-gpr-measure="'+unit+'"]:visible');assert(await control.count(),query+' missing '+unit);await control.click();}if(!liquid&&measures.some(k=>['mL','L','cup'].includes(k))){assert.equal(food.recordType,'afcd','Branded solids must not expose volume');const baseline=await acceptedGenericMeasures(browser,query);assert.deepEqual({id:food.id,units:food.units,measures},{id:baseline.id,units:baseline.units,measures:baseline.measures});(report.unchangedGenericHouseholdMeasures??=[]).push({query,...baseline});}const input=page.locator('[data-gpr-amount]:visible');await input.fill(String(amount));await input.press('Enter');await page.locator('#food-entry-editor.active').waitFor();assert.equal(await page.locator('.screen.active').count(),1);assert.equal(await page.locator('[data-gpr-amount]:visible').count(),0);report.queries.push({query,firstConcept:first.concept?.conceptId,selected:food.name,brand:food.brand,steps:identity.steps,unit,reviewCount:1});}
  qa.requireEvidence(report.diagnostic);await context.close();
  report.failures=[];for(const mode of ['stalled','rejected']){const diagnostic=qa.evidence(),c=await qa.contextFor(browser,{width:375,height:812},diagnostic),p=await c.newPage();await qa.openLibrary(p);await t.submit(p,'Super IGA');const held=[],pattern='**/data/iga-au/products/**';await p.route(pattern,route=>{held.push(route);if(mode==='rejected')return route.abort('failed');});const start=Date.now();await p.locator('[data-retailer-category="yoghurt"]').click();await p.locator('[data-retailer-retry]').waitFor({timeout:20000});const s=await p.evaluate(()=>HEC_RETAILER_TEST.state());assert(!s.loading&&s.error);assert(!/Loading foods/.test(await p.locator('#food-results').innerText()));const elapsedMs=Date.now()-start;assert(elapsedMs<20000);for(const route of held)if(mode==='stalled')await route.abort().catch(()=>{});await p.unroute(pattern);await p.locator('[data-retailer-retry]').click();await t.settled(p);assert.equal(await p.locator('[data-universal-result]').count(),1);assert.deepEqual(diagnostic.pageErrors,[]);assert.equal(diagnostic.liveFallthrough,0);report.failures.push({mode,elapsedMs,retryProducts:1,injectedRequests:held.length,diagnostic});await c.close();}
  const diagnostic=qa.evidence(),c=await qa.contextFor(browser,{width:375,height:812},diagnostic),p=await c.newPage();await qa.openLibrary(p);await t.submit(p,'IGA Local Grocer');let hold=true,release;const gate=new Promise(r=>release=r),pending=[],held=[],pattern='**/data/iga-au/products/**';await p.route(pattern,route=>{const work=(async()=>{if(hold){held.push(route.request().url());await gate;}await route.fallback();})();pending.push(work);return work;});try{await p.locator('[data-retailer-category="bread"]').click();await p.waitForFunction(()=>HEC_RETAILER_TEST.state()?.loading);await p.waitForTimeout(50);assert(held.length);await p.locator('[data-retailer-back]').click();await t.settled(p);hold=false;await p.locator('[data-retailer-category="cereal"]').click();await p.waitForFunction(()=>HEC_RETAILER_TEST.state()?.categoryId==='cereal');}finally{hold=false;release();await Promise.all(pending);await p.waitForLoadState('networkidle');}await p.unroute(pattern);await t.settled(p);const state=await p.evaluate(()=>HEC_RETAILER_TEST.state());assert.equal(state.result.categoryId,'cereal');assert(!state.loading);await t.submit(p,'Coles');assert.equal(await p.evaluate(()=>HEC_RETAILER_TEST.state().retailerId),'coles');qa.requireEvidence(diagnostic);report.lateNavigation={pass:true,held:held.length,finalCategory:state.categoryId,switchTo:'coles',diagnostic};await c.close();report.pass=true;return report;
 }catch(e){report.error={message:e.message,stack:e.stack};if(page&&!page.isClosed())await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});throw e;}finally{await browser.close();fs.writeFileSync(path.join(out,'wave-4a-rendered.json'),JSON.stringify(report,null,2)+'\n');}}
if(require.main===module)run(process.argv[2]).then(r=>console.log(JSON.stringify({pass:r.pass,aliases:r.aliases.length,routes:r.routes.length,queries:r.queries.length,reviews:r.reviews.length}))).catch(e=>{console.error(e);process.exitCode=1;});module.exports={run};
