'use strict';
// Reproducible, offline derivation. Never refreshes the protected OFF snapshot.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const C=require('../food-catalogue'),S=require('../serving-foundation'),OFF=require('../off-catalogue');
const root=path.resolve(__dirname,'..'),base=path.join(root,'data/woolworths-au');
const read=file=>JSON.parse(fs.readFileSync(path.join(base,file),'utf8'));
const hash=value=>crypto.createHash('sha256').update(value).digest('hex');
const KEYS=['calories','energyKj','protein','carbs','fat','satFat','sugar','fibre','sodium'];
const NAMES={'Energy':'energyKj','Protein':'protein','Fat, Total':'fat','Carbohydrate':'carbs','Sodium':'sodium','Dietary Fibre':'fibre','– Saturated':'satFat','– Sugars':'sugar'};
function validGtin(value){if(!/^(?:\d{8}|\d{12}|\d{13}|\d{14})$/.test(value||''))return false;const digits=[...value].map(Number);return (10-digits.slice(0,-1).reduce((sum,n,i)=>sum+n*((digits.length-i)%2===0?3:1),0)%10)%10===digits.at(-1);}
function number(value,unit=''){const match=String(value??'').trim().match(new RegExp('^(?:Approx\\.\\s*)?(\\d+(?:\\.\\d+)?)\\s*'+unit+'$','i'));return match?Number(match[1]):null;}
function nutrition(rows,column){const values=Object.fromEntries(KEYS.map(key=>[key,null]));for(const row of rows){const key=NAMES[row.Name];if(!key)continue;const value=number(row.Values?.[column],key==='energyKj'?'kJ':key==='sodium'?'mg':'g');if(values[key]!==null&&values[key]!==value)throw Error('Duplicate contradictory nutrient rows');values[key]=value;}if(values.energyKj!==null)values.calories=values.energyKj/4.184;return values;}
function convert(raw,policy,sourcePolicy){
  const p=raw.product,id='woolworths-au:'+raw.sourceRecordId,brand=p.Brand,name=p.DisplayName;
  if(!name||!brand||p.AgeRestricted||p.IsTobacco||p.IsMarketProduct)throw Error('Unusable or out-of-scope product '+id);
  const evidence={...raw.provenance,recordId:raw.sourceRecordId},privateLabel=sourcePolicy.privateLabels.find(label=>label.consumerBrand===brand);
  const servingTexts=[...new Set(raw.nutrition.map(row=>row.ServingSize).filter(Boolean))],countTexts=[...new Set(raw.nutrition.map(row=>row.ServingsPerPack).filter(Boolean))];
  if(servingTexts.length>1||countTexts.length>1)throw Error('Contradictory serving metadata '+id);
  const servingText=servingTexts[0]||'',serve=C.metricEvidence(servingText),pack=C.metricEvidence(p.PackageSize),count=number(countTexts[0]);
  const metric=serve?.unit||(policy.physicalForm==='liquid'?'mL':'g'),per100=nutrition(raw.nutrition,'Quantity Per 100g / 100mL'),perServe=nutrition(raw.nutrition,'Quantity Per Serving');
  const units={[metric]:.01},labels={[metric]:metric};if(serve){units.serve=serve.amount/100;labels.serve=`Manufacturer serve (${servingText})`;}
  const food={id,canonicalId:id,recordType:'packaged',sourceCatalogueId:'woolworths-au-public',sourceId:raw.sourceRecordId,market:'AU',country:'Australia',name,brand,aliases:[p.Name],barcode:validGtin(p.Barcode)?p.Barcode:null,sourceBarcode:p.Barcode,pack,packageSize:p.PackageSize,packCount:/^(\d+)\s+pack$/i.test(p.PackageSize)?Number(p.PackageSize.match(/^\d+/)[0]):null,manufacturerServing:serve,sourceServingEvidence:{text:servingText,servingsPerPack:countTexts[0]||null},servingsPerPack:count,packageServingText:servingText,packageServingExplicit:!!serve,serving:serve?`Source serving ${servingText}; retail pack ${p.PackageSize}`:`Nutrition reference per 100 ${metric}; retail pack ${p.PackageSize}`,defaultUnit:serve?'serve':metric,defaultAmount:serve?1:100,units,unitLabels:labels,nutrients:{...per100},nutritionPer100:per100,nutritionPerServing:perServe,nutritionPer100Unit:metric,sourceNutritionBasis:{per100Unit:metric,state:policy.nutritionState},sourceNutritionEvidence:raw.nutrition,physicalForm:policy.physicalForm,physicalFormSource:'Reviewed captured product title/category and published serving unit',measureEvidencePolicy:'source-and-published-standard-only',category:sourcePolicy.categories.find(c=>c.id===policy.categoryId).label,categoryMemberships:JSON.parse(raw.attributes.piescategorynamesjson||'[]'),sourceCategories:{departments:JSON.parse(raw.attributes.piesdepartmentnamesjson||'[]'),categories:JSON.parse(raw.attributes.piescategorynamesjson||'[]'),subcategories:JSON.parse(raw.attributes.piessubcategorynamesjson||'[]')},conceptIds:policy.conceptIds,sourceProvenance:evidence,sourceUrl:evidence.url,source:`Official Woolworths Australia product facts · checked ${evidence.retrievedAt.slice(0,10)}`,verified:true,verificationStatus:'verified',currentState:'listed-at-retrieval',availabilityEvidence:{...raw.availabilityContext,isRanged:p.IsRanged,isAvailable:p.IsAvailable,isInStock:p.IsInStock,isPurchasable:p.IsPurchasable},retailerMemberships:[{retailerId:'woolworths',market:'AU',scope:'food',verified:true,categoryIds:[policy.categoryId],listingState:'listed-at-retrieval',evidence}],commercialIdentities:privateLabel?[{entityId:'woolworths',relationship:privateLabel.relationship,consumerBrand:brand,market:'AU',verified:true,evidence:privateLabel.evidence,productEvidence:evidence}]:[],nutritionStatus:per100.energyKj===null?'unavailable':Object.values(per100).some(value=>value===null)?'partial':'complete',loggable:per100.energyKj!==null,evidenceFlags:raw.nutrition.flatMap(row=>Object.entries(row.Values||{}).filter(([,v])=>/[<>]/.test(v)).map(([basis,value])=>({code:'qualified-nutrient-not-exact',nutrient:row.Name,basis,value}))),score:6};
  food.ingredients=raw.attributes.ingredients||'';food.sourceAnomalies=policy.nutritionState==='as-sold dry product'?['Nutrition applies to the dry product before preparation.']:policy.nutritionState==='as-sold uncooked product'?['Nutrition applies to the uncooked product as sold.']:[];if(food.sourceAnomalies.length)food.serving+='; '+food.sourceAnomalies[0];
  food.evidenceConflicts=C.sourceConflicts(food);if(food.evidenceConflicts.length){food.loggable=false;food.nutritionStatus='needs-review';food.entryBlockedReason='Published serving or nutrition evidence disagrees. Review the source before logging.';}
  S.applyToFood(food);return food;
}
function build(){
  const policy=read('source-policy.json'),facts=read('public-products.json'),off=read('off-corroboration.json'),byId=new Map(facts.records.map(r=>[r.sourceRecordId,r]));
  const official=policy.products.map(p=>convert(byId.get(p.sourceRecordId),p,policy)),quarantine=official.filter(f=>!f.barcode).map(f=>({id:f.id,barcode:f.sourceBarcode,reason:'Invalid GTIN: source-specific identity only; never used for exact GTIN joining.'}));
  const valid=new Set(official.map(f=>f.barcode).filter(Boolean)),corroboration=off.matches.filter(m=>valid.has(m.record.barcode)).map(m=>{
    const file=path.join(root,'data/open-food-facts-au',m.shard),raw=fs.readFileSync(file);if(hash(raw)!==m.sha256||JSON.stringify(JSON.parse(raw).products[m.index])!==JSON.stringify(m.record))throw Error('Protected OFF evidence mismatch');
    const food=OFF.toFood(m.record);food.sourceProvenance={...C.sourceEvidence(food),sha256:m.sha256,snapshotSha256:off.protectedSnapshot.sourceSha256,shard:m.shard,row:m.index};return food;
  });
  const groups=official.map(food=>[food,...corroboration.filter(other=>other.barcode===food.barcode)]),entries=[],files=[];
  for(let i=0;i<groups.length;i+=8){const relative=`products/${String(i/8).padStart(2,'0')}.json`,records=groups.slice(i,i+8).flat(),text=JSON.stringify({records})+'\n';fs.mkdirSync(path.dirname(path.join(base,relative)),{recursive:true});fs.writeFileSync(path.join(base,relative),text);files.push({path:relative,sha256:hash(text),records:records.length});for(const food of records)entries.push(Object.fromEntries(['id','canonicalId','barcode','recordType','market','brand','name','aliases','conceptIds','retailerMemberships','commercialIdentities'].filter(key=>food[key]!==undefined).map(key=>[key,food[key]]).concat([['shard',relative]])));}
  const index={schemaVersion:1,retailer:policy.retailer,categories:policy.categories,entries,files,base:'./data/woolworths-au/',sourceDigest:hash(JSON.stringify({policy,facts,off}))};
  const output="/* Generated by scripts/build_woolworths_catalogue.js; attributed public food facts. */\n(function(global){'use strict';const index="+JSON.stringify(index)+";const adapter=global.HECRetailerSource||(typeof require==='function'?require('./retailer-source.js'):null);const registration=adapter.register(index);global.HECWoolworthsAustralia={index,registration};if(typeof module!=='undefined'&&module.exports)module.exports={index,registration};})(typeof window!=='undefined'?window:globalThis);\n";
  fs.writeFileSync(path.join(root,'woolworths-au-catalogue.js'),output);
  const canonical=C.canonicaliseRecords(groups.flat()),eligibility=f=>C.productEligibility(f).addability.status,report={officialEvidenceRows:official.length,rawEvidenceRows:groups.flat().length,canonicalIdentities:canonical.length,retailerProducts:canonical.length,verifiedGTINs:new Set(official.map(f=>f.barcode).filter(Boolean)).size,categories:policy.categories.length,privateLabel:official.filter(f=>f.commercialIdentities.length).length,nationalBrand:official.filter(f=>!f.commercialIdentities.length).length,eligibility:Object.fromEntries(['loggable-now','needs-nutrition-completion','details-only'].map(key=>[key,canonical.filter(f=>eligibility(f)===key).length])),conflictBlocked:canonical.filter(f=>C.sourceConflicts(f).some(c=>c.severity==='material'&&(!c.resolution||c.resolution==='unresolved'))).length,listingEvidenced:official.length,uncertainAvailability:official.length,exactOFFCorroborations:corroboration.length,identitiesStrengthened:groups.filter(g=>g.length>1).length,unsafeMergesPrevented:canonical.filter(f=>C.sourceConflicts(f).some(c=>c.code==='same-gtin-identity-conflict')).length,invalidGTINQuarantine:quarantine,rawRowsCollapsed:groups.flat().length-canonical.length,excluded:policy.excluded,products:canonical.map(f=>({id:f.id,name:f.name,brand:f.brand,gtin:f.barcode,category:f.category,status:C.productEligibility(f).addability,conflicts:C.sourceConflicts(f).map(c=>({code:c.code,fields:c.fields,resolution:c.resolution})),officialDisplayMatches:official.some(o=>o.barcode===f.barcode&&o.name===f.name&&o.brand===f.brand)}))};
  fs.writeFileSync(path.join(base,'build-report.json'),JSON.stringify(report,null,2)+'\n');return report;
}
if(require.main===module)console.log(JSON.stringify(build(),null,2));
module.exports={build,convert,validGtin,number,nutrition};
