'use strict';
// Offline, attributable view of the protected OFF AU layer. No network access.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const C=require('../food-catalogue'),OFF=require('../off-catalogue');
const root=path.resolve(__dirname,'..'),base=path.join(root,'data/coles-au');
const hash=raw=>crypto.createHash('sha256').update(raw).digest('hex');
const read=file=>JSON.parse(fs.readFileSync(path.join(base,file),'utf8'));
function validGtin(code){if(!/^(?:\d{8}|\d{12}|\d{13}|\d{14})$/.test(code||''))return false;const d=[...code].map(Number);return (10-d.slice(0,-1).reduce((s,n,i)=>s+n*((d.length-i)%2===0?3:1),0)%10)%10===d.at(-1);}
function derive(){
  const policy=read('source-policy.json'),manifest=require('../data/open-food-facts-au/manifest.json'),cache=new Map();
  if(manifest.sourceSha256!==policy.source.sha256||manifest.sourceSnapshotDate!==policy.source.snapshotDate)throw Error('Protected OFF snapshot differs');
  for(const pin of policy.source.shards){const raw=fs.readFileSync(path.join(root,'data/open-food-facts-au',pin.path));if(hash(raw)!==pin.sha256)throw Error('Protected OFF shard differs: '+pin.path);cache.set(pin.path,JSON.parse(raw));}
  const rows=policy.products.map(item=>{
    const [shard,index]=item.ref.split(':'),file='products/'+shard+'.json',record=cache.get(file)?.products[Number(index)];
    if(!record||record.id!==item.id||C.brandKey(record.brand)!=='coles'||!record.countries.includes('en:australia'))throw Error('Selected source identity differs: '+item.ref);
    const food=OFF.toFood(record),evidence={trustClass:'open-food-facts-au',sourceId:'open-food-facts-au',recordId:record.id,url:record.sourceUrl,snapshotDate:manifest.sourceSnapshotDate,snapshotSha256:manifest.sourceSha256,sha256:policy.source.shards.find(p=>p.path===file).sha256,shard:file,row:Number(index),lastModified:record.lastModified};
    food.sourceProvenance=evidence;
    food.privateLabelCollections=[{retailerId:'coles',market:'AU',scope:'food',basis:'source-declared-brand',verified:false,consumerBrand:record.brand,categoryIds:[item.categoryId],evidence}];
    food.retailerMemberships=[];food.currentState='unknown';food.availabilityEvidence={listingState:'unknown',currentAvailability:'unknown',reason:'Community brand metadata is not current retailer listing evidence.'};
    food.conceptIds=item.conceptIds||[];
    food.sourceCategories=[...record.categories];food.category=policy.categories.find(c=>c.id===item.categoryId).label;
    food.sourceAttribution=manifest.licence;
    // Retain source identity even for an invalid barcode, but never use it for a
    // GTIN join. Such a row is kept in the completion report, outside browsing.
    const valid=validGtin(record.barcode),eligibility=C.productEligibility(food),gaps=[];
    if(!record.quantity)gaps.push('pack-size-not-recorded');
    if(!record.servingSize)gaps.push('serving-size-not-recorded');
    if(food.physicalForm==='unknown')gaps.push('physical-form-not-resolved-use-existing-grams');
    if(!valid)gaps.push('invalid-gtin-not-admitted');
    const unitConflict=food.quarantinedMeasures?.some(m=>m.rejectionReason==='source-serving-unit-conflicts-with-nutrition-basis');
    if(unitConflict)gaps.push('serving-unit-conflict');
    if(food.quarantinedMeasures?.length&&!unitConflict)gaps.push('unsupported-or-equivalent-measures-omitted-by-shared-layer');
    const reviewed=item.deferReason||null;if(reviewed)gaps.push(reviewed);
    food.browseEligible=valid&&!reviewed&&!unitConflict&&eligibility.addability.status==='loggable-now';
    return {item,record,food,eligibility,gaps};
  });
  return {policy,rows};
}
function outputs(){
  const {policy,rows}=derive(),files=[],entries=[],out={};
  for(let i=0;i<rows.length;i+=8){const file='products/'+String(i/8).padStart(2,'0')+'.json',records=rows.slice(i,i+8).map(r=>r.food),raw=JSON.stringify({attribution:policy.licence,records})+'\n';out[file]=raw;files.push({path:file,sha256:hash(raw),records:records.length});
    for(const food of records)entries.push(Object.fromEntries(['id','barcode','recordType','market','brand','name','aliases','conceptIds','retailerMemberships','privateLabelCollections','browseEligible'].map(key=>[key,food[key]]).concat([['shard',file]])));
  }
  const index={schemaVersion:1,retailer:policy.retailer,categories:policy.categories,selectableOnly:true,entries,files,base:'./data/coles-au/',sourceDigest:hash(JSON.stringify(policy)),licence:policy.licence};
  out['../../coles-au-catalogue.js']="/* Generated by scripts/build_coles_catalogue.js. Open Food Facts contributors; ODbL/DbCL. */\n(function(global){'use strict';const index="+JSON.stringify(index)+";const adapter=global.HECRetailerSource||(typeof require==='function'?require('./retailer-source.js'):null);const registration=adapter.register(index);global.HECColesAustralia={index,registration};if(typeof module!=='undefined'&&module.exports)module.exports={index,registration};})(typeof window!=='undefined'?window:globalThis);\n";
  const report={schemaVersion:1,mode:'private-testing-community-brand-collection',source:policy.source,licence:policy.licence,rawEvidenceRows:rows.length,canonicalIdentities:new Set(rows.map(r=>C.canonicalKey(r.food))).size,newCanonicalIdentities:0,existingOFFIdentitiesEnriched:rows.length,verifiedRetailerMemberships:0,nationalBrandProducts:0,sourceDeclaredColesBrandProducts:rows.length,independentlyVerifiedPrivateLabelProducts:0,loggableNow:rows.filter(r=>r.eligibility.addability.status==='loggable-now').length,ordinaryBrowseProducts:rows.filter(r=>r.food.browseEligible).length,incompleteOrRestricted:rows.filter(r=>r.eligibility.addability.status!=='loggable-now').length,materialEvidenceConflicts:rows.filter(r=>C.sourceConflicts(r.food).some(c=>c.severity==='material')).length,nutritionReviewRequired:rows.filter(r=>r.food.nutritionIntegrity?.status==='suspect').length,identityOnly:rows.filter(r=>r.food.nutritionIntegrity?.status==='identity-only').length,reviewDeferredDespiteSharedLoggability:rows.filter(r=>r.eligibility.addability.status==='loggable-now'&&!r.food.browseEligible).length,verifiedGtins:0,checksumValidSourceGtins:rows.filter(r=>validGtin(r.record.barcode)).length,crossRetailerCompatibleMerges:0,unsafeMergeRejections:0,countNotes:'GTIN checksums validate identifier structure, not independent package verification. Loggable Now uses unchanged shared eligibility; ordinary browse additionally requires reviewed identity/basis. Restricted and nutrition-review counts can overlap. No new listing or current stock claim.',categories:policy.categories.map(c=>({...c,retained:rows.filter(r=>r.item.categoryId===c.id).length,ordinaryBrowse:rows.filter(r=>r.item.categoryId===c.id&&r.food.browseEligible).length})),coverageGaps:policy.coverageGaps,products:rows.map(({item,record,food,eligibility,gaps})=>({id:record.id,ref:item.ref,sourceUrl:record.sourceUrl,brand:record.brand,name:record.name,barcode:record.barcode,pack:record.quantity||null,serving:record.servingSize||null,lastModified:record.lastModified,nutritionBasis:record.nutritionBasis,nutritionState:'not separately recorded by the pinned import',status:eligibility.addability,ordinaryBrowse:food.browseEligible,nutritionIntegrity:food.nutritionIntegrity,conflicts:C.sourceConflicts(food),gaps,measures:food.units,categoryId:item.categoryId}))};
  out['coverage-gap-manifest.json']=JSON.stringify(report,null,2)+'\n';return out;
}
function build({check=false}={}){const out=outputs();for(const [relative,raw] of Object.entries(out)){const file=path.resolve(base,relative);if(check){if(!fs.existsSync(file)||fs.readFileSync(file,'utf8')!==raw)throw Error('Stale generated Coles output: '+relative);}else{fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,raw);}}return JSON.parse(out['coverage-gap-manifest.json']);}
if(require.main===module){const report=build({check:process.argv.includes('--check')});console.log(JSON.stringify({records:report.rawEvidenceRows,loggableNow:report.loggableNow,browse:report.ordinaryBrowseProducts,restricted:report.incompleteOrRestricted,categories:report.categories}));}
module.exports={derive,outputs,build,validGtin};
