'use strict';
// Offline derivation only. This builder never refreshes protected source data.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),C=require('../food-catalogue'),S=require('../serving-foundation'),sources=require('../food-sources');
const read=file=>JSON.parse(fs.readFileSync(path.join(root,file),'utf8'));
const slug=value=>C.norm(value).replace(/\s+/g,'-');
const hash=value=>crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex');
function energy(values){const result={...Object.fromEntries(['energyKj','calories','protein','carbs','fat','satFat','fibre','sugar','sodium'].map(key=>[key,null])),...values};if(result.energyKj!=null&&result.calories==null)result.calories=Math.round(result.energyKj/4.184*10)/10;return result;}
function convert(raw,source){
  const conflicts=C.sourceConflicts(raw),material=conflicts.some(item=>item.severity==='material'),serve=raw.manufacturerServing,restaurant=source.sourceType==='official-au-restaurant',servingUsable=!!serve&&!material&&raw.nutritionPerServing.energyKj!=null,nutrition=energy(servingUsable?raw.nutritionPerServing:raw.nutritionPer100),per100=energy(raw.nutritionPer100),id=`supplemental:${source.id}:${slug(raw.sourceRecordId)}`,nonspecific=raw.flags.some(flag=>['source-text-encoding-uncertain','source-menu-serving-unavailable'].includes(flag.code));
  const food={id,canonicalId:id,measureEvidencePolicy:'source-and-published-standard-only',recordType:restaurant?'food-source':'packaged',sourceCatalogueId:source.id,sourceId:raw.sourceRecordId,name:raw.name,brand:raw.brand,market:'AU',country:'Australia',category:raw.category,categoryMemberships:[raw.category],familyId:`${C.brandKey(raw.brand)}:${slug(raw.family||C.canonicalName(raw))}`,familyName:raw.family||C.canonicalName(raw),productFamily:raw.family||null,aliases:[raw.name],barcode:raw.barcode||null,pack:raw.pack,packageSize:raw.pack?`${raw.pack.amount} ${raw.pack.unit}`:'',servingsPerPack:raw.servingsPerPack,currentState:raw.currentState,manufacturerServing:servingUsable?serve:null,sourceServingEvidence:serve,sourceNutritionEvidence:raw.nutrientEvidence,nutrients:nutrition,nutritionPer100:per100,nutritionPer100Unit:'g',defaultUnit:servingUsable?'serve':'g',defaultAmount:servingUsable?1:100,units:servingUsable?{serve:1,g:1/serve.amount}:{g:.01},unitLabels:servingUsable?{serve:`Manufacturer serve (${serve.amount} g)`,g:'g'}:{g:'g'},serving:servingUsable?`Source serving ${serve.amount} g`:'Nutrition reference per 100 g',verified:true,verificationStatus:'verified',nutritionStatus:material?'needs-review':nonspecific?'unavailable':Object.values(nutrition).some(value=>value==null)?'partial':'complete',loggable:!material&&!nonspecific&&nutrition.energyKj!=null,source:`${restaurant?'Official Australian restaurant nutrition':'Official Australian manufacturer nutrition'} · checked ${raw.provenance.retrievedAt.slice(0,10)}`,sourceUrl:raw.provenance.url,sourceProvenance:{sourceId:source.id,recordId:raw.sourceRecordId,trustClass:source.sourceType,url:raw.provenance.url,retrievedAt:raw.provenance.retrievedAt,verifiedAt:raw.provenance.retrievedAt.slice(0,10),sha256:raw.provenance.sha256,publishedDate:raw.provenance.publishedDate||null,page:raw.provenance.page||null},evidenceConflicts:conflicts,evidenceFlags:raw.flags,rawSourceReference:{id:raw.sourceRecordId,sourceId:source.id},score:6};
  if(raw.foodForm)food.physicalForm=raw.foodForm;if(raw.measureProfile)food.measureProfile=raw.measureProfile;
  if(material){food.entryBlockedReason='The published nutrition or serving fields disagree. Complete the nutrition evidence before logging.';food.quarantinedMeasures=serve?[{key:'serve',sourceServing:serve,rejectionReason:'source-conflict'}]:[];}
  if(restaurant){food.foodSourceId=source.id;food.sourceItemId=slug(raw.canonicalSourceRecordId||raw.name);food.canonicalId=`food-source:${source.id}:${food.sourceItemId}`;food.id=food.canonicalId;food.sourceDisplayName=raw.brand;food.sourceAliases=[raw.brand];food.itemStatus='current';food.sourceType='restaurant/fast food';
    if(raw.productSemantics){
      const naturalReady=!material&&!nonspecific&&(!!serve||raw.officialNaturalServing)&&raw.nutritionPerServing.energyKj!=null,unit=raw.naturalUnit||'item';
      food.productSemantics=raw.productSemantics;food.browseCategory=raw.browseCategory;food.aliases=[...new Set([raw.name,...(raw.aliases||[])])];food.availabilityEvidence=raw.availabilityEvidence;food.menuEvidence=raw.menuEvidence||[];
      food.sourceAliases=[...new Set([raw.brand,raw.brand.replace(/ Australia$/,''),...(source.aliases||[])])];
      if(raw.sourceConceptId)food.sourceConceptId=raw.sourceConceptId;
      if(raw.choiceFamily){food.choiceFamily=raw.choiceFamily;food.choiceOrder=raw.choiceOrder;}
      food.canonicalEvidence=(raw.menuEvidence||[]).map(page=>({source:{...page.provenance,trustClass:source.sourceType},name:page.name,nutrients:page.nutritionPerServing,servingSize:page.servingSize}));
      food.nutritionPerServingProvenance=raw.nutritionPerServingProvenance||food.sourceProvenance;
      food.sourceTableReference={...food.rawSourceReference,page:raw.provenance.page,table:raw.sourceTable?.table,row:raw.sourceTable?.row};
      if(naturalReady){food.nutrients=energy(raw.nutritionPerServing);food.loggable=true;food.defaultUnit=unit;food.defaultAmount=1;food.units={[unit]:1,...(serve?.unit==='g'?{g:1/serve.amount}:{})};food.unitLabels={[unit]:raw.naturalLabel||'Item',...(serve?.unit==='g'?{g:'g'}:{})};food.serving=`1 official ${raw.naturalLabel||'item'}${serve?.unit==='g'?` (${serve.amount} g)`:''}`;food.nutritionStatus=Object.values(food.nutrients).some(value=>value==null)?'partial':'complete';}
      if(raw.productSemantics.type==='configurable-bundle'){food.loggable=false;food.nutritionStatus='configurable';food.entryBlockedReason='Meal choices are configurable; the source does not define one fixed drink and side configuration for ordinary logging.';}
      if(raw.flags.some(flag=>flag.code==='source-text-encoding-uncertain'))food.catalogueEligibility={status:'details-only',label:'Details only',reasonCode:'source-identity-uncertain',normalLoggingAllowed:false,actions:[{id:'details',label:'View Details'}],message:'The publication does not provide an unambiguous product name.'};
      if(raw.productSemantics.type==='sized-variant'){food.choiceFamily=raw.family;food.choiceOrder=['Small','Medium','Large'].indexOf(raw.productSemantics.size);}
    }
  }
  S.applyToFood(food);return food;
}
function restaurantCatalogue(source,foods){
  const date=source.discovery.retrievedAt.slice(0,10),displayName=foods[0]?.brand||source.id;
  return {source:{id:source.id,displayName,sourceType:'restaurant/fast food',country:'Australia',market:'AU',aliases:[displayName,displayName.replace(/ Australia$/,'')],officialUrl:source.directory,lastCheckedDate:date,catalogueVersion:`${source.id}-${date}.1`,catalogueCheckedAt:date,productionApproved:false,usageScope:'Local source development: attributed public nutrition facts',licenceStatus:'Public nutrition facts; source branding and source documents not redistributed',...(source.browseCategories?{inventory:{browseCategories:source.browseCategories}}:{})},items:foods.map(food=>({id:food.sourceItemId,name:food.name,aliases:food.aliases,category:food.category,browseCategory:food.browseCategory,choiceFamily:food.choiceFamily,choiceOrder:food.choiceOrder,status:'current',standardServingLabel:food.serving,serving:{unitKey:food.defaultUnit||'serve',unitLabel:food.unitLabels[food.defaultUnit]||'Source serving unavailable'},servingWeightG:food.manufacturerServing?.amount||null,servingVolumeMl:null,nutritionStatus:food.loggable?(food.nutritionStatus==='partial'?'partial':'complete'):'unavailable',loggable:food.loggable,nutritionPerServing:food.nutrients,nutritionPer100:food.nutritionPer100,provenance:{url:food.sourceUrl},entryBlockedReason:food.entryBlockedReason||'',canonicalRecord:food}))};
}
function build(){
  const input=read('data/australian-catalogue/supplemental.json'),curated=read('data/australian-catalogue/curated-products.json'),sourceMap=new Map(input.sources.map(source=>[source.id,source]));
  const rawFoods=input.records.map(row=>convert(row,sourceMap.get(row.sourceId))),foods=C.canonicaliseRecords(rawFoods),restaurant=foods.filter(food=>food.foodSourceId),packaged=foods.filter(food=>!food.foodSourceId),catalogues=input.sources.filter(source=>source.sourceType==='official-au-restaurant').map(source=>restaurantCatalogue(source,restaurant.filter(food=>food.foodSourceId===source.id)));
  for(const catalogue of catalogues)sources.normaliseCatalogue(catalogue);
  const manifest=read('data/open-food-facts-au/manifest.json'),brands=new Map();
  for(const shard of manifest.intelligenceShards){const data=read('data/open-food-facts-au/'+shard.path);for(const [key,entry] of Object.entries(data.brands||{}))brands.set(key,{name:entry.name,count:entry.refs.length});}
  for(const food of [...packaged,...curated]){const key=C.brandKey(food.brand),entry=brands.get(key)||{name:food.brand,count:0};entry.name=food.brand;entry.count++;brands.set(key,entry);}
  const data={schemaVersion:1,sourceDigest:hash(input),brands:[...brands.values()].sort((a,b)=>C.brandKey(a.name).localeCompare(C.brandKey(b.name))),packagedProducts:[...curated,...packaged],restaurantCatalogues:catalogues};
  const output='/* Generated by scripts/build_australian_catalogue.js; public composition facts and derived indexes. */\n(function(global){\n\'use strict\';\nconst data='+JSON.stringify(data)+';\nconst sources=global.HECFoodSources||(typeof require===\'function\'?require(\'./food-sources.js\'):null);\nfor(const catalogue of data.restaurantCatalogues)sources.registerCatalogue(catalogue);\nglobal.HECAustralianCatalogueData=data;\nif(typeof module!==\'undefined\'&&module.exports)module.exports=data;\n})(typeof window!==\'undefined\'?window:globalThis);\n';
  fs.writeFileSync(path.join(root,'australian-catalogue-data.js'),output);
  const report={rawRows:rawFoods.length,canonicalSupplementalProducts:foods.length,curatedProducts:curated.length,mergedRows:rawFoods.length-foods.length,brands:brands.size,sourceCounts:Object.fromEntries(input.sources.map(source=>[source.id,{raw:rawFoods.filter(food=>food.sourceCatalogueId===source.id).length,canonical:foods.filter(food=>food.sourceCatalogueId===source.id).length,loggable:foods.filter(food=>food.sourceCatalogueId===source.id&&food.loggable).length}])),sourceConflicts:foods.filter(food=>food.evidenceConflicts?.length).length,gaps:input.gaps};
  fs.writeFileSync(path.join(root,'data/australian-catalogue/build-report.json'),JSON.stringify(report,null,2)+'\n');return report;
}
if(require.main===module)console.log(JSON.stringify(build(),null,2));
module.exports={build,convert,restaurantCatalogue};
