'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),contract=require('./release-contract');
const ROOT=path.resolve(__dirname,'..'),hash=data=>crypto.createHash('sha256').update(data).digest('hex');
const START='<!-- HEC RELEASE BOOTSTRAP START -->',END='<!-- HEC RELEASE BOOTSTRAP END -->';
function build(root=ROOT,overrides={}){
  const read=file=>(overrides[file]??fs.readFileSync(path.join(root,file),'utf8')).replace(/\r\n/g,'\n');
  const html=read('index.html'),start=html.indexOf(START),end=html.indexOf(END)+END.length;
  if(start<0||end<END.length)throw Error('Release bootstrap markers missing');
  const shell=html.slice(0,start)+START+'\n'+END+html.slice(end),bootstrap=read('release-bootstrap.js'),worker=read('scripts/service-worker.template.js');
  const files=Object.fromEntries([...contract.runtime,...contract.support].map(file=>[file,hash(read(file))]));
  const roles=Object.fromEntries(['my-data','test'].map(role=>[role,Object.fromEntries(['installation-config.js','manifest.webmanifest'].map(file=>[file,hash(read(role==='test'?'deployment/test/'+file:file))]))]));
  const generation=hash(JSON.stringify({contract,files,roles,shell,bootstrap,worker})).slice(0,24);
  const release={generation,version:contract.version,runtime:contract.runtime,files,roles,optional:contract.optional};
  const builtHtml=html.slice(0,start)+START+'\n<script>\nwindow.HEC_RELEASE='+JSON.stringify(release)+';\n'+bootstrap+'\n</script>\n'+END+html.slice(end);
  const manifest={...release,files:{'index.html':hash(builtHtml),...files}};
  return {'index.html':builtHtml,'release-manifest.json':JSON.stringify(manifest,null,2)+'\n','service-worker.js':'// Generated by scripts/build_release.js. Edit scripts/service-worker.template.js.\nconst RELEASE = '+JSON.stringify(manifest)+';\n'+worker};
}
function check(root=ROOT){const wanted=build(root);return Object.keys(wanted).filter(file=>fs.readFileSync(path.join(root,file),'utf8')!==wanted[file]);}
if(require.main===module){if(process.argv.includes('--check')){const stale=check();if(stale.length){console.error('Stale generated release files: '+stale.join(', '));process.exitCode=1;}else console.log('Release generation is current');}else {for(const [file,text] of Object.entries(build()))fs.writeFileSync(path.join(ROOT,file),text);console.log('Built coherent release manifest, shell and worker');}}
module.exports={build,check,hash,ROOT,contract};
