#!/usr/bin/env node
'use strict';
/* Rebuild only derived brand/category intelligence from the committed product
   shards. This never reads or changes the raw Open Food Facts source snapshot. */
const fs=require('fs'),path=require('path');
const ROOT=path.resolve(__dirname,'..'),DATA=path.join(ROOT,'data','open-food-facts-au'),OUT=path.join(DATA,'intelligence'),SCHEMA=2;
const norm=value=>String(value||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/&/g,' and ').replace(/[’']/g,'').replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,' ');
const singular=value=>String(value||'').replace(/ies$/,'y').replace(/sses$/,'ss').replace(/([a-z]{4,})s$/,'$1');
const prefix=value=>(String(value||'').slice(0,2)+'__').slice(0,2);
function stable(value){if(Array.isArray(value))return value.map(stable);if(value&&typeof value==='object')return Object.fromEntries(Object.keys(value).sort().map(key=>[key,stable(value[key])]));return value;}
function write(file,value){const data=JSON.stringify(stable(value))+'\n';fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,data,'utf8');return Buffer.byteLength(data);}
function categoryFacet(product){const broad=new Set(['food','foods','product','products','groceries','packaged food','plant based foods and beverages','plant based foods']);return (product.categories||[]).find(value=>!broad.has(norm(value)))||product.genericName||'Other products';}
function quality(product){const name=norm(product.name),brand=norm(product.brand),energy=product.nutrients?.calories!=null||product.nutrients?.energyKj!=null,macros=['protein','carbs','fat'].filter(key=>product.nutrients?.[key]!=null).length,countries=product.countries||[];let score=0;if(name&&name!==brand&&!/^barcode \d+$/.test(name))score+=1000;else if(name===brand)score-=1000;else score-=500;if(name.split(' ').length>1)score+=80;if(brand&&(` ${name} `).includes(` ${brand} `))score+=100;if(product.genericName)score+=30;if(product.quantity)score+=20;if(product.barcode)score+=10;if(countries.length===1&&countries[0]==='en:australia')score+=220;else score-=Math.max(0,countries.length-1)*30;if(energy)score+=120+macros*20;return score;}
function conceptQuality(product,key){const name=norm(product.name),generic=singular(norm(product.genericName)),categories=(product.categories||[]).map(value=>singular(norm(value))),heads=categories.map(value=>value.split(' ').slice(-1)[0]);let score=quality(product);if(name===key)score+=2200;else if(` ${name} `.includes(` ${key} `))score+=1400;if(generic===key)score+=1100;if(categories.includes(key))score+=900;else if(heads.includes(key))score+=400;return score;}
function conceptsFor(product){const out=new Map();for(const raw of [...(product.categories||[]),product.genericName||'']){const value=norm(raw);if(!value)continue;const words=value.split(' '),head=singular(words[words.length-1]);for(const key of new Set([singular(value),head]))if(key&&key.length>1&&!/^\d+$/.test(key))out.set(key,head===key?raw.split(/[- ]/).slice(-1)[0]:raw);}return out;}
function main(){
  const manifestPath=path.join(DATA,'manifest.json'),manifest=JSON.parse(fs.readFileSync(manifestPath,'utf8')),brands=new Map(),concepts=new Map(),rank=new Map(),productsByRef=new Map();
  if(manifest.sourceSnapshotDate!=='2026-08-30'||manifest.sourceSha256!=='F72687EE8BC6522054FE69DBFDA6B91902C16AF1EC2E043CDE27BC6C29AD8176')throw new Error('Refusing to rebuild intelligence from an unapproved catalogue snapshot.');
  for(const shard of manifest.productShards){const data=JSON.parse(fs.readFileSync(path.join(DATA,shard.path),'utf8'));data.products.forEach((product,index)=>{const ref=`${path.basename(shard.path,'.json')}:${index}`;rank.set(ref,quality(product));productsByRef.set(ref,product);if(product.brandKey){const entry=brands.get(product.brandKey)||{name:product.brand||product.brandKey,refs:[],names:new Map(),facets:new Map()};entry.refs.push(ref);const nameKey=norm(product.name);if(nameKey){const nameRefs=entry.names.get(nameKey)||[];nameRefs.push(ref);entry.names.set(nameKey,nameRefs);}const label=categoryFacet(product),key=norm(label)||'other products',facet=entry.facets.get(key)||{key,label,count:0};facet.count++;entry.facets.set(key,facet);brands.set(product.brandKey,entry);}for(const [key,label] of conceptsFor(product)){const entry=concepts.get(key)||{name:label||key,refs:new Set()};entry.refs.add(ref);concepts.set(key,entry);}});}
  const groups=new Map(),group=key=>{const p=prefix(key),value=groups.get(p)||{schema:SCHEMA,brands:{},concepts:{}};groups.set(p,value);return value;};
  for(const [key,entry] of [...brands].sort(([a],[b])=>a.localeCompare(b))){entry.refs.sort((a,b)=>(rank.get(b)||0)-(rank.get(a)||0)||a.localeCompare(b));const names={};for(const [nameKey,nameRefs] of [...entry.names].sort(([a],[b])=>a.localeCompare(b)))names[nameKey]=nameRefs.sort((a,b)=>(rank.get(b)||0)-(rank.get(a)||0)||a.localeCompare(b));group(key).brands[key]={name:entry.name,refs:entry.refs,names,facets:[...entry.facets.values()].filter(facet=>facet.count>1).sort((a,b)=>b.count-a.count||a.label.localeCompare(b.label)).slice(0,24)};}
  for(const [key,entry] of [...concepts].sort(([a],[b])=>a.localeCompare(b))){const refs=[...entry.refs].sort((a,b)=>conceptQuality(productsByRef.get(b),key)-conceptQuality(productsByRef.get(a),key)||a.localeCompare(b));group(key).concepts[key]={name:entry.name,refs};}
  if(path.basename(OUT)!=='intelligence'||path.dirname(OUT)!==DATA)throw new Error('Unsafe intelligence output path.');
  fs.rmSync(OUT,{recursive:true,force:true});fs.mkdirSync(OUT,{recursive:true});const files=[];
  for(const [key,value] of [...groups].sort(([a],[b])=>a.localeCompare(b))){const relative=`intelligence/${key}.json`,bytes=write(path.join(DATA,relative),value);files.push({path:relative,brands:Object.keys(value.brands).length,concepts:Object.keys(value.concepts).length,bytes});}
  manifest.intelligenceShards=files;manifest.searchIntelligence={schemaVersion:SCHEMA,builder:'scripts/build_off_search_intelligence.js',derivedFromCommittedProducts:true,brands:brands.size,concepts:concepts.size,files:files.length,bytes:files.reduce((sum,item)=>sum+item.bytes,0)};
  const generated=[...manifest.productShards,...manifest.searchShards,...manifest.brandShards,...manifest.barcodeShards,...files];manifest.generatedShardCount=generated.length;manifest.generatedBytes=generated.reduce((sum,item)=>sum+item.bytes,0);manifest.largestShardBytes=Math.max(...generated.map(item=>item.bytes));manifest.averageShardBytes=Math.round(manifest.generatedBytes/generated.length);
  write(manifestPath,manifest);console.log(JSON.stringify({snapshot:manifest.sourceSnapshotDate,products:manifest.importedProducts,brands:brands.size,concepts:concepts.size,files:files.length,bytes:manifest.searchIntelligence.bytes,largestBytes:Math.max(...files.map(item=>item.bytes)),manifestBytes:fs.statSync(manifestPath).size},null,2));
}
if(require.main===module)main();
module.exports={norm,singular,categoryFacet,quality,conceptQuality,conceptsFor,main};
