'use strict';
// Reuses accepted canonical products; official family evidence never supplies nutrition.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),zlib=require('node:zlib');
const C=require('../food-catalogue'),S=require('../serving-foundation'),SEM=require('./food-category-semantics'),X=require('./catalogue-round-two');
const ROOT=path.resolve(__dirname,'..'),BASE=path.join(ROOT,'data/catalogue-wave-4a'),read=n=>JSON.parse(fs.readFileSync(path.join(BASE,n),'utf8'));
function inputs(){const policy=read('policy.json');for(const [f,h]of Object.entries(policy.inputs))assert.equal(X.hash(fs.readFileSync(path.join(BASE,f))),h,'Reviewed input changed: '+f);
 for(const c of [...read('public-captures.json'),...read('supplemental-captures.json')]){if(!c.file)continue;const raw=fs.readFileSync(path.join(BASE,c.file));assert.equal(X.hash(c.file.endsWith('.gz')?zlib.gunzipSync(raw):raw),c.sha256);}
 return {policy,manifest:read('candidate-manifest.json'),evidence:read('reviewed-evidence.json'),baseline:read('baseline-records.json'),independent:read('independent-baseline.json')};}
function derive(){const input=inputs(),{manifest,evidence,baseline,independent,policy}=input,products=[],reviews=[];
 assert(manifest.candidates.length<=80);assert.equal(new Set(manifest.candidates.map(c=>c.canonicalKey)).size,manifest.candidates.length);
 for(const [g,max]of Object.entries(manifest.groupLimits))assert(manifest.candidates.filter(c=>c.group===g).length<=max);
 for(const candidate of manifest.candidates){const decision=evidence.reviews.find(r=>r.candidateId===candidate.candidateId);assert(decision);const review={...candidate,...decision,canonicalOverlap:candidate.overlap,duplicateEvidenceCollapsed:0};reviews.push(review);if(decision.disposition!=='improved')continue;
  const prior=[...baseline.approved,...independent].find(f=>C.canonicalKey(f)===candidate.canonicalKey);assert(prior);assert(C.canLog(prior));const food=structuredClone(prior);
  const category=decision.recategorise?SEM.reviewedFamily(food):null;if(decision.recategorise)assert(category,'No shared category rule');
  if(category){food.categoryId=category.id;food.browseCategoryId=category.id;food.category=require('../data/woolworths-au/source-policy.json').categories.find(c=>c.id===category.id).label;food.conceptIds=category.conceptIds;food.categoryEvidence={wave:'4A',rule:category.rule,candidateId:candidate.candidateId,projectionOnly:true};review.category={before:prior.categoryId,after:category.id,rule:category.rule};}
  const stamp={trustClass:'official-au-retailer',sourceId:'iga-au-wave-4a',recordId:candidate.candidateId,retrievedAt:evidence.checkedAt,sha256:policy.inputs['reviewed-evidence.json'],hashBasis:'reviewed-public-source-facts',privateTestingApproved:true,publicReleaseReviewRequired:true};
  if(candidate.group==='C'){
   const listing=evidence.storeListings.find(e=>e.id==='pepsi-mansfield');assert.equal(food.brand,listing.brand);assert.deepEqual(food.pack,listing.pack);
   const member={retailerId:'iga',market:'AU',scope:'food',verified:true,categoryIds:[food.categoryId],listingState:'listed-at-retrieval',availabilityScope:'store',bannerId:listing.bannerId,storeId:listing.storeId,storeName:listing.storeName,storeAddress:listing.address,broaderAvailability:'unknown',currentAvailability:'unknown',evidence:{...stamp,url:listing.url,recordId:listing.id,acquisition:listing.acquisition,directHttpUsable:false,identityMatch:listing.identityMatch}};
   food.retailerMemberships=[...(food.retailerMemberships||[]),member];assert.equal(C.privateLabelCollectionMembership(food,'iga').length,0);assert.equal(C.commercialIdentityMembership({id:'iga',type:'retailer'},food).matches,false);
  }else{
   const family=evidence.relationships.find(f=>f.brandKey===C.brandKey(food.brand));assert(family);const raw=baseline.associated.find(p=>p.record.barcode===food.barcode);assert(raw);assert.deepEqual(raw.record.countries,['en:australia']);
   const relationship={...stamp,url:evidence.sources.find(s=>s.id==='iga-brands').url,houseBrandRelationship:{retailerId:'iga',brandKey:family.brandKey,status:family.status,relationshipVerified:true,commercialProvider:family.commercialProvider,relationship:family.relationship,scope:'retailer-family',evidenceIds:family.evidenceIds},productEvidence:{recordId:raw.record.id,sha256:X.hash(JSON.stringify(raw.record)),countriesTags:raw.record.countries},sourceCaptures:evidence.sources.filter(s=>family.evidenceIds.includes(s.id)).map(s=>({id:s.id,url:s.url,sha256:s.sha256,retrievedAt:s.retrievedAt}))};
   food.privateLabelCollections=[...(food.privateLabelCollections||[]),{retailerId:'iga',market:'AU',scope:'food',basis:'official-house-brand-relationship',verified:true,consumerBrand:food.brand,categoryIds:[food.categoryId],availabilityScope:'retailer-family-relationship',currentAvailability:'unknown',broaderAvailability:'unknown',evidence:relationship}];
   assert.equal(C.privateLabelCollectionMembership(food,'iga').length,1);assert.equal(C.retailerMembership(food,'iga').length,0,'Family relationship is not product listing');
  }
  food.catalogueWave4A={candidateId:candidate.candidateId,privateTestingApproved:true,publicReleaseReviewRequired:true,checkedAt:evidence.checkedAt,nutrition:'Unchanged accepted canonical evidence; official relationship does not upgrade nutrition trust'};
  for(const k of ['id','barcode','brand','name','nutrients','units','unitLabels','sourceProvenance','sourceNutritionBasis','manufacturerServing','nutritionPer100Unit'])assert.deepEqual(food[k],prior[k],food.name+' '+k);
  assert(require('./build_coles_catalogue').validGtin(food.barcode));assert(C.canLog(food));assert(!C.sourceConflicts(food).some(c=>c.severity==='material'&&(!c.resolution||c.resolution==='unresolved')));
  const measures=S.servingMeasureProfile(food).measures;assert(measures.length);if(food.nutritionPer100Unit==='g')assert(!measures.some(m=>['mL','L','cup'].includes(m.key)));products.push(food);
 }
 const groups=Object.fromEntries(['A','B','C','D'].map(group=>{const r=reviews.filter(r=>r.group===group),count=p=>r.filter(p).length;const g={reviewed:r.length,newCanonicalAdmitted:0,existingImproved:count(r=>r.disposition==='improved'),newlyRetailerLinked:count(r=>r.newlyRetailerLinked),recategorised:count(r=>r.recategorise),held:count(r=>r.disposition==='held'),deferredRejected:count(r=>r.disposition==='deferred'),canonicalOverlap:count(r=>r.canonicalOverlap),duplicateEvidenceCollapsed:0};assert.equal(g.reviewed,g.existingImproved+g.held+g.deferredRejected);return [group,g];}));return {groups,reviews,products,input};}
function augment(out){const {products}=derive(),file='../../brand-au-catalogue.js',match=out[file].match(/const index=(.*?);if\(typeof module/s);assert(match);const index=JSON.parse(match[1]),patches=new Map(products.map(f=>[C.canonicalKey(f),f])),fields=['privateLabelCollections','retailerMemberships','catalogueWave4A','categoryId','browseCategoryId','category','conceptIds','categoryEvidence'];
 for(const shard of index.files){const data=JSON.parse(out[shard.path]);let changed=false;for(const f of data.records){const patch=patches.get(C.canonicalKey(f));if(!patch)continue;for(const k of ['id','barcode','name','brand','nutrients','units','sourceProvenance'])assert.deepEqual(f[k],patch[k]);for(const k of fields)if(patch[k]!==undefined)f[k]=patch[k];changed=true;}if(changed){out[shard.path]=X.bytes(data);shard.sha256=X.hash(out[shard.path]);}}
 for(const entry of index.entries){const patch=patches.get(C.canonicalKey(entry));if(patch)for(const key of ['privateLabelCollections','retailerMemberships','categoryId','browseCategoryId','conceptIds'])if(patch[key]!==undefined)entry[key]=patch[key];}
 index.wave4A={reviewed:32,existingImproved:products.length,newCanonical:0,publicReleaseReviewRequired:true};out[file]=out[file].replace(match[1],JSON.stringify(index));out['wave-4a-report.json']=X.bytes(index.wave4A);return out;}
module.exports={inputs,derive,augment};
