'use strict';
// Deterministic evidence adapter for the existing canonical/retailer architecture.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),zlib=require('node:zlib');
const C=require('../food-catalogue'),O=require('../off-catalogue'),S=require('../serving-foundation'),X=require('./catalogue-round-two'),SEM=require('./food-category-semantics');
const ROOT=path.resolve(__dirname,'..'),BASE=path.join(ROOT,'data/catalogue-wave-3a');
const read=n=>JSON.parse(fs.readFileSync(path.join(BASE,n),'utf8'));
function inputs(){
 const policy=read('policy.json');for(const [file,hash]of Object.entries(policy.inputs))assert.equal(X.hash(fs.readFileSync(path.join(BASE,file))),hash,'Changed reviewed input: '+file);
 const manifest=read('candidate-manifest.json'),peers=read('baseline-peers.json'),facts=read('reviewed-evidence.json'),captures=read('public-captures.json');
 assert(manifest.candidates.length<=70);assert.equal(new Set(manifest.candidates.map(c=>c.canonicalKey)).size,manifest.candidates.length);
 for(const [group,limit]of Object.entries(manifest.groupLimits))assert(manifest.candidates.filter(c=>c.group===group).length<=limit);
 const cache=new Map();for(const p of peers.records){if(!cache.has(p.file)){const raw=fs.readFileSync(path.join(ROOT,p.file));assert.equal(X.hash(raw),p.sha256);cache.set(p.file,JSON.parse(raw));}assert.deepEqual(cache.get(p.file).products[p.row],p.record);}
 for(const capture of [...captures.records,...read('manufacturer-captures.json')]){if(capture.status!==200)assert(capture.webReaderCheckedAt&&capture.directHttpUsable===false,'Failed HTTP capture is not nutrition evidence');assert.equal(X.hash(zlib.gunzipSync(fs.readFileSync(path.join(BASE,capture.file)))),capture.sha256);for(const asset of [...(capture.images||[]),...(capture.highResolution?[capture.highResolution]:[])])assert.equal(X.hash(fs.readFileSync(path.join(BASE,asset.file))),asset.sha256);}
 return {policy,manifest,peers,facts,captures,baseline:read('baseline-records.json'),resolution:read('identity-resolution.json')};
}
function product(fact,input){
 const capture=input.captures.records.find(c=>c.id===fact.candidateId),panel=capture.images[fact.panelImage-1];assert(panel);
 const evidence={trustClass:fact.nutritionTrustClass||'official-au-retailer',sourceId:fact.nutritionTrustClass?'pepsi-au-package':'aldi-au-wave-3a',recordId:fact.gtin,url:panel.url,retailerPage:capture.url,retrievedAt:capture.retrievedAt,checkedAt:input.facts.checkedAt,sha256:panel.sha256,sourceSnapshotDate:null,publishedDate:null,formulationDate:null,sourceCurrentness:'package-image-at-capture; local stock unknown',privateTestingApproved:true,publicReleaseReviewRequired:true};
 const listing={...evidence,trustClass:'official-au-retailer',sourceId:'aldi-au-wave-3a',recordId:capture.url.split('-').at(-1),url:capture.url,sha256:capture.sha256,hashBasis:capture.hashBasis};
 const nutrients={...fact.per100};if(nutrients.calories===null)nutrients.calories=nutrients.energyKj/4.184;
 const categories=[...require('../data/woolworths-au/source-policy.json').categories,...X.extraCategories],category=categories.find(c=>c.id===fact.categoryId);assert(category);
 const food={id:'package:au:'+fact.gtin,canonicalId:'barcode:'+fact.gtin,barcode:fact.gtin,sourceBarcode:fact.rawGtin,recordType:'packaged',market:'AU',country:'Australia',name:fact.name,brand:fact.brand,sourceBrands:fact.sourceBrand||fact.brand,sourceBrandTokens:[{key:C.brandKey(fact.brand),name:fact.brand}],aliases:fact.sourceName?[fact.sourceName]:[],sourceId:fact.gtin,sourceCatalogueId:evidence.sourceId,source:'Verified Australian package panel',sourceUrl:evidence.url,sourceProvenance:evidence,verified:true,verificationStatus:'verified',privateTestingApproved:true,publicReleaseReviewRequired:true,browseEligible:true,currentState:'unknown',categoryId:fact.categoryId,browseCategoryId:fact.categoryId,category:category.label,conceptIds:fact.conceptIds,pack:fact.pack,packageSize:fact.pack.amount+' '+fact.pack.unit,nutrients,nutritionPer100:{...nutrients},nutritionPer100Unit:fact.nutritionUnit,sourceNutritionBasis:{basis:'per-100',amount:100,unit:fact.nutritionUnit,state:fact.nutritionState},sourceNutritionEvidence:{rawHeading:fact.rawNutritionHeading,per100:fact.per100,sha256:panel.sha256},nutritionBasisNote:fact.nutritionState,preparationContext:fact.nutritionState,manufacturerServing:fact.manufacturerServing,sourceServingEvidence:{text:fact.manufacturerServing.text,servingsPerPack:fact.servingsPerPack},servingsPerPack:fact.servingsPerPack,packageServingText:fact.manufacturerServing.text,packageServingExplicit:true,serving:'Per 100 '+fact.nutritionUnit+'; '+fact.nutritionState,defaultUnit:'serve',defaultAmount:1,units:{[fact.nutritionUnit]:.01,serve:fact.manufacturerServing.amount/100},unitLabels:{[fact.nutritionUnit]:fact.nutritionUnit==='g'?'g (prepared by boiling)':'mL',serve:'Manufacturer serve ('+fact.manufacturerServing.text+')'},physicalForm:fact.physicalForm,physicalFormSource:'Verified Australian package and explicit nutrition unit',measureEvidencePolicy:'source-and-published-standard-only',nutritionStatus:'usable',loggable:true,evidenceFlags:[],evidenceConflicts:[],retailerMemberships:[{retailerId:'aldi',market:'AU',scope:'food',verified:true,currentAvailability:'unknown',categoryIds:[fact.categoryId],listingState:'listed-at-capture',evidence:listing}],privateLabelCollections:[],commercialIdentities:[],availabilityEvidence:{currentAvailability:'unknown',listingState:'listed-at-capture',reason:'Official page checked; no nationwide stock assertion'},fieldProvenance:{identity:listing,nutrition:evidence,serving:evidence,retailerPresence:listing},catalogueReview:{wave:'3A',candidateId:fact.candidateId,checkedAt:input.facts.checkedAt,disposition:fact.decision,publicReleaseReviewRequired:true},identityEvidence:{rawGtin:fact.rawGtin,validatedGtin:fact.gtin,packageImage:fact.identityImage==='highResolution'?capture.highResolution:capture.images[fact.identityImage-1],independentCorroboration:fact.independentEvidence||null}};
 if(fact.candidateId.includes('-C-')){
  const prior=input.peers.records.find(p=>p.record.barcode===fact.gtin);assert(prior);assert.deepEqual(prior.record.nutrients,{},'No unresolved same-GTIN panel may be overwritten');assert.equal(C.brandKey(prior.record.brand),C.brandKey(fact.brand));
  assert(fact.rawRelationship.includes('registered trademark of ALDI Stores'));
  const relationship={...listing,houseBrandRelationship:{retailerId:'aldi',brandKey:C.brandKey(fact.brand),status:'current',relationshipVerified:true,rawWording:fact.rawRelationship},productEvidence:{recordId:prior.record.id,sha256:prior.sha256,countriesTags:prior.record.countries},packageEvidence:evidence};
  food.privateLabelCollections=[{retailerId:'aldi',market:'AU',scope:'food',basis:'official-house-brand-relationship',verified:true,consumerBrand:food.brand,currentAvailability:'unknown',categoryIds:[fact.categoryId],evidence:relationship}];food.fieldProvenance.ownership=relationship;
  food.canonicalEvidence=[{source:C.sourceEvidence(O.toFood(prior.record)),recordId:prior.record.id,canonicalId:food.canonicalId,retainedSource:prior}];
 }
 food.brandAdmission={status:'audited-wave-3a',evidenceSha256:input.policy.inputs['reviewed-evidence.json']};
 S.applyToFood(food);assert(C.canLog(food),JSON.stringify(C.productEligibility(food)));assert(require('./build_coles_catalogue').validGtin(food.barcode));
 if(fact.candidateId.includes('-D-')){assert.equal(C.privateLabelCollectionMembership(food,'aldi').length,0);assert.equal(C.retailerMembership(food,'aldi').length,1);}
 else assert.equal(C.privateLabelCollectionMembership(food,'aldi').length,1);
 assert(!C.sourceConflicts(food).some(c=>c.severity==='material'&&(!c.resolution||c.resolution==='unresolved')));
 return food;
}
function derive(){
 const input=inputs(),admissions=[],seen=new Set();
 const reviews=input.manifest.candidates.map(c=>{
  const fact=input.facts.records.find(f=>f.candidateId===c.candidateId),resolved=input.resolution.records.find(r=>r.candidateId===c.candidateId),canonicalKey=resolved?.canonicalKey||c.canonicalKey;assert(!seen.has(canonicalKey),'Resolved duplicate candidate');seen.add(canonicalKey);
  const base={...c,canonicalKey,sourceReviewKey:c.canonicalKey,privateTestingApproved:false,publicReleaseReviewRequired:true,checkedAt:input.facts.checkedAt,evidenceHash:input.policy.inputs['reviewed-evidence.json'],canonicalOverlap:c.group==='A'||c.group==='B'||!!resolved?.overlap,possibleOverlapKeys:c.possibleOverlapKeys||[],duplicateEvidenceCollapsed:0,newCanonicalIdentity:false,recategorised:false};
  if(c.group==='A'){const familyFact=input.facts.records.find(f=>f.rawRelationship?.includes('registered trademark of ALDI Stores')&&C.brandKey(f.brand)===c.family);return {...base,disposition:'restricted',unresolved:true,reason:fact?.reason||(familyFact?'New official package evidence verifies the family relationship; this selected GTIN still lacks complete nutrition or a safe serving basis. Original product hold remains.':'Retained hold: '+c.priorReasons.join('; ')+'. No exact compatible replacement evidence established.'),familyCorroboration:familyFact?{candidateId:familyFact.candidateId,rawRelationship:familyFact.rawRelationship,evidenceHash:base.evidenceHash}:null,evidence:fact||null};}
  if(c.group==='B'){const old=input.baseline.aldi.other.find(f=>C.canonicalKey(f)===c.canonicalKey);assert.equal(X.hash(JSON.stringify(old)),c.baselineSha256);const category=SEM.additionalFallbackFamily(old);assert(category,'Enrolled semantic rule missing: '+c.name);return {...base,disposition:'improved',recategorised:true,category,reason:category.rule,privateTestingApproved:true};}
  assert(fact);if(fact.decision==='deferred')return {...base,disposition:'deferred',unresolved:true,reason:fact.reason,evidence:fact};
  assert(resolved&&fact.gtin===resolved.gtin);const food=product(fact,input);admissions.push(food);return {...base,disposition:resolved.overlap?'improved':'admitted',newCanonicalIdentity:!resolved.overlap,newlyLoggable:true,privateTestingApproved:true,duplicateEvidenceCollapsed:resolved.overlap?1:0,reason:fact.reason,evidence:fact,measures:S.servingMeasureProfile(food).measures.map(m=>({key:m.key,label:m.label}))};
 });
 const groups=Object.fromEntries(['A','B','C','D'].map(group=>{const rows=reviews.filter(r=>r.group===group),count=p=>rows.filter(p).length;const g={reviewed:rows.length,newCanonicalAdmitted:count(r=>r.disposition==='admitted'),existingCanonicalImproved:count(r=>r.disposition==='improved'),recategorised:count(r=>r.recategorised),restricted:count(r=>r.disposition==='restricted'),deferredRejected:count(r=>r.disposition==='deferred'),canonicalOverlaps:count(r=>r.canonicalOverlap),duplicateEvidenceCollapsed:rows.reduce((n,r)=>n+r.duplicateEvidenceCollapsed,0)};assert.equal(g.reviewed,g.newCanonicalAdmitted+g.existingCanonicalImproved+g.restricted+g.deferredRejected);return [group,g];}));
 return {schemaVersion:1,wave:'3A',startingHead:input.manifest.startingHead,candidateCount:reviews.length,groups,newCanonicalIdentities:reviews.filter(r=>r.newCanonicalIdentity).length,newlyLoggable:admissions.length,reviews,admissions,inputHashes:input.policy.inputs};
}
function augment(out,kind){
 const report=derive(),reviews=new Map(report.reviews.map(r=>[r.canonicalKey,r])),file='../../'+kind+'-au-catalogue.js',script=out[file],match=script.match(/const index=(.*?);(?:const adapter|if\(typeof module)/s);assert(match);
 const index=JSON.parse(match[1]),byId=new Map(),keys=new Set(),changes=[];
 const categories=[...require('../data/woolworths-au/source-policy.json').categories,...X.extraCategories];
 for(const shard of index.files){const data=JSON.parse(out[shard.path]);for(const food of data.records){const key=C.canonicalKey(food);keys.add(key);const before=food.browseCategoryId||food.categoryId,category=before==='other-food'&&food.browseEligible!==false&&C.canLog(food)?SEM.additionalFallbackFamily(food):null;
  if(category){if(kind==='aldi'&&C.privateLabelCollectionMembership(food,'aldi').length)assert.equal(reviews.get(key)?.group,'B','Unenrolled Aldi category identity');changes.push({canonicalKey:key,id:food.id,name:food.name,brand:food.brand,before,after:category.id,rule:category.rule,source:C.sourceEvidence(food)});food.categoryId=category.id;food.browseCategoryId=category.id;food.category=categories.find(c=>c.id===category.id).label;food.conceptIds=category.conceptIds;food.categoryEvidence={wave:'3A',rule:category.rule,projectionOnly:true,source:C.sourceEvidence(food)};}
  byId.set(food.id,food);
 }out[shard.path]=X.bytes(data);shard.sha256=X.hash(out[shard.path]);}
 const extra=report.admissions.filter(f=>(kind==='brand'||kind==='aldi'&&C.privateLabelCollectionMembership(f,'aldi').length)&&!keys.has(C.canonicalKey(f)));
 if(extra.length){const relative='products/wave-3a-000.json';out[relative]=X.bytes({records:extra});index.files.push({path:relative,sha256:X.hash(out[relative]),records:extra.length});for(const food of extra){byId.set(food.id,food);index.entries.push({id:food.id,shard:relative});}}
 for(const entry of index.entries){const food=byId.get(entry.id),isNew=extra.includes(food);if(!isNew&&!changes.some(c=>c.id===food.id))continue;const fields=isNew?['canonicalId','barcode','recordType','market','brand','name','aliases','conceptIds','retailerMemberships','privateLabelCollections','commercialIdentities','browseEligible','browseCategoryId']:['conceptIds','browseCategoryId'];for(const key of fields)if(food[key]!==undefined)entry[key]=food[key];if(kind==='brand'){entry.categoryId=food.categoryId;if(isNew){entry.brandKeys=food.sourceBrandTokens.map(b=>b.key);entry.pack=food.packageSize;entry.sourceBrands=food.sourceBrands;}}}
 for(const food of extra){if(!index.categories.some(c=>c.id===food.categoryId))index.categories.push(categories.find(c=>c.id===food.categoryId));if(kind==='brand'){let brand=index.brands.find(b=>b.key===C.brandKey(food.brand));if(!brand){brand={key:C.brandKey(food.brand),name:food.brand,aliases:[food.brand],count:0,tier:'private-testing'};index.brands.push(brand);}brand.count++;}else if(!index.retailer.houseBrandFamilies.some(b=>b.key===C.brandKey(food.brand)))index.retailer.houseBrandFamilies.push({key:C.brandKey(food.brand),name:food.brand,status:'current',evidenceIds:[food.catalogueReview.candidateId]});}
 changes.sort((a,b)=>a.canonicalKey.localeCompare(b.canonicalKey)||a.id.localeCompare(b.id));index.wave3A={candidateManifestSha256:report.inputHashes['candidate-manifest.json'],reviewed:report.candidateCount,addedToProjection:extra.length,categoryChanges:changes.length,publicReleaseReviewRequired:true};
 out[file]=script.replace(match[1],JSON.stringify(index));out['wave-3a-report.json']=X.bytes({kind,...index.wave3A,changes});return out;
}
if(require.main===module){const report=derive(),raw=JSON.stringify({...report,admissions:report.admissions.map(f=>({id:f.id,canonicalKey:C.canonicalKey(f),brand:f.brand,name:f.name}))},null,2)+'\n';if(process.argv.includes('--check'))assert.equal(fs.readFileSync(path.join(BASE,'review-report.json'),'utf8'),raw);else fs.writeFileSync(path.join(BASE,'review-report.json'),raw);console.log(JSON.stringify({groups:report.groups,newlyLoggable:report.newlyLoggable}));}
module.exports={inputs,derive,augment,product};
