const fs=require('fs'),crypto=require('crypto'),path=require('path');const root=path.resolve('data/catalogue-round-three');
const sources=[
{id:'aldi-2025',url:'https://www.aldiunpacked.com.au/from-aisle-to-idol-its-time-to-crown-australias-favourite-aldi-finds-as-voting-for-the-peoples-picks-2025-opens/',relationship:'Official ALDI exclusive core-range shortlist; does not verify current stock or every product formulation.',brands:['Choceur','Regal','Specially Selected','Sweet Haven','Bakers Life','Expressi','Farmwood','Yoguri','Lazzio','Sprinters','Emporium Selection','Westacre Dairy','Orchard & Vine','Jindarra Station','The Fresh Salad Co','Colway','Ready, Set... Cook!','Urban Eats','White Mill','Ocean Royale','Belmont Biscuit Co','Brooklea','Seasons Pride','Grandessa','Oh So Natural','Goldenvale','Snackers Market','Hillcrest','Damora','Westcliffe','World Kitchen','Cafe Series','El Tora','Bon Appetit']},
{id:'aldi-2026',url:'https://www.aldiunpacked.com.au/the-basket-has-spoken-aldis-most-loved-products-of-2026-revealed-with-the-peoples-picks-awards/',relationship:'Official 2026 ALDI awards listing; current family presence, individual stock unknown.',brands:['Elmsbury','International Cuisine','Berg','Deli Originals','Brooklea','Snackers Market','Sprinters','Bakers Life','Damora','Dairy Fine']},
{id:'aldi-products',url:'https://www.aldi.com.au/products',relationship:'Official ALDI branded range introduction and current product listings.',brands:['Expressi','Lazzio','Moser Roth','Choceur','Urban Eats','Mamia']},
{id:'aldi-freezer',url:'https://www.aldi.com.au/products/freezer/frozen-fruit-vegetables/k/1111111192',relationship:'Current official Australian product listings; retailer association corroboration, not ownership alone.',brands:['Seasons Pride','Market Fare','Orchard & Vine']},
{id:'aldi-cereal',url:'https://www.aldi.com.au/products/pantry/cereals-muesli/k/1111111180',relationship:'Current official Australian product listings; retailer association corroboration, not ownership alone.',brands:['Hillcrest','Goldenvale','Oh So Natural']},
{id:'aldi-cheese',url:'https://www.aldi.com.au/products/dairy-eggs-fridge/cheese/k/1111111163',relationship:'Current official Australian product listings; retailer association corroboration, not ownership alone.',brands:['Westacre','Westacre Dairy','Emporium Selection','Snackers Market']},
{id:'aldi-elmsbury',url:'https://www.aldi.com.au/product/elmsbury-chunky-beef-pies-4-pack-700g-000000000000365634',relationship:'Current ELMSBURY Australian product page. Site says unavailable in selected store; family current does not imply stock.',brands:['Elmsbury']},
{id:'coles-brands',url:'https://www.coles.com.au/about/who-we-are/our-brands',relationship:'Official current brands exclusive to Coles directory.',brands:['Coles Simply','Coles','Coles Finest',"Nature's Kitchen",'Coles PerForm',"Coles I’m Free From",'Coles Wellness Road','Coles Organic','Coles Kitchen',"Coles I’m Perfect","Coles Grower’s Selection",'Coles Made Easy','Coles Free Range','GRAZE','Drovers Choice',"El-Amin’s",'Wild Tides','Urban Coffee Culture','DALEY ST','Cucina Matese','Coles Asia','Coles BOM',"Coles Mum’s",'The Sweetporium Co']},
{id:'woolworths-macro',url:'https://www.woolworths.com.au/shop/about/our-brands/macro',relationship:'Current official Woolworths own brand Macro range.',brands:['Macro']},
{id:'woolworths-health',url:'https://www.woolworthsgroup.com.au/au/en/our-impact/sustainability/health-and-nutrition/Making-our-own-brands-healthier.html',relationship:'Current official own-brand statement identifies Woolworths, bakery products, Macro and Odd Bunch.',brands:['Woolworths','Macro','Odd Bunch']},
{id:'woolworths-history',url:'https://www.woolworthsgroup.com.au/au/en/who-we-are/our-history.html',relationship:'Historical ownership corroboration of Select, Homebrand and Macro; not currentness.',brands:['Select','Home Brand','Macro']},
{id:'select-legacy',url:'https://www.sbs.com.au/news/article/woolworths-to-dump-its-select-brand/9r3p07xg5',relationship:'Contemporaneous 6 June 2016 report of Select replacement by Woolworths. Legacy classification; source product spellings retained.',brands:['Select']}
];
async function run(){const results=[];for(const source of sources){try{const response=await fetch(source.url,{signal:AbortSignal.timeout(20000)});const bytes=Buffer.from(await response.arrayBuffer());const html=bytes.toString('utf8');const text=html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&#0?39;|&apos;/g,"'").replace(/&nbsp;/g,' ').replace(/\s+/g,' ');const productLinks=[...html.matchAll(/href="([^"]*(?:\/product\/|\/shop\/productdetails\/)[^"]*)"/g)].map(m=>m[1]);results.push({...source,retrievedAt:new Date().toISOString(),status:response.status,sha256:crypto.createHash('sha256').update(bytes).digest('hex'),bytes:bytes.length,brandPresence:Object.fromEntries(source.brands.map(b=>[b,text.toLowerCase().includes(b.toLowerCase())])),productLinks:[...new Set(productLinks)]});console.log(source.id,response.status,bytes.length,results.at(-1).brandPresence);}catch(e){results.push({...source,retrievedAt:new Date().toISOString(),error:e.message});console.log(source.id,e.message);}fs.writeFileSync(path.join(root,'public-evidence.json'),JSON.stringify(results,null,2)+'\n');}}
run().catch(e=>{console.error(e);process.exitCode=1});
