'use strict';
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),assert=require('node:assert/strict');
const C=require('../food-catalogue'),R=require('../retailer-catalogue'),X=require('./catalogue-round-two'),W=require('./catalogue-wave-3a');
const ROOT=path.resolve(__dirname,'..'),BASE=path.join(ROOT,'data/catalogue-wave-3a'),baseline=require('../data/catalogue-wave-3a/baseline.json');
async function derive(){
 const retailers={};for(const kind of ['aldi','woolworths','coles']){require('../'+kind+'-au-catalogue');const foods=[];for(let offset=0;;offset+=20){const page=await R.page(kind,{offset});foods.push(...page.foods);if(!page.hasMore)break;}
  const dir=R.directory(kind),byKey=new Map(foods.map(f=>[C.canonicalKey(f),f])),changes=[];
  for(const prior of baseline.retailers[kind].identities){const food=byKey.get(prior.key);assert(food);assert.equal(C.canLog(food),prior.loggable);const after=food.browseCategoryId||food.categoryId;if(after!==prior.categoryId)changes.push({canonicalKey:prior.key,name:food.name,brand:food.brand,before:prior.categoryId,after,evidence:food.categoryEvidence});}
  retailers[kind]={visible:foods.length,loggable:foods.filter(C.canLog).length,restricted:foods.filter(f=>!C.canLog(f)).length,categories:dir.categories,houseBrandFamilies:dir.brands.length,brands:dir.brands,otherPackagedFood:dir.categories.find(c=>c.id==='other-food').count,changes};
 }
 const protectedFiles=require('../data/catalogue-wave-3a/protected-files.json');for(const p of protectedFiles)assert.equal(X.hash(fs.readFileSync(path.join(ROOT,p.file))),p.sha256,p.file);
 const changed=cp.execFileSync('git',['-c','core.safecrlf=false','diff','--name-only','--diff-filter=M',baseline.startingHead],{cwd:ROOT,encoding:'utf8'}).trim().split('\n'),projectionDiff=[];
 const allowed=new Set(['categoryId','browseCategoryId','category','conceptIds','categoryEvidence']);
 for(const file of changed.filter(f=>/^data\/(?:aldi|coles|woolworths|brand)-au\/products\//.test(f))){const before=JSON.parse(cp.execFileSync('git',['show',baseline.startingHead+':'+file],{cwd:ROOT,encoding:'utf8',maxBuffer:10*1024*1024})).records,after=JSON.parse(fs.readFileSync(path.join(ROOT,file))).records;assert.equal(before.length,after.length);for(let i=0;i<before.length;i++){const fields=[...new Set([...Object.keys(before[i]),...Object.keys(after[i])])].filter(k=>JSON.stringify(before[i][k])!==JSON.stringify(after[i][k]));if(fields.length){assert(fields.every(k=>allowed.has(k)),file+' '+before[i].id+' '+fields);assert.equal(C.canonicalKey(before[i]),C.canonicalKey(after[i]));projectionDiff.push({file,id:before[i].id,canonicalKey:C.canonicalKey(before[i]),fields});}}}
 const review=W.derive(),global=require('../brand-au-catalogue');return {schemaVersion:1,generation:require('../release-manifest.json').generation,version:require('../release-manifest.json').version,retailers,global:{canonicalIdentities:global.entries.length,brands:global.brands.length,categoryChanges:require('../data/brand-au/wave-3a-report.json').changes.length},review:review.groups,protectedFiles:{checked:protectedFiles.length,unchanged:protectedFiles.length},projectionDiff};
}
if(require.main===module)derive().then(r=>{const raw=JSON.stringify(r,null,2)+'\n';if(process.argv.includes('--check'))assert.equal(fs.readFileSync(path.join(BASE,'final-report.json'),'utf8'),raw);else fs.writeFileSync(path.join(BASE,'final-report.json'),raw);console.log(JSON.stringify({generation:r.generation,retailers:Object.fromEntries(Object.entries(r.retailers).map(([k,v])=>[k,{visible:v.visible,loggable:v.loggable,restricted:v.restricted,other:v.otherPackagedFood,moved:v.changes.length}])),global:r.global,protected:r.protectedFiles,projectionChanges:r.projectionDiff.length}));}).catch(e=>{console.error(e);process.exitCode=1;});
module.exports={derive};
