'use strict';
const fs=require('node:fs'),path=require('node:path'),C=require('../food-catalogue'),R=require('../retailer-catalogue'),B=require('../brand-au-catalogue'),X=require('./catalogue-round-two');
const base=path.resolve(__dirname,'../data/catalogue-round-two'),before=X.read('baseline-counts.json'),baseline=X.read('baseline-products.json').records,approved=X.read('approved-products.json').records,audit=X.read('audit.json');
const stats=rows=>({found:rows.length,withGtin:rows.filter(r=>require('./build_coles_catalogue').validGtin(r.gtin)).length,withServing:rows.filter(r=>r.hasServing).length,admissionRejected:rows.filter(r=>r.reasons.length).length,incompleteNutrition:rows.filter(r=>r.reasons.some(s=>/missing-required-macros|needs-nutrition-completion|incomplete-nutrition/.test(s))).length,conflictHeld:rows.filter(r=>r.reasons.some(s=>/conflict|incompatible|collision|incoherent|energy-disagreement/.test(s))).length,exclusionReasons:rows.reduce((out,r)=>(r.reasons.forEach(s=>out[s]=(out[s]||0)+1),out),{})});
const manufacturerFacts=X.read('mccain-facts.json').records;
const manufacturerRows=audit.manufacturer.map(r=>({...r,hasServing:manufacturerFacts.find(f=>f.url===r.url)?.servingText.some(t=>/^Serving size /i.test(t))}));
const summary={dateChecked:'2026-09-18',preflight:X.read('preflight.json'),privateTestingPolicy:X.read('policy.json'),retailers:{},brands:[],sources:{OFF:{...stats(audit.off),sourceType:'Pinned Open Food Facts Australian public data',snapshotDate:'2026-08-30'},McCain:{...stats(manufacturerRows),sourceType:'Official Australian manufacturer product nutrition pages',pagesFound:audit.manufacturer.length,admittedPages:audit.manufacturer.filter(r=>!r.reasons.length).length,duplicates:audit.manufacturer.filter(r=>r.reasons.includes('duplicate-manufacturer-page')).length,details:audit.manufacturer}},generation:require('../release-manifest.json').generation};
const all=[];
for(const id of ['woolworths','coles','aldi']){const index=require('../'+id+'-au-catalogue').index,foods=C.canonicaliseRecords(index.files.flatMap(s=>require('../data/'+id+'-au/'+s.path).records));all.push(...foods);const previousKeys=new Set(before.retailers[id].keys),added=foods.filter(f=>!previousKeys.has(C.canonicalKey(f))&&X.membership(f,id).length);summary.retailers[id]={...stats(audit.off.filter(r=>r.retailers.includes(id))),sourceTypes:['Existing accepted retailer evidence','Pinned Australian OFF explicit store or private-label evidence'],previousDirectory:before.retailers[id].directory,newDirectory:R.directory(id).total,addedDirectory:R.directory(id).total-before.retailers[id].directory,previousOrdinaryLoggable:id==='woolworths'?23:before.retailers[id].directory,ordinaryLoggable:foods.filter(f=>f.browseEligible!==false&&X.membership(f,id).length&&C.productEligibility(f).addability.normalLoggingAllowed).length,canonicalOverlaps:require('../data/'+id+'-au/round-two-report.json').canonicalOverlaps,retainedRestricted:foods.filter(f=>!C.productEligibility(f).addability.normalLoggingAllowed).length,publicReleaseReviewRequired:true,newProducts:added.map(f=>({id:f.id,gtin:f.barcode,name:f.name,brand:f.brand,source:f.sourceProvenance.url}))};}
const sourceRowsByBrand=new Map();for(const r of audit.off)for(const key of new Set(String(r.brand||'').split(',').map(C.brandKey))){const rows=sourceRowsByBrand.get(key)||[];rows.push(r);sourceRowsByBrand.set(key,rows);}
for(const b of B.brands){const prev=before.brands.find(p=>p.key===b.key);const sourceRows=sourceRowsByBrand.get(b.key)||[];summary.brands.push({key:b.key,name:b.name,previous:prev?.count||0,current:b.count,added:b.count-(prev?.count||0),sourceAudit:stats(sourceRows),manufacturerPages:b.key==='mccain'?stats(manufacturerRows):undefined,publicReleaseReviewRequired:true});}
const foods=B.files.flatMap(s=>require('../data/brand-au/'+s.path).records);all.push(...foods);const oldCandidateKeys=new Set(baseline.filter(f=>f.brandAdmission||f.browseEligible===true||f.id.startsWith('woolworths-au:')).map(C.canonicalKey)),oldBrowse=new Set(C.canonicaliseRecords(baseline).filter(f=>oldCandidateKeys.has(C.canonicalKey(f))&&C.productEligibility(f).addability.normalLoggingAllowed).map(C.canonicalKey)),newBrowse=new Set(all.filter(f=>f.browseEligible!==false&&C.productEligibility(f).addability.normalLoggingAllowed).map(C.canonicalKey));
const oldUniverse=new Set(baseline.map(C.canonicalKey)),raw=require('../data/open-food-facts-au/manifest.json');for(const shard of raw.productShards)for(const f of require('../data/open-food-facts-au/'+shard.path).products)oldUniverse.add(C.canonicalKey(f));const universe=new Set([...oldUniverse,...approved.map(C.canonicalKey)]);
summary.totals={brandPrevious:before.brandProducts,brandCurrent:B.entries.length,newBrandBrowse:B.entries.length-before.brandProducts,brandDirectoryPrevious:before.brands.length,brandDirectoryCurrent:B.brands.length,previousBrowsableCanonicalSet:oldBrowse.size,browsableCanonicalSet:newBrowse.size,newlyBrowsableCanonicalIdentities:[...newBrowse].filter(k=>!oldBrowse.has(k)).length,packagedUniverseBefore:oldUniverse.size,packagedUniverseAfter:universe.size,newCanonicalIdentities:universe.size-oldUniverse.size,approvedEvidenceRecords:approved.length,existingCanonicalOverlaps:approved.filter(f=>oldUniverse.has(C.canonicalKey(f))).length,manufacturerKnownGtins:approved.filter(f=>f.sourceProvenance.trustClass==='official-au-manufacturer'&&f.barcode).length};
summary.countNotes='Directory additions are not all new food identities: most already existed in the frozen OFF universe. Packaged universe includes incomplete records; excludes generic AFCD foods and restaurant chains. Woolworths retains its original restricted/detail records separately from ordinary loggable products. Rejection-reason counts overlap.';
fs.writeFileSync(path.join(base,'summary.json'),JSON.stringify(summary,null,2)+'\n');console.log(JSON.stringify({totals:summary.totals,retailers:Object.fromEntries(Object.entries(summary.retailers).map(([k,v])=>[k,{previous:v.previousDirectory,current:v.newDirectory,added:v.addedDirectory,loggable:v.ordinaryLoggable}])),brands:summary.brands.filter(b=>['mccain','kelloggs','nescafe','campbells'].includes(b.key))},null,2));
