'use strict';
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),assert=require('node:assert/strict'),X=require('./catalogue-round-two'),C=require('../food-catalogue'),R=require('../retailer-catalogue'),W=require('./catalogue-wave-4a');
const ROOT=path.resolve(__dirname,'..'),BASE=path.join(ROOT,'data/catalogue-wave-4a'),baseline=require('../data/catalogue-wave-4a/baseline.json');
async function derive(){const {products,groups,reviews}=W.derive(),retailers={};for(const kind of ['iga','aldi','woolworths','coles']){require('../'+kind+'-au-catalogue');const records=[];for(let offset=0;;offset+=20){const p=await R.page(kind,{offset});records.push(...p.foods);if(!p.hasMore)break;}const d=R.directory(kind);retailers[kind]={visible:records.length,loggable:records.filter(C.canLog).length,restricted:records.filter(f=>!C.canLog(f)).length,categories:d.categories,families:d.brands,other:d.categories.find(c=>c.id==='other-food')?.count||0};if(kind!=='iga')assert.deepEqual(records,baseline.retailers[kind].records);}
 const protectedFiles=require('../data/catalogue-wave-4a/protected-files.json');for(const p of protectedFiles)assert.equal(X.hash(fs.readFileSync(path.join(ROOT,p.file))),p.sha256,p.file);
 const changes=[],allowed=new Set(['privateLabelCollections','retailerMemberships','catalogueWave4A','categoryId','browseCategoryId','category','conceptIds','categoryEvidence']),expected=new Set(products.map(C.canonicalKey));
 const files=cp.execFileSync('git',['-c','core.safecrlf=false','diff','--name-only',baseline.head],{cwd:ROOT,encoding:'utf8'}).trim().split('\n').filter(f=>/^data\/brand-au\/products\//.test(f));for(const file of files){const before=JSON.parse(cp.execFileSync('git',['show',baseline.head+':'+file],{cwd:ROOT,maxBuffer:12*1024*1024})).records,after=JSON.parse(fs.readFileSync(path.join(ROOT,file))).records;assert.equal(before.length,after.length);for(let i=0;i<before.length;i++){const a=before[i],b=after[i],fields=[...new Set([...Object.keys(a),...Object.keys(b)])].filter(k=>JSON.stringify(a[k])!==JSON.stringify(b[k]));if(fields.length){assert(expected.has(C.canonicalKey(a)));assert(fields.every(k=>allowed.has(k)));assert.equal(C.canonicalKey(a),C.canonicalKey(b));changes.push({file,id:a.id,canonicalKey:C.canonicalKey(a),fields,beforeCategory:a.categoryId,afterCategory:b.categoryId});}}}
 assert.equal(changes.length,9);const global=require('../brand-au-catalogue');assert.equal(global.entries.length,baseline.globalCanonical);
 const result={generation:require('../release-manifest.json').generation,version:'0.6.33',sourceHeadBefore:baseline.head,groups,reviews:reviews.map(({candidateId,name,brand,disposition,reason,canonicalKey,category})=>({candidateId,name,brand,disposition,reason,canonicalKey,category})),retailers,global:{canonical:global.entries.length,newCanonical:0,changedExisting:changes.length,categoryChanges:changes.filter(c=>c.beforeCategory!==c.afterCategory).length,changes},protected:{checked:protectedFiles.length,unchanged:protectedFiles.length},availability:'Eight private-label family relationships and one store-specific independent listing; no national product-stock assertions',builderInputs:W.inputs().policy.inputs};return result;}
if(require.main===module)derive().then(r=>{const raw=JSON.stringify(r,null,2)+'\n';if(process.argv.includes('--check'))assert.equal(fs.readFileSync(path.join(BASE,'final-report.json'),'utf8'),raw);else fs.writeFileSync(path.join(BASE,'final-report.json'),raw);console.log(JSON.stringify({generation:r.generation,counts:Object.fromEntries(Object.entries(r.retailers).map(([k,v])=>[k,{visible:v.visible,loggable:v.loggable,restricted:v.restricted,categories:v.categories.length,families:v.families.length,other:v.other}])),protected:r.protected}));}).catch(e=>{console.error(e);process.exitCode=1;});module.exports={derive};
