'use strict';
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const ROOT=path.resolve(__dirname,'..'),BASE=path.join(ROOT,'data/catalogue-wave-5a'),phase=process.argv[2];assert(['focused','acceptance'].includes(phase));
const target=path.join(BASE,phase+'-result.json');assert(!fs.existsSync(target),'Keep original gate results');const generation=require('../release-manifest.json').generation;
if(phase==='acceptance'){for(const file of ['focused-result.json','rendered-complete/rendered.json']){const gate=JSON.parse(fs.readFileSync(path.join(BASE,file)));assert(gate.pass,file);assert.equal(gate.generation,generation);}assert.equal(require('./build_release').check().length,0);}
const focused=['catalogue-wave-5a','query-ownership','retailer-loading','retailer-architecture','same-gtin-identity-safety','physical-form-measure-compatibility','product-serving-semantics','canonical-result-consumers','portion-handoff-integrity','release-coherence','brand-generation','brand-catalogue'].map(f=>'tests/'+f+'.test.js');
const testFiles=phase==='focused'?focused:[...require('../data/catalogue-wave-4a/acceptance-plan.json').testFiles,'tests/catalogue-wave-5a.test.js'];
const startedAt=new Date().toISOString(),args=['--test','--test-concurrency=2',...testFiles],run=cp.spawnSync(process.execPath,args,{cwd:ROOT,encoding:'utf8',maxBuffer:100*1024*1024}),log=(run.stdout||'')+(run.stderr||'');fs.writeFileSync(path.join(BASE,phase+'.log'),log);
const count=name=>Number(log.match(new RegExp('(?:ℹ |# )'+name+' (\\d+)'))?.[1]||0),result={phase,pass:run.status===0,generation,startedAt,completedAt:new Date().toISOString(),exitCode:run.status,signal:run.signal,error:run.error?.message||null,tests:count('tests'),passed:count('pass'),failed:count('fail'),skipped:count('skipped'),cancelled:count('cancelled'),testFiles,command:[process.execPath,...args],logSha256:crypto.createHash('sha256').update(log).digest('hex')};fs.writeFileSync(target,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));process.exitCode=result.pass?0:1;
