'use strict';
const fs=require('node:fs'),cp=require('node:child_process'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const base='data/catalogue-wave-5a-continuation',hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),git=(...args)=>cp.execFileSync('git',args,{encoding:'utf8',stdio:['ignore','pipe','ignore']}).trim(),generation=require('../release-manifest.json').generation,baseline='365ceef537f15c0550ffd16b9b9221b0e60187e6';
assert.equal(git('rev-parse','HEAD'),baseline);assert.equal(git('branch','--show-current'),'alpha-0.6.33');
const gates={};for(const file of ['focused-complete-result.json','navigation-final-result.json','rendered/rendered.json','restaurant-navigation-verified/rendered.json','restaurant-family-gate.json','acceptance-result.json']){const r=JSON.parse(fs.readFileSync(base+'/'+file));assert(r.pass,file);assert.equal(r.generation,generation,file);gates[file]={pass:r.pass,tests:r.tests||null,sha256:hash(base+'/'+file)};if(r.tests){assert.equal(r.tests,r.passed);assert.equal(r.failed+r.skipped+r.cancelled,0);}}
const acceptance=JSON.parse(fs.readFileSync(base+'/acceptance-result.json'));assert.deepEqual(acceptance.testFiles,[...require('../data/catalogue-wave-4a/acceptance-plan.json').testFiles,'tests/catalogue-wave-5a.test.js','tests/catalogue-wave-5a-continuation.test.js']);
assert.equal(require('./build_release').check().length,0);for(const [p,h]of Object.entries(require('../'+base+'/production-freeze-final.json').sha256))assert.equal(hash(p),h,p);
const original=require('../'+base+'/retained-inventory.json'),protectedFiles=require('../data/catalogue-wave-5a/protected-baseline.json'),evidence=Object.entries(original.files).filter(([p])=>p.startsWith('data/catalogue-wave-5a/'));for(const [p,h]of [...Object.entries(protectedFiles),...evidence])assert.equal(hash(p),h,p);
const retainedEdits=new Set(['catalogue-discovery.js','alpha06.js','brand-au-catalogue.js','coles-au-catalogue.js','index.html','release-manifest.json','service-worker.js','serving-foundation.js','woolworths-au-catalogue.js']);for(const [p,h]of Object.entries(original.files))if(hash(p)!==h)assert(retainedEdits.has(p),'Unrelated retained edit: '+p);
const extra=new Set(['alpha064.js','scripts/audit_live_prefix_alphabetical_edge.js','scripts/audit_post_kfc_search_edge.js','scripts/audit_restaurant_family_search.js','scripts/audit_navigation_startup_edge.js','tests/aldi-source.test.js','tests/canonical-search-identity-consistency.test.js','tests/catalogue-round-two.test.js','tests/catalogue-search-intelligence.test.js','tests/catalogue-search-regression-recovery.test.js','tests/catalogue-wave-2a.test.js','tests/catalogue-wave-3a.test.js','tests/catalogue-wave-4a.test.js','tests/universal-food-search-source-branching.test.js','scripts/audit_catalogue_wave_5a_memory.js','scripts/audit_catalogue_wave_5a_restaurants_edge.js','scripts/catalogue-test-resources.js','scripts/catalogue-wave-5a-restaurant-probes.js','scripts/verify_catalogue_wave_5a_continuation.js','scripts/verify_catalogue_wave_5a_rendered_continuation.js','scripts/verify_catalogue_wave_5a_commit_gate.js','tests/catalogue-wave-5a-continuation.test.js']);
const paths=[...new Set([...git('diff','--name-only').split('\n'),...git('diff','--cached','--name-only').split('\n'),...git('ls-files','--others','--exclude-standard').split('\n')].filter(Boolean))];for(const p of paths)assert(original.files[p]||extra.has(p)||p.startsWith(base+'/'),'Unaccounted change: '+p);git('diff','--check');const report={pass:true,verifiedAt:new Date().toISOString(),baseline,branch:'alpha-0.6.33',generation,gates,protectedFiles:Object.keys(protectedFiles).length,originalEvidenceFiles:evidence.length,onlyIntendedChanges:true,files:paths.length,noPush:true,noDeployment:true};fs.writeFileSync(base+'/final-verification.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
