'use strict';
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const ROOT=path.resolve(__dirname,'..'),BASE=path.join(ROOT,'data/catalogue-wave-5a-continuation'),phase=process.argv[2],label=process.argv[3]||phase;assert(['focused','acceptance','isolated'].includes(phase));
const target=path.join(BASE,label+'-result.json');assert(!fs.existsSync(target),'Preserve original results');const generation=require('../release-manifest.json').generation;
if(phase==='acceptance'){for(const file of ['focused-complete-result.json','rendered/rendered.json','restaurant-navigation-verified/rendered.json','restaurant-family-gate.json','navigation-final-result.json']){const gate=JSON.parse(fs.readFileSync(path.join(BASE,file)));assert(gate.pass,file);assert.equal(gate.generation,generation);}assert.equal(require('./build_release').check().length,0);assert(!fs.existsSync(path.join(BASE,'acceptance-started.json')),'Only one additional complete run authorised');fs.writeFileSync(path.join(BASE,'acceptance-started.json'),JSON.stringify({generation,started:new Date().toISOString()}));}
const focused=['catalogue-wave-5a','catalogue-wave-5a-continuation','query-ownership','retailer-loading','retailer-architecture','same-gtin-identity-safety','physical-form-measure-compatibility','product-serving-semantics','canonical-result-consumers','portion-handoff-integrity','release-coherence','brand-generation','brand-catalogue','aldi-source','canonical-search-identity-consistency','catalogue-round-two','catalogue-search-intelligence','catalogue-search-regression-recovery','catalogue-wave-2a','catalogue-wave-3a','catalogue-wave-4a','hungry-jacks-australia-expansion','live-prefix-alphabetical','post-kfc-search-regressions','restaurant-family-search','universal-food-search-source-branching'].map(f=>'tests/'+f+'.test.js');
const testFiles=phase==='isolated'?process.argv.slice(4):phase==='focused'?focused:[...require('../data/catalogue-wave-4a/acceptance-plan.json').testFiles,'tests/catalogue-wave-5a.test.js','tests/catalogue-wave-5a-continuation.test.js'];
const startedAt=new Date().toISOString(),args=['--require','./scripts/catalogue-test-resources.js','--test','--test-concurrency=1',...testFiles],logPath=path.join(BASE,label+'.log'),fd=fs.openSync(logPath,'wx'),child=cp.spawn(process.execPath,args,{cwd:ROOT,env:{...process.env,HEC_RESOURCE_DIRECTORY:path.join(BASE,label+'-resources')},stdio:['ignore',fd,fd]});
child.on('close',(code,signal)=>{fs.closeSync(fd);const log=fs.readFileSync(logPath,'utf8'),count=name=>Number(log.match(new RegExp('(?:ℹ |# )'+name+' (\\d+)'))?.[1]||0),result={phase,pass:code===0,generation,startedAt,completedAt:new Date().toISOString(),exitCode:code,signal,tests:count('tests'),passed:count('pass'),failed:count('fail'),skipped:count('skipped'),cancelled:count('cancelled'),testFiles,command:[process.execPath,...args],logSha256:crypto.createHash('sha256').update(log).digest('hex')};fs.writeFileSync(target,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));process.exitCode=result.pass?0:1;});
